import type { PlacementEffectProgram } from './placementTcgEffectDsl';
import { defineMagicUnitProgram } from './placementTcgUniqueEffectFactory';

export const PLACEMENT_TCG_MAGIC_UNIT_PROGRAMS: Readonly<Record<string, PlacementEffectProgram>> = {
  MTCG_MAGIC_HERO_AKARI_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_AKARI_BEFORE', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '星宮あかりは星光と星脈を重ねる。SP優位なら魔力刻印を残す、刻印が残っていれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-akari-before-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'hero-akari-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_AKARI_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_AKARI_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '星宮あかり／星冠の魔法騎士は星光と星脈を重ねる。中央レーンなら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'hero-akari-after-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-akari-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SHIZUKU_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_SHIZUKU_BEFORE', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '水城しずくは水晶と清流の魔力を反射させる。ライフ半分以下なら敵全体を停止、空きレーンがあれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'WATER'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'hero-shizuku-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'hero-shizuku-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SHIZUKU_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SHIZUKU_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '水城しずく／月鏡の水晶騎士は月光と満ち欠けを術式へ変える。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MOON'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-shizuku-after-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-shizuku-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_HIYORI_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_HIYORI_BEFORE', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '花咲ひよりは花蔓と生命魔力を循環させる。空きレーンがあれば味方全体の体力を1上げる、味方がいれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'FLORA'],
    steps: [
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 1, label: 'hero-hiyori-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'HAS_OWN_UNIT', amount: 2, duration: 0, label: 'hero-hiyori-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_HIYORI_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_HIYORI_AFTER', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '花咲ひより／命花の治癒術師は花蔓と生命魔力を循環させる。敵がいれば魔力刻印を残す、刻印が残っていれば味方全体の体力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'FLORA'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-hiyori-after-1' },
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 2, label: 'hero-hiyori-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_TSUBASA_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_TSUBASA_BEFORE', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '火神つばさは炎を代償ごと燃え上がらせる。SP優位なら魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-tsubasa-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-tsubasa-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_TSUBASA_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_TSUBASA_AFTER', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '火神つばさ／神鍛の炎戦士は炎を代償ごと燃え上がらせる。SP優位なら味方全体の攻撃力を1上げる、ライフ半分以下なら手札を1枚失う。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'FIRE'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 2, label: 'hero-tsubasa-after-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'hero-tsubasa-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_REI_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_REI_BEFORE', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '黒羽れいは怪異の性質を魔力として蓄え、場へ解き放つ。中央レーンなら敵1体を停止、奇数ターンなら敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'hero-rei-before-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 2, duration: 0, label: 'hero-rei-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_REI_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_REI_AFTER', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '黒羽れい／深紅の符術姫は怪異の性質を魔力として蓄え、場へ解き放つ。奇数ターンなら魔力刻印を残す、刻印が残っていればSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-rei-after-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-rei-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MADOKA_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_MADOKA_BEFORE', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '翠川まどかは怪異の性質を魔力として蓄え、場へ解き放つ。奇数ターンなら自身へシールド2、敵がいれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'MYSTERY'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'ODD_TURN', amount: 2, duration: 0, label: 'hero-madoka-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-madoka-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MADOKA_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MADOKA_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '翠川まどか／時環の錬金術師は時間を刻印し蓄積した時を解放する。空きレーンがあれば空きレーンへ移動、味方がいればSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'TIME'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'hero-madoka-after-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'hero-madoka-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_KOHARU_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_KOHARU_BEFORE', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '風森こはるは風の流れで位置と間合いを操る。SP優位なら魔力刻印を残す、刻印が残っていれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-koharu-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'hero-koharu-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_KOHARU_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_KOHARU_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '風森こはる／翠嵐の精霊弓士は風の流れで位置と間合いを操る。中央レーンなら魔力刻印を残す、刻印が残っていれば正面の敵へ1ダメージ。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'hero-koharu-after-1' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-koharu-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MIRAI_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_MIRAI_BEFORE', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '紫藤みらいは怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら敵1体を停止、ライフ半分以下なら自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-mirai-before-1' },
      { action: 'HEAL', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'hero-mirai-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MIRAI_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MIRAI_AFTER', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '紫藤みらい／夢幻の舞台魔術師は影と夢を代償付きの幻術へ変える。奇数ターンなら魔力刻印を残す、刻印が残っていれば自身へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-mirai-after-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-mirai-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SERA_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_SERA_BEFORE', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白峰セラは怪異の性質を魔力として蓄え、場へ解き放つ。ライフ半分以下なら自身へシールド1、空きレーンがあれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'hero-sera-before-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'EMPTY_LANE', amount: 2, duration: 0, label: 'hero-sera-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SERA_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SERA_AFTER', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '白峰セラ／星界の光術師は星光と星脈を重ねる。敵がいれば魔力刻印を残す、刻印が残っていれば自身の体力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-sera-after-1' },
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'hero-sera-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_REN_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_REN_BEFORE', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '朝霧 蓮は怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら魔力刻印を残す、刻印が残っていれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-ren-before-1' },
      { action: 'HEAL', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-ren-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_REN_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_REN_AFTER', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '朝霧 蓮／蒼風の守護騎士は風の流れで位置と間合いを操る。敵がいれば敵1体を停止、SP優位ならSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'WIND'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-ren-after-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-ren-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SOMA_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_SOMA_BEFORE', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '御影 颯真は影と夢を代償付きの幻術へ変える。味方がいれば敵全体へ2ダメージ、中央レーンなら敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'SHADOW'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 2, duration: 0, label: 'hero-soma-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 2, duration: 0, label: 'hero-soma-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SOMA_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SOMA_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '御影 颯真／氷律の執行騎士は水晶と清流の魔力を反射させる。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'WATER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-soma-after-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-soma-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MINATO_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_MINATO_BEFORE', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '白石 湊は怪異の性質を魔力として蓄え、場へ解き放つ。中央レーンなら自身へシールド1、奇数ターンなら自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'MYSTERY'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'hero-minato-before-1' },
      { action: 'HEAL', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-minato-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_MINATO_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MINATO_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白石 湊／清流の癒術騎士は水晶と清流の魔力を反射させる。ライフ半分以下なら敵全体を停止、空きレーンがあれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'WATER'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'hero-minato-after-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'hero-minato-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_RIKU_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_RIKU_BEFORE', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '天音 理玖は怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら魔力刻印を残す、刻印が残っていれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-riku-before-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'hero-riku-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_RIKU_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_RIKU_AFTER', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '天音 理玖／時詠の観測騎士は時間を刻印し蓄積した時を解放する。中央レーンなら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'hero-riku-after-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-riku-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_YAMATO_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_YAMATO_BEFORE', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '黒瀬 大和は怪異の性質を魔力として蓄え、場へ解き放つ。敵がいれば敵1体を停止、SP優位なら敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-yamato-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-yamato-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_YAMATO_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_YAMATO_AFTER', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '黒瀬 大和／紅蓮の拳闘騎士は炎を代償ごと燃え上がらせる。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-yamato-after-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-yamato-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_LEON_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_LEON_BEFORE', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '神代 レオンは怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら自身へシールド1、ライフ半分以下なら敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-leon-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'LIFE_BELOW_HALF', amount: 2, duration: 0, label: 'hero-leon-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_LEON_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_LEON_AFTER', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '神代 レオン／幻奏の舞台騎士は魔力を武技へ重ね、位置取りから強撃を放つ。敵がいれば魔力刻印を残す、刻印が残っていれば味方全体の体力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'KNIGHT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-leon-after-1' },
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'hero-leon-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_ELLIOT_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_ELLIOT_BEFORE', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: 'エリオット・ノクスは怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hero-elliot-before-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-elliot-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_ELLIOT_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_ELLIOT_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'エリオット・ノクス／星界の記録騎士は星光と星脈を重ねる。奇数ターンなら味方全体へシールド1、敵がいれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-elliot-after-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'hero-elliot-after-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SAKUYA_BEFORE: defineMagicUnitProgram('MTCG_MAGIC_HERO_SAKUYA_BEFORE', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '九条 朔夜は怪異の性質を魔力として蓄え、場へ解き放つ。空きレーンがあれば敵1体を停止、味方がいれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'hero-sakuya-before-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 2, duration: 0, label: 'hero-sakuya-before-2' },
    ],
  }),
  MTCG_MAGIC_HERO_SAKUYA_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SAKUYA_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '九条 朔夜／宵闇の封印騎士は影と夢を代償付きの幻術へ変える。奇数ターンなら魔力刻印を残す、刻印が残っていれば敵1体へ1ダメージ。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'hero-sakuya-after-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'hero-sakuya-after-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_001: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_001', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '星屑の使い魔は星光と星脈を重ねる。味方がいれば味方全体へシールド1、中央レーンなら敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'STAR'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-001-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-001-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_002: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_002', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '月影スライムは月光と満ち欠けを術式へ変える。SP優位なら味方全体へシールド2、ライフ半分以下ならSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'MOON'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 2, duration: 0, label: 'enemy-002-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-002-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_003: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_003', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '花迷宮の芽獣は花蔓と生命魔力を循環させる。SP優位なら魔力刻印を残す、刻印が残っていれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'FLORA'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-003-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-003-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_004: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_004', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '火花コウモリは花蔓と生命魔力を循環させる。ライフ半分以下なら味方全体の体力を1上げる、空きレーンがあれば自身へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'FLORA'],
    steps: [
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 1, label: 'enemy-004-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-004-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_005: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_005', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '影縫いの欠片は影と夢を代償付きの幻術へ変える。奇数ターンなら敵全体へ1ダメージ、敵がいれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'SHADOW'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-005-1' },
      { action: 'HEAL', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-005-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_006: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_006', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '時計塔の歯車霊は時間を刻印し蓄積した時を解放する。奇数ターンなら魔力刻印を残す、刻印が残っていれば自身へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-006-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-006-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_007: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_007', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '風読みの小竜は風の流れで位置と間合いを操る。敵がいれば敵1体を停止、SP優位なら手札を2枚失う。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'WIND'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'enemy-007-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'SP_LEAD', amount: 2, duration: 0, label: 'enemy-007-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_008: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_008', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '夢喰いの泡は影と夢を代償付きの幻術へ変える。敵がいれば魔力刻印を残す、刻印が残っていれば自身の体力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-008-1' },
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'enemy-008-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_009: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_009', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '光膜のクラゲは光の結界を広げて場全体を制御する。SP優位なら魔力刻印を残す、刻印が残っていれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'LIGHT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-009-1' },
      { action: 'HEAL', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-009-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_010: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_010', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '魔導書の幼体は魔導記録を蓄え、読解した術式を展開する。中央レーンならSPを1得る、奇数ターンならSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'ARCANE_TEXT'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-010-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-010-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_011: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_011', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '結晶ネズミは怪異の性質を魔力として蓄え、場へ解き放つ。ライフ半分以下なら敵1体を停止、空きレーンがあれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-011-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 2, duration: 0, label: 'enemy-011-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_012: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_012', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '黒板魔法陣は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'CASTER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-012-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-012-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_013: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_013', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '星砂ミミックは星光と星脈を重ねる。空きレーンがあれば味方全体へシールド1、味方がいれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'STAR'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-013-1' },
      { action: 'HEAL', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-013-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_014: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_014', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '月輪ガーゴイルは月光と満ち欠けを術式へ変える。敵がいれば味方全体へシールド1、SP優位なら味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MOON'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-014-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-014-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_015: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_015', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '蔓薔薇の怪は花蔓と生命魔力を循環させる。SP優位なら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'FLORA'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-015-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-015-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_016: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_016', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '炎冠の小鬼は炎を代償ごと燃え上がらせる。SP優位なら味方全体の攻撃力を1上げる、ライフ半分以下なら味方全体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'FIRE'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 2, label: 'enemy-016-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-016-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_017: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_017', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '闇インクの影は影と夢を代償付きの幻術へ変える。中央レーンなら敵全体へ2ダメージ、奇数ターンなら敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'SHADOW'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 2, duration: 0, label: 'enemy-017-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-017-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_018: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_018', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '時砂の亡霊は時間を刻印し蓄積した時を解放する。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-018-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'enemy-018-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_019: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_019', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '旋風ケットシーは風の流れで位置と間合いを操る。奇数ターンなら敵1体を停止、敵がいれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'WIND'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-019-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'enemy-019-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_020: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_020', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '悪夢の仮面は影と夢を代償付きの幻術へ変える。敵がいれば魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-020-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-020-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_021: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_021', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '聖灯の羽虫は光の結界を広げて場全体を制御する。SP優位なら魔力刻印を残す、刻印が残っていれば相手から1吸収。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'LIGHT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-021-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-021-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_022: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_022', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '魔石ゴーレムは怪異の性質を魔力として蓄え、場へ解き放つ。味方がいれば自身へシールド2、中央レーンなら味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'MYSTERY'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 2, duration: 0, label: 'enemy-022-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-022-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_023: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_023', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '封印リボンは怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら敵1体を停止、ライフ半分以下なら敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-023-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 2, duration: 0, label: 'enemy-023-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_024: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_024', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '彗星の尾獣は星光と星脈を重ねる。奇数ターンなら魔力刻印を残す、刻印が残っていれば敵1体を停止。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-024-1' },
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-024-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_025: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_025', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '月読の鏡片は月光と満ち欠けを術式へ変える。ライフ半分以下なら相手から1吸収、空きレーンがあれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'MOON'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-025-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-025-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_026: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_026', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '花粉の幻霧は花蔓と生命魔力を循環させる。奇数ターンなら相手から1吸収、敵がいればSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'FLORA'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-026-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-026-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_027: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_027', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '火球の精は炎を代償ごと燃え上がらせる。SP優位なら魔力刻印を残す、刻印が残っていれば正面の敵へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-027-1' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-027-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_028: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_028', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '影絵の騎獣は影と夢を代償付きの幻術へ変える。敵がいれば敵全体を停止、SP優位なら自身へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'SHADOW'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-028-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-028-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_029: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_029', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '遅刻ベルの霊は怪異の性質を魔力として蓄え、場へ解き放つ。味方がいれば敵1体を停止、中央レーンなら手札を1枚失う。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-029-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-029-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_030: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_030', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '風鈴の魔物は風の流れで位置と間合いを操る。奇数ターンなら魔力刻印を残す、刻印が残っていれば自身の攻撃力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-030-1' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'enemy-030-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_031: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_031', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '夢色キャンディ怪は影と夢を代償付きの幻術へ変える。中央レーンなら敵全体を停止、奇数ターンなら敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'SHADOW'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-031-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 2, duration: 0, label: 'enemy-031-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_032: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_032', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '光輪の番犬は光の結界を広げて場全体を制御する。ライフ半分以下なら敵全体へ2ダメージ、空きレーンがあれば味方全体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'LIGHT'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 2, duration: 0, label: 'enemy-032-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-032-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_033: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_033', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '星図の蛇は星光と星脈を重ねる。SP優位なら魔力刻印を残す、刻印が残っていれば空きレーンへ移動。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-033-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-033-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_034: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_034', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '月蝕ランタンは月光と満ち欠けを術式へ変える。空きレーンがあれば相手から1吸収、味方がいればSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MOON'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-034-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-034-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_035: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_035', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '花冠の毒蜂は花蔓と生命魔力を循環させる。敵がいれば相手から1吸収、SP優位なら敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'FLORA'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-035-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 2, duration: 0, label: 'enemy-035-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_036: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_036', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '炎筆の魔獣は炎を代償ごと燃え上がらせる。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方1体の攻撃力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-036-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'enemy-036-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_037: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_037', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '闇劇場の人形は影と夢を代償付きの幻術へ変える。SP優位なら敵全体を停止、ライフ半分以下なら自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'SHADOW'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 2, duration: 0, label: 'enemy-037-1' },
      { action: 'HEAL', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-037-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_038: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_038', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '時針の蜘蛛は時間を刻印し蓄積した時を解放する。中央レーンなら空きレーンへ移動、奇数ターンなら味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'TIME'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-038-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-038-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_039: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_039', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '風札の狐面は風の流れで位置と間合いを操る。SP優位なら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-039-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-039-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_040: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_040', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '夢頁の蝶は影と夢を代償付きの幻術へ変える。中央レーンなら魔力刻印を残す、刻印が残っていれば味方全体を1回復。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-040-1' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-040-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_041: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_041', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '光晶の盾獣は光の結界を広げて場全体を制御する。空きレーンがあれば敵全体へ1ダメージ、味方がいれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'LIGHT'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-041-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-041-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_042: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_042', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '魔力試験の残滓は魔導記録を蓄え、読解した術式を展開する。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'ARCANE_TEXT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-042-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 2, label: 'enemy-042-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_043: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_043', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '星鍵の守り手は星光と星脈を重ねる。味方がいれば味方全体へシールド1、中央レーンなら敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'STAR'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-043-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 2, duration: 0, label: 'enemy-043-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_044: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_044', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '月光庭園の影花は月光と満ち欠けを術式へ変える。敵がいれば魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MOON'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-044-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-044-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_045: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_045', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '深淵図書館の栞獣は影と夢を代償付きの幻術へ変える。SP優位なら魔力刻印を残す、刻印が残っていれば相手から1吸収。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-045-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-045-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_046: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_046', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '見習い魔女の反逆者は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。ライフ半分以下なら敵全体へ1ダメージ、空きレーンがあれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'CASTER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-046-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-046-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_047: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_047', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '仮面の魔法剣士は魔力を武技へ重ね、位置取りから強撃を放つ。奇数ターンなら自身へシールド2、敵がいれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'KNIGHT'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'ODD_TURN', amount: 2, duration: 0, label: 'enemy-047-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'enemy-047-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_048: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_048', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: 'ルーン図書委員は魔導記録を蓄え、読解した術式を展開する。奇数ターンなら魔力刻印を残す、刻印が残っていれば敵支援を1削る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'ARCANE_TEXT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-048-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-048-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_049: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_049', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '水晶錬金術師は水晶と清流の魔力を反射させる。敵がいれば味方全体を1回復、SP優位なら敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'WATER'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-049-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-049-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_050: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_050', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '影舞台の奇術師は影と夢を代償付きの幻術へ変える。味方がいれば敵全体へ1ダメージ、中央レーンならSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'SHADOW'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-050-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-050-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_051: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_051', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '月社の祓い手は月光と満ち欠けを術式へ変える。SP優位なら魔力刻印を残す、刻印が残っていれば正面の敵へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MOON'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-051-1' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-051-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_052: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_052', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '茨庭の魔導士は花蔓と生命魔力を循環させる。中央レーンなら魔力刻印を残す、刻印が残っていれば正面の敵へ1ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'FLORA'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-052-1' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-052-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_053: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_053', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '鐘鎧の召喚士は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。ライフ半分以下なら敵支援全体を1削る、空きレーンがあれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'CASTER'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-053-1' },
      { action: 'HEAL', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'enemy-053-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_054: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_054', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '呪い人形の操者は怪異の性質を魔力として蓄え、場へ解き放つ。奇数ターンなら魔力刻印を残す、刻印が残っていれば自身へシールド1。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-054-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-054-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_055: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_055', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '炎厨房の魔法使いは炎を代償ごと燃え上がらせる。空きレーンがあれば味方全体の攻撃力を1上げる、味方がいれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'FIRE'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 1, label: 'enemy-055-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 2, duration: 0, label: 'enemy-055-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_056: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_056', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '重盾の魔法騎士は魔力を武技へ重ね、位置取りから強撃を放つ。敵がいれば魔力刻印を残す、刻印が残っていれば自身の体力を1上げる。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'KNIGHT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-056-1' },
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'enemy-056-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_057: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_057', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '紙嵐の忍術士は風の流れで位置と間合いを操る。SP優位なら魔力刻印を残す、刻印が残っていれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-057-1' },
      { action: 'HEAL', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-057-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_058: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_058', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '鏡界の幻術師は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。SP優位なら敵全体へ1ダメージ、ライフ半分以下ならSPを1得る。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'CASTER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-058-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-058-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_059: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_059', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '雷指揮のコンダクターは怪異の性質を魔力として蓄え、場へ解き放つ。中央レーンなら敵1体を停止、奇数ターンなら敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'TURN_END', 'MYSTERY'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-059-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'ODD_TURN', amount: 2, duration: 0, label: 'enemy-059-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_060: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_060', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '氷鏡の槍術士は水晶と清流の魔力を反射させる。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方1体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DAMAGED', 'WATER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-060-1' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-060-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_061: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_061', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '獣面の地脈術師は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。奇数ターンなら敵全体へ1ダメージ、敵がいれば自身を1回復。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'CASTER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-061-1' },
      { action: 'HEAL', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'enemy-061-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_062: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_062', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '時計塔の時術師は時間を刻印し蓄積した時を解放する。空きレーンがあれば空きレーンへ移動、味方がいれば手札を1枚失う。',
    tags: ['MAGIC', 'UNIT', 'DEFEAT', 'TIME'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 2, duration: 0, label: 'enemy-062-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'enemy-062-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_063: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_063', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '蝋燭の死霊学徒は怪異の性質を魔力として蓄え、場へ解き放つ。SP優位なら魔力刻印を残す、刻印が残っていれば敵全体へ2ダメージ。',
    tags: ['MAGIC', 'UNIT', 'TURN_START', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-063-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'enemy-063-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_064: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_064', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '星見台の弓術士は星光と星脈を重ねる。中央レーンなら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'UNIT', 'ATTACK', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'enemy-064-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-064-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_065: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_065', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '禁術学園の風紀長は風の流れで位置と間合いを操る。SP優位なら敵全体へ1ダメージ、ライフ半分以下なら敵支援全体を1削る。',
    tags: ['MAGIC', 'UNIT', 'DIRECT_ATTACK', 'WIND'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'enemy-065-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'enemy-065-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_066: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_066', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '大魔女校長は術式を重ねて条件が揃った瞬間に大魔法へ繋ぐ。奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体へシールド1。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'CASTER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'enemy-066-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'enemy-066-2' },
    ],
  }),
  MTCG_MAGIC_ENEMY_067: defineMagicUnitProgram('MTCG_MAGIC_ENEMY_067', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '星災の女王は星光と星脈を重ねる。ライフ半分以下なら味方全体へシールド2、空きレーンがあれば敵支援を2削る。',
    tags: ['MAGIC', 'UNIT', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'LIFE_BELOW_HALF', amount: 2, duration: 0, label: 'enemy-067-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 2, duration: 0, label: 'enemy-067-2' },
    ],
  }),
};
