import type { PlacementEffectProgram } from './placementTcgEffectDsl';
import { defineHighSchoolUnitProgram } from './placementTcgUniqueEffectFactory';

export const PLACEMENT_TCG_HIGH_SCHOOL_REST_PROGRAMS: Readonly<Record<string, PlacementEffectProgram>> = {
  MTCG_HIGH_SCHOOL_ENEMY_052: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_052', {
    legacyEffect: 'REGEN',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '剣道部の風紀委員はSPで優位なら正面の相手を面で制し、中央では同じレーンの支援まで取り締まる。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'KENDO_DISCIPLINE'],
    steps: [
      { action: 'STUN', target: 'ENEMY_SAME_LANE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'kendo-discipline-men' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_SAME_LANE', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'kendo-discipline-confiscate' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_053: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_053', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白衣の査問官は被弾すると相手の支援を検査して破壊し、SPで優位なら証拠を1枚押収する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'WHITECOAT_INQUISITOR'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'inquisitor-inspect' },
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'inquisitor-evidence' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_054: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_054', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '禁書管理の書記は中央で禁書を1枚記録し、SPで優位なら敵支援を禁書指定して破棄する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'FORBIDDEN_ARCHIVE'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'archive-record' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'archive-ban' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_055: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_055', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '銀髪の審査員は中央で撃退すると評価点をSPに変え、SP優位なら味方1体へ合格判定の攻撃強化を与える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEFEAT', 'SILVER_JUDGE'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'judge-score' },
      { action: 'BUFF_ATTACK', target: 'OWN_ANY', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'judge-pass' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_056: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_056', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '鎖の執行部員はSPで優位なら敵1体を拘束し、中央では鎖を敵支援へ伸ばして耐久を削る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'CHAIN_EXECUTOR'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'chain-bind' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'chain-seize' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_057: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_057', {
    legacyEffect: 'PIERCE',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '赤章の副会長はSP優位で直接攻撃を通すと相手ライフへ追加圧力をかけ、中央では味方全体へ権威の防壁を張る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'RED_BADGE_VICE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vice-pressure' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vice-authority' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_058: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_058', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '実験区画の主任は中央で被弾すると反応薬を敵1体へ返し、危険域では失敗データからカードを1枚得る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'LAB_SUPERVISOR'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'lab-counter-reaction' },
      { action: 'DRAW', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'lab-risk-data' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_059: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_059', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '表彰台の王子はSP優位で登場すると味方全体を鼓舞し、中央の表彰台では自身へ防壁も得る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'PODIUM_PRINCE'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'podium-speech' },
      { action: 'SHIELD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'podium-guard' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_060: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_060', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '紅衣の監察官はSP優位なら敵支援を一斉監査し、中央では正面の敵へ処分ダメージを与える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'CRIMSON_INSPECTOR'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'crimson-audit' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'crimson-sanction' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_061: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_061', {
    legacyEffect: 'RUSH',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '冬制服の支配者はSP優位の直接攻撃で敵全体を凍らせるが、追い込まれると次の策を求めてカードを引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'WINTER_RULER'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'winter-freeze' },
      { action: 'DRAW', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'winter-contingency' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_062: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_062', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '紫扇の評議員はSP優位なら味方全体を扇で守り、中央では審議記録を1枚手札へ加える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'PURPLE_COUNCIL'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'council-fan-guard' },
      { action: 'DRAW', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'council-minutes' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_063: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_063', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '黒翼の番長は追い込まれるほど敵全体へ荒々しく当たり、SP優位なら自身の攻撃力まで一時的に高める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'BLACKWING_BOSS'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'blackwing-rampage' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'blackwing-dominance' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_064: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_064', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '校長は中央から朝礼を行い味方全体を強化し、SP優位なら学校運営の主導権をさらにSPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'PRINCIPAL_RULE'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 1, label: 'principal-assembly' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'principal-authority' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_065: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_065', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '真・校長は撃退のたびSP優位なら相手ライフを吸い上げ、中央では敵支援を一斉に無効化する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEFEAT', 'TRUE_PRINCIPAL'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'true-principal-drain' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'true-principal-purge' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_066: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_066', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '新米風紀委員は被弾すると味方1体をかばい、SP優位なら学んだばかりの規律で敵1体を止める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'ROOKIE_DISCIPLINE'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'rookie-cover' },
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'rookie-warning' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_067: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_067', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '竹刀の体育係は正面の敵を竹刀でひるませ、SP優位ならその勢いで自身の攻撃力を高める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'SHINAI_PE'],
    steps: [
      { action: 'STUN', target: 'ENEMY_SAME_LANE', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'shinai-check' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'shinai-pressure' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_068: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_068', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '赤ペン監督生は直接攻撃後に敵支援を添削し、中央では採点記録を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'RED_PEN_PROCTOR'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'red-proctor-correct' },
      { action: 'DRAW', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'red-proctor-record' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_069: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_069', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '図書委員の番人は中央で書架を盾に味方全体を守り、敵が残っていれば監視記録を1枚増やす。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'LIBRARY_GUARD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'library-guard-shelves' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'library-guard-log' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_070: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_070', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '購買部の用心棒はSP優位で登場すると体力を一時的に増やし、正面の敵へ強引に割り込む。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'CANTEEN_BODYGUARD'],
    steps: [
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'canteen-bodyguard-bulk' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'canteen-bodyguard-shove' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_071: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_071', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '軽音部の刺客は攻撃後に空きレーンへステージ移動し、SP優位ならアンプの勢いで相手ライフを削る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'LIGHT_MUSIC_ASSASSIN'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'light-music-stage-step' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'light-music-feedback' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_072: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_072', {
    legacyEffect: 'REGEN',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: 'バスケ部の壁は中央で被弾すると守備姿勢を固め、SP優位ならリバウンドからSPを得る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'BASKETBALL_WALL'],
    steps: [
      { action: 'SHIELD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'basket-wall-block' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'basket-wall-rebound' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_073: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_073', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '化学部の実験兵はSP優位で被弾すると反応液を敵全体へ撒き、危険域では薬品で自身の体力を一時増強する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'CHEMISTRY_TROOPER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'chem-trooper-splash' },
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 1, label: 'chem-trooper-serum' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_074: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_074', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '新聞部の追跡者はSP優位なら朝刊のネタを1枚確保し、中央では追跡対象の敵1体を足止めする。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'NEWSPAPER_TRACKER'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'newspaper-scoop' },
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'newspaper-tail' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_075: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_075', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '生徒会の斥候は直接攻撃後、空きレーンからSPを確保し、SP優位なら敵支援の配置情報を使って破壊する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'COUNCIL_SCOUT'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'council-scout-route' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'council-scout-sabotage' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_076: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_076', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '剣道場の門番は中央で正面の敵を止め、味方がいれば道場全体へ守りを広げる。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'DOJO_GATEKEEPER'],
    steps: [
      { action: 'STUN', target: 'ENEMY_SAME_LANE', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'dojo-stop' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'dojo-guard' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_077: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_077', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '応援団の番長は窮地で味方全体を奮い立たせ、SP優位なら応援の熱を追加SPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'CHEER_BOSS'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 1, label: 'cheer-rally' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'cheer-momentum' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_078: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_078', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '保健委員の執行者は中央で味方1体を処置し、SP優位ならそのまま味方全体へ防護を広げる。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'HEALTH_EXECUTOR'],
    steps: [
      { action: 'HEAL', target: 'OWN_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'health-executor-treat' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'health-executor-protect' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_079: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_079', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '美術部の幻術師は登場時に空きレーンへ幻像ごと移り、SP優位なら敵全体の視界を奪って動きを止める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'ART_ILLUSIONIST'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'art-illusion-shift' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'art-illusion-blind' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_080: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_080', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '吹奏楽部の号令手はSP優位なら味方全体へテンポを与え、正面の敵へ号令を浴びせて動きを止める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'BAND_COMMANDER'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'band-command-tempo' },
      { action: 'STUN', target: 'ENEMY_SAME_LANE', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'band-command-blast' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_081: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_081', {
    legacyEffect: 'RUSH',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '放送部の支配者はSP優位なら校内放送で敵全体を止め、敵が残っていれば次の原稿を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'BROADCAST_RULER'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'broadcast-ruler-lock' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'broadcast-ruler-script' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_082: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_082', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '進路指導の補佐は中央で進路資料を1枚整理し、SP優位なら面談の主導権を追加SPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'CAREER_ASSISTANT'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'career-assistant-file' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'career-assistant-lead' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_083: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_083', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '数学研究会の刺客はSP優位なら正面の敵へ計算された一撃を与え、中央では解法を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'MATH_ASSASSIN'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'math-assassin-proof' },
      { action: 'DRAW', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'math-assassin-solution' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_084: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_084', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白手袋の監察員はSP優位で被弾すると敵支援を一斉検査し、中央では自身へ防護を張る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'WHITE_GLOVE_INSPECTOR'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'white-glove-audit' },
      { action: 'SHIELD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'white-glove-guard' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_085: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_085', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '文化祭実行委員は味方がいると企画書を1枚増やし、SP優位なら準備の熱気で味方全体の攻撃力を高める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'FESTIVAL_COMMITTEE'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'festival-committee-plan' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'festival-committee-rally' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_086: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_086', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '風紀委員副隊長はSP優位なら敵1体を拘束し、中央では味方1体に護衛を付ける。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'DISCIPLINE_VICE_CAPTAIN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vice-captain-detain' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vice-captain-escort' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_087: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_087', {
    legacyEffect: 'PIERCE',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '剣道部の主将はSP優位で敵を倒すと味方全体を鼓舞し、中央では一本の勢いをSPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEFEAT', 'KENDO_CAPTAIN'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'kendo-captain-rally' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'kendo-captain-ippon' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_088: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_088', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '赤ペン試験官はSP優位の直接攻撃で敵1体へ追試ダメージを与え、中央では同じレーンの支援も赤字訂正する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'RED_PEN_EXAMINER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'examiner-retest' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_SAME_LANE', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'examiner-correction' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_089: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_089', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '禁書庫の司書はSP優位なら禁書を1枚引き、味方がいれば封印棚を味方全体の防壁にする。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'FORBIDDEN_LIBRARIAN'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'forbidden-librarian-read' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'forbidden-librarian-seal' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_090: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_090', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '購買部の番人はSP優位なら自身の体力を一時増やし、正面の敵支援を商品棚ごと壊す。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'CANTEEN_KEEPER'],
    steps: [
      { action: 'BUFF_HEALTH', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'canteen-keeper-stock' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_SAME_LANE', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'canteen-keeper-shove' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_091: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_091', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '軽音部ギタリストは中央でソロを決めると攻撃力を高め、そのまま空きレーンへステージ移動する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'GUITARIST'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 1, label: 'guitar-solo' },
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'guitar-stage-step' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_092: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_092', {
    legacyEffect: 'REGEN',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: 'バスケ部エースは直接攻撃後に空きレーンへ走り込み、SP優位なら速攻の流れを追加SPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'BASKETBALL_ACE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'basket-ace-cut' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'basket-ace-fastbreak' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_093: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_093', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '化学部の白衣兵は中央で被弾すると正面から生命力を吸い、SP優位なら実験記録を1枚確保する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'WHITECOAT_TROOPER'],
    steps: [
      { action: 'LIFE_DRAIN', target: 'ENEMY_SAME_LANE', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'whitecoat-drain' },
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'whitecoat-data' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_094: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_094', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '新聞部カメラマンは敵がいれば証拠写真を1枚撮り、SP優位ならフラッシュで敵1体の動きを止める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'NEWSPAPER_CAMERA'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'camera-scoop' },
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'camera-flash' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_095: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_095', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '生徒会の策士はSP優位をさらにSPへ変換し、中央では盤面を読んで敵支援を一斉に崩す。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'COUNCIL_STRATEGIST'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'strategist-resource' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'strategist-collapse' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_096: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_096', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '茶道部の令嬢はSP優位で登場すると味方全体を一服で整え、中央では自身へ静かな防壁を張る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'TEA_LADY'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'tea-lady-refresh' },
      { action: 'SHIELD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'tea-lady-composure' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_097: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_097', {
    legacyEffect: 'PIERCE',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '弓道部の射手は中央から敵1体を狙い撃ちし、SP優位なら同じレーンの支援まで射抜く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'KYUDO_ARCHER'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'kyudo-shot' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_SAME_LANE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'kyudo-pierce-support' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_098: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_098', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '陸上部の疾走者は直接攻撃後に空きレーンへ駆け抜け、SP優位なら勢いのまま攻撃力を高める。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DIRECT_ATTACK', 'TRACK_RUNNER'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'runner-lane-change' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'runner-sprint' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_099: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_099', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '演劇部の仮面役者は中央に登場すると敵1体を演技で惑わせ、SP優位なら次の台本を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DEPLOY', 'MASKED_ACTOR'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'actor-misdirect' },
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'actor-script' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_100: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_100', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '電算部ハッカーはSP優位なら敵支援を一斉ハックし、空きレーンがあれば盗んだデータを1枚手札へ送る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_START', 'COMPUTER_HACKER'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'hacker-breach' },
      { action: 'DRAW', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'hacker-exfiltrate' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_101: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_101', {
    legacyEffect: 'RUSH',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '天文部の予言者は奇数ターンに星図を1枚読み、中央では予測をSPへ変換する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'TURN_END', 'ASTRONOMY_SEER'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'seer-star-chart' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'seer-forecast' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_102: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_102', {
    legacyEffect: 'REGEN',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '園芸委員の剪定者はSP優位なら敵支援を剪定し、中央では味方1体の攻撃力を伸ばす。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'ATTACK', 'GARDEN_PRUNER'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'pruner-cut-support' },
      { action: 'BUFF_ATTACK', target: 'OWN_ANY', condition: 'CENTER_LANE', amount: 1, duration: 1, label: 'pruner-train-growth' },
    ],
  }),
  MTCG_HIGH_SCHOOL_ENEMY_103: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_ENEMY_103', {
    legacyEffect: 'THORNS',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '試験女王はSP優位で被弾すると敵全体を試験停止に追い込み、窮地では相手ライフから点数を吸い取る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'DAMAGED', 'EXAM_QUEEN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'exam-queen-freeze' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'exam-queen-drain-score' },
    ],
  }),
};
