import type { PlacementEffectProgram } from './placementTcgEffectDsl';
import { definePlacementSupportProgram } from './placementTcgUniqueEffectFactory';

export const PLACEMENT_TCG_SUPPORT_PROGRAMS: Readonly<Record<string, PlacementEffectProgram>> = {
  MTCG_SUPPORT_GON_GITSUNE: definePlacementSupportProgram("MTCG_SUPPORT_GON_GITSUNE", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "ごんぎつねは条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "GON_GITSUNE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_GON_KURU: definePlacementSupportProgram("MTCG_SUPPORT_GON_KURU", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "ごんの栗はターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "GON_KURU"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_HYOJU_RIFLE: definePlacementSupportProgram("MTCG_SUPPORT_HYOJU_RIFLE", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "兵十の火縄銃は敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "HYOJU_RIFLE"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_HASHIRE_MELOS: definePlacementSupportProgram("MTCG_SUPPORT_HASHIRE_MELOS", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "走れメロスは喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "HASHIRE_MELOS"],
    steps: [
      { action: "MARK", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_JACHI_BOGYAKU: definePlacementSupportProgram("MTCG_SUPPORT_JACHI_BOGYAKU", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "邪智暴虐は味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "JACHI_BOGYAKU"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "HAS_OWN_UNIT", amount: 2, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_MELOS_TRUST: definePlacementSupportProgram("MTCG_SUPPORT_MELOS_TRUST", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "メロスの信実はSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "MELOS_TRUST"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_KUMO_NO_ITO: definePlacementSupportProgram("MTCG_SUPPORT_KUMO_NO_ITO", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "蜘蛛の糸は魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "KUMO_NO_ITO"],
    steps: [
      { action: "MARK", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_GOKURAKU_HASU: definePlacementSupportProgram("MTCG_SUPPORT_GOKURAKU_HASU", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "極楽の蓮は味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "GOKURAKU_HASU"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_SANGETSUKI: definePlacementSupportProgram("MTCG_SUPPORT_SANGETSUKI", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "山月記は退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "SANGETSUKI"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-defeat-draw" },
      { action: "GAIN_SP", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_TORA_HO: definePlacementSupportProgram("MTCG_SUPPORT_TORA_HO", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "虎咆は魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "TORA_HO"],
    steps: [
      { action: "MARK", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_BOKKO_CHAN: definePlacementSupportProgram("MTCG_SUPPORT_BOKKO_CHAN", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "ボッコちゃんは身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "BOKKO_CHAN"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_SAME_LANE", condition: "HAS_OWN_UNIT", amount: 2, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_OI_DETEKOI: definePlacementSupportProgram("MTCG_SUPPORT_OI_DETEKOI", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "おーい、でてこいは状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "OI_DETEKOI"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_KOROSHIYA: definePlacementSupportProgram("MTCG_SUPPORT_KOROSHIYA", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "殺し屋ですのよは刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "KOROSHIYA"],
    steps: [
      { action: "MARK", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DAMAGE", target: "ENEMY_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_HOSHI_PRESENT: definePlacementSupportProgram("MTCG_SUPPORT_HOSHI_PRESENT", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "星のプレゼントは味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "HOSHI_PRESENT"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_KAGAMI_HOSHI: definePlacementSupportProgram("MTCG_SUPPORT_KAGAMI_HOSHI", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "DEPLOY",
    resetRule: "ONCE_PER_BATTLE",
    identityNote: "鏡 (星新一)はSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "KAGAMI_HOSHI"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ANY", condition: "SP_LEAD", amount: 2, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_YOSEI_HOSHI: definePlacementSupportProgram("MTCG_SUPPORT_YOSEI_HOSHI", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "妖精 (星新一)は条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "YOSEI_HOSHI"],
    steps: [
      { action: "MARK", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_LIFE_MAINTENANCE: definePlacementSupportProgram("MTCG_SUPPORT_LIFE_MAINTENANCE", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "生活維持省はターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "LIFE_MAINTENANCE"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 2, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_SPACE_GREETING: definePlacementSupportProgram("MTCG_SUPPORT_SPACE_GREETING", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "宇宙のあいさつは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "SPACE_GREETING"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_KAIKETSU_ZORORI: definePlacementSupportProgram("MTCG_SUPPORT_KAIKETSU_ZORORI", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "かいけつゾロリは喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "KAIKETSU_ZORORI"],
    steps: [
      { action: "MARK", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_ZENITEN_DO: definePlacementSupportProgram("MTCG_SUPPORT_ZENITEN_DO", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "銭天堂は味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "ZENITEN_DO"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 1, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_HOSHI_NO_OJI: definePlacementSupportProgram("MTCG_SUPPORT_HOSHI_NO_OJI", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "星の王子さまはSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "HOSHI_NO_OJI"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "SP_LEAD", amount: 2, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_MOMO_TIME: definePlacementSupportProgram("MTCG_SUPPORT_MOMO_TIME", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "モモは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "MOMO_TIME"],
    steps: [
      { action: "MARK", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_TIME_THIEF: definePlacementSupportProgram("MTCG_SUPPORT_TIME_THIEF", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "時間どろぼうは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "TIME_THIEF"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 2, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_NEVERENDING_STORY: definePlacementSupportProgram("MTCG_SUPPORT_NEVERENDING_STORY", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "はてしない物語は退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "NEVERENDING_STORY"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-defeat-draw" },
      { action: "DISCARD", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_TOTTO_CHAN: definePlacementSupportProgram("MTCG_SUPPORT_TOTTO_CHAN", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "窓ぎわのトットちゃんは魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "TOTTO_CHAN"],
    steps: [
      { action: "MARK", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_GALAXY_EXPRESS: definePlacementSupportProgram("MTCG_SUPPORT_GALAXY_EXPRESS", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "銀河鉄道の夜は身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "GALAXY_EXPRESS"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 1, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_YODAKA_NO_HOSHI: definePlacementSupportProgram("MTCG_SUPPORT_YODAKA_NO_HOSHI", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "よだかの星は状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "YODAKA_NO_HOSHI"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_MANY_ORDERS: definePlacementSupportProgram("MTCG_SUPPORT_MANY_ORDERS", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "注文の多い料理店は刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "MANY_ORDERS"],
    steps: [
      { action: "MARK", target: "SELF", condition: "CENTER_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "SHIELD", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_BUY_GLOVES: definePlacementSupportProgram("MTCG_SUPPORT_BUY_GLOVES", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "手袋を買いには味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "BUY_GLOVES"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "CENTER_LANE", amount: 2, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_GAUCHE_CELLO: definePlacementSupportProgram("MTCG_SUPPORT_GAUCHE_CELLO", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "ONCE_PER_TURN",
    identityNote: "セロ弾きのゴーシュはSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "GAUCHE_CELLO"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_MINE_BLAST_G: definePlacementSupportProgram("MTCG_SUPPORT_MINE_BLAST_G", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "トロッコ (芥川)は条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "MINE_BLAST_G"],
    steps: [
      { action: "MARK", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_RASHOMON: definePlacementSupportProgram("MTCG_SUPPORT_RASHOMON", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "羅生門はターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "RASHOMON"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_KUMO_NO_ITO_D: definePlacementSupportProgram("MTCG_SUPPORT_KUMO_NO_ITO_D", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "カンダタの叫びは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "KUMO_NO_ITO_D"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_OSAMU_NIGHT: definePlacementSupportProgram("MTCG_SUPPORT_OSAMU_NIGHT", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "人間失格は喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "OSAMU_NIGHT"],
    steps: [
      { action: "MARK", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_GOSHI_REVENGE: definePlacementSupportProgram("MTCG_SUPPORT_GOSHI_REVENGE", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "走れメロス・ラストスパートは味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "GOSHI_REVENGE"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "ODD_TURN", amount: 2, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_KOKORO_SOSEKI: definePlacementSupportProgram("MTCG_SUPPORT_KOKORO_SOSEKI", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "こころはSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "KOKORO_SOSEKI"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_BOTCHAN: definePlacementSupportProgram("MTCG_SUPPORT_BOTCHAN", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "坊っちゃんは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "BOTCHAN"],
    steps: [
      { action: "MARK", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_WAGAHAI_NEKO: definePlacementSupportProgram("MTCG_SUPPORT_WAGAHAI_NEKO", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "吾輩は猫であるは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "WAGAHAI_NEKO"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_DOKKO_CHAN: definePlacementSupportProgram("MTCG_SUPPORT_DOKKO_CHAN", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "どっこいしょは退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "DOKKO_CHAN"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-defeat-draw" },
      { action: "GAIN_SP", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_KITSUNE_NO_MADO: definePlacementSupportProgram("MTCG_SUPPORT_KITSUNE_NO_MADO", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "きてんの窓は魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "KITSUNE_NO_MADO"],
    steps: [
      { action: "MARK", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_KACHIKACHI_YAMA: definePlacementSupportProgram("MTCG_SUPPORT_KACHIKACHI_YAMA", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "かちかち山は身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "KACHIKACHI_YAMA"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_SAME_LANE", condition: "ODD_TURN", amount: 2, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_URASHIMA_TARO: definePlacementSupportProgram("MTCG_SUPPORT_URASHIMA_TARO", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "浦島太郎は状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "URASHIMA_TARO"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_MOMOTARO: definePlacementSupportProgram("MTCG_SUPPORT_MOMOTARO", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "桃太郎は刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "MOMOTARO"],
    steps: [
      { action: "MARK", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DAMAGE", target: "ENEMY_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_KAGUYA_HIME: definePlacementSupportProgram("MTCG_SUPPORT_KAGUYA_HIME", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "かぐや姫は味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "KAGUYA_HIME"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_HANASAKA_JIISAN: definePlacementSupportProgram("MTCG_SUPPORT_HANASAKA_JIISAN", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "ONCE_PER_TURN",
    identityNote: "花咲かじいさんはSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "HANASAKA_JIISAN"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ANY", condition: "SP_LEAD", amount: 2, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_KASA_JIZO: definePlacementSupportProgram("MTCG_SUPPORT_KASA_JIZO", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "かさじぞうは条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "ALLY_DEFEATED", "KASA_JIZO"],
    steps: [
      { action: "MARK", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_ISSUN_BOSHI: definePlacementSupportProgram("MTCG_SUPPORT_ISSUN_BOSHI", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "一寸法師はターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "ALLY_DEFEATED", "ISSUN_BOSHI"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "HAS_OWN_UNIT", amount: 2, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_TSURU_ONGAESHI: definePlacementSupportProgram("MTCG_SUPPORT_TSURU_ONGAESHI", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "鶴の恩返しは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "ALLY_DEFEATED", "TSURU_ONGAESHI"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ALL", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_OMUSUBI_KORORIN: definePlacementSupportProgram("MTCG_SUPPORT_OMUSUBI_KORORIN", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "おむすびころりんは喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "ALLY_DEFEATED", "OMUSUBI_KORORIN"],
    steps: [
      { action: "MARK", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_NEZUMI_NO_YOMEIRI: definePlacementSupportProgram("MTCG_SUPPORT_NEZUMI_NO_YOMEIRI", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "ねずみの嫁入りは味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "ALLY_DEFEATED", "NEZUMI_NO_YOMEIRI"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "HAS_OWN_UNIT", amount: 1, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_SUNFLOWER: definePlacementSupportProgram("MTCG_SUPPORT_SUNFLOWER", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "ヒマワリはSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "ALLY_DEFEATED", "SUNFLOWER"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "SP_LEAD", amount: 2, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_CACTUS: definePlacementSupportProgram("MTCG_SUPPORT_CACTUS", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "サボテンは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "ALLY_DEFEATED", "CACTUS"],
    steps: [
      { action: "MARK", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_ROSE: definePlacementSupportProgram("MTCG_SUPPORT_ROSE", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "バラは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "ALLY_DEFEATED", "ROSE"],
    steps: [
      { action: "SHIELD", target: "OWN_ALL", condition: "HAS_OWN_UNIT", amount: 2, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_GIANT_VINE: definePlacementSupportProgram("MTCG_SUPPORT_GIANT_VINE", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "巨大なツルは退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "ALLY_DEFEATED", "GIANT_VINE"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-defeat-draw" },
      { action: "DISCARD", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_MANDRAKE_ROOT: definePlacementSupportProgram("MTCG_SUPPORT_MANDRAKE_ROOT", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "マンドレイクは魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "ALLY_DEFEATED", "MANDRAKE_ROOT"],
    steps: [
      { action: "MARK", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_PEA_SHOOTER: definePlacementSupportProgram("MTCG_SUPPORT_PEA_SHOOTER", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "豆鉄砲は身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "ALLY_DEFEATED", "PEA_SHOOTER"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "HAS_OWN_UNIT", amount: 1, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_RIPE_TOMATO: definePlacementSupportProgram("MTCG_SUPPORT_RIPE_TOMATO", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "完熟トマトは状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "ALLY_DEFEATED", "RIPE_TOMATO"],
    steps: [
      { action: "HEAL", target: "OWN_ALL", condition: "SP_LEAD", amount: 2, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_IRON_PUMPKIN: definePlacementSupportProgram("MTCG_SUPPORT_IRON_PUMPKIN", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "鉄壁カボチャは刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "ALLY_DEFEATED", "IRON_PUMPKIN"],
    steps: [
      { action: "MARK", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "SHIELD", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_HOT_CHILI: definePlacementSupportProgram("MTCG_SUPPORT_HOT_CHILI", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "激辛トウガラシは味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "ALLY_DEFEATED", "HOT_CHILI"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "HAS_OWN_UNIT", amount: 2, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_GOLDEN_WHEAT: definePlacementSupportProgram("MTCG_SUPPORT_GOLDEN_WHEAT", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "ALLY_DEFEATED",
    resetRule: "ONCE_PER_TURN",
    identityNote: "黄金の小麦はSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "ALLY_DEFEATED", "GOLDEN_WHEAT"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "SP_LEAD", amount: 1, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_SACRED_LOTUS: definePlacementSupportProgram("MTCG_SUPPORT_SACRED_LOTUS", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "聖なるハスは条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "SACRED_LOTUS"],
    steps: [
      { action: "MARK", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_LUCKY_CLOVER: definePlacementSupportProgram("MTCG_SUPPORT_LUCKY_CLOVER", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "四つ葉のクローバーはターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "LUCKY_CLOVER"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_POISON_IVY: definePlacementSupportProgram("MTCG_SUPPORT_POISON_IVY", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "毒蔦アイビーは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "POISON_IVY"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "CENTER_LANE", amount: 2, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_TULIP_DRAW: definePlacementSupportProgram("MTCG_SUPPORT_TULIP_DRAW", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "魅惑のチューリップは喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "TULIP_DRAW"],
    steps: [
      { action: "MARK", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_STURDY_BAMBOO: definePlacementSupportProgram("MTCG_SUPPORT_STURDY_BAMBOO", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "剛健な竹は味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "STURDY_BAMBOO"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "EMPTY_LANE", amount: 2, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_SAKURA_STORM: definePlacementSupportProgram("MTCG_SUPPORT_SAKURA_STORM", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "さくら吹雪はSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "SAKURA_STORM"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_ETERNAL_PINE: definePlacementSupportProgram("MTCG_SUPPORT_ETERNAL_PINE", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "不老長寿のマツは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "ETERNAL_PINE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_CRIMSON_MAPLE: definePlacementSupportProgram("MTCG_SUPPORT_CRIMSON_MAPLE", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "真紅のモミジは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "CRIMSON_MAPLE"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_HOLY_GARLIC: definePlacementSupportProgram("MTCG_SUPPORT_HOLY_GARLIC", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "魔除けのニンニクは退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "HOLY_GARLIC"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "CENTER_LANE", amount: 2, duration: 0, label: "high-defeat-draw" },
      { action: "GAIN_SP", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_HEALING_GINGER: definePlacementSupportProgram("MTCG_SUPPORT_HEALING_GINGER", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "癒やしのショウガは魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "HEALING_GINGER"],
    steps: [
      { action: "MARK", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_CALM_LAVENDER: definePlacementSupportProgram("MTCG_SUPPORT_CALM_LAVENDER", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "安らぎのラベンダーは身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "CALM_LAVENDER"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_SAME_LANE", condition: "EMPTY_LANE", amount: 2, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_GREAT_OAK: definePlacementSupportProgram("MTCG_SUPPORT_GREAT_OAK", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "大樹のカシは状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "GREAT_OAK"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_MORNING_GLORY: definePlacementSupportProgram("MTCG_SUPPORT_MORNING_GLORY", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "朝露のアサガオは刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "TURN_START", "MORNING_GLORY"],
    steps: [
      { action: "MARK", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DAMAGE", target: "ENEMY_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_RAINBOW_HYDRANGEA: definePlacementSupportProgram("MTCG_SUPPORT_RAINBOW_HYDRANGEA", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "七変化のアジサイは味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_START", "RAINBOW_HYDRANGEA"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_ECHO_BLUEBELL: definePlacementSupportProgram("MTCG_SUPPORT_ECHO_BLUEBELL", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_START",
    resetRule: "EVERY_TRIGGER",
    identityNote: "響き渡る鈴蘭はSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_START", "ECHO_BLUEBELL"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ANY", condition: "CENTER_LANE", amount: 2, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_FORBIDDEN_APPLE: definePlacementSupportProgram("MTCG_SUPPORT_FORBIDDEN_APPLE", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "禁断のリンゴは条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "FORBIDDEN_APPLE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_SOLAR_ORANGE: definePlacementSupportProgram("MTCG_SUPPORT_SOLAR_ORANGE", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "太陽のオレンジはターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "SOLAR_ORANGE"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "LIFE_BELOW_HALF", amount: 2, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_RICH_GRAPE: definePlacementSupportProgram("MTCG_SUPPORT_RICH_GRAPE", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "芳醇なブドウは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "RICH_GRAPE"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_LAYERED_CABBAGE: definePlacementSupportProgram("MTCG_SUPPORT_LAYERED_CABBAGE", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "幾重のキャベツは喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "LAYERED_CABBAGE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_SWORD_DAIKON: definePlacementSupportProgram("MTCG_SUPPORT_SWORD_DAIKON", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "斬鉄ダイコンは味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "SWORD_DAIKON"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "LIFE_BELOW_HALF", amount: 1, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_MYSTIC_MUSHROOM: definePlacementSupportProgram("MTCG_SUPPORT_MYSTIC_MUSHROOM", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "幻覚キノコはSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "MYSTIC_MUSHROOM"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 2, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_SACRED_LILY: definePlacementSupportProgram("MTCG_SUPPORT_SACRED_LILY", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "純白のユリは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "SACRED_LILY"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_WINTER_CAMELLIA: definePlacementSupportProgram("MTCG_SUPPORT_WINTER_CAMELLIA", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "冬枯れのツバキは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "WINTER_CAMELLIA"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "LIFE_BELOW_HALF", amount: 2, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_AUTUMN_COSMOS: definePlacementSupportProgram("MTCG_SUPPORT_AUTUMN_COSMOS", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "秋空のコスモスは退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "AUTUMN_COSMOS"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 1, duration: 0, label: "high-defeat-draw" },
      { action: "DISCARD", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_FLUFFY_DANDELION: definePlacementSupportProgram("MTCG_SUPPORT_FLUFFY_DANDELION", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "綿毛のタンポポは魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "FLUFFY_DANDELION"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-attack-surge" },
    ],
  }),
  MTCG_SUPPORT_WISDOM_GINKGO: definePlacementSupportProgram("MTCG_SUPPORT_WISDOM_GINKGO", "ELEMENTARY", {
    legacyEffect: "HEALTH_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "知恵のイチョウは身近な守りとして味方の体力を底上げし、傷ついた仲間を分かりやすく支える。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "WISDOM_GINKGO"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_SAME_LANE", condition: "LIFE_BELOW_HALF", amount: 1, duration: 1, label: "elementary-health-aura" },
      { action: "HEAL", target: "OWN_ANY", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-health-care" },
    ],
  }),
  MTCG_SUPPORT_CAUSTIC_WASABI: definePlacementSupportProgram("MTCG_SUPPORT_CAUSTIC_WASABI", "HIGH_SCHOOL", {
    legacyEffect: "TURN_HEAL",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "劇薬ワサビは状況判断で味方を回復し、盤面の余裕をSPへ変えて主導権を伸ばす。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "CAUSTIC_WASABI"],
    steps: [
      { action: "HEAL", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 2, duration: 0, label: "high-turn-recover" },
      { action: "GAIN_SP", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-turn-resource" },
    ],
  }),
  MTCG_SUPPORT_POWER_SHIITAKE: definePlacementSupportProgram("MTCG_SUPPORT_POWER_SHIITAKE", "MAGIC", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "剛力のシイタケは刻んだ魔力印を解放し、全体防壁または全体反撃へ変換する。",
    tags: ["MAGIC", 'SUPPORT', "TURN_END", "POWER_SHIITAKE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_OWN_UNIT", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "SHIELD", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-ward-release" },
    ],
  }),
  MTCG_SUPPORT_BOUNTY_PERSIMMON: definePlacementSupportProgram("MTCG_SUPPORT_BOUNTY_PERSIMMON", "ELEMENTARY", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "豊穣のカキは味方の退場や節目を次の1枚へつなぎ、残った仲間を回復して立て直す。",
    tags: ["ELEMENTARY", 'SUPPORT', "TURN_END", "BOUNTY_PERSIMMON"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "LIFE_BELOW_HALF", amount: 2, duration: 0, label: "elementary-defeat-draw" },
      { action: "HEAL", target: "OWN_ANY", condition: "ODD_TURN", amount: 1, duration: 0, label: "elementary-next-friend" },
    ],
  }),
  MTCG_SUPPORT_EARLY_PLUM: definePlacementSupportProgram("MTCG_SUPPORT_EARLY_PLUM", "HIGH_SCHOOL", {
    legacyEffect: "ATTACK_AURA",
    trigger: "TURN_END",
    resetRule: "EVERY_TRIGGER",
    identityNote: "早咲きのウメはSP差や配置を攻撃支援へ変え、さらに敵支援へ圧力をかけて攻め筋を作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "TURN_END", "EARLY_PLUM"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_ANY", condition: "LIFE_BELOW_HALF", amount: 1, duration: 1, label: "high-attack-push" },
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-attack-pressure" },
    ],
  }),
  MTCG_SUPPORT_AWAKE_COFFEE: definePlacementSupportProgram("MTCG_SUPPORT_AWAKE_COFFEE", "MAGIC", {
    legacyEffect: "HEALTH_AURA",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "覚醒のコーヒーは条件を満たすと魔力の印を刻み、その印を媒介に味方全体の体力を高める。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "AWAKE_COFFEE"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_ENEMY", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_HEALTH", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 1, label: "magic-health-bloom" },
    ],
  }),
  MTCG_SUPPORT_SWEET_CACAO: definePlacementSupportProgram("MTCG_SUPPORT_SWEET_CACAO", "ELEMENTARY", {
    legacyEffect: "TURN_HEAL",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "魅惑のカカオはターンの流れに合わせて味方を回復し、続けて小さな守りを与える。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "SWEET_CACAO"],
    steps: [
      { action: "HEAL", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-turn-heal" },
      { action: "SHIELD", target: "OWN_ANY", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-turn-guard" },
    ],
  }),
  MTCG_SUPPORT_EXPLOSIVE_PEPPER: definePlacementSupportProgram("MTCG_SUPPORT_EXPLOSIVE_PEPPER", "HIGH_SCHOOL", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "爆炎のコショウは敵支援へ干渉して守りを崩し、その隙に味方へ防壁を張る高校編らしい対支援策。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "EXPLOSIVE_PEPPER"],
    steps: [
      { action: "BREAK_SUPPORT", target: "ENEMY_ANY", condition: "EMPTY_LANE", amount: 2, duration: 0, label: "high-ward-interfere" },
      { action: "SHIELD", target: "OWN_ANY", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-ward-cover" },
    ],
  }),
  MTCG_SUPPORT_WILLOW_WIND: definePlacementSupportProgram("MTCG_SUPPORT_WILLOW_WIND", "MAGIC", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "柳に風は喪失や転機を魔力印として記録し、印が残れば新たなカードを引き寄せる。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "WILLOW_WIND"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_ENEMY", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "DRAW", target: "SELF", condition: "AFTER_MARK", amount: 1, duration: 0, label: "magic-memory-draw" },
    ],
  }),
  MTCG_SUPPORT_IRON_CYPRESS: definePlacementSupportProgram("MTCG_SUPPORT_IRON_CYPRESS", "ELEMENTARY", {
    legacyEffect: "ATTACK_AURA",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "鉄壁のヒノキは味方の攻撃を後押しし、攻めた後も守りを残す分かりやすい盤面支援を行う。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "IRON_CYPRESS"],
    steps: [
      { action: "BUFF_ATTACK", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 2, duration: 1, label: "elementary-attack-aura" },
      { action: "SHIELD", target: "OWN_ANY", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-attack-cover" },
    ],
  }),
  MTCG_SUPPORT_MEDICINAL_ALOE: definePlacementSupportProgram("MTCG_SUPPORT_MEDICINAL_ALOE", "HIGH_SCHOOL", {
    legacyEffect: "HEALTH_AURA",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "医薬のアロエはSPや配置の優位を味方の耐久へ投資し、手札も補って次の展開につなげる。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "MEDICINAL_ALOE"],
    steps: [
      { action: "BUFF_HEALTH", target: "OWN_ANY", condition: "EMPTY_LANE", amount: 1, duration: 1, label: "high-health-invest" },
      { action: "DRAW", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-health-plan" },
    ],
  }),
  MTCG_SUPPORT_REFRESH_MINT: definePlacementSupportProgram("MTCG_SUPPORT_REFRESH_MINT", "MAGIC", {
    legacyEffect: "TURN_HEAL",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "清涼のミントは魔力の印を起点に回復波を広げ、味方全体をまとめて癒やす。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "REFRESH_MINT"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_ENEMY", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "HEAL", target: "OWN_ALL", condition: "AFTER_MARK", amount: 2, duration: 0, label: "magic-healing-wave" },
    ],
  }),
  MTCG_SUPPORT_FRAGRANT_JASMINE: definePlacementSupportProgram("MTCG_SUPPORT_FRAGRANT_JASMINE", "ELEMENTARY", {
    legacyEffect: "DAMAGE_WARD",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "香華のジャスミンは味方を守る壁になり、守りが整うと敵1体へ小さく反撃する。",
    tags: ["ELEMENTARY", 'SUPPORT', "DEPLOY", "FRAGRANT_JASMINE"],
    steps: [
      { action: "SHIELD", target: "OWN_SAME_LANE", condition: "CENTER_LANE", amount: 1, duration: 0, label: "elementary-damage-ward" },
      { action: "DAMAGE", target: "ENEMY_ANY", condition: "EMPTY_LANE", amount: 1, duration: 0, label: "elementary-counter" },
    ],
  }),
  MTCG_SUPPORT_ULTIMATE_BONSAI: definePlacementSupportProgram("MTCG_SUPPORT_ULTIMATE_BONSAI", "HIGH_SCHOOL", {
    legacyEffect: "DRAW_ON_DEFEAT",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "至高の盆栽は退場や節目を手札補充へ変え、SP獲得または手札コストでリスクと見返りを作る。",
    tags: ["HIGH_SCHOOL", 'SUPPORT', "DEPLOY", "ULTIMATE_BONSAI"],
    steps: [
      { action: "DRAW", target: "SELF", condition: "EMPTY_LANE", amount: 2, duration: 0, label: "high-defeat-draw" },
      { action: "GAIN_SP", target: "SELF", condition: "SP_LEAD", amount: 1, duration: 0, label: "high-hand-tradeoff" },
    ],
  }),
  MTCG_SUPPORT_YGGDRASIL: definePlacementSupportProgram("MTCG_SUPPORT_YGGDRASIL", "MAGIC", {
    legacyEffect: "ATTACK_AURA",
    trigger: "DEPLOY",
    resetRule: "EVERY_TRIGGER",
    identityNote: "ユグドラシルは魔力印を共鳴させ、印が有効な間に味方全体の攻撃力を高める。",
    tags: ["MAGIC", 'SUPPORT', "DEPLOY", "YGGDRASIL"],
    steps: [
      { action: "MARK", target: "SELF", condition: "HAS_ENEMY", amount: 1, duration: 0, label: "magic-support-mark" },
      { action: "BUFF_ATTACK", target: "OWN_ALL", condition: "AFTER_MARK", amount: 1, duration: 1, label: "magic-attack-surge" },
    ],
  }),
};
