import type { PlacementEffectProgram } from './placementTcgEffectDsl';
import { definePlacementEventProgram } from './placementTcgUniqueEffectFactory';

export const PLACEMENT_TCG_EVENT_PROGRAMS: Readonly<Record<string, PlacementEffectProgram>> = {
  MTCG_EVENT_KOKUGO_SYUKUGO: definePlacementEventProgram('MTCG_EVENT_KOKUGO_SYUKUGO', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '四字熟語は言葉と読解を題材に、直感的な一手としてすぐにカードを1枚引く、味方がいればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-kokugo-syukugo-1' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-kokugo-syukugo-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_KOTOWAZA: definePlacementEventProgram('MTCG_EVENT_KOKUGO_KOTOWAZA', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'ことわざの知恵は言葉と読解を題材に、SP差と盤面判断を絡めて中央を押さえていれば味方全体を1回復、空きレーンがあれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-kokugo-kotowaza-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-kotowaza-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_GOKAN: definePlacementEventProgram('MTCG_EVENT_KOKUGO_GOKAN', 'MAGIC', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '五感の表現は言葉と読解を題材に、魔力の条件を重ねてライフ半分以下なら魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を1上げる。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-kokugo-gokan-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 2, label: 'event-kokugo-gokan-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_KANJI_TEST: definePlacementEventProgram('MTCG_EVENT_KOKUGO_KANJI_TEST', 'ELEMENTARY', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '漢字小テストは言葉と読解を題材に、直感的な一手として空きレーンがあれば位置を移す、奇数ターンならSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-kanji-test-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-kokugo-kanji-test-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_MANYO: definePlacementEventProgram('MTCG_EVENT_KOKUGO_MANYO', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '万葉の歌は言葉と読解を題材に、SP差と盤面判断を絡めて敵がいれば敵全体を停止、SP優位なら手札を1枚失う。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-kokugo-manyo-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-kokugo-manyo-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_NIKKI: definePlacementEventProgram('MTCG_EVENT_KOKUGO_NIKKI', 'MAGIC', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '観察日記は言葉と読解を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば敵支援を1削る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-kokugo-nikki-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-kokugo-nikki-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_SYODO: definePlacementEventProgram('MTCG_EVENT_KOKUGO_SYODO', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '止め・跳ね・払いは言葉と読解を題材に、直感的な一手としてすぐに位置を移す、味方がいれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-kokugo-syodo-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-kokugo-syodo-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_DICTIONARY: definePlacementEventProgram('MTCG_EVENT_KOKUGO_DICTIONARY', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '国語辞典は言葉と読解を題材に、SP差と盤面判断を絡めて中央を押さえていればSPを1得る、空きレーンがあれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-kokugo-dictionary-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-dictionary-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_SYOSETSU: definePlacementEventProgram('MTCG_EVENT_KOKUGO_SYOSETSU', 'MAGIC', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '未完の小説は言葉と読解を題材に、魔力の条件を重ねて奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体へシールド2。',
    tags: ['MAGIC', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-kokugo-syosetsu-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-kokugo-syosetsu-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_SYUJI: definePlacementEventProgram('MTCG_EVENT_KOKUGO_SYUJI', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '精神統一は言葉と読解を題材に、直感的な一手として空きレーンがあれば敵1体へ1ダメージ、奇数ターンなら敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-syuji-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-kokugo-syuji-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_KOTONOHA: definePlacementEventProgram('MTCG_EVENT_KOKUGO_KOTONOHA', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '言の葉は言葉と読解を題材に、SP差と盤面判断を絡めて敵がいればカードを1枚引く、SP優位なら位置を移す。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-kokugo-kotonoha-1' },
      { action: 'MOVE', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-kokugo-kotonoha-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_HAIKU: definePlacementEventProgram('MTCG_EVENT_KOKUGO_HAIKU', 'MAGIC', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '五七五は言葉と読解を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば味方全体を1回復。',
    tags: ['MAGIC', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-kokugo-haiku-1' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-kokugo-haiku-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_RITOKU: definePlacementEventProgram('MTCG_EVENT_KOKUGO_RITOKU', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '読解力は言葉と読解を題材に、直感的な一手としてすぐに味方全体の攻撃力を1上げる、味方がいれば敵支援全体を1削る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 1, label: 'event-kokugo-ritoku-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-kokugo-ritoku-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_BUNPO: definePlacementEventProgram('MTCG_EVENT_KOKUGO_BUNPO', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '主語と述語は言葉と読解を題材に、SP差と盤面判断を絡めて中央を押さえていれば位置を移す、空きレーンがあれば敵1体へ1ダメージ。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-kokugo-bunpo-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-bunpo-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_RODOKU: definePlacementEventProgram('MTCG_EVENT_KOKUGO_RODOKU', 'MAGIC', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '朗読は言葉と読解を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-kokugo-rodoku-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-kokugo-rodoku-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_GOKO: definePlacementEventProgram('MTCG_EVENT_KOKUGO_GOKO', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '五光は言葉と読解を題材に、直感的な一手として空きレーンがあれば敵支援を1削る、奇数ターンなら相手ライフへ1ダメージ。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-goko-1' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-kokugo-goko-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_SAKUBUN: definePlacementEventProgram('MTCG_EVENT_KOKUGO_SAKUBUN', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '読書感想文は言葉と読解を題材に、SP差と盤面判断を絡めて敵がいれば位置を移す、SP優位なら相手ライフから1吸収。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-kokugo-sakubun-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-kokugo-sakubun-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_MOJI: definePlacementEventProgram('MTCG_EVENT_KOKUGO_MOJI', 'MAGIC', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '文字の嵐は言葉と読解を題材に、魔力の条件を重ねてライフ半分以下なら魔力刻印を残す、刻印が残っていればSPを1得る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-kokugo-moji-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-kokugo-moji-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_YOMITOKI: definePlacementEventProgram('MTCG_EVENT_KOKUGO_YOMITOKI', 'ELEMENTARY', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '行間を読むは言葉と読解を題材に、直感的な一手としてすぐに味方全体へシールド1、味方がいればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-kokugo-yomitoki-1' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-kokugo-yomitoki-2' },
    ],
  }),
  MTCG_EVENT_KOKUGO_TENREI: definePlacementEventProgram('MTCG_EVENT_KOKUGO_TENREI', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '天礼は言葉と読解を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵全体へ1ダメージ、空きレーンがあれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-kokugo-tenrei-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-kokugo-tenrei-2' },
    ],
  }),
  MTCG_EVENT_SANSU_CALC_SPEED: definePlacementEventProgram('MTCG_EVENT_SANSU_CALC_SPEED', 'MAGIC', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '暗算は数式と図形を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていればカードを2枚引く。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-sansu-calc-speed-1' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-sansu-calc-speed-2' },
    ],
  }),
  MTCG_EVENT_SANSU_TRIANGLE: definePlacementEventProgram('MTCG_EVENT_SANSU_TRIANGLE', 'ELEMENTARY', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '三角定規は数式と図形を題材に、直感的な一手として空きレーンがあれば味方全体を1回復、奇数ターンならSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-triangle-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-triangle-2' },
    ],
  }),
  MTCG_EVENT_SANSU_COMPASS: definePlacementEventProgram('MTCG_EVENT_SANSU_COMPASS', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'コンパス円舞は数式と図形を題材に、SP差と盤面判断を絡めて敵がいれば味方全体の攻撃力を1上げる、SP優位なら味方全体の攻撃力を1上げる。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 1, label: 'event-sansu-compass-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'event-sansu-compass-2' },
    ],
  }),
  MTCG_EVENT_SANSU_PROTRACTOR: definePlacementEventProgram('MTCG_EVENT_SANSU_PROTRACTOR', 'MAGIC', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '分度器アタックは数式と図形を題材に、魔力の条件を重ねて奇数ターンなら魔力刻印を残す、刻印が残っていれば位置を移す。',
    tags: ['MAGIC', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-protractor-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-sansu-protractor-2' },
    ],
  }),
  MTCG_EVENT_SANSU_KUKU: definePlacementEventProgram('MTCG_EVENT_SANSU_KUKU', 'ELEMENTARY', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '九九の連鎖は数式と図形を題材に、直感的な一手としてすぐに敵1体を停止、味方がいれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-sansu-kuku-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-sansu-kuku-2' },
    ],
  }),
  MTCG_EVENT_SANSU_SOROBAN: definePlacementEventProgram('MTCG_EVENT_SANSU_SOROBAN', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'そろばんは数式と図形を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵支援全体を1削る、空きレーンがあれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-sansu-soroban-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-soroban-2' },
    ],
  }),
  MTCG_EVENT_SANSU_DIVISION: definePlacementEventProgram('MTCG_EVENT_SANSU_DIVISION', 'MAGIC', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '割り算は数式と図形を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば位置を移す。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-sansu-division-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-sansu-division-2' },
    ],
  }),
  MTCG_EVENT_SANSU_MULTIPLICATION: definePlacementEventProgram('MTCG_EVENT_SANSU_MULTIPLICATION', 'ELEMENTARY', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '倍々ゲームは数式と図形を題材に、直感的な一手として空きレーンがあればSPを1得る、奇数ターンなら敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-multiplication-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-multiplication-2' },
    ],
  }),
  MTCG_EVENT_SANSU_ZERO: definePlacementEventProgram('MTCG_EVENT_SANSU_ZERO', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'ゼロの発見は数式と図形を題材に、SP差と盤面判断を絡めて敵がいれば味方全体へシールド2、SP優位なら位置を移す。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-sansu-zero-1' },
      { action: 'MOVE', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-sansu-zero-2' },
    ],
  }),
  MTCG_EVENT_SANSU_INFINITY: definePlacementEventProgram('MTCG_EVENT_SANSU_INFINITY', 'MAGIC', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '無限大は数式と図形を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていれば敵全体へ1ダメージ。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-sansu-infinity-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-sansu-infinity-2' },
    ],
  }),
  MTCG_EVENT_SANSU_PERCENT: definePlacementEventProgram('MTCG_EVENT_SANSU_PERCENT', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'パーセント増量は数式と図形を題材に、直感的な一手としてすぐにカードを1枚引く、味方がいれば敵支援全体を1削る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-sansu-percent-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-sansu-percent-2' },
    ],
  }),
  MTCG_EVENT_SANSU_GEOMETRY: definePlacementEventProgram('MTCG_EVENT_SANSU_GEOMETRY', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '幾何学模様は数式と図形を題材に、SP差と盤面判断を絡めて中央を押さえていれば味方全体を1回復、空きレーンがあれば敵1体へ1ダメージ。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-sansu-geometry-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-geometry-2' },
    ],
  }),
  MTCG_EVENT_SANSU_AREA: definePlacementEventProgram('MTCG_EVENT_SANSU_AREA', 'MAGIC', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '面積計算は数式と図形を題材に、魔力の条件を重ねて奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を2上げる。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-area-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'event-sansu-area-2' },
    ],
  }),
  MTCG_EVENT_SANSU_CHART: definePlacementEventProgram('MTCG_EVENT_SANSU_CHART', 'ELEMENTARY', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '円グラフは数式と図形を題材に、直感的な一手として空きレーンがあれば位置を移す、奇数ターンなら相手ライフへ1ダメージ。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-chart-1' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-chart-2' },
    ],
  }),
  MTCG_EVENT_SANSU_UNIT: definePlacementEventProgram('MTCG_EVENT_SANSU_UNIT', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '単位変換は数式と図形を題材に、SP差と盤面判断を絡めて敵がいれば敵全体を停止、中央を押さえていれば手札を1枚失う。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-sansu-unit-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-sansu-unit-2' },
    ],
  }),
  MTCG_EVENT_SANSU_FORMULA: definePlacementEventProgram('MTCG_EVENT_SANSU_FORMULA', 'MAGIC', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '魔法の方程式は数式と図形を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-sansu-formula-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-sansu-formula-2' },
    ],
  }),
  MTCG_EVENT_SANSU_GRID: definePlacementEventProgram('MTCG_EVENT_SANSU_GRID', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '方眼紙の盾は数式と図形を題材に、直感的な一手としてすぐに位置を移す、味方がいればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-sansu-grid-1' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-sansu-grid-2' },
    ],
  }),
  MTCG_EVENT_SANSU_LOGIC: definePlacementEventProgram('MTCG_EVENT_SANSU_LOGIC', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '論理パズルは数式と図形を題材に、SP差と盤面判断を絡めて中央を押さえていればSPを1得る、空きレーンがあれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-sansu-logic-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-logic-2' },
    ],
  }),
  MTCG_EVENT_SANSU_FRACTION: definePlacementEventProgram('MTCG_EVENT_SANSU_FRACTION', 'MAGIC', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '分数の壁は数式と図形を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていれば味方全体へシールド1。',
    tags: ['MAGIC', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-sansu-fraction-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-sansu-fraction-2' },
    ],
  }),
  MTCG_EVENT_SANSU_ABACUS_MASTER: definePlacementEventProgram('MTCG_EVENT_SANSU_ABACUS_MASTER', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '珠算十段は数式と図形を題材に、直感的な一手として空きレーンがあれば敵1体へ1ダメージ、奇数ターンならSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-sansu-abacus-master-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-sansu-abacus-master-2' },
    ],
  }),
  MTCG_EVENT_RIKA_EXPERIMENTAL: definePlacementEventProgram('MTCG_EVENT_RIKA_EXPERIMENTAL', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '試験管の爆発は観察と実験を題材に、SP差と盤面判断を絡めて敵がいればカードを2枚引く、SP優位なら味方全体の攻撃力を1上げる。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-rika-experimental-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'event-rika-experimental-2' },
    ],
  }),
  MTCG_EVENT_RIKA_MICROSCOPE: definePlacementEventProgram('MTCG_EVENT_RIKA_MICROSCOPE', 'MAGIC', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '顕微鏡は観察と実験を題材に、魔力の条件を重ねてライフ半分以下なら魔力刻印を残す、刻印が残っていれば味方全体を1回復。',
    tags: ['MAGIC', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-rika-microscope-1' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-rika-microscope-2' },
    ],
  }),
  MTCG_EVENT_RIKA_MAGNET: definePlacementEventProgram('MTCG_EVENT_RIKA_MAGNET', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '磁石の力は観察と実験を題材に、直感的な一手としてすぐに味方全体の攻撃力を1上げる、味方がいれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 1, label: 'event-rika-magnet-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-rika-magnet-2' },
    ],
  }),
  MTCG_EVENT_RIKA_PHOTOSYNTHESIS: definePlacementEventProgram('MTCG_EVENT_RIKA_PHOTOSYNTHESIS', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '光合成は観察と実験を題材に、SP差と盤面判断を絡めて中央を押さえていれば位置を移す、空きレーンがあれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-rika-photosynthesis-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-photosynthesis-2' },
    ],
  }),
  MTCG_EVENT_RIKA_PLANETS: definePlacementEventProgram('MTCG_EVENT_RIKA_PLANETS', 'MAGIC', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '太陽系の公転は観察と実験を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-rika-planets-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-rika-planets-2' },
    ],
  }),
  MTCG_EVENT_RIKA_VOLCANO: definePlacementEventProgram('MTCG_EVENT_RIKA_VOLCANO', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'マグマの噴火は観察と実験を題材に、直感的な一手として空きレーンがあれば敵支援を1削る、奇数ターンなら敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-volcano-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-rika-volcano-2' },
    ],
  }),
  MTCG_EVENT_RIKA_LITMUS: definePlacementEventProgram('MTCG_EVENT_RIKA_LITMUS', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'リトマス試験紙は観察と実験を題材に、SP差と盤面判断を絡めて敵がいれば位置を移す、SP優位なら位置を移す。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-rika-litmus-1' },
      { action: 'MOVE', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-rika-litmus-2' },
    ],
  }),
  MTCG_EVENT_RIKA_ELECTRIC: definePlacementEventProgram('MTCG_EVENT_RIKA_ELECTRIC', 'MAGIC', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '静電気ショックは観察と実験を題材に、魔力の条件を重ねて奇数ターンなら魔力刻印を残す、刻印が残っていればSPを1得る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-rika-electric-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-rika-electric-2' },
    ],
  }),
  MTCG_EVENT_RIKA_ECLIPSE: definePlacementEventProgram('MTCG_EVENT_RIKA_ECLIPSE', 'ELEMENTARY', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '皆既日食は観察と実験を題材に、直感的な一手としてすぐに味方全体へシールド1、味方がいれば敵支援全体を1削る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-rika-eclipse-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-rika-eclipse-2' },
    ],
  }),
  MTCG_EVENT_RIKA_EVOLUTION: definePlacementEventProgram('MTCG_EVENT_RIKA_EVOLUTION', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '生命の進化は観察と実験を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵全体へ1ダメージ、空きレーンがあれば敵1体へ1ダメージ。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-rika-evolution-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-evolution-2' },
    ],
  }),
  MTCG_EVENT_RIKA_BACTERIA: definePlacementEventProgram('MTCG_EVENT_RIKA_BACTERIA', 'MAGIC', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '細菌の増殖は観察と実験を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていればカードを1枚引く。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-rika-bacteria-1' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-rika-bacteria-2' },
    ],
  }),
  MTCG_EVENT_RIKA_RAINBOW: definePlacementEventProgram('MTCG_EVENT_RIKA_RAINBOW', 'ELEMENTARY', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '虹のプリズムは観察と実験を題材に、直感的な一手として空きレーンがあれば味方全体を1回復、奇数ターンなら相手ライフへ1ダメージ。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-rainbow-1' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-rika-rainbow-2' },
    ],
  }),
  MTCG_EVENT_RIKA_GRAVITY: definePlacementEventProgram('MTCG_EVENT_RIKA_GRAVITY', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '重力の法則は観察と実験を題材に、SP差と盤面判断を絡めて敵がいれば味方全体の攻撃力を2上げる、SP優位なら相手ライフから1吸収。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 1, label: 'event-rika-gravity-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-rika-gravity-2' },
    ],
  }),
  MTCG_EVENT_RIKA_FOSSIL: definePlacementEventProgram('MTCG_EVENT_RIKA_FOSSIL', 'MAGIC', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'アンモナイトは観察と実験を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていれば位置を移す。',
    tags: ['MAGIC', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-rika-fossil-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-rika-fossil-2' },
    ],
  }),
  MTCG_EVENT_RIKA_ANATOMY: definePlacementEventProgram('MTCG_EVENT_RIKA_ANATOMY', 'ELEMENTARY', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '人体模型は観察と実験を題材に、直感的な一手としてすぐに敵1体を停止、味方がいればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-rika-anatomy-1' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-rika-anatomy-2' },
    ],
  }),
  MTCG_EVENT_RIKA_SPRING: definePlacementEventProgram('MTCG_EVENT_RIKA_SPRING', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'バネの弾力は観察と実験を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵支援全体を1削る、空きレーンがあれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-rika-spring-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-spring-2' },
    ],
  }),
  MTCG_EVENT_RIKA_WEATHER: definePlacementEventProgram('MTCG_EVENT_RIKA_WEATHER', 'MAGIC', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '天気予報は観察と実験を題材に、魔力の条件を重ねてライフ半分以下なら魔力刻印を残す、刻印が残っていれば位置を移す。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-rika-weather-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-rika-weather-2' },
    ],
  }),
  MTCG_EVENT_RIKA_ALCOHOL: definePlacementEventProgram('MTCG_EVENT_RIKA_ALCOHOL', 'ELEMENTARY', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'アルコールランプは観察と実験を題材に、直感的な一手として空きレーンがあればSPを1得る、奇数ターンならSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-rika-alcohol-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-rika-alcohol-2' },
    ],
  }),
  MTCG_EVENT_RIKA_CONSTELLATION: definePlacementEventProgram('MTCG_EVENT_RIKA_CONSTELLATION', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '冬の大三角形は観察と実験を題材に、SP差と盤面判断を絡めて敵がいれば味方全体へシールド1、SP優位なら味方全体の攻撃力を1上げる。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-rika-constellation-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'event-rika-constellation-2' },
    ],
  }),
  MTCG_EVENT_RIKA_ROBOT: definePlacementEventProgram('MTCG_EVENT_RIKA_ROBOT', 'MAGIC', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '二足歩行ロボットは観察と実験を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば敵全体へ1ダメージ。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-rika-robot-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-rika-robot-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_GEOGRAPHY: definePlacementEventProgram('MTCG_EVENT_SYAKAI_GEOGRAPHY', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '日本地図は社会と歴史を題材に、直感的な一手としてすぐにカードを1枚引く、味方がいれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-syakai-geography-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-syakai-geography-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_HISTORY: definePlacementEventProgram('MTCG_EVENT_SYAKAI_HISTORY', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '歴史の教科書は社会と歴史を題材に、SP差と盤面判断を絡めて中央を押さえていれば味方全体を1回復、空きレーンがあれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-history-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-history-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_COIN: definePlacementEventProgram('MTCG_EVENT_SYAKAI_COIN', 'MAGIC', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '小銭入れは社会と歴史を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を1上げる。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-syakai-coin-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 2, label: 'event-syakai-coin-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_LAW: definePlacementEventProgram('MTCG_EVENT_SYAKAI_LAW', 'ELEMENTARY', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '校則遵守は社会と歴史を題材に、直感的な一手として空きレーンがあれば位置を移す、奇数ターンなら敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-law-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-syakai-law-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_MARKET: definePlacementEventProgram('MTCG_EVENT_SYAKAI_MARKET', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'バザーの掘り出し物は社会と歴史を題材に、SP差と盤面判断を絡めて敵がいれば敵全体を停止、ライフ半分以下なら手札を1枚失う。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-syakai-market-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-syakai-market-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_CITY: definePlacementEventProgram('MTCG_EVENT_SYAKAI_CITY', 'MAGIC', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '未来都市は社会と歴史を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば敵支援を1削る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-city-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-syakai-city-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_TRADE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_TRADE', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '交換留学生は社会と歴史を題材に、直感的な一手としてすぐに位置を移す、味方がいれば敵支援全体を1削る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-syakai-trade-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-syakai-trade-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_VOTE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_VOTE', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '学級委員選挙は社会と歴史を題材に、SP差と盤面判断を絡めて中央を押さえていればSPを1得る、空きレーンがあれば敵1体へ1ダメージ。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-vote-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-vote-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_FACTORY: definePlacementEventProgram('MTCG_EVENT_SYAKAI_FACTORY', 'MAGIC', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '町工場は社会と歴史を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば味方全体へシールド2。',
    tags: ['MAGIC', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-syakai-factory-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-syakai-factory-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_TEMPLE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_TEMPLE', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '古い寺院は社会と歴史を題材に、直感的な一手として空きレーンがあれば敵1体へ1ダメージ、奇数ターンなら相手ライフへ1ダメージ。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-temple-1' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-syakai-temple-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_RICE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_RICE', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '豊作の秋は社会と歴史を題材に、SP差と盤面判断を絡めて敵がいればカードを1枚引く、SP優位なら相手ライフから1吸収。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-syakai-rice-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-syakai-rice-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_EXPLORER: definePlacementEventProgram('MTCG_EVENT_SYAKAI_EXPLORER', 'MAGIC', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '探検隊は社会と歴史を題材に、魔力の条件を重ねて奇数ターンなら魔力刻印を残す、刻印が残っていれば味方全体を1回復。',
    tags: ['MAGIC', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-syakai-explorer-1' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-syakai-explorer-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_CASTLE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_CASTLE', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'お城の守りは社会と歴史を題材に、直感的な一手としてすぐに味方全体の攻撃力を1上げる、味方がいればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 1, label: 'event-syakai-castle-1' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-syakai-castle-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_NEWS: definePlacementEventProgram('MTCG_EVENT_SYAKAI_NEWS', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '校内ニュースは社会と歴史を題材に、SP差と盤面判断を絡めて中央を押さえていれば位置を移す、空きレーンがあれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-news-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-news-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_BANK: definePlacementEventProgram('MTCG_EVENT_SYAKAI_BANK', 'MAGIC', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'お年玉貯金は社会と歴史を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば敵全体を停止。',
    tags: ['MAGIC', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-bank-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-syakai-bank-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_REVOLUTION: definePlacementEventProgram('MTCG_EVENT_SYAKAI_REVOLUTION', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '産業革命は社会と歴史を題材に、直感的な一手として空きレーンがあれば敵支援を1削る、奇数ターンならSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-revolution-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-syakai-revolution-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_GLOBAL: definePlacementEventProgram('MTCG_EVENT_SYAKAI_GLOBAL', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '世界一周は社会と歴史を題材に、SP差と盤面判断を絡めて敵がいれば位置を移す、SP優位なら味方全体の攻撃力を1上げる。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-syakai-global-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'SP_LEAD', amount: 1, duration: 1, label: 'event-syakai-global-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_CULTURE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_CULTURE', 'MAGIC', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '伝統文化は社会と歴史を題材に、魔力の条件を重ねて敵がいれば魔力刻印を残す、刻印が残っていればSPを1得る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-syakai-culture-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-syakai-culture-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_COIN_BAG: definePlacementEventProgram('MTCG_EVENT_SYAKAI_COIN_BAG', 'ELEMENTARY', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'お宝の袋は社会と歴史を題材に、直感的な一手としてすぐに味方全体へシールド1、味方がいれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-syakai-coin-bag-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-syakai-coin-bag-2' },
    ],
  }),
  MTCG_EVENT_SYAKAI_HERITAGE: definePlacementEventProgram('MTCG_EVENT_SYAKAI_HERITAGE', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '世界遺産登録は社会と歴史を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵全体へ1ダメージ、空きレーンがあれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-syakai-heritage-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-syakai-heritage-2' },
    ],
  }),
  MTCG_EVENT_PE_DASH: definePlacementEventProgram('MTCG_EVENT_PE_DASH', 'MAGIC', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '50m走は運動と連携を題材に、魔力の条件を重ねてライフ半分以下なら魔力刻印を残す、刻印が残っていればカードを2枚引く。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-pe-dash-1' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'event-pe-dash-2' },
    ],
  }),
  MTCG_EVENT_PE_JUMP: definePlacementEventProgram('MTCG_EVENT_PE_JUMP', 'ELEMENTARY', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '縄跳びは運動と連携を題材に、直感的な一手として空きレーンがあれば味方全体を1回復、奇数ターンなら敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-jump-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-pe-jump-2' },
    ],
  }),
  MTCG_EVENT_PE_BALL: definePlacementEventProgram('MTCG_EVENT_PE_BALL', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'ドッジボール投球は運動と連携を題材に、SP差と盤面判断を絡めて敵がいれば味方全体の攻撃力を1上げる、SP優位なら位置を移す。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 1, label: 'event-pe-ball-1' },
      { action: 'MOVE', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-pe-ball-2' },
    ],
  }),
  MTCG_EVENT_PE_SWIM: definePlacementEventProgram('MTCG_EVENT_PE_SWIM', 'MAGIC', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '25mクロールは運動と連携を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば位置を移す。',
    tags: ['MAGIC', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-pe-swim-1' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-pe-swim-2' },
    ],
  }),
  MTCG_EVENT_PE_TEAM: definePlacementEventProgram('MTCG_EVENT_PE_TEAM', 'ELEMENTARY', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '二人三脚は運動と連携を題材に、直感的な一手としてすぐに敵1体を停止、味方がいれば敵支援全体を1削る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-pe-team-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'event-pe-team-2' },
    ],
  }),
  MTCG_EVENT_PE_CHEER: definePlacementEventProgram('MTCG_EVENT_PE_CHEER', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '応援合戦は運動と連携を題材に、SP差と盤面判断を絡めて中央を押さえていれば敵支援全体を1削る、空きレーンがあれば敵1体へ1ダメージ。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-pe-cheer-1' },
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-cheer-2' },
    ],
  }),
  MTCG_EVENT_PE_GYM_MAT: definePlacementEventProgram('MTCG_EVENT_PE_GYM_MAT', 'MAGIC', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'マット運動は運動と連携を題材に、魔力の条件を重ねてライフ半分以下なら位置を移す、敵がいれば敵全体へ1ダメージ。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'event-pe-gym-mat-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-pe-gym-mat-2' },
    ],
  }),
  MTCG_EVENT_EVENT_CLEANING: definePlacementEventProgram('MTCG_EVENT_EVENT_CLEANING', 'ELEMENTARY', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '大掃除のホウキは学校生活を題材に、直感的な一手として空きレーンがあればSPを1得る、奇数ターンなら相手ライフへ1ダメージ。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-event-cleaning-1' },
      { action: 'DAMAGE', target: 'ENEMY_LIFE', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'event-event-cleaning-2' },
    ],
  }),
  MTCG_EVENT_EVENT_LUNCH: definePlacementEventProgram('MTCG_EVENT_EVENT_LUNCH', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '給食の当番は学校生活を題材に、SP差と盤面判断を絡めて敵がいれば味方全体へシールド2、SP優位なら相手ライフから1吸収。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 2, duration: 0, label: 'event-event-lunch-1' },
      { action: 'LIFE_DRAIN', target: 'ENEMY_LIFE', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-event-lunch-2' },
    ],
  }),
  MTCG_EVENT_EVENT_FESTIVAL: definePlacementEventProgram('MTCG_EVENT_EVENT_FESTIVAL', 'MAGIC', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '学芸会の主役は学校生活を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば敵全体へ1ダメージ。',
    tags: ['MAGIC', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-event-festival-1' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-event-festival-2' },
    ],
  }),
  MTCG_EVENT_PE_HORIZONTAL_BAR: definePlacementEventProgram('MTCG_EVENT_PE_HORIZONTAL_BAR', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DRAW',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '鉄棒の逆上がりは運動と連携を題材に、直感的な一手としてすぐにカードを1枚引く、空きレーンがあればカードを1枚引く。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DRAW'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-pe-horizontal-bar-1' },
      { action: 'DRAW', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-horizontal-bar-2' },
    ],
  }),
  MTCG_EVENT_PE_VAULTING: definePlacementEventProgram('MTCG_EVENT_PE_VAULTING', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_HEAL',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '跳び箱10段は運動と連携を題材に、SP差と盤面判断を絡めて中央を押さえていれば味方全体を1回復、敵がいれば味方1体を1回復。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_HEAL'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-pe-vaulting-1' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-pe-vaulting-2' },
    ],
  }),
  MTCG_EVENT_PE_SOCCER: definePlacementEventProgram('MTCG_EVENT_PE_SOCCER', 'MAGIC', {
    legacyEffect: 'EVENT_BUFF',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'PK戦は運動と連携を題材に、魔力の条件を重ねてSP優位なら魔力刻印を残す、刻印が残っていれば味方全体の攻撃力を2上げる。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BUFF'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'event-pe-soccer-1' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'event-pe-soccer-2' },
    ],
  }),
  MTCG_EVENT_PE_MARATHON: definePlacementEventProgram('MTCG_EVENT_PE_MARATHON', 'ELEMENTARY', {
    legacyEffect: 'EVENT_MOVE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '持久走は運動と連携を題材に、直感的な一手として空きレーンがあれば位置を移す、すぐにSPを1得る。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_MOVE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-marathon-1' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-pe-marathon-2' },
    ],
  }),
  MTCG_EVENT_PE_DANCE: definePlacementEventProgram('MTCG_EVENT_PE_DANCE', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_STUN',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'フォークダンスは運動と連携を題材に、SP差と盤面判断を絡めて敵がいれば敵全体を停止、空きレーンがあれば手札を1枚失う。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_STUN'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-pe-dance-1' },
      { action: 'DISCARD', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-dance-2' },
    ],
  }),
  MTCG_EVENT_EVENT_MORNING: definePlacementEventProgram('MTCG_EVENT_EVENT_MORNING', 'MAGIC', {
    legacyEffect: 'EVENT_BREAK',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '朝の会は学校生活を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば敵支援全体を1削る。',
    tags: ['MAGIC', 'EVENT', 'EVENT_BREAK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-event-morning-1' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-event-morning-2' },
    ],
  }),
  MTCG_EVENT_EVENT_HOME: definePlacementEventProgram('MTCG_EVENT_EVENT_HOME', 'ELEMENTARY', {
    legacyEffect: 'EVENT_BOUNCE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '帰りの会は学校生活を題材に、直感的な一手としてすぐに位置を移す、空きレーンがあれば自身へシールド1。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_BOUNCE'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-event-home-1' },
      { action: 'SHIELD', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-event-home-2' },
    ],
  }),
  MTCG_EVENT_EVENT_TRIP: definePlacementEventProgram('MTCG_EVENT_EVENT_TRIP', 'HIGH_SCHOOL', {
    legacyEffect: 'EVENT_ENERGY',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '修学旅行の枕は学校生活を題材に、SP差と盤面判断を絡めて中央を押さえていればSPを1得る、敵がいれば味方全体へシールド1。',
    tags: ['HIGH_SCHOOL', 'EVENT', 'EVENT_ENERGY'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-event-trip-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'event-event-trip-2' },
    ],
  }),
  MTCG_EVENT_PE_BASKET: definePlacementEventProgram('MTCG_EVENT_PE_BASKET', 'MAGIC', {
    legacyEffect: 'EVENT_SHIELD',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '3ポイントシュートは運動と連携を題材に、魔力の条件を重ねて中央を押さえていれば魔力刻印を残す、刻印が残っていれば味方全体へシールド1。',
    tags: ['MAGIC', 'EVENT', 'EVENT_SHIELD'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'event-pe-basket-1' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'event-pe-basket-2' },
    ],
  }),
  MTCG_EVENT_PE_CHAMPION: definePlacementEventProgram('MTCG_EVENT_PE_CHAMPION', 'ELEMENTARY', {
    legacyEffect: 'EVENT_DAMAGE',
    trigger: 'EVENT_PLAY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'スポーツ王は運動と連携を題材に、直感的な一手として空きレーンがあれば敵1体へ1ダメージ、すぐに敵全体を停止。',
    tags: ['ELEMENTARY', 'EVENT', 'EVENT_DAMAGE'],
    steps: [
      { action: 'DAMAGE', target: 'ENEMY_ANY', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'event-pe-champion-1' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'ALWAYS', amount: 1, duration: 0, label: 'event-pe-champion-2' },
    ],
  }),
};
