import type { PlacementEffectProgram } from './placementTcgEffectDsl';
import {
  defineHighSchoolUnitProgram,
  defineMagicUnitProgram,
} from './placementTcgUniqueEffectFactory';

export const PLACEMENT_TCG_VACATION_UNIT_PROGRAMS: Readonly<Record<string, PlacementEffectProgram>> = {
  MTCG_HIGH_SCHOOL_HERO_WARRIOR_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_WARRIOR_VACATION', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '反逆の高校生／バカンスは中央の波打ち際から先陣を切り、SPで主導権を握れば正面の相手へ水しぶきごと踏み込む。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'ATTACK', 'REBELLION'],
    steps: [
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-rebel-wave-charge' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'SP_LEAD', amount: 2, duration: 0, label: 'vacation-rebel-splash-through' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_CARETAKER_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_CARETAKER_VACATION', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '生物部の先輩／バカンスは休憩時間に仲間全体を手当てし、観察できる味方がいれば次の記録を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'TURN_END', 'CARE'],
    steps: [
      { action: 'HEAL', target: 'OWN_ALL', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-caretaker-first-aid' },
      { action: 'DRAW', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-caretaker-field-notes' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_ASSASSIN_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_ASSASSIN_VACATION', {
    legacyEffect: 'THORNS',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '謎めく転入生／バカンスは直接攻撃の隙に相手の支援網をまとめて崩し、空いたレーンへ浴衣の残像だけを残して移る。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'DIRECT_ATTACK', 'INFILTRATION'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-transfer-festival-sabotage' },
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'vacation-transfer-yukata-step' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_DODGEBALL_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_DODGEBALL_VACATION', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: 'バスケ部エース／バカンスは砂浜の空きコースへ走り込み、中央を取れた時は速攻の余力をSPへ変える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'ATTACK', 'FAST_BREAK'],
    steps: [
      { action: 'MOVE', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'vacation-ace-beach-cut' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-ace-center-tempo' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_BARD_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_BARD_VACATION', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '放送部ディレクター／バカンスは中央の夏祭りステージから全敵へ合図を送り、SP優位なら次の進行台本を1枚引く。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'TURN_START', 'BROADCAST'],
    steps: [
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-bard-stage-cue' },
      { action: 'DRAW', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-bard-run-sheet' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_LIBRARIAN_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_LIBRARIAN_VACATION', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '文芸部書記／バカンスは奇数ターンの夕涼みに一節を書き留め、中央なら推敲した言葉で味方1体の体力を一時的に支える。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'TURN_END', 'EDITORIAL'],
    steps: [
      { action: 'DRAW', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-librarian-summer-draft' },
      { action: 'BUFF_HEALTH', target: 'OWN_ANY', condition: 'CENTER_LANE', amount: 1, duration: 1, label: 'vacation-librarian-evening-edit' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_CHEF_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_CHEF_VACATION', {
    legacyEffect: 'PIERCE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '学食の料理長／バカンスは浜辺の臨時キッチンを開き、味方全体へ夏の一皿を振る舞い、ピンチなら補給分のSPも確保する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'DEPLOY', 'COOKING'],
    steps: [
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'HAS_OWN_UNIT', amount: 1, duration: 1, label: 'vacation-chef-beach-meal' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-chef-cooler-stock' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_GARDENER_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_GARDENER_VACATION', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'TURN_END',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '園芸部部長／バカンスはターン終了時に仲間へ水分を分け、奇数ターンには夏の花の勢いを自身の攻撃へ乗せる。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'TURN_END', 'GROWTH'],
    steps: [
      { action: 'HEAL', target: 'OWN_ANY', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-gardener-water-break' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 1, label: 'vacation-gardener-summer-bloom' },
    ],
  }),
  MTCG_HIGH_SCHOOL_HERO_MAGE_VACATION: defineHighSchoolUnitProgram('MTCG_HIGH_SCHOOL_HERO_MAGE_VACATION', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '化学研究会長／バカンスは朝の実験で敵支援全体の仕掛けを解析し、奇数ターンには研究メモから1枚を補充する。',
    tags: ['HIGH_SCHOOL', 'UNIT', 'VACATION', 'TURN_START', 'EXPERIMENT'],
    steps: [
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-mage-reaction-test' },
      { action: 'DRAW', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-mage-lab-note' },
    ],
  }),

  MTCG_MAGIC_HERO_AKARI_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_AKARI_VACATION', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '星宮あかり／バカンスは浜辺へ着くと敵の気配を星砂へ刻印し、その輝きを仲間全体のシールドへ広げる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-akari-star-sand-mark' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-akari-star-shore-aegis' },
    ],
  }),
  MTCG_MAGIC_HERO_SHIZUKU_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_SHIZUKU_VACATION', {
    legacyEffect: 'RUSH',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '水城しずく／バカンスは中央で月光の水面を観測して刻印を作り、その反射で敵全体の動きを止める。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_START', 'MOON'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-shizuku-moon-tide-mark' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-shizuku-moon-reflection' },
    ],
  }),
  MTCG_MAGIC_HERO_HIYORI_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_HIYORI_VACATION', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '花咲ひより／バカンスは仲間との夏の記憶を花弁へ刻印し、夕暮れに味方全体へ癒やしとして返す。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_END', 'FLOWER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-hiyori-flower-memory' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-hiyori-sunset-bloom' },
    ],
  }),
  MTCG_MAGIC_HERO_TSUBASA_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_TSUBASA_VACATION', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '火神つばさ／バカンスはSP優位の熱気を刻印し、火花と水蒸気を敵全体へ一気に爆ぜさせる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'ATTACK', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-tsubasa-steam-mark' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-tsubasa-steam-burst' },
    ],
  }),
  MTCG_MAGIC_HERO_REI_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_REI_VACATION', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'DAMAGED',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '黒羽れい／バカンスは追い込まれた時ほど封印札へ傷を刻み、敵支援全体の結界を切り崩す。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DAMAGED', 'DARK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-rei-seal-mark' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-rei-night-seal-break' },
    ],
  }),
  MTCG_MAGIC_HERO_MADOKA_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_MADOKA_VACATION', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '翠川まどか／バカンスは奇数ターンの時刻を防水時計へ刻印し、直接攻撃後に未来の手札を1枚先取りする。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DIRECT_ATTACK', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-madoka-tide-clock-mark' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-madoka-future-draw' },
    ],
  }),
  MTCG_MAGIC_HERO_KOHARU_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_KOHARU_VACATION', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '風森こはる／バカンスは空きレーンへ潮風の道を刻印し、その流れに乗って別レーンへ移る。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'ATTACK', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'vacation-koharu-seabreeze-mark' },
      { action: 'MOVE', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-koharu-gale-step' },
    ],
  }),
  MTCG_MAGIC_HERO_MIRAI_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_MIRAI_VACATION', {
    legacyEffect: 'PIERCE',
    trigger: 'TURN_END',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '紫藤みらい／バカンスはSP優位の観客の熱を夢へ刻印し、味方全体の攻撃を一時的な夏のアンコールで高める。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_END', 'DREAM'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-mirai-encore-mark' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'vacation-mirai-summer-encore' },
    ],
  }),
  MTCG_MAGIC_HERO_SERA_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_SERA_VACATION', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '白峰セラ／バカンスは敵の気配を星図へ刻印し、読み解いた星界の航路からSPを得る。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_START', 'LIGHT'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-sera-starchart-mark' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-sera-celestial-route' },
    ],
  }),
  MTCG_MAGIC_HERO_REN_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_REN_VACATION', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '朝霧 蓮／バカンスは仲間との合流を風へ刻印し、浜辺の強風から味方1体を守る盾へ変える。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DEPLOY', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-ren-breeze-mark' },
      { action: 'SHIELD', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-ren-windbreak' },
    ],
  }),
  MTCG_MAGIC_HERO_SOMA_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_SOMA_VACATION', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'TURN_START',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '御影 颯真／バカンスはSP優位の秩序を氷紋へ刻印し、敵支援全体を冷気で封じて削る。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_START', 'ICE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-soma-ice-rule-mark' },
      { action: 'BREAK_SUPPORT', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-soma-frozen-order' },
    ],
  }),
  MTCG_MAGIC_HERO_MINATO_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_MINATO_VACATION', {
    legacyEffect: 'RUSH',
    trigger: 'TURN_END',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白石 湊／バカンスはピンチの体調を清流へ刻印し、ターン終了時に味方1体へ丁寧な手当てを返す。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_END', 'WATER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-minato-rescue-mark' },
      { action: 'HEAL', target: 'OWN_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-minato-clearstream-aid' },
    ],
  }),
  MTCG_MAGIC_HERO_RIKU_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_RIKU_VACATION', {
    legacyEffect: 'REGEN',
    trigger: 'TURN_START',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '天音 理玖／バカンスは奇数ターンの潮時を観測端末へ刻印し、次の分岐となるカードを1枚見つける。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TURN_START', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-riku-tide-time-mark' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-riku-observation-draw' },
    ],
  }),
  MTCG_MAGIC_HERO_YAMATO_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_YAMATO_VACATION', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '黒瀬 大和／バカンスは正面の敵を祭り火の刻印に捉え、紅蓮の拳を同じレーンへ叩き込む。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'ATTACK', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-yamato-festival-fire-mark' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-yamato-red-fist' },
    ],
  }),
  MTCG_MAGIC_HERO_LEON_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_LEON_VACATION', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'DIRECT_ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '神代 レオン／バカンスは中央ステージを幻奏の刻印に変え、直接攻撃の成功を次の一撃の強化へつなげる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DIRECT_ATTACK', 'ILLUSION'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-leon-stage-mark' },
      { action: 'BUFF_ATTACK', target: 'SELF', condition: 'AFTER_MARK', amount: 1, duration: 1, label: 'vacation-leon-summer-spotlight' },
    ],
  }),
  MTCG_MAGIC_HERO_ELLIOT_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_ELLIOT_VACATION', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: 'エリオット・ノクス／バカンスは勝利の星界記録を刻印し、その記録光を味方全体の守りへ変換する。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DEFEAT', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-elliot-record-mark' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-elliot-constellation-guard' },
    ],
  }),
  MTCG_MAGIC_HERO_SAKUYA_VACATION: defineMagicUnitProgram('MTCG_MAGIC_HERO_SAKUYA_VACATION', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '九条 朔夜／バカンスは奇数ターンの傷を宵闇の札へ刻印し、そこから敵1体の動きを封じる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'DAMAGED', 'DARK'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-sakuya-night-seal-mark' },
      { action: 'STUN', target: 'ENEMY_ANY', condition: 'AFTER_MARK', amount: 1, duration: 0, label: 'vacation-sakuya-night-seal' },
    ],
  }),

  MTCG_MAGIC_HERO_AKARI_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_AKARI_VACATION_AFTER', {
    legacyEffect: 'PIERCE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '星宮あかり／星冠の魔法騎士／バカンスは敵の気配を真夏の星砂へ刻印し、星冠の光を解放して敵全体の動きを止める。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-after-akari-starfire-mark' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-akari-crown-flare' },
    ],
  }),
  MTCG_MAGIC_HERO_SHIZUKU_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SHIZUKU_VACATION_AFTER', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '水城しずく／月鏡の水晶騎士／バカンスは中央の水面へ月鏡の刻印を映し、その反射を味方全体を包む強い水晶障壁へ変える。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'MOON'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-after-shizuku-moonpool-mark' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-shizuku-crystal-tide' },
    ],
  }),
  MTCG_MAGIC_HERO_HIYORI_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_HIYORI_VACATION_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '花咲ひより／命花の治癒術師／バカンスは傷ついた時に真夏の生命力を花冠へ刻印し、咲き広がる命花で味方全体の体力を長く支える。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DAMAGED', 'FLORA'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-after-hiyori-sunflower-mark' },
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'vacation-after-hiyori-life-bloom' },
    ],
  }),
  MTCG_MAGIC_HERO_TSUBASA_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_TSUBASA_VACATION_AFTER', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEFEAT',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '火神つばさ／神鍛の炎戦士／バカンスは撃退の熱気を灼熱の砂へ刻印し、神鍛の炎を味方全体の攻撃へ夏の火勢として分け与える。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEFEAT', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-after-tsubasa-scorch-mark' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'vacation-after-tsubasa-forge-surge' },
    ],
  }),
  MTCG_MAGIC_HERO_REI_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_REI_VACATION_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '黒羽れい／深紅の符術姫／バカンスは窮地の魔力を濡れた封印札へ刻印し、深紅の符を切って夏夜の霊力をSPへ回収する。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'MYSTERY'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-after-rei-crimson-seal-mark' },
      { action: 'GAIN_SP', target: 'SELF', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-rei-night-talisman' },
    ],
  }),
  MTCG_MAGIC_HERO_MADOKA_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MADOKA_VACATION_AFTER', {
    legacyEffect: 'REGEN',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '翠川まどか／時環の錬金術師／バカンスは空いた潮間へ未来の時刻を刻印し、夏の一瞬を先取りして次の選択肢を2枚手元へ引き寄せる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEPLOY', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'vacation-after-madoka-tideglass-mark' },
      { action: 'DRAW', target: 'SELF', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-madoka-future-pick' },
    ],
  }),
  MTCG_MAGIC_HERO_KOHARU_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_KOHARU_VACATION_AFTER', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '風森こはる／翠嵐の精霊弓士／バカンスは空きレーンを抜ける海風へ刻印を放ち、翠嵐の矢を正面へ収束させて敵を強く射抜く。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'EMPTY_LANE', amount: 1, duration: 0, label: 'vacation-after-koharu-sea-gale-mark' },
      { action: 'DAMAGE', target: 'ENEMY_SAME_LANE', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-koharu-emerald-arrow' },
    ],
  }),
  MTCG_MAGIC_HERO_MIRAI_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MIRAI_VACATION_AFTER', {
    legacyEffect: 'CENTER_POWER',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '紫藤みらい／夢幻の舞台魔術師／バカンスはSP優位の歓声を夏夜の舞台へ刻印し、傷さえ演出へ変えて味方全体の攻撃を大きく高める。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DAMAGED', 'DREAM'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-after-mirai-dream-stage-mark' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'vacation-after-mirai-midsummer-encore' },
    ],
  }),
  MTCG_MAGIC_HERO_SERA_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SERA_VACATION_AFTER', {
    legacyEffect: 'KILL_DRAW',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '白峰セラ／星界の光術師／バカンスは中央の水平線へ勝利の星図を刻印し、星界の光を味方全体へ降らせて体力を大きく底上げする。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEFEAT', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'CENTER_LANE', amount: 1, duration: 0, label: 'vacation-after-sera-horizon-star-mark' },
      { action: 'BUFF_HEALTH', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 2, label: 'vacation-after-sera-celestial-radiance' },
    ],
  }),
  MTCG_MAGIC_HERO_REN_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_REN_VACATION_AFTER', {
    legacyEffect: 'SUPPORT_BOND',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '朝霧 蓮／蒼風の守護騎士／バカンスは敵を捉えた潮風へ守護の刻印を置き、蒼風を味方全体へ巡らせて強い防壁を張る。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'WIND'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-after-ren-bluewind-mark' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-ren-guardian-gale' },
    ],
  }),
  MTCG_MAGIC_HERO_SOMA_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SOMA_VACATION_AFTER', {
    legacyEffect: 'PIERCE',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: '御影 颯真／氷律の執行騎士／バカンスはSP優位の冷気を氷砂へ刻印し、浜辺を覆う氷律で敵全体の動きを強く封じる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEPLOY', 'ICE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-after-soma-icesand-mark' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-soma-frozen-verdict' },
    ],
  }),
  MTCG_MAGIC_HERO_MINATO_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_MINATO_VACATION_AFTER', {
    legacyEffect: 'DIRECT_HEAL',
    trigger: 'ATTACK',
    resetRule: 'ONCE_PER_TURN',
    identityNote: '白石 湊／清流の癒術騎士／バカンスは窮地の体調を清流へ刻印し、攻撃の余波を涼やかな治癒波へ変えて味方全体を大きく回復する。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'WATER'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'LIFE_BELOW_HALF', amount: 1, duration: 0, label: 'vacation-after-minato-clearwater-mark' },
      { action: 'HEAL', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-minato-healing-surge' },
    ],
  }),
  MTCG_MAGIC_HERO_RIKU_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_RIKU_VACATION_AFTER', {
    legacyEffect: 'DEPLOY_HEAL',
    trigger: 'DAMAGED',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '天音 理玖／時詠の観測騎士／バカンスは奇数ターンの潮時を観測記録へ刻印し、時の流れを止めて敵全体の行動を強く遅らせる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DAMAGED', 'TIME'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'ODD_TURN', amount: 1, duration: 0, label: 'vacation-after-riku-tideclock-mark' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-riku-time-freeze' },
    ],
  }),
  MTCG_MAGIC_HERO_YAMATO_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_YAMATO_VACATION_AFTER', {
    legacyEffect: 'DEPLOY_DAMAGE',
    trigger: 'DEFEAT',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '黒瀬 大和／紅蓮の拳闘騎士／バカンスは撃退の勢いを灼熱の砂浜へ刻印し、紅蓮の拳圧を敵全体へ夏の爆炎として叩き込む。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEFEAT', 'FIRE'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'SP_LEAD', amount: 1, duration: 0, label: 'vacation-after-yamato-redheat-mark' },
      { action: 'DAMAGE', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-yamato-crimson-break' },
    ],
  }),
  MTCG_MAGIC_HERO_LEON_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_LEON_VACATION_AFTER', {
    legacyEffect: 'RUSH',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '神代 レオン／幻奏の舞台騎士／バカンスは仲間との演奏を真夏の舞台へ刻印し、幻奏のクライマックスで味方全体の攻撃を一気に高める。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'ILLUSION'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-after-leon-summer-stage-mark' },
      { action: 'BUFF_ATTACK', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 1, label: 'vacation-after-leon-phantom-finale' },
    ],
  }),
  MTCG_MAGIC_HERO_ELLIOT_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_ELLIOT_VACATION_AFTER', {
    legacyEffect: 'REGEN',
    trigger: 'DEPLOY',
    resetRule: 'ONCE_PER_BATTLE',
    identityNote: 'エリオット・ノクス／星界の記録騎士／バカンスは仲間との夏の記憶を星界記録へ刻印し、展開した星座陣で味方全体へ強い守りを与える。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'DEPLOY', 'STAR'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_OWN_UNIT', amount: 1, duration: 0, label: 'vacation-after-elliot-summer-record-mark' },
      { action: 'SHIELD', target: 'OWN_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-elliot-constellation-vault' },
    ],
  }),
  MTCG_MAGIC_HERO_SAKUYA_VACATION_AFTER: defineMagicUnitProgram('MTCG_MAGIC_HERO_SAKUYA_VACATION_AFTER', {
    legacyEffect: 'THORNS',
    trigger: 'ATTACK',
    resetRule: 'EVERY_TRIGGER',
    identityNote: '九条 朔夜／宵闇の封印騎士／バカンスは敵の気配を夏夜の封印札へ刻印し、宵闇の結界を広げて敵全体の動きをまとめて封じる。',
    tags: ['MAGIC', 'UNIT', 'VACATION', 'TRANSFORMED', 'ATTACK', 'SHADOW'],
    steps: [
      { action: 'MARK', target: 'SELF', condition: 'HAS_ENEMY', amount: 1, duration: 0, label: 'vacation-after-sakuya-nightseal-mark' },
      { action: 'STUN', target: 'ENEMY_ALL', condition: 'AFTER_MARK', amount: 2, duration: 0, label: 'vacation-after-sakuya-dusk-binding' },
    ],
  }),
};
