const copy: [string, string, string][] = [
  ['ラウンド開始前まで自由に変更できます。', 'Customize freely before the round starts.', 'ラウンドかいしまえまで じゆうに へんこうできます。'],
  ['服の色', 'Outfit color', 'ふくの いろ'],
  ['サーバーが試合を進行します。ホストの離席でもプレイできます。', 'The server runs the round. Play continues when the host steps away.', 'サーバーが しあいを しんこうします。ホストの りせきでも プレイできます。'],
  ['サーバーとの接続が終了しました。部屋に入り直してください。', 'Disconnected from the server. Please rejoin the room.', 'サーバーとの せつぞくが しゅうりょうしました。へやに はいりなおしてください。'],
  ['接続先の設定が不正です。', 'Invalid server URL configuration.', 'せつぞくさきの せっていが ふせいです。'],
  ['接続設定が不正です。', 'Invalid connection settings.', 'せつぞくせっていが ふせいです。'],
  ['操作データが不正です。', 'Invalid input data.', 'そうさデータが ふせいです。'],
  ['ホストだけが問題を設定できます。', 'Only the host can choose the lesson.', 'ホストだけが もんだいを せっていできます。'],
  ['問題の設定が不正です。', 'Invalid lesson settings.', 'もんだいの せっていが ふせいです。'],
  ['ホストだけがラウンドを開始できます。', 'Only the host can start the round.', 'ホストだけが ラウンドを かいしできます。'],
  ['部屋の有効時間が終了しました。', 'This room has expired.', 'へやの ゆうこうじかんが しゅうりょうしました。'],
  ['40人オンラインゴルフ', '40-player online golf', '40にん オンラインゴルフ'],
  ['ゴルフの問題選択', 'Golf lesson selection', 'ゴルフの もんだいせんたく'],
  ['ショット前に3問。正解するほどパワーと精度がアップ', 'Three questions before every shot. Correct answers improve power and accuracy.', 'ショットまえに3もん。せいかいするほど パワーと せいどがアップ'],
  ['コースと問題を準備中…', 'Preparing the course and questions…', 'コースと もんだいを じゅんびちゅう…'],
  ['ショット前の3問', 'Three questions before your shot', 'ショットまえの3もん'],
  ['正答を確認しましょう', 'Check the correct answer', 'せいとうを かくにんしましょう'],
  ['ショットを準備する', 'Prepare your shot', 'ショットを じゅんびする'],
  ['ドライバー', 'Driver', 'ドライバー'], ['アイアン', 'Iron', 'アイアン'], ['ウェッジ', 'Wedge', 'ウェッジ'], ['パター', 'Putter', 'パター'],
  ['グリーン', 'Green', 'グリーン'], ['フェアウェイ', 'Fairway', 'フェアウェイ'], ['ラフ', 'Rough', 'ラフ'], ['バンカー', 'Bunker', 'バンカー'], ['池', 'Water', 'いけ'],
  ['学んで、狙って、カップイン。', 'Learn. Aim. Sink the putt.', 'まなんで、ねらって、カップイン。'],
  ['3ホール・最大40人のオンラインゴルフ', 'Three holes. Up to 40 players online.', '3ホール・さいだい40にんの オンラインゴルフ'],
  ['問題を選んで部屋を作る', 'Choose a lesson and create a room', 'もんだいを えらんで へやを つくる'],
  ['ひとりで練習', 'Practice solo', 'ひとりで れんしゅう'],
  ['ホストが問題の範囲を選びます。全員が自分のペースでプレイできます。', 'The host chooses the lesson. Everyone plays at their own pace.', 'ホストが もんだいの はんいを えらびます。ぜんいんが じぶんの ペースで プレイできます。'],
  ['スタート前の集合', 'Meet at the clubhouse', 'スタートまえの しゅうごう'],
  ['問題の範囲を変更', 'Change the lesson', 'もんだいの はんいを へんこう'],
  ['ラウンド開始', 'Start round', 'ラウンドかいし'],
  ['ホストは画面を開いたままにしてください。離席中は全員が一時停止します。', 'Keep the host screen visible. Switching away pauses the round for everyone.', 'ホストは がめんを ひらいたままに してください。りせきちゅうは ぜんいんが いちじていしします。'],
  ['ホストの開始を待っています。', 'Waiting for the host to start.', 'ホストの かいしを まっています。'],
  ['部屋を退出', 'Leave room', 'へやを たいしゅつ'],
  ['打数', 'Strokes', 'だすう'], ['打', 'strokes', 'だ'], ['ボールを追う', 'Follow ball', 'ボールを おう'], ['コース全景', 'Course overview', 'コースぜんけい'],
  ['スコアボード', 'Scoreboard', 'スコアボード'], ['風', 'Wind', 'かぜ'],
  ['次のショットを強くしよう', 'Power up your next shot', 'つぎの ショットを つよくしよう'],
  ['池・OB：1打罰で元の位置へ', 'Water / OB: one penalty stroke, back to your last position.', 'いけ・OB：1だばつで もとの いちへ'],
  ['3問の正答数で最大パワーと方向の精度が決まります。', 'Your three answers set the maximum power and directional accuracy.', '3もんの せいとうすうで さいだいパワーと ほうこうの せいどが きまります。'],
  ['3問に挑戦', 'Take the three-question challenge', '3もんに ちょうせん'],
  ['最大パワー', 'Max power', 'さいだいパワー'], ['方向の誤差', 'Direction spread', 'ほうこうの ごさ'], ['狙う方向', 'Aim direction', 'ねらう ほうこう'], ['ショットパワー', 'Shot power', 'ショットパワー'],
  ['ショット！', 'Swing!', 'ショット！'], ['ボールの行方を見よう', 'Watch your ball fly', 'ボールの ゆくえを みよう'],
  ['打数上限でホール終了', 'Stroke limit reached', 'だすうじょうげんで ホールしゅうりょう'], ['カップイン！', 'In the cup!', 'カップイン！'],
  ['ラウンド結果へ', 'See round results', 'ラウンドけっかへ'], ['次のホール', 'Next hole', 'つぎの ホール'],
  ['完走！ほかのプレイヤーの終了を待っています。', 'Round complete! Waiting for the other players.', 'かんそう！ほかの プレイヤーの しゅうりょうを まっています。'],
  ['ラウンド結果', 'Round results', 'ラウンドけっか'],
  ['全3ホールの合計打数が少ない人が勝ち。同点は同順位です。', 'Lowest total over three holes wins. Equal scores share a place.', 'ぜん3ホールの ごうけいだすうが すくないひとが かち。どうてんは どうじゅんいです。'],
  ['途中退出', 'Left early', 'とちゅうたいしゅつ'], ['完走', 'Finished', 'かんそう'], ['プレイ中', 'Playing', 'プレイちゅう'], ['クラブハウスへ', 'Back to clubhouse', 'クラブハウスへ'],
  ['毎ショットの前に、選んだ範囲から3問。', 'Three questions from your lesson before every shot.', 'まいショットの まえに、えらんだ はんいから3もん。'],
  ['0・1・2・3問正解で最大パワー55・70・85・100%。', '0 / 1 / 2 / 3 correct answers unlock 55 / 70 / 85 / 100% power.', '0・1・2・3もんせいかいで さいだいパワー55・70・85・100%。'],
  ['クラブと方向を選んでカップを狙おう。池とOBは1打罰。', 'Choose a club and aim for the cup. Water and OB add one stroke.', 'クラブと ほうこうを えらんで カップを ねらおう。いけと OBは1だばつ。'],
  ['満員、またはラウンド開始済みです。', 'Room full or round already started.', 'まんいん、または ラウンドかいしずみです。'],
  ['参加できません。開始前に入り直してください。', 'Cannot join. Please rejoin before the round starts.', 'さんかできません。かいしまえに はいりなおしてください。'],
  ['問題を準備できませんでした。', 'Could not prepare the questions.', 'もんだいを じゅんびできませんでした。'],
  ['接続できませんでした。', 'Could not connect.', 'せつぞくできませんでした。'],
];
export const GOLF_ENGLISH: Record<string, string> = Object.fromEntries(copy.map(([ja, en]) => [ja, en]));
export const GOLF_HIRAGANA: Record<string, string> = Object.fromEntries(copy.map(([ja, , hira]) => [ja, hira]));
