export const SCHOOL_WANDERER_ENGLISH:Record<string,string> = {
  " 🔒封印": " 🔒Sealed",
  " ⭐応援": " ⭐Blessed",
  "冒険手帳": "Notebook",
  "下校まで": "Bell in",
  "未払い": "Bill",
  "学校前と冒険手帳": "School base and notebook",
  "学校前の集合場所": "School meeting point",
  "容器": "Container",
  "放課後の冒険手帳": "After-school notebook",
  "冒険に戻る": "Resume",
  "倉庫と貯金箱はこの端末に保存します。手ぶらの挑戦では持ち込めません。": "Warehouse and savings are stored on this device. Challenge modes start without stored equipment.",
  "冒険を選ぶ": "Choose adventure",
  "救助先": "Rescue floor",
  "残り": "Attempts left",
  "倒れた冒険があると救助できます。": "A defeated adventure creates a rescue request.",
  "持っていくおこづかい": "Starting coins",
  "いっしょに行く同級生": "Classmate",
  "ひとりで挑戦": "Solo",
  "保健係あおい：回復": "Aoi: healing",
  "体育係たける：援護": "Takeru: support",
  "図書係ひなた：道具回収": "Hinata: supplies",
  "今の冒険を終了して、新しい冒険を始めますか？": "End the current adventure and start a new one?",
  "このルールで出発": "Start this adventure",
  "達成した挑戦": "Completed challenges",
  "学校前の倉庫": "Warehouse",
  "おこづかい貯金": "Savings",
  "持ち込み": "Selected",
  "帰りの連絡帳で帰還すると、道具を預けられます。": "Use a return notebook to bring supplies home.",
  "100円を貯金する": "Save 100 coins",
  "帰還した道具は、次の冒険で選んだ分だけ持ち出せます。": "Returned supplies can be selected for the next story adventure.",
  "入れるとHP30回復。取り出すには箱を割ります。": "Store a supply to heal 30 HP. Break the box to retrieve it.",
  "入れた道具が変化します。箱を割って取り出します。": "Stored supplies transform. Break the box to retrieve them.",
  "道具を入れる・取り出すごとに1ターン進みます。": "Storing or taking out a supply costs one turn.",
  "入れる道具": "Store a supply",
  "入っている道具": "Contents",
  "箱を割って全部出す": "Break and empty",
  "足元か正面の施設：＋保健室、＄行商、☺同級生、！会話。水路は浮き輪、？の壁はつるはしで調べよう。": "Facilities on your tile or ahead: + nurse, $ trader, ☺ classmate, ! story. Use a float badge for water and a pickaxe on marked walls.",
  "施設・同級生と話す": "Interact with facility",
  "正面の壁を掘る": "Dig ahead",
  "正面の罠を回収": "Collect trap ahead",
  "正面に罠を置く": "Place trap ahead",
  "同級生：": "Classmate: ",
  "待機→集合": "Wait → follow",
  "集合→待機": "Follow → wait",
  "倉庫・貯金・挑戦一覧": "Warehouse and challenges",
  "達成して学校前へ帰る": "Return after completion",
  "待機中": "Waiting",
  "同行中": "Following",
  "購買部：未払い": "Shop bill",
  "見回り中": "Monitors alerted",
  "精算する": "Pay bill",
  "持っている商品を返す": "Return carried goods",
  "装備の校章・封印・応援印": "Equipment emblems, seals and blessings",
  "工作のりで強化値と校章を合成できます。校章は4枠。封印品はお清め消しゴムで解除。応援印の道具を使うとHP20回復。": "Craft glue combines enhancement and emblems, up to four slots. Cleanse sealed supplies with an eraser. Blessed supplies heal 20 HP when used.",
  "中身を開く": "Open contents",
  "保存領域がいっぱいです。道具を減らして再保存してください。": "Storage is full. Reduce stored supplies and try again.",
  "購買部の未払い中は帰れません。先に精算しよう。": "Settle your shop bill before returning.",
  "救助の途中では帰れません。": "Finish the rescue before returning.",
  "救助できる忘れ物がありません。": "No supplies are available for rescue.",
  "忘れ物を救出！学校前の倉庫へ届けた！": "Supplies rescued and delivered to the warehouse!",
  "挑戦達成！帰還すると道具を倉庫へ持ち帰れます。": "Challenge complete! Return to keep your supplies.",
  "購買部の品を持っています。精算してから階段へ。": "Settle your shop bill before taking the stairs.",
  "水路です。浮き輪バッジで渡れます。": "A waterway. Wear a float badge to cross.",
  "床の穴から次の階へ落ちた！": "You fell through a hole to the next floor!",
  "つるつる床！1マス先まで滑るので足元に注意。": "Slippery floor! Watch the next tile as you slide.",
  "購買部の商品です。冒険手帳から精算できます。": "Shop supply: settle the bill in your adventure notebook.",
  "おこづかいが足りません。商品を返すこともできます。": "Not enough coins. You can return the supplies instead.",
  "精算しました。ありがとう！": "Bill settled. Thank you!",
  "体操服の挑戦では武器と防具は装備できません。": "Weapons and armor are disabled in this challenge.",
  "いたずら封印で外せません。お清め消しゴムを使おう。": "The slot is sealed. Use a cleansing eraser.",
  "いたずら封印で外せません。": "This equipment is sealed.",
  "いたずら封印で使えません。": "This supply is sealed.",
  "商品は精算してから使おう。": "Pay before using shop supplies.",
  "先生の応援印がついた！": "Teacher blessing applied!",
  "いたずら封印が全部消えた！": "All seals removed!",
  "応援する道具を次に選んでください。": "Select a supply to bless next.",
  "持っているだけで、倒れた時に助けてくれます。": "Keep this charm to revive after a defeat.",
  "工作つるはしが必要です。": "You need a working craft pickaxe.",
  "正面に壊せる壁がありません。": "No breakable wall ahead.",
  "隠しロッカーを発見！": "Hidden locker discovered!",
  "持ち物がいっぱいです。": "Your inventory is full.",
  "置ける罠がありません。": "No trap can be placed here.",
  "正面に見えている罠がありません。": "No visible trap ahead.",
  "罠袋は8個までです。": "The trap pouch holds eight traps.",
  "足元か正面の施設に近づこう。": "Approach a facility on your tile or ahead.",
  "保健室で休んだ。HP全回復、お腹も少し回復！": "Rested at the nurse: full HP and some food!",
  "行商のおやつは100円です。": "A trader snack costs 100 coins.",
  "行商のおやつを食べた！": "Enjoyed a trader snack!",
  "迷子の同級生と助け合う約束をした。": "A lost classmate agreed to help you.",
  "購買部の未払い！見回り先生が追ってくる！": "Unpaid supplies! Hall monitors are chasing you!",
  "下校チャイム！長居すると見回りが来ます。": "School bell! Leave before the monitors arrive.",
  "最終下校時刻！学校前へ戻されました。持ち物は忘れ物になりました。": "Final bell! You were sent home and left your supplies behind.",
  "手数を使い切った。もう一度作戦を考えよう。": "Turn limit reached. Try another strategy.",
  "同級生が成長した！": "Your classmate leveled up!",
  "同級生が道具を届けてくれた。": "Your classmate delivered a supply.",
  "同級生は安全な場所へ避難した。保健室で再合流できます。": "Your classmate retreated. Reunite at a facility.",
  "封印シール！道具が封印され、カードも3ターンお休み。": "Seal sticker! One supply is sealed and cards rest for three turns.",
  "筆箱が道具を飲み込んだ！倒すと戻ります。": "The pencil case swallowed a supply! Defeat it to recover it.",
  "道具がおにぎりになった！大事な道具はランドセルへ。": "A supply became a rice ball! Store precious items in a bag.",
  "工作わなに敵がかかった！": "Your crafted trap caught a foe!",
  "保健室のお守りで復活！": "The nurse charm revived you!",
  "放課後の大冒険": "After-school adventure",
  "手ぶらの99階": "Empty-handed 99 floors",
  "なぞなぞ校舎": "Mystery school",
  "いたずら工作室": "Trap workshop",
  "体操服の挑戦": "Gym-clothes challenge",
  "作戦ノートの30階": "Strategy notebook",
  "忘れ物レスキュー": "Lost-supply rescue",
  "放課後の一手": "One clever move",
  "さび防止": "Rustproof",
  "盗難防止": "Theft guard",
  "防火": "Fire guard",
  "身かわし": "Dodge",
  "回復": "Healing",
  "竜退治": "Dragon slayer",
  "腹もち": "Slow hunger",
  "罠見え": "Trap sight",
  "早い回復": "Fast recovery",
  "頑丈": "Sturdy",
  "水わたり": "Water walking",
  "道具持ち込み可。20階の校長先生へ。": "Bring equipment and challenge the principal on floor 20.",
  "倉庫の道具なし。拾った道具と知恵で99階へ。": "No warehouse items. Survive 99 floors with what you find.",
  "道具が未識別。使い方と値段で正体を考える30階。": "Identify mystery supplies through use and prices. 30 floors.",
  "罠を回収・設置して攻略する20階。罠が最初から見える。": "Visible traps, collection and placement. 20 floors.",
  "武器・防具を装備できない20階。道具と位置取りが頼り。": "No weapons or armor. Use supplies and positioning. 20 floors.",
  "2ではカード中心。1では傘とノート中心の道具戦。": "Cards in game 2, umbrellas and notebooks in game 1. 30 floors.",
  "倒れた階へ別の冒険で向かい、道具を倉庫に救出。3回まで。": "Reach the lost floor to recover supplies. Three attempts.",
  "固定配置の8問。限られた手数で階段へ。": "Eight fixed layouts. Reach the stairs within the turn limit.",
  "保存のランドセル": "Storage schoolbag",
  "保健の箱": "Nurse box",
  "調べる筆箱": "Inspection pencil case",
  "工作の箱": "Craft box",
  "お清め消しゴム": "Cleansing eraser",
  "先生の応援シール": "Teacher blessing sticker",
  "帰りの連絡帳": "Return notebook",
  "保健室のお守り": "Nurse charm",
  "工作つるはし": "Craft pickaxe",
  "浮き輪バッジ": "Float badge",
  "保健係のえんぴつ": "Nurse pencil",
  "竜退治の定規": "Dragon ruler",
  "保健係あおい": "Aoi the nurse helper",
  "体育係たける": "Takeru the sports helper",
  "図書係ひなた": "Hinata the librarian",
  "迷子の同級生": "Lost classmate",
  "ちぎれ紙おばけ": "Torn-paper ghost",
  "封印シール小僧": "Seal-sticker imp",
  "ぱくぱく筆箱": "Hungry pencil case",
  "消しゴム怪人": "Eraser monster",
  "おにぎり係": "Rice-ball prankster",
  "ガキ大将": "School bully",
  "見回り先生": "Hall monitor",
  "放課後の見回り": "After-school monitor",
  "居残りおばけ": "Detention ghost",
  "工作わな": "Crafted trap",
  "道具を6個収納。中身は出し入れできる。": "Stores six supplies. Contents can be retrieved.",
  "道具を入れるとHP30回復。中身は取り出せず、割ると戻る。": "Store a supply to heal 30 HP. Break the box to retrieve contents.",
  "入れた道具を識別。4個収納、自由に取り出せる。": "Identifies stored supplies. Four slots; contents can be retrieved.",
  "入れた道具が別の道具へ変化。割って取り出す。": "Stored supplies transform. Break to retrieve them.",
  "全ての装備と持ち物のいたずら封印を解除。": "Removes seals from all carried supplies and equipment.",
  "次に選んだ道具を祝福。使用時にHPを20回復。": "Bless the next selected supply. Using it heals 20 HP.",
  "道具とお金を持って学校前へ帰る。救助中には使えない。": "Return to the school base with supplies and coins. Unavailable during rescue.",
  "倒れた時に1個消費しHPを半分回復。": "Consumed on defeat to revive with half HP.",
  "正面の壁を壊せる。8回使用可能。": "Break a wall ahead. Eight uses.",
  "水路を渡れる腕輪。": "An accessory that allows crossing waterways.",
  "攻撃+4。攻撃するとHP3回復。校章として合成可能。": "Attack +4. Attacking heals 3 HP. Can transfer its emblem.",
  "攻撃+5。竜への攻撃2倍。校章として合成可能。": "Attack +5. Double damage to dragons. Can transfer its emblem."
};
export const SCHOOL_WANDERER_HIRAGANA:Record<string,string> = {
  "保存のランドセル": "ほぞんのらんどせる",
  "保健の箱": "ほけんのはこ",
  "調べる筆箱": "しらべるふでばこ",
  "工作の箱": "こうさくのはこ",
  "お清め消しゴム": "おきよめけしごむ",
  "先生の応援シール": "せんせいのおうえんしーる",
  "帰りの連絡帳": "かえりのれんらくちょう",
  "保健室のお守り": "ほけんしつのおまもり",
  "工作つるはし": "こうさくつるはし",
  "浮き輪バッジ": "うきわばっじ",
  "保健係のえんぴつ": "ほけんがかりのえんぴつ",
  "竜退治の定規": "りゅうたいじのじょうぎ",
  "冒険手帳": "ぼうけんてちょう",
  "学校前の集合場所": "がっこうまえのしゅうごうばしょ",
  "冒険に戻る": "ぼうけんにもどる",
  "倉庫・貯金・挑戦一覧": "そうこ・ちょきん・ちょうせんいちらん",
  "このルールで出発": "このるーるでしゅっぱつ"
};
