export const SCHOOL_WANDERER_ENGLISH:Record<string,string> = {
  " 🔒封印": " 🔒Sealed",
  " ⭐応援": " ⭐Blessed",
  "冒険手帳": "Notebook",
  "下校まで": "Bell in",
  "未払い": "Bill",
  "学校前と冒険手帳": "School base and notebook",
  "学校前の集合場所": "School meeting point",
  "容器": "Container",
  "放課後の冒険手帳": "After-school notebook",
  "冒険に戻る": "Resume",
  "倉庫と貯金箱はこの端末に保存します。手ぶらの挑戦では持ち込めません。": "Warehouse and savings are stored on this device. Challenge modes start without stored equipment.",
  "冒険を選ぶ": "Choose adventure",
  "救助先": "Rescue floor",
  "残り": "Attempts left",
  "倒れた冒険があると救助できます。": "A defeated adventure creates a rescue request.",
  "持っていくおこづかい": "Starting coins",
  "いっしょに行く同級生": "Classmate",
  "ひとりで挑戦": "Solo",
  "保健係あおい：回復": "Aoi: healing",
  "体育係たける：援護": "Takeru: support",
  "図書係ひなた：道具回収": "Hinata: supplies",
  "今の冒険を終了して、新しい冒険を始めますか？": "End the current adventure and start a new one?",
  "このルールで出発": "Start this adventure",
  "達成した挑戦": "Completed challenges",
  "学校前の倉庫": "Warehouse",
  "おこづかい貯金": "Savings",
  "持ち込み": "Selected",
  "帰りの連絡帳で帰還すると、道具を預けられます。": "Use a return notebook to bring supplies home.",
  "100円を貯金する": "Save 100 coins",
  "帰還した道具は、次の冒険で選んだ分だけ持ち出せます。": "Returned supplies can be selected for the next story adventure.",
  "入れるとHP30回復。取り出すには箱を割ります。": "Store a supply to heal 30 HP. Break the box to retrieve it.",
  "入れた道具が変化します。箱を割って取り出します。": "Stored supplies transform. Break the box to retrieve them.",
  "道具を入れる・取り出すごとに1ターン進みます。": "Storing or taking out a supply costs one turn.",
  "入れる道具": "Store a supply",
  "入っている道具": "Contents",
  "箱を割って全部出す": "Break and empty",
  "足元か正面の施設：＋保健室、＄行商、☺同級生、！会話。水路は浮き輪、？の壁はつるはしで調べよう。": "Facilities on your tile or ahead: + nurse, $ trader, ☺ classmate, ! story. Use a float badge for water and a pickaxe on marked walls.",
  "施設・同級生と話す": "Interact with facility",
  "正面の壁を掘る": "Dig ahead",
  "正面の罠を回収": "Collect trap ahead",
  "正面に罠を置く": "Place trap ahead",
  "同級生：": "Classmate: ",
  "待機→集合": "Wait → follow",
  "集合→待機": "Follow → wait",
  "倉庫・貯金・挑戦一覧": "Warehouse and challenges",
  "達成して学校前へ帰る": "Return after completion",
  "待機中": "Waiting",
  "同行中": "Following",
  "購買部：未払い": "Shop bill",
  "見回り中": "Monitors alerted",
  "精算する": "Pay bill",
  "持っている商品を返す": "Return carried goods",
  "装備の校章・封印・応援印": "Equipment emblems, seals and blessings",
  "工作のりで強化値と校章を合成できます。校章は4枠。封印品はお清め消しゴムで解除。応援印の道具を使うとHP20回復。": "Craft glue combines enhancement and emblems, up to four slots. Cleanse sealed supplies with an eraser. Blessed supplies heal 20 HP when used.",
  "中身を開く": "Open contents",
  "保存領域がいっぱいです。道具を減らして再保存してください。": "Storage is full. Reduce stored supplies and try again.",
  "購買部の未払い中は帰れません。先に精算しよう。": "Settle your shop bill before returning.",
  "救助の途中では帰れません。": "Finish the rescue before returning.",
  "救助できる忘れ物がありません。": "No supplies are available for rescue.",
  "忘れ物を救出！学校前の倉庫へ届けた！": "Supplies rescued and delivered to the warehouse!",
  "挑戦達成！帰還すると道具を倉庫へ持ち帰れます。": "Challenge complete! Return to keep your supplies.",
  "購買部の品を持っています。精算してから階段へ。": "Settle your shop bill before taking the stairs.",
  "水路です。浮き輪バッジで渡れます。": "A waterway. Wear a float badge to cross.",
  "床の穴から次の階へ落ちた！": "You fell through a hole to the next floor!",
  "つるつる床！1マス先まで滑るので足元に注意。": "Slippery floor! Watch the next tile as you slide.",
  "購買部の商品です。冒険手帳から精算できます。": "Shop supply: settle the bill in your adventure notebook.",
  "おこづかいが足りません。商品を返すこともできます。": "Not enough coins. You can return the supplies instead.",
  "精算しました。ありがとう！": "Bill settled. Thank you!",
  "体操服の挑戦では武器と防具は装備できません。": "Weapons and armor are disabled in this challenge.",
  "いたずら封印で外せません。お清め消しゴムを使おう。": "The slot is sealed. Use a cleansing eraser.",
  "いたずら封印で外せません。": "This equipment is sealed.",
  "いたずら封印で使えません。": "This supply is sealed.",
  "商品は精算してから使おう。": "Pay before using shop supplies.",
  "先生の応援印がついた！": "Teacher blessing applied!",
  "いたずら封印が全部消えた！": "All seals removed!",
  "応援する道具を次に選んでください。": "Select a supply to bless next.",
  "持っているだけで、倒れた時に助けてくれます。": "Keep this charm to revive after a defeat.",
  "工作つるはしが必要です。": "You need a working craft pickaxe.",
  "正面に壊せる壁がありません。": "No breakable wall ahead.",
  "隠しロッカーを発見！": "Hidden locker discovered!",
  "持ち物がいっぱいです。": "Your inventory is full.",
  "置ける罠がありません。": "No trap can be placed here.",
  "正面に見えている罠がありません。": "No visible trap ahead.",
  "罠袋は8個までです。": "The trap pouch holds eight traps.",
  "足元か正面の施設に近づこう。": "Approach a facility on your tile or ahead.",
  "保健室で休んだ。HP全回復、お腹も少し回復！": "Rested at the nurse: full HP and some food!",
  "行商のおやつは100円です。": "A trader snack costs 100 coins.",
  "行商のおやつを食べた！": "Enjoyed a trader snack!",
  "迷子の同級生と助け合う約束をした。": "A lost classmate agreed to help you.",
  "購買部の未払い！見回り先生が追ってくる！": "Unpaid supplies! Hall monitors are chasing you!",
  "下校チャイム！長居すると見回りが来ます。": "School bell! Leave before the monitors arrive.",
  "最終下校時刻！学校前へ戻されました。持ち物は忘れ物になりました。": "Final bell! You were sent home and left your supplies behind.",
  "手数を使い切った。もう一度作戦を考えよう。": "Turn limit reached. Try another strategy.",
  "同級生が成長した！": "Your classmate leveled up!",
  "同級生が道具を届けてくれた。": "Your classmate delivered a supply.",
  "同級生は安全な場所へ避難した。保健室で再合流できます。": "Your classmate retreated. Reunite at a facility.",
  "封印シール！道具が封印され、カードも3ターンお休み。": "Seal sticker! One supply is sealed and cards rest for three turns.",
  "筆箱が道具を飲み込んだ！倒すと戻ります。": "The pencil case swallowed a supply! Defeat it to recover it.",
  "道具がおにぎりになった！大事な道具はランドセルへ。": "A supply became a rice ball! Store precious items in a bag.",
  "工作わなに敵がかかった！": "Your crafted trap caught a foe!",
  "保健室のお守りで復活！": "The nurse charm revived you!",
  "放課後の大冒険": "After-school adventure",
  "手ぶらの99階": "Empty-handed 99 floors",
  "なぞなぞ校舎": "Mystery school",
  "いたずら工作室": "Trap workshop",
  "体操服の挑戦": "Gym-clothes challenge",
  "作戦ノートの30階": "Strategy notebook",
  "忘れ物レスキュー": "Lost-supply rescue",
  "放課後の一手": "One clever move",
  "さび防止": "Rustproof",
  "盗難防止": "Theft guard",
  "防火": "Fire guard",
  "身かわし": "Dodge",
  "回復": "Healing",
  "竜退治": "Dragon slayer",
  "腹もち": "Slow hunger",
  "罠見え": "Trap sight",
  "早い回復": "Fast recovery",
  "頑丈": "Sturdy",
  "水わたり": "Water walking",
  "道具持ち込み可。20階の校長先生へ。": "Bring equipment and challenge the principal on floor 20.",
  "倉庫の道具なし。拾った道具と知恵で99階へ。": "No warehouse items. Survive 99 floors with what you find.",
  "道具が未識別。使い方と値段で正体を考える30階。": "Identify mystery supplies through use and prices. 30 floors.",
  "罠を回収・設置して攻略する20階。罠が最初から見える。": "Visible traps, collection and placement. 20 floors.",
  "武器・防具を装備できない20階。道具と位置取りが頼り。": "No weapons or armor. Use supplies and positioning. 20 floors.",
  "2ではカード中心。1では傘とノート中心の道具戦。": "Cards in game 2, umbrellas and notebooks in game 1. 30 floors.",
  "倒れた階へ別の冒険で向かい、道具を倉庫に救出。3回まで。": "Reach the lost floor to recover supplies. Three attempts.",
  "固定配置の8問。限られた手数で階段へ。": "Eight fixed layouts. Reach the stairs within the turn limit.",
  "保存のランドセル": "Storage schoolbag",
  "保健の箱": "Nurse box",
  "調べる筆箱": "Inspection pencil case",
  "工作の箱": "Craft box",
  "お清め消しゴム": "Cleansing eraser",
  "先生の応援シール": "Teacher blessing sticker",
  "帰りの連絡帳": "Return notebook",
  "保健室のお守り": "Nurse charm",
  "工作つるはし": "Craft pickaxe",
  "浮き輪バッジ": "Float badge",
  "保健係のえんぴつ": "Nurse pencil",
  "竜退治の定規": "Dragon ruler",
  "保健係あおい": "Aoi the nurse helper",
  "体育係たける": "Takeru the sports helper",
  "図書係ひなた": "Hinata the librarian",
  "迷子の同級生": "Lost classmate",
  "ちぎれ紙おばけ": "Torn-paper ghost",
  "封印シール小僧": "Seal-sticker imp",
  "ぱくぱく筆箱": "Hungry pencil case",
  "消しゴム怪人": "Eraser monster",
  "おにぎり係": "Rice-ball prankster",
  "ガキ大将": "School bully",
  "見回り先生": "Hall monitor",
  "放課後の見回り": "After-school monitor",
  "居残りおばけ": "Detention ghost",
  "工作わな": "Crafted trap",
  "道具を6個収納。中身は出し入れできる。": "Stores six supplies. Contents can be retrieved.",
  "道具を入れるとHP30回復。中身は取り出せず、割ると戻る。": "Store a supply to heal 30 HP. Break the box to retrieve contents.",
  "入れた道具を識別。4個収納、自由に取り出せる。": "Identifies stored supplies. Four slots; contents can be retrieved.",
  "入れた道具が別の道具へ変化。割って取り出す。": "Stored supplies transform. Break to retrieve them.",
  "全ての装備と持ち物のいたずら封印を解除。": "Removes seals from all carried supplies and equipment.",
  "次に選んだ道具を祝福。使用時にHPを20回復。": "Bless the next selected supply. Using it heals 20 HP.",
  "道具とお金を持って学校前へ帰る。救助中には使えない。": "Return to the school base with supplies and coins. Unavailable during rescue.",
  "倒れた時に1個消費しHPを半分回復。": "Consumed on defeat to revive with half HP.",
  "正面の壁を壊せる。8回使用可能。": "Break a wall ahead. Eight uses.",
  "水路を渡れる腕輪。": "An accessory that allows crossing waterways.",
  "攻撃+4。攻撃するとHP3回復。校章として合成可能。": "Attack +4. Attacking heals 3 HP. Can transfer its emblem.",
  "攻撃+5。竜への攻撃2倍。校章として合成可能。": "Attack +5. Double damage to dragons. Can transfer its emblem."
};
export const SCHOOL_WANDERER_HIRAGANA:Record<string,string> = {
  "保存のランドセル": "ほぞんのらんどせる",
  "保健の箱": "ほけんのはこ",
  "調べる筆箱": "しらべるふでばこ",
  "工作の箱": "こうさくのはこ",
  "お清め消しゴム": "おきよめけしごむ",
  "先生の応援シール": "せんせいのおうえんしーる",
  "帰りの連絡帳": "かえりのれんらくちょう",
  "保健室のお守り": "ほけんしつのおまもり",
  "工作つるはし": "こうさくつるはし",
  "浮き輪バッジ": "うきわばっじ",
  "保健係のえんぴつ": "ほけんがかりのえんぴつ",
  "竜退治の定規": "りゅうたいじのじょうぎ",
  "冒険手帳": "ぼうけんてちょう",
  "学校前の集合場所": "がっこうまえのしゅうごうばしょ",
  "冒険に戻る": "ぼうけんにもどる",
  "倉庫・貯金・挑戦一覧": "そうこ・ちょきん・ちょうせんいちらん",
  "このルールで出発": "このるーるでしゅっぱつ"
};

Object.assign(SCHOOL_WANDERER_ENGLISH, {
  "風来の小学生道場：冒険とは別の持ち物で練習。失敗しても倉庫や救助に影響しません。": "School Wanderer dojo: practice with separate supplies. Failure never affects your warehouse or rescue.",
  "この練習をはじめる": "Start this lesson",
  "お腹": "Food",
  "手数": "Turns",
  "道場の練習マップ": "Dojo practice map",
  "道具を使う": "Use tool",
  "先生のヒント": "Teacher hint",
  "やり直す": "Restart",
  "50ステージ一覧": "All 50 stages",
  "練習クリア！学んだ作戦を冒険でも使おう。": "Lesson cleared! Use this strategy in your adventure.",
  "もう一度考えてみよう。道具・位置・手数を見直そう。": "Try again. Review your tools, position and turn budget.",
  "次の練習へ": "Next lesson",
  " 🔒封印": " 🔒Sealed",
  " ⭐応援": " ⭐Blessed",
  "冒険手帳": "Notebook",
  "旅の町：安全地帯": "Journey village: safe area",
  "景勝地：ひと休み": "Scenic stop: rest",
  "下校まで": "Bell in",
  "夜": "Night",
  "昼": "Day",
  "雨": "Rain",
  "霧": "Fog",
  "風": "Wind",
  "晴れ": "Clear",
  "学校前へ帰る": "Return to school base",
  "未払い": "Bill",
  "学校前と冒険手帳": "School base and notebook",
  "風来の小学生道場": "School Wanderer dojo",
  "ダンジョン途中の町": "Journey village",
  "探検の記録": "Adventure records",
  "学校前の集合場所": "School meeting point",
  "容器": "Container",
  "放課後の冒険手帳": "After-school notebook",
  "冒険に戻る": "Resume",
  "学校前へ戻る": "Back to the base",
  "施設の隣に立つと利用できます。町では空腹や下校チャイムは進みません。": "Stand beside a facility to use it. Hunger and the school bell pause in town.",
  "おこづかい": "Coins",
  "利用できます": "Available",
  "施設に近づこう": "Move closer",
  "宿泊・乾燥・全回復：80": "Rest, dry supplies, full recovery: 80",
  "装備+1・封印解除：150": "Equipment +1 and cleanse: 150",
  "おこづかいを全額預ける": "Deposit all carried coins",
  "お祭りの景品を引く：50": "Draw a festival prize: 50",
  "見つけた道具と敵、冒険の出来事を記録します。": "A record of discovered supplies, foes and adventure moments.",
  "道場の修了証": "Dojo certificate",
  "道場10問：報酬を受け取る": "10 lessons: claim reward",
  "道場50問：報酬を受け取る": "50 lessons: claim reward",
  "発見20種：報酬を受け取る": "20 discoveries: claim reward",
  "発見した道具と敵": "Discovered supplies and foes",
  "冒険日記": "Adventure diary",
  "風来の小学生道場：50ステージ": "School Wanderer dojo: 50 stages",
  "探検の記録・修了証": "Records and certificates",
  "倉庫と貯金箱はこの端末に保存します。手ぶらの挑戦では持ち込めません。": "Warehouse and savings are stored on this device. Challenge modes start without stored equipment.",
  "冒険を選ぶ": "Choose adventure",
  "救助先": "Rescue floor",
  "残り": "Attempts left",
  "倒れた冒険があると救助できます。": "A defeated adventure creates a rescue request.",
  "持っていくおこづかい": "Starting coins",
  "いっしょに行く同級生": "Classmate",
  "ひとりで挑戦": "Solo",
  "保健係あおい：回復": "Aoi: healing",
  "体育係たける：援護": "Takeru: support",
  "図書係ひなた：道具回収": "Hinata: supplies",
  "今の冒険を終了して、新しい冒険を始めますか？": "End the current adventure and start a new one?",
  "このルールで出発": "Start this adventure",
  "達成した挑戦": "Completed challenges",
  "学校前の倉庫": "Warehouse",
  "おこづかい貯金": "Savings",
  "持ち込み": "Selected",
  "帰りの連絡帳で帰還すると、道具を預けられます。": "Use a return notebook to bring supplies home.",
  "帰還した道具は、次の冒険で選んだ分だけ持ち出せます。": "Returned supplies can be selected for the next story adventure.",
  "入れるとHP30回復。取り出すには箱を割ります。": "Store a supply to heal 30 HP. Break the box to retrieve it.",
  "入れた道具が変化します。箱を割って取り出します。": "Stored supplies transform. Break the box to retrieve them.",
  "道具を入れる・取り出すごとに1ターン進みます。": "Storing or taking out a supply costs one turn.",
  "入れる道具": "Store a supply",
  "入っている道具": "Contents",
  "箱を割って全部出す": "Break and empty",
  "足元か正面の施設：＋保健室、＄行商、☺同級生、！会話。水路は浮き輪、？の壁はつるはしで調べよう。": "Facilities on your tile or ahead: + nurse, $ trader, ☺ classmate, ! story. Use a float badge for water and a pickaxe on marked walls.",
  "施設・同級生と話す": "Interact with facility",
  "正面の壁を掘る": "Dig ahead",
  "正面の罠を回収": "Collect trap ahead",
  "正面に罠を置く": "Place trap ahead",
  "同級生：": "Classmate: ",
  "待機→集合": "Wait → follow",
  "集合→待機": "Follow → wait",
  "町の施設を利用": "Town facilities",
  "倉庫・貯金・挑戦一覧": "Warehouse and challenges",
  "達成して学校前へ帰る": "Return after completion",
  "待機中": "Waiting",
  "同行中": "Following",
  "購買部：未払い": "Shop bill",
  "見回り中": "Monitors alerted",
  "精算する": "Pay bill",
  "持っている商品を返す": "Return carried goods",
  "装備の校章・封印・応援印": "Equipment emblems, seals and blessings",
  "工作のりで強化値と校章を合成できます。校章は4枠。封印品はお清め消しゴムで解除。応援印の道具を使うとHP20回復。": "Craft glue combines enhancement and emblems, up to four slots. Cleanse sealed supplies with an eraser. Blessed supplies heal 20 HP when used.",
  "中身を開く": "Open contents",
  "保存領域がいっぱいです。道具を減らして再保存してください。": "Storage is full. Reduce stored supplies and try again.",
  "購買部の未払い中は帰れません。先に精算しよう。": "Settle your shop bill before returning.",
  "救助の途中では帰れません。": "Finish the rescue before returning.",
  "救助できる忘れ物がありません。": "No supplies are available for rescue.",
  "忘れ物を救出！学校前の倉庫へ届けた！": "Supplies rescued and delivered to the warehouse!",
  "挑戦達成！帰還すると道具を倉庫へ持ち帰れます。": "Challenge complete! Return to keep your supplies.",
  "購買部の品を持っています。精算してから階段へ。": "Settle your shop bill before taking the stairs.",
  "水路です。浮き輪バッジで渡れます。": "A waterway. Wear a float badge to cross.",
  "床の穴から次の階へ落ちた！": "You fell through a hole to the next floor!",
  "つるつる床！1マス先まで滑るので足元に注意。": "Slippery floor! Watch the next tile as you slide.",
  "購買部の商品です。冒険手帳から精算できます。": "Shop supply: settle the bill in your adventure notebook.",
  "おこづかいが足りません。商品を返すこともできます。": "Not enough coins. You can return the supplies instead.",
  "精算しました。ありがとう！": "Bill settled. Thank you!",
  "体操服の挑戦では武器と防具は装備できません。": "Weapons and armor are disabled in this challenge.",
  "いたずら封印で外せません。お清め消しゴムを使おう。": "The slot is sealed. Use a cleansing eraser.",
  "いたずら封印で外せません。": "This equipment is sealed.",
  "道具が濡れています。町の宿かお手入れセットで乾かそう。": "This supply is wet. Dry it at an inn or use a repair kit.",
  "いたずら封印で使えません。": "This supply is sealed.",
  "商品は精算してから使おう。": "Pay before using shop supplies.",
  "先生の応援印がついた！": "Teacher blessing applied!",
  "いたずら封印が全部消えた！": "All seals removed!",
  "応援する道具を次に選んでください。": "Select a supply to bless next.",
  "持っているだけで、倒れた時に助けてくれます。": "Keep this charm to revive after a defeat.",
  "傘の魔法は使い切りました。": "The umbrella has no charges left.",
  "使う方向を向いてください。": "Face the direction to use it.",
  "敵が近くにいます。安全な場所で休もう。": "Foes are nearby. Find a safe place to rest.",
  "探検道具を使った！": "Explorer supply used!",
  "工作つるはしが必要です。": "You need a working craft pickaxe.",
  "正面に壊せる壁がありません。": "No breakable wall ahead.",
  "隠しロッカーを発見！": "Hidden locker discovered!",
  "持ち物がいっぱいです。": "Your inventory is full.",
  "置ける罠がありません。": "No trap can be placed here.",
  "正面に見えている罠がありません。": "No visible trap ahead.",
  "罠袋は8個までです。": "The trap pouch holds eight traps.",
  "足元か正面の施設に近づこう。": "Approach a facility on your tile or ahead.",
  "景勝地でひと休み。HPとお腹が回復した。": "A scenic rest restored HP and food.",
  "保健室で休んだ。HP全回復、お腹も少し回復！": "Rested at the nurse: full HP and some food!",
  "行商のおやつは100円です。": "A trader snack costs 100 coins.",
  "行商のおやつを食べた！": "Enjoyed a trader snack!",
  "迷子の同級生と助け合う約束をした。": "A lost classmate agreed to help you.",
  "購買部の未払い！見回り先生が追ってくる！": "Unpaid supplies! Hall monitors are chasing you!",
  "下校チャイム！長居すると見回りが来ます。": "School bell! Leave before the monitors arrive.",
  "最終下校時刻！学校前へ戻されました。持ち物は忘れ物になりました。": "Final bell! You were sent home and left your supplies behind.",
  "手数を使い切った。もう一度作戦を考えよう。": "Turn limit reached. Try another strategy.",
  "風で床の道具が少し動いた。": "Wind moved loose supplies on the floor.",
  "雨で紙の道具が濡れた。宿で乾かせます。": "Rain soaked a paper supply. Dry it at an inn.",
  "同級生が成長した！": "Your classmate leveled up!",
  "同級生が道具を届けてくれた。": "Your classmate delivered a supply.",
  "同級生は安全な場所へ避難した。保健室で再合流できます。": "Your classmate retreated. Reunite at a facility.",
  "びっくり宝箱がおこづかいをくわえた！": "The surprise chest grabbed your coins!",
  "封印シール！道具が封印され、カードも3ターンお休み。": "Seal sticker! One supply is sealed and cards rest for three turns.",
  "筆箱が道具を飲み込んだ！倒すと戻ります。": "The pencil case swallowed a supply! Defeat it to recover it.",
  "道具がおにぎりになった！大事な道具はランドセルへ。": "A supply became a rice ball! Store precious items in a bag.",
  "工作わなに敵がかかった！": "Your crafted trap caught a foe!",
  "保健室のお守りで復活！": "The nurse charm revived you!",
  "達成すると一度だけ報酬を受け取れます。": "Complete this milestone to claim its reward once.",
  "修了証の報酬を貯金箱に届けた！": "Certificate reward delivered to your savings!",
  "町の施設の隣へ移動してから利用しよう。": "Move beside the town facility first.",
  "おこづかいが足りません。": "Not enough coins.",
  "この町でのお手入れは済んでいます。": "Your equipment was already serviced in this town.",
  "おこづかいを学校前の貯金箱に送った。": "Coins sent to your savings at school.",
  "お祭りの景品は受け取り済みです。": "You already collected this festival prize.",
  "町で旅の準備を整えた。": "Prepared for the journey in town.",
  "雨ふらしの傘": "Rain umbrella",
  "正面の一直線にいる最初の敵へ20ダメージ。3回使える。": "Deals up to 20 damage and freezes the first foe along your facing direction. Three uses.",
  "おやすみホイッスル": "Sleep whistle",
  "周囲2マスの敵を8ターン眠らせる。": "Puts foes within two tiles to sleep for eight turns.",
  "とびだす折り鶴": "Flying origami crane",
  "敵と罠のない床へワープ。ピンチを抜け出す。": "Warps to a safe floor tile, away from foes and traps.",
  "探検虫めがね": "Explorer magnifier",
  "この階の罠を全て発見。": "Reveals every trap on this floor.",
  "雨よけバッジ": "Rainproof badge",
  "雨の日でも紙の道具が濡れない。": "Protects paper supplies from rain.",
  "ピクニックシート": "Picnic mat",
  "周囲3マスに敵がいなければHP30とお腹20回復。": "Restores 30 HP and 20 food if no foe is within three tiles.",
  "お手入れセット": "Repair kit",
  "装備中の武器と防具を+1。道具の水濡れも直す。": "Improves equipped weapon and armor by one and dries supplies.",
  "探検の金メダル": "Golden explorer medal",
  "先生に見せるとおこづかい300。": "Trade it for 300 coins.",
  "びっくり宝箱": "Surprise chest",
  "夜ふかし傘おばけ": "Night umbrella",
  "どろんこ長ぐつ": "Muddy boot",
  "元気な芽ばえ": "Lively sprout",
  "川辺の宿": "Riverside inn",
  "工作工房": "Craft smith",
  "郵便・預かり所": "Mail and savings",
  "旅のお店": "Travel shop",
  "町のお祭り": "Town festival",
  "ホイッスル": "Whistle",
  "魔法の傘": "Magic umbrella",
  "浮き輪": "Float",
  "虫めがね": "Magnifier",
  "お弁当": "Lunch",
  "鍵": "Key",
  "つるはし": "Pickaxe",
  "道具なし": "No tool"
});
Object.assign(SCHOOL_WANDERER_HIRAGANA, {
  "風来の小学生道場": "ふうらいのしょうがくせいどうじょう",
  "風来の小学生道場：50ステージ": "ふうらいのしょうがくせいどうじょう：50すてーじ",
  "探検の記録": "たんけんのきろく",
  "探検の記録・修了証": "たんけんのきろく・しゅうりょうしょう",
  "ダンジョン途中の町": "だんじょんとちゅうのまち",
  "学校前へ戻る": "がっこうまえへもどる",
  "この練習をはじめる": "このれんしゅうをはじめる",
  "50ステージ一覧": "50すてーじいちらん",
  "先生のヒント": "せんせいのひんと",
  "やり直す": "やりなおす",
  "次の練習へ": "つぎのれんしゅうへ",
  "道具を使う": "どうぐをつかう",
  "お腹": "おなか",
  "手数": "てかず",
  "雨ふらしの傘": "あめふらしのかさ",
  "おやすみホイッスル": "おやすみほいっする",
  "とびだす折り鶴": "とびだすおりづる",
  "探検虫めがね": "たんけんむしめがね",
  "雨よけバッジ": "あめよけばっじ",
  "ピクニックシート": "ぴくにっくしーと",
  "お手入れセット": "おていれせっと",
  "探検の金メダル": "たんけんのきんめだる",
  "びっくり宝箱": "びっくりたからばこ",
  "夜ふかし傘おばけ": "よふかしかさおばけ",
  "どろんこ長ぐつ": "どろんこながぐつ",
  "元気な芽ばえ": "げんきなめばえ",
  "川辺の宿": "かわべのやど",
  "工作工房": "こうさくこうぼう",
  "郵便・預かり所": "ゆうびん・あずかりじょ",
  "旅のお店": "たびのおみせ",
  "町のお祭り": "まちのおまつり",
  "利用できます": "りようできます",
  "施設に近づこう": "しせつにちかづこう",
  "おこづかい": "おこづかい",
  "町の施設を利用": "まちのしせつをりよう",
  "道場の修了証": "どうじょうのしゅうりょうしょう",
  "発見した道具と敵": "はっけんしたどうぐとてき",
  "冒険日記": "ぼうけんにっき",
  "夜": "よる",
  "昼": "ひる",
  "雨": "あめ",
  "霧": "きり",
  "風": "かぜ",
  "晴れ": "はれ",
  "旅の町：安全地帯": "たびのまち：あんぜんちたい",
  "景勝地：ひと休み": "けいしょうち：ひとやすみ",
  "ホイッスル": "ほいっする",
  "魔法の傘": "まほうのかさ",
  "浮き輪": "うきわ",
  "虫めがね": "むしめがね",
  "お弁当": "おべんとう",
  "鍵": "かぎ",
  "つるはし": "つるはし",
  "道具なし": "どうぐなし",
  "宿泊・乾燥・全回復：80": "しゅくはく・かんそう・ぜんかいふく：80",
  "装備+1・封印解除：150": "そうび+1・ふういんかいじょ：150",
  "おこづかいを全額預ける": "おこづかいをぜんがくあずける",
  "お祭りの景品を引く：50": "おまつりのけいひんをひく：50",
  "道場10問：報酬を受け取る": "どうじょう10もん：ほうしゅうをうけとる",
  "道場50問：報酬を受け取る": "どうじょう50もん：ほうしゅうをうけとる",
  "発見20種：報酬を受け取る": "はっけん20しゅ：ほうしゅうをうけとる"
});

Object.assign(SCHOOL_WANDERER_ENGLISH, {'保健係セット':'Nurse set','防災探検セット':'Disaster explorer set','ものを大切にセット':'Careful keeper set','装備の共鳴':'Equipment resonance'});
Object.assign(SCHOOL_WANDERER_HIRAGANA, {'保健係セット':'ほけんがかりせっと','防災探検セット':'ぼうさいたんけんせっと','ものを大切にセット':'ものをたいせつにせっと','装備の共鳴':'そうびのきょうめい'});

Object.assign(SCHOOL_WANDERER_ENGLISH, {'隣のマスをタッチ、または矢印キー。斜めはQ・E・Z・C、道具はスペース。':'Tap an adjacent tile or use arrow keys. Q/E/Z/C move diagonally; Space uses your tool.'});
Object.assign(SCHOOL_WANDERER_HIRAGANA, {'隣のマスをタッチ、または矢印キー。斜めはQ・E・Z・C、道具はスペース。':'となりのますをたっち、またはやじるしきー。ななめはQ・E・Z・C、どうぐはすぺーす。'});

Object.assign(SCHOOL_WANDERER_HIRAGANA, {"一歩と一ターン 1": "いっぽといちたーん 1", "一歩と一ターン 2": "いっぽといちたーん 2", "一歩と一ターン 3": "いっぽといちたーん 3", "一歩と一ターン 4": "いっぽといちたーん 4", "一歩と一ターン 5": "いっぽといちたーん 5", "斜めと壁の角 1": "ななめとかべのかど 1", "斜めと壁の角 2": "ななめとかべのかど 2", "斜めと壁の角 3": "ななめとかべのかど 3", "斜めと壁の角 4": "ななめとかべのかど 4", "斜めと壁の角 5": "ななめとかべのかど 5", "通路の一対一 1": "つうろのいちたいいち 1", "通路の一対一 2": "つうろのいちたいいち 2", "通路の一対一 3": "つうろのいちたいいち 3", "通路の一対一 4": "つうろのいちたいいち 4", "通路の一対一 5": "つうろのいちたいいち 5", "眠らせて通る 1": "ねむらせてとおる 1", "眠らせて通る 2": "ねむらせてとおる 2", "眠らせて通る 3": "ねむらせてとおる 3", "眠らせて通る 4": "ねむらせてとおる 4", "眠らせて通る 5": "ねむらせてとおる 5", "一直線の道具 1": "いっちょくせんのどうぐ 1", "一直線の道具 2": "いっちょくせんのどうぐ 2", "一直線の道具 3": "いっちょくせんのどうぐ 3", "一直線の道具 4": "いっちょくせんのどうぐ 4", "一直線の道具 5": "いっちょくせんのどうぐ 5", "水路の備え 1": "すいろのそなえ 1", "水路の備え 2": "すいろのそなえ 2", "水路の備え 3": "すいろのそなえ 3", "水路の備え 4": "すいろのそなえ 4", "水路の備え 5": "すいろのそなえ 5", "罠を調べる 1": "わなをしらべる 1", "罠を調べる 2": "わなをしらべる 2", "罠を調べる 3": "わなをしらべる 3", "罠を調べる 4": "わなをしらべる 4", "罠を調べる 5": "わなをしらべる 5", "お腹とお弁当 1": "おなかとおべんとう 1", "お腹とお弁当 2": "おなかとおべんとう 2", "お腹とお弁当 3": "おなかとおべんとう 3", "お腹とお弁当 4": "おなかとおべんとう 4", "お腹とお弁当 5": "おなかとおべんとう 5", "鍵と寄り道 1": "かぎとよりみち 1", "鍵と寄り道 2": "かぎとよりみち 2", "鍵と寄り道 3": "かぎとよりみち 3", "鍵と寄り道 4": "かぎとよりみち 4", "鍵と寄り道 5": "かぎとよりみち 5", "掘って近道 1": "ほってちかみち 1", "掘って近道 2": "ほってちかみち 2", "掘って近道 3": "ほってちかみち 3", "掘って近道 4": "ほってちかみち 4", "掘って近道 5": "ほってちかみち 5", "階段への最短経路を考えよう。": "かいだんへのさいたんけいろをかんがえよう。", "壁の角は斜めに通り抜けられない。": "かべのかどはななめにとおりぬけられない。", "敵に向かって歩くと攻撃。敵が並ぶ通路で一体ずつ。": "てきにむかってあるくとこうげき。てきがならぶつうろでいったいずつ。", "ホイッスルで近くの敵を眠らせ、反撃を止めよう。": "ほいっするでちかくのてきをねむらせ、はんげきをとめよう。", "傘の魔法は向いている方向の一直線に届く。": "かさのまほうはむいているほうこうのいっちょくせんにとどく。", "浮き輪を使ってから水路へ入ろう。": "うきわをつかってからすいろへはいろう。", "虫めがねで罠を見つけてから、安全な道へ。": "むしめがねでわなをみつけてから、あんぜんなみちへ。", "お腹が0だと毎ターンHPが減る。早めに食べよう。": "おなかが0だとまいたーんHPがへる。はやめにたべよう。", "鍵を拾い、扉の隣で道具を使って開けよう。": "かぎをひろい、とびらのとなりでどうぐをつかってあけよう。", "つるはしで正面の壁を掘り、近道を作ろう。": "つるはしでしょうめんのかべをほり、ちかみちをつくろう。"});
Object.assign(SCHOOL_WANDERER_ENGLISH, {"そこには進めません。向きは変えられます。": "Blocked. You can still change facing.", "道具の残り回数がありません。": "No tool uses remain.", "罠を踏んだ！HP3減。": "A trap! Lost 3 HP.", "攻撃した。敵が隣にいると反撃されます。": "Attacked. Adjacent foes can retaliate.", "一歩進んだ。": "Moved one step.", "近くの敵を眠らせた。": "Nearby foes fell asleep.", "正面へ傘の魔法！": "Umbrella magic cast ahead!", "浮き輪を装着した。": "Float equipped.", "隠れた罠を調べた。": "Hidden traps revealed.", "お弁当でお腹が20回復。": "Lunch restored 20 food.", "鍵で扉を開けた。": "Door unlocked.", "正面の壁を掘った。": "Dug the wall ahead."});

Object.assign(SCHOOL_WANDERER_ENGLISH, {'遊び方・操作':'How to play'});Object.assign(SCHOOL_WANDERER_HIRAGANA, {'遊び方・操作':'あそびかた・そうさ'});

Object.assign(SCHOOL_WANDERER_ENGLISH, {'川辺の宿場町':'Riverside village','桜の滝見坂':'Cherry waterfall path','竹林の天空橋':'Bamboo sky bridge','紅葉の鏡湖':'Autumn mirror lake','雪山の星灯り':'Snowy starlight'});Object.assign(SCHOOL_WANDERER_HIRAGANA, {'川辺の宿場町':'かわべのしゅくばまち','桜の滝見坂':'さくらのたきみざか','竹林の天空橋':'ちくりんのてんくうばし','紅葉の鏡湖':'こうようのかがみこ','雪山の星灯り':'ゆきやまのほしあかり'});

Object.assign(SCHOOL_WANDERER_ENGLISH, {' 💧ぬれ':' 💧Wet'});Object.assign(SCHOOL_WANDERER_HIRAGANA, {' 💧ぬれ':' 💧ぬれ'});

Object.assign(SCHOOL_WANDERER_ENGLISH,{'移動・攻撃はいつもの十字キーとAボタン。Bで道具とヒント、Rで道具を使えます。':'Use the usual D-pad and A button to move and attack. B opens tools and hints; R uses your tool.','道場5問修了 または 大冒険クリア':'Clear 5 dojo lessons or the story','道場15問修了 または 大冒険クリア':'Clear 15 dojo lessons or the story','放課後の大冒険クリア':'Clear the after-school adventure','なぞなぞ校舎 または 作戦ノートクリア':'Clear Mystery school or Strategy notebook','体操服の挑戦クリア':'Clear the gym-clothes challenge','倒れた冒険の救助依頼':'A rescue request from a defeated adventure'});
Object.assign(SCHOOL_WANDERER_HIRAGANA,{'移動・攻撃はいつもの十字キーとAボタン。Bで道具とヒント、Rで道具を使えます。':'いどう・こうげきは いつもの じゅうじキーとAボタン。Bで どうぐとヒント、Rで どうぐを つかえます。','道場5問修了 または 大冒険クリア':'どうじょう5もん しゅうりょう または だいぼうけんクリア','道場15問修了 または 大冒険クリア':'どうじょう15もん しゅうりょう または だいぼうけんクリア','放課後の大冒険クリア':'ほうかごの だいぼうけんクリア','なぞなぞ校舎 または 作戦ノートクリア':'なぞなぞこうしゃ または さくせんノートクリア','体操服の挑戦クリア':'たいそうふくの ちょうせんクリア','倒れた冒険の救助依頼':'たおれた ぼうけんの きゅうじょいらい'});
