
import { Card, CardType, TargetType } from './types';

export const ADDITIONAL_CARDS: Record<string, Omit<Card, 'id'>> = {
  // --- 国語系 (20枚) ---
  KOKUGO_SYUKUGO: { name: '四字熟語', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '4ダメージを4回与える。', damage: 4, playCopies: 3, rarity: 'COMMON', textureRef: 'NOTEBOOK|灰|ATTACK' },
  KOKUGO_KOTOWAZA: { name: 'ことわざの知恵', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック7。カードを1枚引く。', block: 7, draw: 1, rarity: 'COMMON', textureRef: 'NOTEBOOK|白|SKILL' },
  KOKUGO_GOKAN: { name: '五感の表現', cost: 1, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ2にする。', weak: 2, rarity: 'COMMON', textureRef: 'EYE|白|SKILL' },
  KOKUGO_KANJI_TEST: { name: '漢字小テスト', cost: 0, type: CardType.ATTACK, target: TargetType.ENEMY, description: '3ダメージ。カードを1枚引く。廃棄。', damage: 3, draw: 1, exhaust: true, rarity: 'COMMON', textureRef: 'NOTEBOOK|白|ATTACK' },
  KOKUGO_MANYO: { name: '万葉の歌', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン開始時に追加で1枚引く。', applyPower: { id: 'DRAW_POWER', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'PLANT|緑|POWER' },
  KOKUGO_NIKKI: { name: '観察日記', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '次のターン、カードを2枚引く。', nextTurnDraw: 2, rarity: 'COMMON', textureRef: 'NOTEBOOK|青|SKILL' },
  KOKUGO_SYODO: { name: '止め・跳ね・払い', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '9ダメージ。対象をびくびく1にする。', damage: 9, vulnerable: 1, rarity: 'COMMON', textureRef: 'SWORD|黒|ATTACK' },
  KOKUGO_DICTIONARY: { name: '国語辞典', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: '手札のカードを2枚コピーする。廃棄。', promptsCopy: 2, exhaust: true, rarity: 'RARE', textureRef: 'NOTEBOOK|青|SKILL' },
  KOKUGO_SYOSETSU: { name: '未完の小説', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '捨て札をすべて山札に戻す。廃棄。', shuffleHandToDraw: true, exhaust: true, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|灰|SKILL' },
  KOKUGO_SYUJI: { name: '精神統一', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'カチカチ1を得る。自分に1ダメージ。', applyPower: { id: 'DEXTERITY', amount: 1 }, selfDamage: 1, rarity: 'UNCOMMON', textureRef: 'HUMANOID|黒|SKILL' },
  KOKUGO_KOTONOHA: { name: '言の葉', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: 'ドクドク5を与える。', poison: 5, rarity: 'COMMON', textureRef: 'PLANT|緑|SKILL' },
  KOKUGO_HAIKU: { name: '五七五', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '6ダメージを3回与える。', damage: 6, playCopies: 2, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|白|ATTACK' },
  KOKUGO_RITOKU: { name: '読解力', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '次に使うスキルは2回発動する。', applyPower: { id: 'BURST', amount: 1 }, rarity: 'RARE', textureRef: 'EYE|青|SKILL' },
  KOKUGO_BUNPO: { name: '主語と述語', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、ブロック1を得る。', applyPower: { id: 'AFTER_IMAGE', amount: 1 }, rarity: 'RARE', textureRef: 'NOTEBOOK|白|POWER' },
  KOKUGO_RODOKU: { name: '朗読', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に6ダメージ。1枚引く。', damage: 6, draw: 1, rarity: 'UNCOMMON', textureRef: 'MIC|白|ATTACK' },
  KOKUGO_GOKO: { name: '五光', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '20ダメージ。キラキラ1を得る。', damage: 20, applyPower: { id: 'ARTIFACT', amount: 1 }, rarity: 'RARE', textureRef: 'GEM|黄|ATTACK' },
  KOKUGO_SAKUBUN: { name: '読書感想文', cost: 3, type: CardType.SKILL, target: TargetType.SELF, description: '手札の非攻撃カードをすべて廃棄する。', promptsExhaust: 99, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|白|SKILL' },
  KOKUGO_MOJI: { name: '文字の嵐', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '「えんぴつの削りかす」を2枚手札に加える。', addCardToHand: { cardName: 'SHIV', count: 2, cost0: true }, rarity: 'COMMON', textureRef: 'NOTEBOOK|灰|SKILL' },
  KOKUGO_YOMITOKI: { name: '行間を読む', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '次のターン、エネルギー1を得る。', nextTurnEnergy: 1, rarity: 'UNCOMMON', textureRef: 'EYE|黄|SKILL' },
  KOKUGO_TENREI: { name: '天礼', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、ムキムキ2を得る。', applyPower: { id: 'DEMON_FORM', amount: 2 }, rarity: 'LEGENDARY', textureRef: 'FLAME|赤|POWER' },

  // --- 算数系 (20枚) ---
  SANSU_CALC_SPEED: { name: '暗算', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを2枚引く。1枚捨てる。', draw: 2, promptsDiscard: 1, rarity: 'COMMON', textureRef: 'BRAIN|白|SKILL' },
  SANSU_TRIANGLE: { name: '三角定規', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。1枚引く。', damage: 8, draw: 1, rarity: 'UNCOMMON', textureRef: 'SWORD|青|ATTACK' },
  SANSU_COMPASS: { name: 'コンパス円舞', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に5ダメージ。ブロック5を得る。', damage: 5, block: 5, rarity: 'COMMON', textureRef: 'SHIELD|灰|ATTACK' },
  SANSU_PROTRACTOR: { name: '分度器アタック', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージ。敵をへろへろ1にする。', damage: 10, weak: 1, rarity: 'COMMON', textureRef: 'SWORD|黄|ATTACK' },
  SANSU_KUKU: { name: '九九の連鎖', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '9ダメージ。今ターン使用した攻撃枚数分ダメージ追加。', damage: 9, damagePerAttackPlayed: 2, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|黄|ATTACK' },
  SANSU_SOROBAN: { name: 'そろばん', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー1を得る。手札を1枚捨てる。', energy: 1, promptsDiscard: 1, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|茶|SKILL' },
  SANSU_DIVISION: { name: '割り算', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '7ダメージ。対象をびくびく1にする。', damage: 7, vulnerable: 1, rarity: 'UNCOMMON', textureRef: 'DIVIDE|白|ATTACK' },
  SANSU_MULTIPLICATION: { name: '倍々ゲーム', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキを倍にする。廃棄。', doubleStrength: true, exhaust: true, rarity: 'RARE', textureRef: 'FLAME|赤|SKILL' },
  SANSU_ZERO: { name: 'ゼロの発見', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '「発見」の効果を得る。廃棄。', addCardToHand: { cardName: 'DISCOVERY', count: 1 }, exhaust: true, rarity: 'RARE', textureRef: 'GEM|青|SKILL' },
  SANSU_INFINITY: { name: '無限大', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: 'ターン開始時にエネルギー1を得る。', applyPower: { id: 'BERSERK_POWER', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'LIGHTNING|紫|POWER' },
  SANSU_PERCENT: { name: 'パーセント増量', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '現在のブロック値を1.5倍にする。', blockMultiplier: 1.5, rarity: 'UNCOMMON', textureRef: 'SHIELD|白|SKILL' },
  SANSU_GEOMETRY: { name: '幾何学模様', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: '被ダメージ時、ランダムな敵に5ダメージ。', applyPower: { id: 'STATIC_DISCHARGE', amount: 1 }, rarity: 'RARE', textureRef: 'GEM|青|POWER' },
  SANSU_AREA: { name: '面積計算', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '手札の枚数x3ダメージ。', damagePerCardInHand: 3, rarity: 'COMMON', textureRef: 'NOTEBOOK|黄|ATTACK' },
  SANSU_CHART: { name: '円グラフ', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを3枚引き、2枚捨てる。', draw: 3, promptsDiscard: 2, rarity: 'COMMON', textureRef: 'NOTEBOOK|青|SKILL' },
  SANSU_UNIT: { name: '単位変換', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札をすべて入れ替える。', shuffleHandToDraw: true, draw: 5, rarity: 'RARE', textureRef: 'NOTEBOOK|白|SKILL' },
  SANSU_FORMULA: { name: '魔法の方程式', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを2枚引き、エネルギー1を得る。', draw: 2, energy: 1, rarity: 'UNCOMMON', textureRef: 'EYE|黄|SKILL' },
  SANSU_GRID: { name: '方眼紙の盾', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック9。山札に「ケガ」を1枚加える。', block: 9, addCardToDraw: { cardName: 'WOUND', count: 1 }, rarity: 'COMMON', textureRef: 'SHIELD|白|SKILL' },
  SANSU_LOGIC: { name: '論理パズル', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '次のターン、カードを1枚追加で引く。', nextTurnDraw: 1, rarity: 'COMMON', textureRef: 'BRAIN|白|SKILL' },
  SANSU_FRACTION: { name: '分数の壁', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: '次に受けるダメージを0にする。', applyPower: { id: 'BUFFER', amount: 1 }, rarity: 'RARE', textureRef: 'SHIELD|青|POWER' },
  SANSU_ABACUS_MASTER: { name: '珠算十段', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '12ダメージ。倒すと最大HP+2。', damage: 12, fatalMaxHp: 2, rarity: 'RARE', textureRef: 'SWORD|黒|ATTACK' },

  // --- 理科系 (20枚) ---
  RIKA_EXPERIMENTAL: { name: '試験管の爆発', cost: 2, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体12ダメージ。自分に2ダメージ。', damage: 12, selfDamage: 2, rarity: 'COMMON', textureRef: 'FLAME|赤|ATTACK' },
  RIKA_MICROSCOPE: { name: '顕微鏡', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '敵をびくびく2にする。', vulnerable: 2, rarity: 'COMMON', textureRef: 'EYE|白|SKILL' },
  RIKA_MAGNET: { name: '磁石の力', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '捨て札からランダムなカードを1枚手札に加える。', rarity: 'UNCOMMON', textureRef: 'MAGNET|赤|SKILL' },
  RIKA_PHOTOSYNTHESIS: { name: '光合成', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー1を得る。HP2回復。', energy: 1, heal: 2, rarity: 'UNCOMMON', textureRef: 'PLANT|緑|SKILL' },
  RIKA_PLANETS: { name: '太陽系の公転', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、敵全体に3ダメージ。', applyPower: { id: 'MERCURY_HOURGLASS', amount: 3 }, rarity: 'RARE', textureRef: 'CLOCK|黄|POWER' },
  RIKA_VOLCANO: { name: 'マグマの噴火', cost: 3, type: CardType.ATTACK, target: TargetType.ENEMY, description: '25ダメージ。対象にドクドク5。', damage: 25, poison: 5, rarity: 'RARE', textureRef: 'FLAME|赤|ATTACK' },
  RIKA_LITMUS: { name: 'リトマス試験紙', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象にへろへろ2、びくびく2を付与。', weak: 2, vulnerable: 2, rarity: 'RARE', textureRef: 'NOTEBOOK|赤|SKILL' },
  RIKA_ELECTRIC: { name: '静電気ショック', cost: 0, type: CardType.ATTACK, target: TargetType.ENEMY, description: '4ダメージ。次ターンエネルギー1。', damage: 4, nextTurnEnergy: 1, rarity: 'UNCOMMON', textureRef: 'LIGHTNING|黄|ATTACK' },
  RIKA_ECLIPSE: { name: '皆既日食', cost: 2, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ2、びくびく2にする。', weak: 2, vulnerable: 2, rarity: 'RARE', textureRef: 'GHOST|黒|SKILL' },
  RIKA_EVOLUTION: { name: '生命の進化', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: '状態異常を引く度、カードを1枚引く。', applyPower: { id: 'EVOLVE', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'SLIME|緑|POWER' },
  RIKA_BACTERIA: { name: '細菌の増殖', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: 'ドクドクを3倍にする。廃棄。', poisonMultiplier: 3, exhaust: true, rarity: 'RARE', textureRef: 'SLIME|緑|SKILL' },
  RIKA_RAINBOW: { name: '虹のプリズム', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札のランダムなカード2枚を強化する。', rarity: 'UNCOMMON', textureRef: 'GEM|虹|SKILL' },
  RIKA_GRAVITY: { name: '重力の法則', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '15ダメージ。対象の攻撃力を2下げる。', damage: 15, strength: -2, rarity: 'RARE', textureRef: 'FIST|灰|ATTACK' },
  RIKA_FOSSIL: { name: 'アンモナイト', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック12。廃棄。', block: 12, exhaust: true, rarity: 'COMMON', textureRef: 'SNAKE|灰|SKILL' },
  RIKA_ANATOMY: { name: '人体模型', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'スケスケ1（ダメージ1化）を得る。', applyPower: { id: 'INTANGIBLE', amount: 1 }, rarity: 'RARE', textureRef: 'HUMANOID|白|SKILL' },
  RIKA_SPRING: { name: 'バネの弾力', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック5。次に使う攻撃のダメージ2倍。', block: 5, rarity: 'UNCOMMON', textureRef: 'SHIELD|灰|SKILL' },
  RIKA_WEATHER: { name: '天気予報', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '山札のトップ3枚を確認して戻すか捨てる。', rarity: 'COMMON', textureRef: 'EYE|青|SKILL' },
  RIKA_ALCOHOL: { name: 'アルコールランプ', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '7ダメージ。対象にドクドク3。', damage: 7, poison: 3, rarity: 'COMMON', textureRef: 'FLAME|青|ATTACK' },
  RIKA_CONSTELLATION: { name: '冬の大三角形', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '6ダメージを3回与える。', damage: 6, playCopies: 2, rarity: 'UNCOMMON', textureRef: 'GEM|白|ATTACK' },
  RIKA_ROBOT: { name: '二足歩行ロボット', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、ブロック5を得る。', applyPower: { id: 'METALLICIZE', amount: 5 }, rarity: 'UNCOMMON', textureRef: 'ROBOT|灰|POWER' },

  // --- 社会系 (20枚) ---
  SYAKAI_GEOGRAPHY: { name: '日本地図', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを3枚引く。', draw: 3, rarity: 'RARE', textureRef: 'NOTEBOOK|黄|SKILL' },
  SYAKAI_HISTORY: { name: '歴史の教科書', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターンの開始時、手札の全コストを1下げる。', applyPower: { id: 'COST_REDUCTION', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'NOTEBOOK|茶|POWER' },
  SYAKAI_COIN: { name: '小銭入れ', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '20ゴールドを得る。廃棄。', gold: 20, rarity: 'COMMON', textureRef: 'GEM|黄|SKILL' },
  SYAKAI_LAW: { name: '校則遵守', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'キラキラ2（デバフ無効）を得る。', applyPower: { id: 'ARTIFACT', amount: 2 }, rarity: 'UNCOMMON', textureRef: 'SHIELD|白|SKILL' },
  SYAKAI_MARKET: { name: 'バザーの掘り出し物', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなポーションを1つ得る。', addPotion: true, rarity: 'RARE', textureRef: 'BACKPACK|桃|SKILL' },
  SYAKAI_CITY: { name: '未来都市', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン開始時にエネルギー1、ドロー1。', applyPower: { id: 'ENERGY_DRAW_POWER', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'ROBOT|青|POWER' },
  SYAKAI_TRADE: { name: '交換留学生', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札を1枚廃棄し、カードを2枚引く。', promptsExhaust: 1, draw: 2, rarity: 'UNCOMMON', textureRef: 'HUMANOID|白|SKILL' },
  SYAKAI_VOTE: { name: '学級委員選挙', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札をすべて強化する。', upgradeHand: true, rarity: 'RARE', textureRef: 'NOTEBOOK|白|SKILL' },
  SYAKAI_FACTORY: { name: '町工場', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '「定規で叩く」を2枚手札に加える。', addCardToHand: { cardName: 'POMMEL_STRIKE', count: 2, cost0: true }, rarity: 'COMMON', textureRef: 'ROBOT|灰|SKILL' },
  SYAKAI_TEMPLE: { name: '古い寺院', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '全デバフを解除する。', applyPower: { id: 'CLEAR_DEBUFFS', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'GHOST|白|SKILL' },
  SYAKAI_RICE: { name: '豊作の秋', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを5回復する。廃棄。', heal: 5, exhaust: true, rarity: 'COMMON', textureRef: 'PLANT|黄|SKILL' },
  SYAKAI_EXPLORER: { name: '探検隊', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。ゴールドを10得る。', damage: 8, gold: 10, rarity: 'UNCOMMON', textureRef: 'BACKPACK|黄|ATTACK' },
  SYAKAI_CASTLE: { name: 'お城の守り', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック20。廃棄。', block: 20, exhaust: true, rarity: 'COMMON', textureRef: 'SHIELD|白|SKILL' },
  SYAKAI_NEWS: { name: '校内ニュース', cost: 1, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ2にする。', weak: 2, rarity: 'COMMON', textureRef: 'MIC|白|SKILL' },
  SYAKAI_BANK: { name: 'お年玉貯金', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '100ゴールドを得る。廃棄。', gold: 100, rarity: 'RARE', textureRef: 'GEM|黄|SKILL' },
  SYAKAI_REVOLUTION: { name: '産業革命', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー2を得る。廃棄。', energy: 2, exhaust: true, rarity: 'LEGENDARY', textureRef: 'LIGHTNING|赤|SKILL' },
  SYAKAI_GLOBAL: { name: '世界一周', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを5枚引く。', draw: 5, rarity: 'RARE', textureRef: 'EYE|青|SKILL' },
  SYAKAI_CULTURE: { name: '伝統文化', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: '手札に加わるカードを常に強化する。', applyPower: { id: 'MASTER_REALITY', amount: 1 }, rarity: 'RARE', textureRef: 'NOTEBOOK|茶|POWER' },
  SYAKAI_COIN_BAG: { name: 'お宝の袋', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '18ダメージ。ゴールドを20得る。', damage: 18, gold: 20, rarity: 'RARE', textureRef: 'BACKPACK|黄|ATTACK' },
  SYAKAI_HERITAGE: { name: '世界遺産登録', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '最大HPを5増やす。廃棄。', fatalMaxHp: 5, exhaust: true, rarity: 'RARE', textureRef: 'GEM|白|SKILL' },

  // --- 体育・行事・生活系 (20枚) ---
  PE_DASH: { name: '50m走', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ2を得る。', strength: 2, rarity: 'UNCOMMON', textureRef: 'SHOE|赤|SKILL' },
  PE_JUMP: { name: '縄跳び', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '3ダメージを3回与える。', damage: 3, playCopies: 2, rarity: 'COMMON', textureRef: 'SWORD|灰|ATTACK' },
  PE_BALL: { name: 'ドッジボール投球', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '12ダメージ。', damage: 12, rarity: 'COMMON', textureRef: 'FIST|赤|ATTACK' },
  PE_SWIM: { name: '25mクロール', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック6。カードを1枚引く。', block: 6, draw: 1, rarity: 'COMMON', textureRef: 'SHOE|青|SKILL' },
  PE_TEAM: { name: '二人三脚', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ1、カチカチ1を得る。', strength: 1, rarity: 'UNCOMMON', textureRef: 'HUMANOID|白|SKILL' },
  PE_CHEER: { name: '応援合戦', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ2を得る。', strength: 2, rarity: 'UNCOMMON', textureRef: 'MIC|赤|SKILL' },
  PE_GYM_MAT: { name: 'マット運動', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック10。', block: 10, rarity: 'RARE', textureRef: 'SHIELD|白|SKILL' },
  EVENT_CLEANING: { name: '大掃除のホウキ', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に7ダメージ。対象をへろへろ1にする。', damage: 7, weak: 1, rarity: 'COMMON', textureRef: 'SWORD|茶|ATTACK' },
  EVENT_LUNCH: { name: '給食の当番', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札に「完熟トマト(回復)」を2枚加える。', addCardToHand: { cardName: 'RIPE_TOMATO', count: 2, cost0: true }, rarity: 'UNCOMMON', textureRef: 'CHEF|白|SKILL' },
  EVENT_FESTIVAL: { name: '学芸会の主役', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、ブロック1を得る。', applyPower: { id: 'AFTER_IMAGE', amount: 1 }, rarity: 'RARE', textureRef: 'HUMANOID|黄|POWER' },
  PE_HORIZONTAL_BAR: { name: '鉄棒の逆上がり', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '捨て札からランダムなカードを1枚手札に戻す。', rarity: 'UNCOMMON', textureRef: 'SHOE|灰|SKILL' },
  PE_VAULTING: { name: '跳び箱10段', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '18ダメージ。', damage: 18, rarity: 'UNCOMMON', textureRef: 'FIST|茶|ATTACK' },
  PE_SOCCER: { name: 'PK戦', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '7ダメージを2回。対象をびくびく1にする。', damage: 7, playCopies: 1, vulnerable: 1, rarity: 'UNCOMMON', textureRef: 'FIST|青|ATTACK' },
  PE_MARATHON: { name: '持久走', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、ブロック4を得る。', applyPower: { id: 'METALLICIZE', amount: 4 }, rarity: 'RARE', textureRef: 'SHOE|青|POWER' },
  PE_DANCE: { name: 'フォークダンス', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札を1枚コピーする。', promptsCopy: 1, rarity: 'UNCOMMON', textureRef: 'HUMANOID|桃|SKILL' },
  EVENT_MORNING: { name: '朝の会', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札をすべて強化する。廃棄。', upgradeHand: true, exhaust: true, rarity: 'RARE', textureRef: 'NOTEBOOK|黄|SKILL' },
  EVENT_HOME: { name: '帰りの会', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック20を得る。廃棄。', block: 20, exhaust: true, rarity: 'RARE', textureRef: 'NOTEBOOK|黒|SKILL' },
  EVENT_TRIP: { name: '修学旅行の枕', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。対象をへろへろ2にする。', damage: 8, weak: 2, rarity: 'RARE', textureRef: 'FIST|白|ATTACK' },
  PE_BASKET: { name: '3ポイントシュート', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '22ダメージ。廃棄。', damage: 22, exhaust: true, rarity: 'UNCOMMON', textureRef: 'FIST|橙|ATTACK' },
  PE_CHAMPION: { name: 'スポーツ王', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: 'ムキムキ2、カチカチ2を得る。', strength: 2, applyPower: { id: 'DEXTERITY', amount: 2 }, rarity: 'LEGENDARY', textureRef: 'HUMANOID|金|POWER' },

  // --- 学校外ライフ（100枚抜粋） ---
  OUT_PARK_SWING: { name: '公園のブランコ', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '30ダメージ。敵全体にびくびく2。', damage: 30, vulnerable: 2, rarity: 'RARE', textureRef: 'FIST|青|ATTACK' },
  OUT_PARK_SLIDE: { name: '超高速すべり台', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '35ダメージ。1枚引く。', damage: 35, draw: 1, rarity: 'RARE', textureRef: 'SHOE|橙|ATTACK' },
  OUT_SECRET_BASE: { name: '空き地の秘密基地', cost: 4, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、ブロック10を得る。', applyPower: { id: 'METALLICIZE', amount: 10 }, rarity: 'RARE', textureRef: 'BACKPACK|茶|POWER' },
  OUT_GAME_NIGHT: { name: '徹夜のゲーム大会', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: '毎ターンエネルギー1を得る。自分に1ダメージ。', applyPower: { id: 'BERSERK_POWER', amount: 1 }, selfDamage: 1, rarity: 'LEGENDARY', textureRef: 'LIGHTNING|黄|POWER' },
  OUT_CONVENIENCE: { name: 'コンビニの買い食い', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを12回復。エネルギー1を得る。廃棄。', heal: 12, energy: 1, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|白|SKILL' },
  OUT_DAGASHI_ALL: { name: '駄菓子屋の全買い', cost: 6, type: CardType.SKILL, target: TargetType.SELF, description: '100ゴールドを得る。カードを5枚引く。', gold: 100, draw: 5, rarity: 'LEGENDARY', textureRef: 'BACKPACK|黄|SKILL' },
  OUT_BICYCLE_DASH: { name: '立ちこぎ坂道', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '40ダメージ。自分に3ダメージ。', damage: 40, selfDamage: 3, rarity: 'RARE', textureRef: 'SHOE|赤|ATTACK' },
  OUT_DOG_BARK: { name: '近所の番犬', cost: 4, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ3、びくびく3にする。', weak: 3, vulnerable: 3, rarity: 'RARE', textureRef: 'BEAST|茶|SKILL' },
  OUT_GRANDMA_GIFT: { name: 'おばあちゃんの小遣い', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: '300ゴールドを得る。廃棄。', gold: 300, exhaust: true, rarity: 'LEGENDARY', textureRef: 'GEM|金|SKILL' },
  OUT_FESTIVAL_FIRE: { name: '夏祭りの打ち上げ花火', cost: 5, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '20ダメージ。敵全体にドクドク8。', damage: 20, poison: 8, rarity: 'LEGENDARY', textureRef: 'FLAME|虹|ATTACK' },
  OUT_SNOWBALL_WAR: { name: '本気の雪合戦', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージを5回与える。', damage: 10, playCopies: 4, rarity: 'RARE', textureRef: 'GEM|白|ATTACK' },
  OUT_KICKBOARD: { name: '最強のキックボード', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: '45ダメージ。', damage: 45, rarity: 'RARE', textureRef: 'SHOE|灰|ATTACK' },
  OUT_BUG_CATCH: { name: 'かぶとむし狩り', cost: 4, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象を捕獲する。', capture: true, rarity: 'RARE', textureRef: 'BEAST|黒|SKILL' },
  OUT_STRAY_CAT: { name: '路地裏の野良猫', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '次に使うアタックを3回発動する。', rarity: 'LEGENDARY', textureRef: 'BEAST|灰|SKILL' },
  OUT_ANIME_BINGE: { name: 'アニメ一気見', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: 'ターンの開始時、手札の全コストを1下げる。', applyPower: { id: 'COST_REDUCTION', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'EYE|青|POWER' },
  OUT_NEW_YEAR_GOLD: { name: 'お年玉の誘惑', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札のランダムなカード1枚を、その戦闘中0コストにする。', rarity: 'RARE', textureRef: 'GEM|黄|SKILL' },
  OUT_PARK_HIDE: { name: '伝説のかくれんぼ', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'スケスケ2（無敵）を得る。廃棄。', applyPower: { id: 'INTANGIBLE', amount: 2 }, exhaust: true, rarity: 'LEGENDARY', textureRef: 'GHOST|白|SKILL' },
  OUT_GACHA_LUCK: { name: 'ガチャの神引き', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'デッキからランダムなレジェンダリーカードを手札に加える。', rarity: 'LEGENDARY', textureRef: 'GEM|虹|SKILL' },
  OUT_MUD_FIGHT: { name: '泥まみれの決闘', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '15ダメージ。敵全体をへろへろ3にする。', damage: 15, weak: 3, rarity: 'RARE', textureRef: 'SLIME|茶|ATTACK' },
  OUT_LIBRARY_SLEEP: { name: '図書室での昼寝', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '全デバフを解除し、HPを全回復。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'GHOST|白|SKILL' },
  OUT_ARCADE_MASTER: { name: 'ゲーセンの達人', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: 'コンボ：今ターン使ったカード1枚につき10ダメージ。', damagePerAttackPlayed: 10, rarity: 'LEGENDARY', textureRef: 'LIGHTNING|黄|ATTACK' },
  OUT_MODEL_BUILD: { name: 'プラモデル製作', cost: 4, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、ブロック4を得る。', applyPower: { id: 'AFTER_IMAGE', amount: 4 }, rarity: 'RARE', textureRef: 'ROBOT|灰|POWER' },
  OUT_BATH_TIME: { name: '極楽の銭湯', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: '最大HP+5。HP20回復。廃棄。', fatalMaxHp: 5, heal: 20, exhaust: true, rarity: 'RARE', textureRef: 'SLIME|青|SKILL' },
  OUT_STARRY_SKY: { name: '満天の星空', cost: 6, type: CardType.POWER, target: TargetType.SELF, description: '毎ターンカードを2枚追加で引く。', applyPower: { id: 'DRAW_POWER_2', amount: 2 }, rarity: 'LEGENDARY', textureRef: 'GEM|青|POWER' },
  OUT_MOSQUITO_WAR: { name: '蚊との死闘', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '1ダメージを20回与える。', damage: 1, playCopies: 19, rarity: 'RARE', textureRef: 'FIST|赤|ATTACK' },
  OUT_SUMMER_HOMEWORK: { name: '最後の宿題', cost: 8, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に80ダメージ。廃棄。', damage: 80, exhaust: true, rarity: 'LEGENDARY', textureRef: 'NOTEBOOK|紫|ATTACK' },
  OUT_MORNING_EXERCISE: { name: 'ラジオ体操皆勤賞', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、ムキムキ3、カチカチ3を得る。', applyPower: { id: 'DEMON_FORM', amount: 3 }, rarity: 'LEGENDARY', textureRef: 'HUMANOID|金|POWER' },
  OUT_JUNGLE_GYM: { name: 'ジャングルジムの頂上', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック30。次ターンのエネルギー+2。', block: 30, nextTurnEnergy: 2, rarity: 'RARE', textureRef: 'SHIELD|白|SKILL' },
  OUT_PIZZA_PARTY: { name: '出前ピザパーティー', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '自分とパートナーのHPを全回復。廃棄。', heal: 99, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|橙|SKILL' },
  OUT_HAUNTED_HOUSE: { name: '近所の幽霊屋敷', cost: 5, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象をこの戦闘中ずっと「びくびく」にする。', vulnerable: 99, rarity: 'LEGENDARY', textureRef: 'GHOST|紫|SKILL' },
  OUT_TRADING_CARD: { name: '最強の激レアカード', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: 'デッキのカード枚数×2ダメージ。', damagePerCardInDraw: 2, rarity: 'RARE', textureRef: 'GEM|金|ATTACK' },
  OUT_RAIN_PUDDLE: { name: '水たまりジャンプ', cost: 3, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック12。このターン、カードをプレイする度にエネルギー1を得る。', block: 12, rarity: 'LEGENDARY', textureRef: 'SHOE|青|SKILL' },
  OUT_Kite_FLYING: { name: 'お正月の凧揚げ', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '山札の枚数×3ダメージ。', damagePerCardInDraw: 3, rarity: 'RARE', textureRef: 'FLIER|白|ATTACK' },
  OUT_FIRE_TRUCK: { name: '消防署見学', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック50を得る。', block: 50, rarity: 'RARE', textureRef: 'SHIELD|赤|SKILL' },
  OUT_CONSTRUCTION: { name: '工事現場の重機', cost: 6, type: CardType.ATTACK, target: TargetType.ENEMY, description: '60ダメージ。敵全体のブロックを粉砕する。', damage: 60, rarity: 'LEGENDARY', textureRef: 'ROBOT|黄|ATTACK' },
  OUT_GHOST_STORY: { name: '夜の怖い話', cost: 4, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ5にする。', weak: 5, rarity: 'RARE', textureRef: 'GHOST|紫|SKILL' },
  OUT_TREASURE_MAP: { name: '手作りの宝地図', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなレリックを1つ入手する。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'NOTEBOOK|茶|SKILL' },
  OUT_GRANDPA_WISDOM: { name: 'おじいちゃんの教え', cost: 4, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、ムキムキ1を得る。', applyPower: { id: 'RUPTURE', amount: 1 }, rarity: 'RARE', textureRef: 'HUMANOID|白|POWER' },
  OUT_KABUTO_WRESTLE: { name: 'カぶとむし相撲', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: '30ダメージ。対象にびくびく3。', damage: 30, vulnerable: 3, rarity: 'RARE', textureRef: 'BEAST|黒|ATTACK' },
  OUT_CANDY_SUGAR: { name: '綿菓子の雲', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '次のターン、カードを5枚引く。', nextTurnDraw: 5, rarity: 'UNCOMMON', textureRef: 'GHOST|白|SKILL' },
  OUT_BALLOON_POP: { name: '風船割り', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体10ダメージを3回与える。', damage: 10, playCopies: 2, rarity: 'UNCOMMON', textureRef: 'GEM|赤|ATTACK' },
  OUT_SHRINE_PRAY: { name: '初詣の願い事', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札の全カードのコストを0にする。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'GEM|金|SKILL' },
  OUT_CRAYON_WALL: { name: '壁への落書き', cost: 5, type: CardType.POWER, target: TargetType.ALL_ENEMIES, description: '毎ターン敵全体にドクドク5。', applyPower: { id: 'NOXIOUS_FUMES', amount: 5 }, rarity: 'RARE', textureRef: 'NOTEBOOK|虹|POWER' },
  OUT_BIRD_WATCH: { name: '鳥になった気分', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札のカードを3枚コピーする。廃棄。', promptsCopy: 3, exhaust: true, rarity: 'RARE', textureRef: 'FLIER|青|SKILL' },
  OUT_RADIO_CONTROL: { name: 'ラジコン操作', cost: 5, type: CardType.ATTACK, target: TargetType.RANDOM_ENEMY, description: '12ダメージを6回与える。', damage: 12, playCopies: 5, rarity: 'RARE', textureRef: 'ROBOT|赤|ATTACK' },
  OUT_ICE_CREAM_BINGE: { name: 'アイス食べ放題', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー3を得る。自分に5ダメージ。', energy: 3, selfDamage: 5, rarity: 'UNCOMMON', textureRef: 'POTION|白|SKILL' },
  OUT_STREET_PERFORM: { name: '街頭パフォーマンス', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '50ゴールドを得る。敵全体をへろへろ2にする。', gold: 50, weak: 2, rarity: 'UNCOMMON', textureRef: 'HUMANOID|虹|SKILL' },
  OUT_SUPER_HERO_POSE: { name: '戦隊ヒーローのポーズ', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: 'ムキムキが減らなくなる。', applyPower: { id: 'ARTIFACT', amount: 99 }, rarity: 'LEGENDARY', textureRef: 'HUMANOID|赤|POWER' },
  OUT_PET_WALK: { name: '犬の散歩', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '20ダメージ。次ターンのエネルギー+1。', damage: 20, nextTurnEnergy: 1, rarity: 'UNCOMMON', textureRef: 'BEAST|茶|ATTACK' },
  OUT_FISH_CATCH: { name: '川での魚つかみ', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなポーションを2つ得る。廃棄。', addPotion: true, exhaust: true, rarity: 'RARE', textureRef: 'SLIME|青|SKILL' },
  OUT_HIDDEN_SHORTCUT: { name: '秘密の近道', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '山札のカードを1枚選んで手札に加える。', rarity: 'RARE', textureRef: 'SHOE|緑|SKILL' },
  OUT_DREAM_FUTURE: { name: '将来の夢', cost: 6, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、ムキムキ2を得る。', applyPower: { id: 'STRENGTH', amount: 2 }, rarity: 'LEGENDARY', textureRef: 'EYE|黄|POWER' },
  OUT_WOOD_CRAFT: { name: '夏休みの工作', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、ブロック15を得る。', applyPower: { id: 'METALLICIZE', amount: 15 }, rarity: 'RARE', textureRef: 'ROBOT|茶|POWER' },
  OUT_STAMP_COLLECT: { name: 'スタンプラリー', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを4枚引く。廃棄。', draw: 4, exhaust: true, rarity: 'UNCOMMON', textureRef: 'NOTEBOOK|赤|SKILL' },
  OUT_GHOST_PHOTO: { name: '心霊写真', cost: 4, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象にドクドク20を付与。', poison: 20, rarity: 'RARE', textureRef: 'GHOST|黒|SKILL' },
  OUT_PARK_FOUNTAIN: { name: '公園の噴水', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを10回復。全デバフ解除。', heal: 10, applyPower: { id: 'CLEAR_DEBUFFS', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'SLIME|青|SKILL' },
  OUT_ROLLER_BLADE: { name: 'ローラーシューズ', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'このターン、全手札のコストを0にする。', rarity: 'LEGENDARY', textureRef: 'SHOE|白|SKILL' },
  OUT_KIMONO_DRESS: { name: '七五三の晴れ着', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: 'キラキラ3を得る。', applyPower: { id: 'ARTIFACT', amount: 3 }, rarity: 'RARE', textureRef: 'HUMANOID|桃|POWER' },
  OUT_FLOWER_CROWN: { name: 'シロツメクサの冠', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック25を得る。', block: 25, rarity: 'UNCOMMON', textureRef: 'PLANT|白|SKILL' },
  OUT_TELESCOPE: { name: '天体観測', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '山札をすべて確認し、並べ替える。', rarity: 'RARE', textureRef: 'EYE|黒|SKILL' },
  OUT_PAPER_PLANE_ULTRA: { name: '最強の紙飛行機', cost: 5, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '25ダメージ。廃棄されない。', damage: 25, rarity: 'RARE', textureRef: 'FLIER|白|ATTACK' },
  OUT_BUG_BOX: { name: '虫かごの秘密', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札にランダムな「捕獲」済みカードを加える。', rarity: 'RARE', textureRef: 'BACKPACK|緑|SKILL' },
  OUT_STREET_LIGHT: { name: '夜道の街灯', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'カチカチ10を得る。', applyPower: { id: 'DEXTERITY', amount: 10 }, rarity: 'RARE', textureRef: 'LIGHTNING|黄|SKILL' },
  OUT_OLD_HOUSE: { name: 'おじいちゃんの古民家', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを全回復。最大HP+2。廃棄。', heal: 99, fatalMaxHp: 2, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|茶|SKILL' },
  OUT_CANDY_BOMB: { name: 'パチパチキャンディ', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '5ダメージを10回与える。', damage: 5, playCopies: 9, rarity: 'UNCOMMON', textureRef: 'FLAME|虹|ATTACK' },
  OUT_MUD_DUMPLING: { name: '究極の泥団子', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '30ダメージ。対象にへろへろ5。', damage: 30, weak: 5, rarity: 'RARE', textureRef: 'GEM|茶|ATTACK' },
  OUT_SECRET_LETTER: { name: '秘密のラブレター', cost: 4, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象をこの戦闘から除外する（ボス無効）。', rarity: 'LEGENDARY', textureRef: 'NOTEBOOK|桃|SKILL' },
  OUT_PIRATE_PLAY: { name: '海賊ごっこ', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージ。対象の所持金を50奪う。', damage: 10, gold: 50, rarity: 'RARE', textureRef: 'SWORD|黒|ATTACK' },
  OUT_SAND_CASTLE: { name: '砂浜の城', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック40。次のターン、ブロックは0になる。', block: 40, rarity: 'UNCOMMON', textureRef: 'SHIELD|黄|SKILL' },
  OUT_RAINBOW_CHASE: { name: '虹を追いかけて', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: 'デッキのランダムなカード5枚を強化する。', rarity: 'RARE', textureRef: 'GEM|虹|SKILL' },
  OUT_CLIMBING_TREE: { name: '木登り名人', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'このターン、受けるダメージをすべて1にする。', applyPower: { id: 'INTANGIBLE', amount: 1 }, rarity: 'RARE', textureRef: 'PLANT|緑|SKILL' },
  OUT_DRAGON_GOD: { name: '神社の龍神様', cost: 7, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に50ダメージ。HP10回復。', damage: 50, heal: 10, rarity: 'LEGENDARY', textureRef: 'SNAKE|金|ATTACK' },
  OUT_YAKISOBA: { name: '屋台の焼きそば', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ5を得る。次ターン、エネルギー-1。', strength: 5, nextTurnEnergy: -1, rarity: 'UNCOMMON', textureRef: 'BACKPACK|茶|SKILL' },
  OUT_GOLD_FISH: { name: '金魚すくい', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札を1枚選んで強化し、コストを0にする。', rarity: 'RARE', textureRef: 'GEM|赤|SKILL' },
  OUT_MASK_HERO: { name: '縁日のお面', cost: 4, type: CardType.POWER, target: TargetType.SELF, description: '被ダメージを常に3軽減する。', applyPower: { id: 'BUFFER', amount: 3 }, rarity: 'RARE', textureRef: 'HUMANOID|赤|POWER' },
  OUT_SCARE_CROW: { name: '田んぼのかかし', cost: 4, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体を2ターン行動不能にする。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'HUMANOID|茶|SKILL' },
  OUT_SPARKLER: { name: '手持ち花火', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '2ダメージを15回与える。対象にドクドク5。', damage: 2, playCopies: 14, poison: 5, rarity: 'UNCOMMON', textureRef: 'FLAME|黄|ATTACK' },
  OUT_SLEEP_IN: { name: '休日の二度寝', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを15回復。次のターンのエネルギー+2、ドロー+2。廃棄。', heal: 15, exhaust: true, rarity: 'LEGENDARY', textureRef: 'GHOST|白|SKILL' },
  OUT_MUSEUM_TRIP: { name: '博物館の恐竜', cost: 6, type: CardType.ATTACK, target: TargetType.ENEMY, description: '55ダメージ。', damage: 55, rarity: 'RARE', textureRef: 'BEAST|灰|ATTACK' },
  OUT_KIMODAMESHI: { name: '真夏の肝試し', cost: 4, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体の攻撃力を3下げる。', strength: -3, rarity: 'RARE', textureRef: 'GHOST|青|SKILL' },
  OUT_FALL_LEAVES: { name: '落ち葉の絨毯', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック15。カードを2枚引く。', block: 15, draw: 2, rarity: 'UNCOMMON', textureRef: 'PLANT|橙|SKILL' },
  OUT_KOTATSU: { name: '冬のこたつ', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、ブロック10を得る。', applyPower: { id: 'METALLICIZE', amount: 10 }, rarity: 'RARE', textureRef: 'SHIELD|赤|POWER' },
  OUT_TOSHIKOSHI: { name: '年越しそば', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを15回復。最大HP+1。', heal: 15, fatalMaxHp: 1, rarity: 'UNCOMMON', textureRef: 'BACKPACK|白|SKILL' },
  OUT_FIRST_SUN: { name: '初日の出', cost: 5, type: CardType.POWER, target: TargetType.SELF, description: 'ターン開始時にエネルギー2を得る。', applyPower: { id: 'BERSERK_POWER', amount: 2 }, rarity: 'LEGENDARY', textureRef: 'GEM|金|POWER' },
  OUT_SNOW_MAN: { name: '巨大雪だるま', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック50。廃棄。', block: 50, exhaust: true, rarity: 'RARE', textureRef: 'SHIELD|白|SKILL' },
  OUT_SOCCER_STREET: { name: '路地のストリートサッカー', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージを4回。1枚引く。', damage: 8, playCopies: 3, draw: 1, rarity: 'UNCOMMON', textureRef: 'FIST|白|ATTACK' },
  OUT_RADIO_STATION: { name: '地元のラジオ局', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '手札のランダムなカード3枚をコピーする。', promptsCopy: 3, rarity: 'RARE', textureRef: 'MIC|灰|SKILL' },
  OUT_ZOO_TRIP: { name: '動物園のライオン', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: '25ダメージ。対象にびくびく5。', damage: 25, vulnerable: 5, rarity: 'RARE', textureRef: 'BEAST|黄|ATTACK' },
  OUT_AQUARIUM: { name: '水族館のサメ', cost: 5, type: CardType.ATTACK, target: TargetType.ENEMY, description: '15ダメージを3回。HP5回復。', damage: 15, playCopies: 2, heal: 5, rarity: 'RARE', textureRef: 'BEAST|青|ATTACK' },
  OUT_TOY_STORE: { name: '夢のおもちゃ屋', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなレジェンダリーカードを1枚生成する。', rarity: 'LEGENDARY', textureRef: 'BACKPACK|虹|SKILL' },
  OUT_STREET_DOG: { name: '迷い犬の恩返し', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: '次の戦闘開始時、エネルギー+3。廃棄。', exhaust: true, rarity: 'RARE', textureRef: 'BEAST|白|SKILL' },
  OUT_UMBRELLA_SWORD: { name: '傘チャンバラ', cost: 4, type: CardType.ATTACK, target: TargetType.ENEMY, description: '12ダメージを3回。ブロック12。', damage: 12, playCopies: 2, block: 12, rarity: 'UNCOMMON', textureRef: 'SWORD|青|ATTACK' },
  OUT_EVENING_CHIME: { name: '夕焼けのチャイム', cost: 5, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体を即死させる（ボス無効）。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'CLOCK|赤|SKILL' },
  OUT_MY_HERO: { name: '僕だけのヒーロー', cost: 7, type: CardType.ATTACK, target: TargetType.ENEMY, description: '50ダメージ。自分のHPが半分以下の時、コスト0になりダメージが2倍になる。', damage: 50, rarity: 'LEGENDARY', textureRef: 'HUMANOID|虹|ATTACK' },
  OUT_FRIEND_FOREVER: { name: '親友との約束', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'パートナーの最大HPを20増やし、HPを全回復する。', rarity: 'RARE', textureRef: 'HUMANOID|白|SKILL' },
  OUT_GRANDMA_CAKE: { name: 'おばあちゃんの手作りケーキ', cost: 4, type: CardType.SKILL, target: TargetType.SELF, description: 'HP30回復。最大HP+5。廃棄。', heal: 30, fatalMaxHp: 5, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|白|SKILL' },
  OUT_SUPER_GACHA: { name: '究極の10連ガチャ', cost: 5, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなカード10枚を手札に加える。', rarity: 'LEGENDARY', textureRef: 'GEM|虹|SKILL' },
  OUT_LAST_BATTLE: { name: '公園の決戦', cost: 6, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に30ダメージを2回。', damage: 30, playCopies: 1, rarity: 'RARE', textureRef: 'FIST|赤|ATTACK' },
  OUT_GRADUATION_DAY: { name: 'いつかの卒業式', cost: 6, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ20、カチカチ20、キラキラ5を得る。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'BOSS|白|SKILL' },

  // --- カッコいいカード (BOYS) ---
  BOYS_DRAGON_BUSTER: { name: 'ドラグニル・バースト', cost: 3, type: CardType.ATTACK, target: TargetType.ENEMY, description: '35ダメージ。対象にびくびく2。', damage: 35, vulnerable: 2, rarity: 'RARE', textureRef: 'DRAGON|赤|ATTACK' },
  BOYS_VOID_SLASH: { name: '虚空の断罪', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '15ダメージを2回。廃棄。', damage: 15, playCopies: 1, exhaust: true, rarity: 'RARE', textureRef: 'SWORD|黒|ATTACK' },
  BOYS_THUNDER_FIST: { name: '雷神の鉄拳', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージ。次のアタックのコスト-1。', damage: 10, rarity: 'UNCOMMON', textureRef: 'FIST|黄|ATTACK' },
  BOYS_GRAVITY_PRESS: { name: '重力100倍プレス', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '現在のブロック値の2倍のダメージ。', damageBasedOnBlock: true, rarity: 'RARE', textureRef: 'ROBOT|紫|ATTACK' },
  BOYS_SHADOW_BIND: { name: '影縫いの太刀', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。対象をへろへろ2にする。', damage: 8, weak: 2, rarity: 'COMMON', textureRef: 'SWORD|紫|ATTACK' },
  BOYS_MECHA_DIVE: { name: '電脳世界へのダイブ', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'カードを3枚引き、1枚捨てる。', draw: 3, promptsDiscard: 1, rarity: 'UNCOMMON', textureRef: 'ROBOT|青|SKILL' },
  BOYS_BLACK_HOLE: { name: '暗黒の特異点', cost: 3, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ3、びくびく3にする。', weak: 3, vulnerable: 3, rarity: 'RARE', textureRef: 'GHOST|黒|SKILL' },
  BOYS_SAMURAI_SPIRIT: { name: '侍の魂', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'アタックを使う度、ブロック2を得る。', applyPower: { id: 'AFTER_IMAGE', amount: 2 }, rarity: 'RARE', textureRef: 'SWORD|白|POWER' },
  BOYS_NINJA_VANISH: { name: '忍法・隠れ身', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'スケスケ1（ダメージ1化）を得る。廃棄。', applyPower: { id: 'INTANGIBLE', amount: 1 }, exhaust: true, rarity: 'LEGENDARY', textureRef: 'GHOST|灰|SKILL' },
  BOYS_ROBOT_BOOST: { name: 'フルドライブ', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー2を得る。このターン中のみムキムキ5。', energy: 2, strength: 5, applyPower: { id: 'LOSE_STRENGTH', amount: 5 }, rarity: 'RARE', textureRef: 'LIGHTNING|黄|SKILL' },
  BOYS_BLADE_STORM: { name: '無尽蔵の剣線', cost: 2, type: CardType.ATTACK, target: TargetType.RANDOM_ENEMY, description: '5ダメージを5回。', damage: 5, playCopies: 4, rarity: 'UNCOMMON', textureRef: 'SWORD|灰|ATTACK' },
  BOYS_VOLCANO_CRASH: { name: '紅蓮爆華', cost: 3, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に20ダメージ。自分に5ダメージ。', damage: 20, selfDamage: 5, rarity: 'UNCOMMON', textureRef: 'FLAME|赤|ATTACK' },
  BOYS_CYBER_SHIELD: { name: '電磁障壁', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック10。カードを1枚引く。', block: 10, draw: 1, rarity: 'COMMON', textureRef: 'SHIELD|青|SKILL' },
  BOYS_GENESIS_RAY: { name: '創世の光線', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に40ダメージ。', damage: 40, rarity: 'RARE', textureRef: 'LIGHTNING|白|ATTACK' },
  BOYS_IRON_BLOOD: { name: '鉄血の誓い', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'HPを失う度、ムキムキ2を得る。', applyPower: { id: 'RUPTURE', amount: 2 }, rarity: 'RARE', textureRef: 'FLAME|赤|POWER' },
  BOYS_RAILGUN: { name: '超電磁加速砲', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '24ダメージ。対象のブロックを除去。', damage: 24, rarity: 'RARE', textureRef: 'LIGHTNING|青|ATTACK' },
  BOYS_DARK_PACT: { name: '悪魔の契約', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '自分に6ダメージ。エネルギー3を得る。', selfDamage: 6, energy: 3, rarity: 'RARE', textureRef: 'GHOST|紫|SKILL' },
  BOYS_KNIGHT_GUARD: { name: '守護騎士の盾', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック15。キラキラ1を得る。', block: 15, applyPower: { id: 'ARTIFACT', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'SHIELD|白|SKILL' },
  BOYS_STRIKE_GOD: { name: '神速の連撃', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '3ダメージを6回。', damage: 3, playCopies: 5, rarity: 'RARE', textureRef: 'FIST|赤|ATTACK' },
  BOYS_SPACE_WARP: { name: '次元跳躍', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: '手札と山札の全ての状態異常・呪いを消滅させ、その数だけムキムキを永続強化する。廃棄。', exhaust: true, rarity: 'LEGENDARY', textureRef: 'GEM|紫|SKILL' },
  BOYS_SAMURAI_AURA: { name: '戦意高揚', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、ムキムキ1、カチカチ1を得る。', strength: 1, applyPower: { id: 'DEXTERITY', amount: 1 }, rarity: 'RARE', textureRef: 'HUMANOID|赤|POWER' },
  BOYS_METEOR: { name: '流星の鉄槌', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '18ダメージ。倒すと最大HP+3。', damage: 18, fatalMaxHp: 3, rarity: 'UNCOMMON', textureRef: 'GEM|黄|ATTACK' },
  BOYS_REVENGE: { name: 'リベンジ・バースト', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '今ターン失ったHPの2倍のダメージを与える。', damage: 0, rarity: 'RARE', textureRef: 'FIST|黒|ATTACK' },
  BOYS_SHADOW_CLONE: { name: '影分身の術', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: '手札の全アタックカードをコピーする。', promptsCopy: 5, rarity: 'LEGENDARY', textureRef: 'HUMANOID|灰|SKILL' },
  BOYS_BATTLE_STANCE: { name: '修羅の構え', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: '次のアタックは2回発動する。自分に2ダメージ。', selfDamage: 2, rarity: 'UNCOMMON', textureRef: 'FIST|赤|SKILL' },
  BOYS_HEAVY_SMASH: { name: '超重力粉砕', cost: 3, type: CardType.ATTACK, target: TargetType.ENEMY, description: '50ダメージ。廃棄。', damage: 50, exhaust: true, rarity: 'RARE', textureRef: 'FIST|黒|ATTACK' },
  BOYS_CYBER_BLADE: { name: 'プラズマ・ブレード', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '12ダメージ。このカードは常に強化状態で生成される。', damage: 12, rarity: 'COMMON', textureRef: 'SWORD|青|ATTACK' },
  BOYS_DRAGON_EYE: { name: '竜の眼光', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象をびくびく3、へろへろ3にする。', vulnerable: 3, weak: 3, rarity: 'RARE', textureRef: 'EYE|赤|SKILL' },
  BOYS_VOID_ARMOR: { name: '虚無の鎧', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、ブロックが消えなくなる。', applyPower: { id: 'BARRICADE', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'SHIELD|黒|POWER' },
  BOYS_THUNDER_STORM: { name: '雷鳴の轟き', cost: 2, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に5ダメージを4回。', damage: 5, playCopies: 3, rarity: 'RARE', textureRef: 'LIGHTNING|黄|ATTACK' },
  BOYS_SOLDIER_HUNT: { name: '賞金稼ぎ', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '9ダメージ。倒すと20ゴールド。', damage: 9, gold: 20, rarity: 'UNCOMMON', textureRef: 'BACKPACK|黄|ATTACK' },
  BOYS_IRON_WALL: { name: '鉄壁の陣', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック25。廃棄。', block: 25, exhaust: true, rarity: 'COMMON', textureRef: 'SHIELD|灰|SKILL' },
  BOYS_FLAME_DRIVE: { name: '焔の突撃', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '14ダメージ。自分に1ダメージ。', damage: 14, selfDamage: 1, rarity: 'COMMON', textureRef: 'FLAME|赤|ATTACK' },
  BOYS_SPACE_MINE: { name: '次元地雷', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象にドクドク15。', poison: 15, rarity: 'UNCOMMON', textureRef: 'GEM|紫|SKILL' },
  BOYS_HERO_AWAKEN: { name: '真の勇者覚醒', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、エネルギー+1、ドロー+1。', applyPower: { id: 'ENERGY_DRAW_POWER', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'HUMANOID|金|POWER' },
  BOYS_OMEGA_CANNON: { name: 'オメガ・キャノン', cost: 3, type: CardType.ATTACK, target: TargetType.ENEMY, description: '40ダメージ。', damage: 40, rarity: 'RARE', textureRef: 'ROBOT|白|ATTACK' },
  BOYS_SHADOW_STEP: { name: '暗影の歩法', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック8。カードを2枚引く。', block: 8, draw: 2, rarity: 'UNCOMMON', textureRef: 'SHOE|黒|SKILL' },
  BOYS_BLAZING_FIST: { name: '烈火拳', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '7ダメージ。ムキムキ1を得る。', damage: 7, strength: 1, rarity: 'COMMON', textureRef: 'FIST|赤|ATTACK' },
  BOYS_SONIC_WAVE: { name: '音速の波動', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に8ダメージ。カードを1枚引く。', damage: 8, draw: 1, rarity: 'UNCOMMON', textureRef: 'LIGHTNING|白|ATTACK' },
  BOYS_TITAN_SHIELD: { name: '巨神の盾', cost: 3, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック40。', block: 40, rarity: 'RARE', textureRef: 'SHIELD|灰|SKILL' },
  BOYS_BERSERK_MODE: { name: '狂戦士の咆哮', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ3を得る。対象をびくびく2にする。自分に3ダメージ。', strength: 3, vulnerable: 2, selfDamage: 3, rarity: 'RARE', textureRef: 'HUMANOID|赤|SKILL' },
  BOYS_JUDGEMENT: { name: '終焉の審判', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に60ダメージ。廃棄。', damage: 60, exhaust: true, rarity: 'LEGENDARY', textureRef: 'BOSS|黒|ATTACK' },
  BOYS_PHANTOM_EDGE: { name: '幻影の刃', cost: 0, type: CardType.ATTACK, target: TargetType.ENEMY, description: '6ダメージ。廃棄。', damage: 6, exhaust: true, rarity: 'COMMON', textureRef: 'SWORD|白|ATTACK' },
  BOYS_CORE_STRIKE: { name: 'コア・ストライク', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージ。エネルギー1を得る。', damage: 10, energy: 1, rarity: 'UNCOMMON', textureRef: 'GEM|青|ATTACK' },
  BOYS_DEFENCE_SYS: { name: '自動防衛システム', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、ブロック6を得る。', applyPower: { id: 'METALLICIZE', amount: 6 }, rarity: 'UNCOMMON', textureRef: 'ROBOT|青|POWER' },
  BOYS_INFINITE_BLADE: { name: '無限の剣舞', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン「幻影の刃」を1枚手札に加える。', applyPower: { id: 'INFINITE_BLADES', amount: 1 }, rarity: 'RARE', textureRef: 'SWORD|白|POWER' },
  BOYS_STRENGTH_UP: { name: 'マッスル・ビルド', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ2を得る。', strength: 2, rarity: 'COMMON', textureRef: 'HUMANOID|赤|SKILL' },
  BOYS_WOLF_PACK: { name: '孤狼の群れ', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '9ダメージ。手札のアタック1枚につき+3。', damage: 9, rarity: 'UNCOMMON', textureRef: 'BEAST|灰|ATTACK' },
  BOYS_OVERLOAD: { name: 'オーバーロード', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー3を得る。次のターン、エネルギー0。', energy: 3, nextTurnEnergy: -3, rarity: 'RARE', textureRef: 'LIGHTNING|赤|SKILL' },
  BOYS_FINAL_FANTASY: { name: 'ラスト・ファンタジー', cost: 3, type: CardType.ATTACK, target: TargetType.ENEMY, description: 'この戦闘で使ったカード1枚につき5ダメージ。', damagePerAttackPlayed: 5, rarity: 'LEGENDARY', textureRef: 'SWORD|虹|ATTACK' },

  // --- 女子向け可愛いキラキラしたカード (50枚) ---
  GIRLS_STAR_SYMPHONY: { name: 'スターライト・シンフォニー', cost: 1, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体をへろへろ2、びくびく2にする。', weak: 2, vulnerable: 2, rarity: 'RARE', textureRef: 'GEM|黄|SKILL' },
  GIRLS_HEART_BLOOM: { name: 'ハートフル・ブルーム', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを8回復。ブロック8。', heal: 8, block: 8, rarity: 'UNCOMMON', textureRef: 'PLANT|桃|SKILL' },
  GIRLS_MACARON_HEAL: { name: '恋するマカロン・ヒール', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'HPを5回復。廃棄。', heal: 5, exhaust: true, rarity: 'COMMON', textureRef: 'BACKPACK|桃|SKILL' },
  GIRLS_MAGIC_WAND: { name: 'ミラクル・ステッキ', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '10ダメージ。カードを1枚引く。', damage: 10, draw: 1, rarity: 'COMMON', textureRef: 'GEM|白|ATTACK' },
  GIRLS_RIBBON_BIND: { name: '夢見るリボン・バインド', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象の攻撃力を3下げる。', strength: -3, rarity: 'UNCOMMON', textureRef: 'PLANT|桃|SKILL' },
  GIRLS_SWEET_DREAM: { name: 'おやすみスウィート', cost: 2, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体を2ターン行動不能にする。廃棄。', exhaust: true, rarity: 'RARE', textureRef: 'GHOST|白|SKILL' },
  GIRLS_JEWEL_SHINE: { name: 'ジュエル・シャイン', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: 'ターン開始時にキラキラ1を得る。', applyPower: { id: 'ARTIFACT', amount: 1 }, rarity: 'RARE', textureRef: 'GEM|虹|POWER' },
  GIRLS_FLOWER_GARDEN: { name: '花咲く乙女の庭', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'ターン終了時、HPを2回復する。', applyPower: { id: 'REGEN', amount: 2 }, rarity: 'UNCOMMON', textureRef: 'PLANT|緑|POWER' },
  GIRLS_PRINCESS_DRESS: { name: '憧れのドレスアップ', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'カチカチ3を得る。ブロック10。', applyPower: { id: 'DEXTERITY', amount: 3 }, block: 10, rarity: 'RARE', textureRef: 'HUMANOID|桃|SKILL' },
  GIRLS_CANDY_WAVE: { name: 'キャンディ・ポップ・ウェーブ', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に7ダメージ。全員をドクドク3にする。', damage: 7, poison: 3, rarity: 'UNCOMMON', textureRef: 'SLIME|虹|ATTACK' },
  GIRLS_MOON_SERENADE: { name: '月光のセレナーデ', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー1を得る。2枚引く。廃棄。', energy: 1, draw: 2, exhaust: true, rarity: 'RARE', textureRef: 'CLOCK|黄|SKILL' },
  GIRLS_ANGEL_WINGS: { name: '天使の羽ばたき', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック5。次のターンのエネルギー+1。', block: 5, nextTurnEnergy: 1, rarity: 'COMMON', textureRef: 'FLIER|白|SKILL' },
  GIRLS_CHERRY_BLOSSOM: { name: 'さくらんぼのワルツ', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '6ダメージを2回。HPを3回復。', damage: 6, playCopies: 1, heal: 3, rarity: 'UNCOMMON', textureRef: 'PLANT|赤|ATTACK' },
  GIRLS_SPARKLE_DUST: { name: 'キラキラの粉', cost: 0, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象をびくびく2にする。', vulnerable: 2, rarity: 'COMMON', textureRef: 'GEM|白|SKILL' },
  GIRLS_DREAM_CATCHER: { name: 'ドリーム・キャッチャー', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '山札から好きなカードを1枚手札に加える。', rarity: 'RARE', textureRef: 'EYE|青|SKILL' },
  GIRLS_UNICORN_STRIKE: { name: '一角獣の突進', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '20ダメージ。対象にへろへろ2。', damage: 20, weak: 2, rarity: 'UNCOMMON', textureRef: 'BEAST|白|ATTACK' },
  GIRLS_RAINBOW_MAGIC: { name: 'なないろマジック', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札のランダムなカードのコストを0にする。', rarity: 'RARE', textureRef: 'GEM|虹|SKILL' },
  GIRLS_CAKE_TOPPER: { name: 'デコレーション・ケーキ', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: 'カードを使用する度、HPを1回復。', applyPower: { id: 'HEAL_ON_PLAY', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'BACKPACK|桃|POWER' },
  GIRLS_FAIRY_TALE: { name: 'おとぎ話の扉', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなスペシャルカードを3枚手札に加える。', rarity: 'LEGENDARY', textureRef: 'BOOK|黄|SKILL' },
  GIRLS_TIARA_SHIELD: { name: '輝くティアラの守り', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '現在のブロック値を2倍にする。', doubleBlock: true, rarity: 'RARE', textureRef: 'GEM|白|SKILL' },
  GIRLS_CUPCAKE_BOOST: { name: '元気が出るカップケーキ', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ2を得る。廃棄。', strength: 2, exhaust: true, rarity: 'UNCOMMON', textureRef: 'BACKPACK|桃|SKILL' },
  GIRLS_STAR_RAIN: { name: '流星の願い', cost: 2, type: CardType.ATTACK, target: TargetType.RANDOM_ENEMY, description: '4ダメージを7回。', damage: 4, playCopies: 6, rarity: 'RARE', textureRef: 'GEM|黄|ATTACK' },
  GIRLS_TEA_PARTY: { name: 'お茶会の時間', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'エネルギー2を得る。カードを2枚引く。', energy: 2, draw: 2, rarity: 'RARE', textureRef: 'BACKPACK|茶|SKILL' },
  GIRLS_KIRAKIRA_PUNCH: { name: 'キラキラパンチ', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。対象にドクドク4。', damage: 8, poison: 4, rarity: 'COMMON', textureRef: 'FIST|桃|ATTACK' },
  GIRLS_GOSSIP_GIRL: { name: '内緒の噂話', cost: 1, type: CardType.SKILL, target: TargetType.ENEMY, description: '対象にへろへろ3。', weak: 3, rarity: 'UNCOMMON', textureRef: 'MIC|白|SKILL' },
  GIRLS_DOLL_HOUSE: { name: 'お人形遊び', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '手札のカード1枚をコピーする。', promptsCopy: 1, rarity: 'UNCOMMON', textureRef: 'HUMANOID|桃|SKILL' },
  GIRLS_CHOCO_VALENTINE: { name: '本命チョコ', cost: 2, type: CardType.ATTACK, target: TargetType.ENEMY, description: '15ダメージ。対象を1ターンスタンさせる。', damage: 15, rarity: 'RARE', textureRef: 'GEM|茶|ATTACK' },
  GIRLS_MELODY_LINE: { name: '夢色メロディ', cost: 1, type: CardType.POWER, target: TargetType.SELF, description: 'スキルを使う度、ブロック3を得る。', applyPower: { id: 'SKILL_BLOCK', amount: 3 }, rarity: 'RARE', textureRef: 'MIC|青|POWER' },
  GIRLS_BUTTERFLY: { name: 'ひらひら蝶々', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック4。1枚引く。', block: 4, draw: 1, rarity: 'COMMON', textureRef: 'FLIER|虹|SKILL' },
  GIRLS_SNOW_FLAKE: { name: '雪の結晶', cost: 1, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体にへろへろ2。ブロック10。', weak: 2, block: 10, rarity: 'UNCOMMON', textureRef: 'GEM|白|SKILL' },
  GIRLS_GIFT_BOX: { name: '秘密のプレゼント', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ランダムなポーションを2つ得る。廃棄。', addPotion: true, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|赤|SKILL' },
  GIRLS_MERMAID_SONG: { name: '人魚の歌声', cost: 2, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に10ダメージ。自分にカチカチ2。', damage: 10, applyPower: { id: 'DEXTERITY', amount: 2 }, rarity: 'RARE', textureRef: 'GHOST|青|ATTACK' },
  GIRLS_SUN_FLOWER: { name: 'ひまわりスマイル', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ムキムキ2、カチカチ2を得る。廃棄。', strength: 2, applyPower: { id: 'DEXTERITY', amount: 2 }, exhaust: true, rarity: 'UNCOMMON', textureRef: 'PLANT|黄|SKILL' },
  GIRLS_JEWELRY_BOX: { name: '宝石箱の魔法', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: '手札の全てのカードをアップグレードする。廃棄。', upgradeHand: true, exhaust: true, rarity: 'RARE', textureRef: 'BACKPACK|虹|SKILL' },
  GIRLS_LOVELY_KISS: { name: 'ラブリー・キッス', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '8ダメージ。HPを全ダメージ分回復。', damage: 8, lifesteal: true, rarity: 'RARE', textureRef: 'FIST|赤|ATTACK' },
  GIRLS_SWEET_PARADE: { name: 'お菓子の行進', cost: 1, type: CardType.ATTACK, target: TargetType.ENEMY, description: '4ダメージを4回。', damage: 4, playCopies: 3, rarity: 'COMMON', textureRef: 'SLIME|虹|ATTACK' },
  GIRLS_MOON_LIGHT: { name: 'ムーンライト・ステップ', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック12。廃棄。', block: 12, exhaust: true, rarity: 'COMMON', textureRef: 'SHIELD|白|SKILL' },
  GIRLS_COLORFUL_RAIN: { name: 'カラフル・レインボー', cost: 2, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '敵全体のブロックを解除し、10ダメージ。', damage: 10, rarity: 'RARE', textureRef: 'GEM|虹|SKILL' },
  GIRLS_ANGEL_HEAL: { name: '天使の祈り', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '最大HP+2。HP10回復。', fatalMaxHp: 2, heal: 10, rarity: 'RARE', textureRef: 'HUMANOID|白|SKILL' },
  GIRLS_FRIENDSHIP: { name: 'ずっと友達だよ', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'パートナーのHPを全回復。自分にブロック15。', block: 15, rarity: 'RARE', textureRef: 'HUMANOID|桃|SKILL' },
  GIRLS_PURE_HEART: { name: '純真な心', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '全デバフを解除。カードを2枚引く。', draw: 2, applyPower: { id: 'CLEAR_DEBUFFS', amount: 1 }, rarity: 'UNCOMMON', textureRef: 'GEM|白|SKILL' },
  GIRLS_BALLERINA: { name: '華麗な舞', cost: 0, type: CardType.SKILL, target: TargetType.SELF, description: 'ブロック6。次に使うアタックを強化。', block: 6, rarity: 'UNCOMMON', textureRef: 'HUMANOID|白|SKILL' },
  GIRLS_STRAWBERRY: { name: 'いちごの奇跡', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: '最大HPを3増やす。', fatalMaxHp: 3, rarity: 'RARE', textureRef: 'PLANT|赤|SKILL' },
  GIRLS_CANDY_SHOWER: { name: '飴玉の嵐', cost: 1, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に3ダメージを3回。', damage: 3, playCopies: 2, rarity: 'COMMON', textureRef: 'SLIME|黄|ATTACK' },
  GIRLS_MIRACLE_RIBBON: { name: '奇跡のリボン', cost: 2, type: CardType.SKILL, target: TargetType.SELF, description: 'エナジーを全回復。廃棄。', energy: 3, exhaust: true, rarity: 'LEGENDARY', textureRef: 'PLANT|虹|SKILL' },
  GIRLS_STAR_DUST: { name: '星屑のきらめき', cost: 1, type: CardType.SKILL, target: TargetType.ALL_ENEMIES, description: '対象にびくびく2。カードを1枚引く。', vulnerable: 2, draw: 1, rarity: 'UNCOMMON', textureRef: 'GEM|黄|SKILL' },
  GIRLS_MAGIC_CIRCLE: { name: '魔法陣の展開', cost: 2, type: CardType.POWER, target: TargetType.SELF, description: '毎ターン開始時、エネルギー1を得る。', applyPower: { id: 'BERSERK_POWER', amount: 1 }, rarity: 'RARE', textureRef: 'GEM|紫|POWER' },
  GIRLS_PRINCESS_CALL: { name: 'お姫様の呼び声', cost: 1, type: CardType.SKILL, target: TargetType.SELF, description: 'デッキからランダムなスキルを1枚手札に加える。', rarity: 'UNCOMMON', textureRef: 'HUMANOID|金|SKILL' },
  GIRLS_ETERNAL_LOVE: { name: '永遠の約束', cost: 3, type: CardType.POWER, target: TargetType.SELF, description: '敗北時、HP50%で1度だけ復活する。', applyPower: { id: 'LIZARD_TAIL', amount: 1 }, rarity: 'LEGENDARY', textureRef: 'GEM|虹|POWER' },
  GIRLS_FLOWER_BOMB: { name: '百花繚乱', cost: 4, type: CardType.ATTACK, target: TargetType.ALL_ENEMIES, description: '全体に30ダメージ。HP5回復。', damage: 30, heal: 5, rarity: 'RARE', textureRef: 'PLANT|虹|ATTACK' },
};

export const STARTING_DECK_TEMPLATE = [
  'STRIKE', 'STRIKE', 'STRIKE', 'STRIKE',
  'DEFEND', 'DEFEND', 'DEFEND', 'DEFEND',
  'BASH', 'IRON_WAVE'
];
