export const RPG_ARCADE_ENGLISH: Record<string, string> = {
  '3枚から1枚を選ぼう。当たりでカードと20コイン！': 'Pick one of three cards. Win a card and 20 coins!',
  '赤・青・緑から予想。当たりで20コインとHP20％回復！': 'Choose red, blue or green. Win 20 coins and heal 20% HP!',
  '星が3つそろえば大当たり！50コインを獲得！': 'Three stars win the jackpot: 50 coins!',
  '町のゲームセンター': 'Town arcade',
  'ひと息、わくわく。': 'Take a break. Try your luck!',
  '所持コイン': 'Your coins',
  '残り回数': 'Plays left',
  '1回10コイン。問題に正解して景品に挑戦！3問以上正解で10コインの追加報酬。': '10 coins per play. Answer correctly to qualify for prizes! Three or more correct answers earn 10 bonus coins.',
  '遊ぶ →': 'Play →',
  '当たりは抽選です。問題挑戦のあとに結果を発表します。': 'Winners are drawn at random. Results appear after the questions.',
  '問題を準備しています…': 'Preparing questions…',
  '10コインで挑戦する': 'Play for 10 coins',
  'ゲームを選び直す': 'Choose another game',
  '開始できませんでした。接続と利用回数を確認してください。': 'Unable to start. Check your connection and remaining plays.',
  '町のデータを同期しています…': 'Synchronizing town data…',
  '10コインが必要です。': 'You need 10 coins.',
  '3つのリールを順に止めよう！': 'Stop the three reels one by one!',
  'リールを止める': 'Stop a reel',
  '獲得コイン': 'Coins earned',
  'HP回復': 'HP restored',
  '景品獲得には問題の正解が必要です。': 'Answer a question correctly to qualify for a prize.',
  'もう一度遊ぶ': 'Play again',
  '探索へ戻る': 'Return to exploration',
  '結果発表！': 'The results are in!',
  '3つの遊びで景品に挑戦': 'Three games. Exciting prizes!',
};
export const RPG_ARCADE_HIRAGANA: Record<string, string> = {
  '3枚から1枚を選ぼう。当たりでカードと20コイン！': '3まいから1まいをえらぼう。あたりでカードと20コイン！',
  '赤・青・緑から予想。当たりで20コインとHP20％回復！': 'あか・あお・みどりからよそう。あたりで20コインとHP20％かいふく！',
  '星が3つそろえば大当たり！50コインを獲得！': 'ほしが3つそろえばおおあたり！50コインをかくとく！',
  '町のゲームセンター': 'まちのゲームセンター',
  'ひと息、わくわく。': 'ひといき、わくわく。',
  '所持コイン': 'もっているコイン',
  '残り回数': 'のこりかいすう',
  '1回10コイン。問題に正解して景品に挑戦！3問以上正解で10コインの追加報酬。': '1かい10コイン。もんだいにせいかいしてけいひんにちょうせん！3もんいじょうせいかいで10コインのついかほうしゅう。',
  '遊ぶ →': 'あそぶ →',
  '当たりは抽選です。問題挑戦のあとに結果を発表します。': 'あたりはちゅうせんです。もんだいちょうせんのあとにけっかをはっぴょうします。',
  '問題を準備しています…': 'もんだいをじゅんびしています…',
  '10コインで挑戦する': '10コインでちょうせんする',
  'ゲームを選び直す': 'ゲームをえらびなおす',
  '開始できませんでした。接続と利用回数を確認してください。': 'かいしできませんでした。せつぞくとりようかいすうをかくにんしてください。',
  '町のデータを同期しています…': 'まちのデータをどうきしています…',
  '10コインが必要です。': '10コインがひつようです。',
  '3つのリールを順に止めよう！': '3つのリールをじゅんにとめよう！',
  'リールを止める': 'リールをとめる',
  '獲得コイン': 'かくとくコイン',
  'HP回復': 'HPかいふく',
  '景品獲得には問題の正解が必要です。': 'けいひんかくとくにはもんだいのせいかいがひつようです。',
  'もう一度遊ぶ': 'もういちどあそぶ',
  '探索へ戻る': 'たんさくへもどる',
  '結果発表！': 'けっかはっぴょう！',
  '3つの遊びで景品に挑戦': '3つのあそびでけいひんにちょうせん',
};
