export const CAMPAIGN_ENGLISH:Record<string,string>={
  "魔王": "Demon King",
  "真・魔王": "True Demon King",
  "スーパー魔王ハイグレードEXスペシャルエディションαオメガMAX": "Super Demon King High Grade EX Special Edition Alpha Omega MAX",
  "魔王城": "Demon King’s Citadel",
  "魔王城へ": "To the Demon King’s Citadel",
  "魔王を倒しました！": "The Demon King is defeated!",
  "魔王が真の姿を現した！": "The Demon King reveals his true form!",
  "魔王が最終形態に変身した！": "The Demon King transforms into his final form!",
  "6地域の試験官を倒すと魔王城の結界が解除されます。": "Defeat all six regional examiners to break the citadel barrier.",
  "6地域の試験官を倒し、三段階に変身する魔王に挑もう。": "Defeat the six regional examiners, then face the Demon King’s three forms.",
  "異世界の冒険が始まる。6地域の試験官を倒し、魔王城の結界を解こう。": "Your otherworld adventure begins. Defeat the six examiners and break the citadel barrier.",
  "魔王の力を封じろ": "Seal the Demon King’s power",
  "エンディング": "Epilogue",
  "魔王、消滅": "The Demon King vanishes",
  "学んだことは、力になる": "Learning becomes strength",
  "六地域に、朝が来る": "Dawn returns to the six regions",
  "おかえり、私たちの英雄": "Welcome home, our hero",
  "次は、幸せをつくる番": "Now, build happiness",
  "世界運営、解放": "World management unlocked",
  "未来を引き受ける": "Accept the future",
  "物語を進める": "Continue the story",
  "最後の一撃が、無限を名乗る魔王の核を砕いた。三度姿を変えた闇は、今度こそ光の粒となって消えていく。": "The final blow shattered the core of the king who claimed infinity. After three transformations, the darkness finally dissolves into light.",
  "この世界へ来た日は、何も分からなかった。一問ずつ考え、仲間と支え合い、六地域の試練を越えた。その積み重ねが世界を救った。": "You arrived knowing nothing of this world. One question at a time, with friends beside you, you overcame six trials. Everything you learned helped save the world.",
  "草原に花が咲き、森に歌が戻る。湿原の水は澄み、砂丘に旅人が帰り、高原に灯がともり、遺跡の時計が再び動き出す。": "Flowers bloom in the meadow, songs return to the forest. The wetland clears, travelers return to the dunes, lights glow in the highlands, and ancient clocks begin again.",
  "住人たちは、あなたの名前を呼んで迎えた。守ったのは王冠ではない。友達と食卓を囲み、明日を楽しみにできる、この暮らしだ。": "The residents welcome you by name. You protected more than a crown: you saved shared meals, friendship, and the hope of another day.",
  "六地域の試験官は、世界の復興をあなたに託した。道をつなぎ、住まいと仕事を増やし、水・電気・教育・医療を届けよう。": "The six examiners entrust the world’s recovery to you. Connect roads, create homes and jobs, and provide water, power, education and healthcare.",
  "戦いの物語はここで結ぶ。そして暮らしの物語は続いていく。時間制限のない平和な世界で、住人の幸福を育てる街づくりを始めよう。": "The tale of battle ends here. The story of everyday life continues. Build a happy community in a peaceful world with no time limit.",
  "木漏れ日の草原の試験官": "Sunlit Meadow Examiner",
  "ささやきの森の試験官": "Whispering Forest Examiner",
  "鏡水の湿原の試験官": "Mirrorwater Wetland Examiner",
  "琥珀の砂丘の試験官": "Amber Dunes Examiner",
  "星霜の高原の試験官": "Starfrost Highlands Examiner",
  "暁の古代遺跡の試験官": "Dawn Ancient Ruins Examiner"
};
export const CAMPAIGN_HIRAGANA:Record<string,string>={
  "魔王": "まおう",
  "真・魔王": "しん・まおう",
  "スーパー魔王ハイグレードEXスペシャルエディションαオメガMAX": "すーぱーまおう はいぐれーど いーえっくす すぺしゃるえでぃしょん あるふぁ おめが まっくす",
  "魔王城": "まおうじょう",
  "魔王城へ": "まおうじょうへ",
  "魔王を倒しました！": "まおうをたおしました！",
  "魔王が真の姿を現した！": "まおうがしんのすがたをあらわした！",
  "魔王が最終形態に変身した！": "まおうがさいしゅうけいたいにへんしんした！",
  "6地域の試験官を倒すと魔王城の結界が解除されます。": "ろくちいきのしけんかんをたおすと まおうじょうのけっかいがかいじょされます。",
  "6地域の試験官を倒し、三段階に変身する魔王に挑もう。": "ろくちいきのしけんかんをたおし、さんだんかいにへんしんするまおうにいどもう。",
  "異世界の冒険が始まる。6地域の試験官を倒し、魔王城の結界を解こう。": "いせかいのぼうけんがはじまる。ろくちいきのしけんかんをたおし、まおうじょうのけっかいをとこう。",
  "魔王の力を封じろ": "まおうのちからをふうじろ",
  "エンディング": "えんでぃんぐ",
  "魔王、消滅": "まおう、しょうめつ",
  "学んだことは、力になる": "まなんだことは、ちからになる",
  "六地域に、朝が来る": "ろくちいきに、あさがくる",
  "おかえり、私たちの英雄": "おかえり、わたしたちのえいゆう",
  "次は、幸せをつくる番": "つぎは、しあわせをつくるばん",
  "世界運営、解放": "せかいうんえい、かいほう",
  "未来を引き受ける": "みらいをひきうける",
  "物語を進める": "ものがたりをすすめる",
  "最後の一撃が、無限を名乗る魔王の核を砕いた。三度姿を変えた闇は、今度こそ光の粒となって消えていく。": "さいごのいちげきが、むげんをなのるまおうのかくをくだいた。さんどすがたをかえたやみは、こんどこそひかりのつぶとなってきえていく。",
  "この世界へ来た日は、何も分からなかった。一問ずつ考え、仲間と支え合い、六地域の試練を越えた。その積み重ねが世界を救った。": "このせかいへきたひは、なにもわからなかった。いちもんずつかんがえ、なかまとささえあい、ろくちいきのしれんをこえた。そのつみかさねがせかいをすくった。",
  "草原に花が咲き、森に歌が戻る。湿原の水は澄み、砂丘に旅人が帰り、高原に灯がともり、遺跡の時計が再び動き出す。": "そうげんにはながさき、もりにうたがもどる。しつげんのみずはすみ、さきゅうにたびびとがかえり、こうげんにひがともり、いせきのとけいがふたたびうごきだす。",
  "住人たちは、あなたの名前を呼んで迎えた。守ったのは王冠ではない。友達と食卓を囲み、明日を楽しみにできる、この暮らしだ。": "じゅうにんたちは、あなたのなまえをよんでむかえた。まもったのはおうかんではない。ともだちとしょくたくをかこみ、あしたをたのしみにできる、このくらしだ。",
  "六地域の試験官は、世界の復興をあなたに託した。道をつなぎ、住まいと仕事を増やし、水・電気・教育・医療を届けよう。": "ろくちいきのしけんかんは、せかいのふっこうをあなたにたくした。みちをつなぎ、すまいとしごとをふやし、みず・でんき・きょういく・いりょうをとどけよう。",
  "戦いの物語はここで結ぶ。そして暮らしの物語は続いていく。時間制限のない平和な世界で、住人の幸福を育てる街づくりを始めよう。": "たたかいのものがたりはここでむすぶ。そしてくらしのものがたりはつづいていく。じかんせいげんのないへいわなせかいで、じゅうにんのこうふくをそだてるまちづくりをはじめよう。",
  "木漏れ日の草原の試験官": "こもれびのそうげんのしけんかん",
  "ささやきの森の試験官": "ささやきのもりのしけんかん",
  "鏡水の湿原の試験官": "きょうすいのしつげんのしけんかん",
  "琥珀の砂丘の試験官": "こはくのさきゅうのしけんかん",
  "星霜の高原の試験官": "せいそうのこうげんのしけんかん",
  "暁の古代遺跡の試験官": "あかつきのこだいいせきのしけんかん"
};
