import {FISH} from './fishing';
export const RPG_FISH_ENGLISH:Record<string,string>={
 ...Object.fromEntries(FISH.map(f=>[f.name,f.english])),
 "釣り図鑑":"Fish collection",
 "生息地":"Habitat",
 "すべての生息地":"All habitats",
 "発見済みのみ":"Discovered only",
 "すべての魚":"All fish",
 "ふつう":"Common",
 "珍しい":"Uncommon",
 "希少":"Rare",
 "伝説":"Legendary",
 "最大":"Best size",
 "部屋の釣果":"Room catches",
 "釣果":"Catch result",
 "サイズ記録更新！":"New size record!",
 "釣れました！":"Caught!",
 "大成功！素材の魚を2匹獲得":"Perfect! Received 2 fish materials",
 "素材の魚を1匹獲得":"Received 1 fish material",
 "釣りを続ける":"Keep fishing",
 "釣りを止める":"Stop fishing",
 "図鑑を見る":"Open collection",
 "発見と最大サイズはこの端末に保存。釣果数はこの部屋の記録です。":"Discoveries and best sizes are saved on this device. Catch counts are for this room.",
 "まだ魚を釣っていません。水辺へ出かけよう！":"No fish discovered yet. Head to the water!",
 "糸が切れました。光る範囲で巻きましょう。":"The line snapped. Reel inside the glowing zone.",
 "釣れました！サイズ記録を更新！":"Caught! New room size record!",
 "釣れました！図鑑に記録しました。":"Caught! Added to your collection.",
 "光る範囲で巻いて、魚を引き寄せよう！":"Reel in the glowing zone to bring the fish closer!",
 "今！巻く！":"Reel now!",
 "成功":"Success",
};
export const RPG_FISH_HIRAGANA:Record<string,string>={
 ...Object.fromEntries(FISH.map(f=>[f.name,f.kana])),
 "釣り図鑑":"つりずかん",
 "生息地":"せいそくち",
 "すべての生息地":"すべてのせいそくち",
 "発見済みのみ":"はっけんずみのみ",
 "すべての魚":"すべてのさかな",
 "ふつう":"ふつう",
 "珍しい":"めずらしい",
 "希少":"きしょう",
 "伝説":"でんせつ",
 "最大":"さいだい",
 "部屋の釣果":"へやのちょうか",
 "釣果":"ちょうか",
 "サイズ記録更新！":"さいずきろくこうしん！",
 "釣れました！":"つれました！",
 "大成功！素材の魚を2匹獲得":"だいせいこう！そざいのさかなを２ひきかくとく",
 "素材の魚を1匹獲得":"そざいのさかなを１ひきかくとく",
 "釣りを続ける":"つりをつづける",
 "釣りを止める":"つりをやめる",
 "図鑑を見る":"ずかんをみる",
 "発見と最大サイズはこの端末に保存。釣果数はこの部屋の記録です。":"はっけんとさいだいさいずはこのたんまつにほぞん。ちょうかすうはこのへやのきろくです。",
 "まだ魚を釣っていません。水辺へ出かけよう！":"まださかなをつっていません。みずべへでかけよう！",
 "糸が切れました。光る範囲で巻きましょう。":"いとがきれました。ひかるはんいでまきましょう。",
 "釣れました！サイズ記録を更新！":"つれました！さいずきろくをこうしん！",
 "釣れました！図鑑に記録しました。":"つれました！ずかんにきろくしました。",
 "光る範囲で巻いて、魚を引き寄せよう！":"ひかるはんいでまいて、さかなをひきよせよう！",
 "今！巻く！":"いま！まく！",
 "成功":"せいこう",
};
