import {drawFarmSprite} from './farm/draw';
import type {FarmPet} from './farm/model';
import type {HouseGuest} from './town/HouseGuests';
import {heroFrame} from './customHero';
import React,{useEffect,useRef} from 'react';
import {assetUrl} from '../utils/assetPaths';

import {ROOM_WIDTH,ROOM_HEIGHT,furnitureSource,furnitureImage,ROOM_DOOR,furnishing,furnitureSize,type Interior,type PlacedFurniture} from './homeCatalog';
import type {Adventurer} from './engine';
const T=24,images=new Map<string,HTMLImageElement>();
function sprite(path:string){let image=images.get(path);if(!image){image=new Image();image.src=assetUrl(path);images.set(path,image);}return image;}
export default function HomeCanvas({room,players,guests=[],pets=[],selfId,selected,preview,onTile,onHover,label}:{room:Interior;players:Adventurer[];guests?:HouseGuest[];pets?:FarmPet[];selfId:string;selected?:string;preview?:PlacedFurniture;onTile:(x:number,y:number)=>void;onHover:(x:number,y:number)=>void;label:string}){
 const canvas=useRef<HTMLCanvasElement>(null),state=useRef({room,players,guests,pets,selfId,selected,preview});state.current={room,players,guests,pets,selfId,selected,preview};
 useEffect(()=>{let frame=0;const paint=(time:number)=>{const el=canvas.current;if(!el)return;const c=el.getContext('2d')!;const width=el.clientWidth,height=width*ROOM_HEIGHT/ROOM_WIDTH;const dpr=Math.min(2,window.devicePixelRatio||1);el.width=Math.round(width*dpr);el.height=Math.round(height*dpr);c.scale(width*dpr/(ROOM_WIDTH*T),width*dpr/(ROOM_WIDTH*T));c.imageSmoothingEnabled=false;const v=state.current;
 for(let y=0;y<ROOM_HEIGHT;y++)for(let x=0;x<ROOM_WIDTH;x++){const wall=x===0||y===0||x===ROOM_WIDTH-1||y===ROOM_HEIGHT-1;c.fillStyle=wall?'#465349':(x+y)%2?'#aa8055':'#b38b61';c.fillRect(x*T,y*T,T,T);c.strokeStyle=wall?'#687469':'#94704a';c.lineWidth=.5;c.strokeRect(x*T,y*T,T,T);if(!wall){c.strokeStyle='#c5a578';c.beginPath();c.moveTo(x*T+3,y*T+8);c.lineTo(x*T+18,y*T+8);c.stroke();}}
 for(const x of [4,12]){c.fillStyle='#e4d1a0';c.fillRect(x*T,2,2*T,18);c.fillStyle='#91c6cb';c.fillRect(x*T+4,5,2*T-8,11);c.fillStyle='#eee4c4';c.fillRect(x*T+T-1,5,2,11);}
 c.fillStyle='#f1cf86';c.fillRect(ROOM_DOOR.x*T,ROOM_DOOR.y*T,T,T);c.fillStyle='#494436';c.font='bold 16px sans-serif';c.textAlign='center';c.fillText('↓',ROOM_DOOR.x*T+T/2,ROOM_DOOR.y*T+18);
 const draw=(p:PlacedFurniture,ghost=false)=>{const f=furnishing(p.item);if(!f)return;const size=furnitureSize(p),image=sprite(furnitureImage(f.id)),w=size.width*T,h=size.height*T,drawSize=Math.max(w,h)+8,x=p.x*T+w/2,y=p.y*T+h;if(p.id===v.selected||ghost){c.fillStyle=ghost?'#b6edaf66':'#fff0ac66';c.fillRect(p.x*T,p.y*T,w,h);c.strokeStyle='#fbdd8e';c.lineWidth=1.5;c.strokeRect(p.x*T,p.y*T,w,h);}c.save();if(ghost)c.globalAlpha=.6;if(image.complete&&image.naturalWidth){c.translate(x,y-drawSize/2);if(p.rotation)c.rotate(Math.PI/2);const [sx,sy,sw,sh]=furnitureSource(f.id,image);c.drawImage(image,sx,sy,sw,sh,-drawSize/2,-drawSize/2,drawSize,drawSize);}c.restore();};
 v.room.placed.filter(p=>furnishing(p.item)?.floor).forEach(p=>draw(p));
 const actors:Array<{y:number;draw:()=>void}>=v.room.placed.filter(p=>!furnishing(p.item)?.floor).map(p=>({y:p.y+furnitureSize(p).height,draw:()=>draw(p)}));
 for(const guest of v.guests){actors.push({y:guest.y+1,draw:()=>{const image=sprite(guest.image||'sprites/rpg/town/family.webp'),x=guest.x*T+T/2,y=(guest.y+1)*T;if(image.complete&&image.naturalWidth){const i=guest.atlasIndex;if(i===undefined){const ratio=Math.min(25/image.naturalWidth,32/image.naturalHeight);c.drawImage(image,x-image.naturalWidth*ratio/2,y-image.naturalHeight*ratio,image.naturalWidth*ratio,image.naturalHeight*ratio);}else c.drawImage(image,i%4*image.naturalWidth/4,Math.floor(i/4)*image.naturalHeight/3,image.naturalWidth/4,image.naturalHeight/3,x-16,y-32,32,32);}c.font='bold 7px sans-serif';c.textAlign='center';c.fillStyle='#1d3844df';c.fillRect(x-22,y,44,10);c.fillStyle='#c7edc1';c.fillText(guest.name.slice(0,8),x,y+7);}});}
 for(const p of v.players){const pos=p.life?.roomPos||{x:9,y:11};actors.push({y:pos.y+1,draw:()=>{const x=pos.x*T+T/2,y=pos.y*T+T;c.fillStyle='#3b332b55';c.beginPath();c.ellipse(x,y-2,9,3,0,0,Math.PI*2);c.fill();const source=p.hero?heroFrame(p.hero,'idle',time):p.profile?.image;const image=source?sprite(source):null;if(image?.complete&&image.naturalWidth){const ratio=Math.min(22/image.naturalWidth,30/image.naturalHeight);c.drawImage(image,x-image.naturalWidth*ratio/2,y-image.naturalHeight*ratio,image.naturalWidth*ratio,image.naturalHeight*ratio);}else{c.fillStyle=p.id===v.selfId?'#e9c067':'#9ac9d2';c.fillRect(x-5,y-20,10,16);c.fillStyle='#f1d4aa';c.fillRect(x-4,y-25,8,8);}c.font='bold 7px sans-serif';c.textAlign='center';const text=p.name.slice(0,12),tw=c.measureText(text).width;c.fillStyle='#173239df';c.fillRect(x-tw/2-3,y+1,tw+6,11);c.fillStyle=p.id===v.selfId?'#ffe49d':'#fff';c.fillText(text,x,y+9);}});}
 for(const [i,pet]of v.pets.entries()){actors.push({y:4+Math.floor(i/3),draw:()=>drawFarmSprite(c,'pet',pet.kind,(2+i%3*2)*T+12,(4+Math.floor(i/3))*T+20,30)});}
 actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());if(v.preview)draw(v.preview,true);frame=requestAnimationFrame(paint);};frame=requestAnimationFrame(paint);return()=>cancelAnimationFrame(frame);},[]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>|React.MouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return {x:Math.floor((e.clientX-r.left)/r.width*ROOM_WIDTH),y:Math.floor((e.clientY-r.top)/r.height*ROOM_HEIGHT)};};
 return <canvas className="rpg-room-canvas" ref={canvas} aria-label={label} onClick={e=>{const p=point(e);onTile(p.x,p.y);}} onPointerMove={e=>{const p=point(e);onHover(p.x,p.y);}}/>;
}
