export const RPG_HOME_ENGLISH:Record<string,string> = {
  "家の建築キット": "House building kit",
  "草地に自分の家を建てるキット。": "A kit to build your home on grass.",
  "建築キットか家をすでに持っています。": "You already have a house or building kit.",
  "ゲーム家具の近くへ移動してください。": "Move closer to the game furniture.",
  "家具の作成・配置は自分の家の中で行えます。": "Craft and arrange furniture inside your own home.",
  "家具の持ち物がいっぱいです。": "Your furniture inventory is full.",
  "家具を作りました。持ち物から場所を選んで飾れます。": "Furniture crafted! Choose it from your inventory and place it.",
  "家具や入口・通路に重ならない場所を選んでください。": "Choose a spot that keeps furniture and the doorway clear.",
  "家具を飾りました！": "Furniture placed!",
  "対戦中の家具は変更できません。": "Furniture cannot be changed during a game.",
  "家具を回転しました。": "Furniture rotated.",
  "家具を持ち物に戻しました。": "Furniture returned to inventory.",
  "家の中のマップ": "Indoor map",
  "入口へ向かう": "Walk to the exit",
  "室内を歩く": "Walk indoors",
  "家具を作る": "Craft furniture",
  "持ち物と配置": "Inventory & placement",
  "ミニゲーム": "Mini-games",
  "室内の移動": "Move indoors",
  "飾る場所をマップで選んでください。": "Choose a spot on the map to place it.",
  "マップをタップ、または矢印キー・WASDで移動。下の入口に重なると外へ出ます。": "Tap the map or use arrow keys / WASD to move. Step onto the bottom doorway to leave.",
  "向きを変える": "Change orientation",
  "配置をやめる": "Cancel placement",
  "ここで遊ぶ": "Play here",
  "家具へ向かう": "Walk to furniture",
  "回転する": "Rotate",
  "持ち物に戻す": "Pack away",
  "家具を作ると持ち物に入ります。場所を選んで飾りましょう。": "Crafted furniture goes into your inventory. Choose a spot to decorate.",
  "家具の作成・配置は家の持ち主が行います。": "The homeowner can craft and arrange furniture.",
  "すべて": "All",
  "家具とインテリア": "Furniture & decor",
  "ぬいぐるみ": "Plush toys",
  "ゲーム家具": "Game furniture",
  "作った家具を選び、室内マップの好きな場所に配置できます。": "Choose crafted furniture and place it on the indoor map.",
  "飾る": "Place",
  "持ち物に家具がありません。家具を作るか、配置済みの家具を持ち物に戻しましょう。": "No furniture in inventory. Craft some or pack away placed furniture.",
  "ゲーム家具の近くで参加できます。家具は室内マップで選べます。": "Join games near their furniture. Select furniture on the indoor map.",
  "室内へ戻る": "Back to the room",
  "木のベッド": "Oak bed",
  "森色のソファ": "Forest sofa",
  "木のチェア": "Wooden chair",
  "丸いテーブル": "Round table",
  "本棚": "Bookshelf",
  "木のクローゼット": "Oak wardrobe",
  "石の暖炉": "Stone fireplace",
  "観葉植物": "Potted plant",
  "花の花瓶": "Flower vase",
  "フロアランプ": "Floor lamp",
  "青いラグ": "Blue rug",
  "赤いラグ": "Red rug",
  "くまのぬいぐるみ": "Teddy bear plush",
  "うさぎのぬいぐるみ": "Bunny plush",
  "ねこのぬいぐるみ": "Cat plush",
  "きつねのぬいぐるみ": "Fox plush",
  "ペンギンのぬいぐるみ": "Penguin plush",
  "スライムのぬいぐるみ": "Slime plush",
  "風景画": "Landscape painting",
  "柱時計": "Grandfather clock",
  "魔晶石の飾り台": "Crystal display",
  "騎士のよろい飾り": "Knight armor display",
  "水槽": "Aquarium",
  "オルゴール": "Music box",
  "作業台": "Workbench"
};
export const RPG_HOME_HIRAGANA:Record<string,string> = {
  "家の建築キット": "いえのけんちくきっと",
  "草地に自分の家を建てるキット。": "くさちにじぶんのいえをたてるきっと。",
  "建築キットか家をすでに持っています。": "けんちくきっとかいえをすでにもっています。",
  "ゲーム家具の近くへ移動してください。": "げーむかぐのちかくへいどうしてください。",
  "家具の作成・配置は自分の家の中で行えます。": "かぐのさくせい・はいちはじぶんのいえのなかでおこなえます。",
  "家具の持ち物がいっぱいです。": "かぐのもちものがいっぱいです。",
  "家具を作りました。持ち物から場所を選んで飾れます。": "かぐをつくりました。もちものからばしょをえらんでかざれます。",
  "家具や入口・通路に重ならない場所を選んでください。": "かぐやいりぐち・つうろにかさならないばしょをえらんでください。",
  "家具を飾りました！": "かぐをかざりました！",
  "対戦中の家具は変更できません。": "たいせんちゅうのかぐはへんこうできません。",
  "家具を回転しました。": "かぐをかいてんしました。",
  "家具を持ち物に戻しました。": "かぐをもちものにもどしました。",
  "家の中のマップ": "いえのなかのまっぷ",
  "入口へ向かう": "いりぐちへむかう",
  "室内を歩く": "しつないをあるく",
  "家具を作る": "かぐをつくる",
  "持ち物と配置": "もちものとはいち",
  "ミニゲーム": "みにげーむ",
  "室内の移動": "しつないのいどう",
  "飾る場所をマップで選んでください。": "かざるばしょをまっぷでえらんでください。",
  "マップをタップ、または矢印キー・WASDで移動。下の入口に重なると外へ出ます。": "まっぷをたっぷ、またはやじるしきー・WASDでいどう。したのいりぐちにかさなるとそとへでます。",
  "向きを変える": "むきをかえる",
  "配置をやめる": "はいちをやめる",
  "ここで遊ぶ": "ここであそぶ",
  "家具へ向かう": "かぐへむかう",
  "回転する": "かいてんする",
  "持ち物に戻す": "もちものにもどす",
  "家具を作ると持ち物に入ります。場所を選んで飾りましょう。": "かぐをつくるともちものにはいります。ばしょをえらんでかざりましょう。",
  "家具の作成・配置は家の持ち主が行います。": "かぐのさくせい・はいちはいえのもちぬしがおこないます。",
  "すべて": "すべて",
  "家具とインテリア": "かぐといんてりあ",
  "ぬいぐるみ": "ぬいぐるみ",
  "ゲーム家具": "げーむかぐ",
  "作った家具を選び、室内マップの好きな場所に配置できます。": "つくったかぐをえらび、しつないまっぷのすきなばしょにはいちできます。",
  "飾る": "かざる",
  "持ち物に家具がありません。家具を作るか、配置済みの家具を持ち物に戻しましょう。": "もちものにかぐがありません。かぐをつくるか、はいちずみのかぐをもちものにもどしましょう。",
  "ゲーム家具の近くで参加できます。家具は室内マップで選べます。": "げーむかぐのちかくでさんかできます。かぐはしつないまっぷでえらべます。",
  "室内へ戻る": "しつないへもどる",
  "木のベッド": "きのべっど",
  "森色のソファ": "もりいろのそふぁ",
  "木のチェア": "きのちぇあ",
  "丸いテーブル": "まるいてーぶる",
  "本棚": "ほんだな",
  "木のクローゼット": "きのくろーぜっと",
  "石の暖炉": "いしのだんろ",
  "観葉植物": "かんようしょくぶつ",
  "花の花瓶": "はなのかびん",
  "フロアランプ": "ふろあらんぷ",
  "青いラグ": "あおいらぐ",
  "赤いラグ": "あかいらぐ",
  "くまのぬいぐるみ": "くまのぬいぐるみ",
  "うさぎのぬいぐるみ": "うさぎのぬいぐるみ",
  "ねこのぬいぐるみ": "ねこのぬいぐるみ",
  "きつねのぬいぐるみ": "きつねのぬいぐるみ",
  "ペンギンのぬいぐるみ": "ぺんぎんのぬいぐるみ",
  "スライムのぬいぐるみ": "すらいむのぬいぐるみ",
  "風景画": "ふうけいが",
  "柱時計": "はしらどけい",
  "魔晶石の飾り台": "ましょうせきのかざりだい",
  "騎士のよろい飾り": "きしのよろいかざり",
  "水槽": "すいそう",
  "オルゴール": "おるごーる",
  "作業台": "さぎょうだい"
};
