import {useRpgMusic} from './music';
import RpgSettings from './RpgSettings';
import MiniGameLab from './MiniGameLab';
import {trans} from '../utils/textUtils';
import React,{useEffect,useState} from 'react';
import GameTitleScreen from '../mini-games/shared/GameTitleScreen';
import {assetUrl} from '../utils/assetPaths';
import {readWorldSave,type RpgWorldSave} from './worldSave';
import type {LanguageMode} from '../types';
export default function RpgTitle({languageMode,onNew,onContinue,onClose,debugEnabled=false}:{languageMode:LanguageMode;onNew:(mode:'solo'|'online')=>void;onContinue:(save:RpgWorldSave)=>void;onClose:()=>void;debugEnabled?:boolean}){const t=(s:string)=>trans(s,languageMode);const [settings,setSettings]=useState(false),[lab,setLab]=useState(false);const [save,setSave]=useState<RpgWorldSave|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let live=true;readWorldSave().then(s=>{if(live)setSave(s);}).catch(()=>{if(live)setError('保存データを読み込めませんでした。');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);useRpgMusic(lab&&debugEnabled?null:settings?'settings':'title');if(lab&&debugEnabled)return <MiniGameLab languageMode={languageMode} onClose={()=>setLab(false)}/>;return <>{settings&&<RpgSettings languageMode={languageMode} onClose={()=>setSettings(false)}/>}<GameTitleScreen kind="rpg" title={t('木漏れ日のフロンティア')} subtitle={t('学び、冒険し、自分だけの暮らしをつくろう。')} languageMode={languageMode} onClose={onClose} backdrop={<img src={assetUrl('sprites/rpg/title/frontier.webp')} alt=""/>} actions={[{label:'ひとりで遊ぶ',onClick:()=>onNew('solo')},{label:'続きから',disabled:loading||!save||(save.world.ended&&save.world.endReason!=='clear'),onClick:()=>save&&onContinue(save)},{label:'オンラインで遊ぶ',onClick:()=>onNew('online')},{label:'RPG設定',onClick:()=>setSettings(true)},...(debugEnabled?[{label:'ゲーム家具の練習室',onClick:()=>setLab(true)}]:[])] }>{error|| (loading?'保存データを確認中…':save?<><strong>{save.world.players[save.selfId].name}</strong><span>{new Date(save.savedAt).toLocaleString(languageMode==='ENGLISH'?'en-US':'ja-JP')}</span><span>{t('戦闘勝利')} {save.world.players[save.selfId].completedBattles} · {t('家')} {save.world.life.houses.length}</span></>: 'この端末に保存した冒険はまだありません。')}{save?.world.ended&&save.world.endReason!=='clear'&&<p>{t('この冒険は終了しました。新しい冒険を始めましょう。')}</p>}<p>{t('ひとり用ワールドは自動保存。制限時間なしで遊べます。')}</p></GameTitleScreen></>;}
