export const RPG_SOCIAL_ENGLISH: Record<string, string> = {
  "これからも一緒に歩いていこう。":"Let us keep walking together.",
  "今日から同じ家で暮らそう。":"Let us make this house our home.",
  "よろしくね！":"Looking forward to it!",
  オリジナル主人公ビルダー: "Original hero builder",
  オリジナル主人公: "Original hero",
  主人公の名前: "Hero name",
  "写真・イラストを切り抜き、6動作に各4枚まで登録できます。未登録の動作は待機画像を使います。":
    "Cut out photos or illustrations and register up to four frames for each of six actions. Empty actions use the idle image.",
  閉じる: "Close",
  待機: "Idle",
  特殊待機: "Special idle",
  被弾: "Hit",
  瀕死: "Low HP",
  フレーム画像を選ぶ: "Choose frame image",
  このフレームを削除: "Delete this frame",
  立ち絵を選ぶ: "Choose portrait",
  画像の切り抜き: "Image cutout",
  範囲を切り抜く: "Crop area",
  消しゴム: "Eraser",
  元画像で修復: "Restore original pixels",
  "範囲をドラッグして切り抜き。消しゴムは指でなぞって調整できます。":
    "Drag to crop. Use the eraser with your finger to refine the cutout.",
  ブラシの大きさ: "Brush size",
  背景除去の許容値: "Background tolerance",
  四隅の背景色を除去: "Remove connected corner background",
  ひとつ戻す: "Undo",
  この画像を登録: "Register this image",
  編集をやめる: "Cancel editing",
  主人公のボイス: "Hero voice",
  ボイスを試聴: "Preview voice",
  "画像と主人公はこの端末に保存され、参加した部屋へ共有されます。":
    "Images and your hero are saved on this device and shared with the room you join.",
  保存してこの主人公を使う: "Save and use this hero",
  元の主人公に戻す: "Return to the original hero",
  "画像は16MB以下にしてください。": "Choose an image under 16 MB.",
  "画像ファイルを選んでください。": "Choose an image file.",
  "画像を読み込めませんでした。": "Could not load the image.",
  "画像が空です。": "The image is empty.",
  "画像の容量を減らしてください。": "Reduce image file size.",
  "待機の画像を1枚以上登録してください。": "Register at least one idle image.",
  "名前と画像を確認してください。": "Check the name and images.",
  "保存できませんでした。端末の空き容量を確認してください。":
    "Could not save. Check device storage.",
  主人公と交流: "Hero and friendships",
  交流: "Friendships",
  オリジナル主人公を作る: "Create an original hero",
  会話の性格: "Conversation personality",
  やさしい: "Kind",
  論理的: "Logical",
  とぼけた: "Quirky",
  近くの主人公と自動で会話: "Chat automatically with nearby heroes",
  "好きな言葉を12個まで覚えます。友好度20で同居、50で結婚を申し込めます。":
    "Remember up to 12 favorite phrases. Friendship 20 unlocks cohabitation requests; 50 unlocks marriage proposals.",
  覚えさせる言葉: "Phrase to remember",
  言葉を覚える: "Remember phrase",
  言葉を忘れる: "Forget phrase",
  主人公に話しかける: "Talk to your hero",
  話す: "Talk",
  同居のお誘い: "Cohabitation invitation",
  結婚のお申し込み: "Marriage proposal",
  "承諾すると成立します。いつでも解消できます。":
    "Accept to confirm. You can end the relationship at any time.",
  承諾する: "Accept",
  お断りする: "Decline",
  "相手の返事を待っています。": "Waiting for their reply.",
  友好度: "Friendship",
  結婚: "Married",
  同居: "Living together",
  "近くにいます。": "Nearby.",
  "近くへ移動して会話できます。": "Move closer to chat.",
  主人公同士で会話: "Let heroes chat",
  同居を申し込む: "Invite to live together",
  同居を解消: "End cohabitation",
  結婚を申し込む: "Propose marriage",
  結婚を解消: "End marriage",
  会話の思い出: "Conversation memories",
  "友好度・同居・結婚と会話履歴は、この部屋の冒険中に共有されます。":
    "Friendship, cohabitation, marriage and conversation history are shared during this room's adventure.",
};
export const RPG_SOCIAL_HIRAGANA: Record<string, string> = {
  "これからも一緒に歩いていこう。":"これからもいっしょにあるいていこう。",
  "今日から同じ家で暮らそう。":"きょうからおなじいえでくらそう。",
  "よろしくね！":"よろしくね！",
  オリジナル主人公ビルダー: "オリジナルしゅじんこうビルダー",
  オリジナル主人公: "オリジナルしゅじんこう",
  主人公の名前: "しゅじんこうのなまえ",
  "写真・イラストを切り抜き、6動作に各4枚まで登録できます。未登録の動作は待機画像を使います。":
    "しゃしん・イラストをきりぬき、6どうさにかく4まいまでとうろくできます。みとうろくのどうさはたいきがぞうをつかいます。",
  閉じる: "とじる",
  待機: "たいき",
  特殊待機: "とくしゅたいき",
  被弾: "ひだん",
  瀕死: "ひんし",
  フレーム画像を選ぶ: "フレームがぞうをえらぶ",
  このフレームを削除: "このフレームをさくじょ",
  立ち絵を選ぶ: "たちえをえらぶ",
  画像の切り抜き: "がぞうのきりぬき",
  範囲を切り抜く: "はんいをきりぬく",
  消しゴム: "けしゴム",
  元画像で修復: "もとがぞうでしゅうふく",
  "範囲をドラッグして切り抜き。消しゴムは指でなぞって調整できます。":
    "はんいをドラッグしてきりぬき。けしゴムはゆびでなぞってちょうせいできます。",
  ブラシの大きさ: "ブラシのおおきさ",
  背景除去の許容値: "はいけいじょきょのきょようち",
  四隅の背景色を除去: "よすみのはいけいしょくをじょきょ",
  ひとつ戻す: "ひとつもどす",
  この画像を登録: "このがぞうをとうろく",
  編集をやめる: "へんしゅうをやめる",
  主人公のボイス: "しゅじんこうのボイス",
  ボイスを試聴: "ボイスをしちょう",
  "画像と主人公はこの端末に保存され、参加した部屋へ共有されます。":
    "がぞうとしゅじんこうはこのたんまつにほぞんされ、さんかしたへやへきょうゆうされます。",
  保存してこの主人公を使う: "ほぞんしてこのしゅじんこうをつかう",
  元の主人公に戻す: "もとのしゅじんこうにもどす",
  "画像は16MB以下にしてください。": "がぞうは16MBいかにしてください。",
  "画像ファイルを選んでください。": "がぞうファイルをえらんでください。",
  "画像を読み込めませんでした。": "がぞうをよみこめませんでした。",
  "画像が空です。": "がぞうがからです。",
  "画像の容量を減らしてください。": "がぞうのようりょうをへらしてください。",
  "待機の画像を1枚以上登録してください。":
    "たいきのがぞうを1まいいじょうとうろくしてください。",
  "名前と画像を確認してください。": "なまえとがぞうをかくにんしてください。",
  "保存できませんでした。端末の空き容量を確認してください。":
    "ほぞんできませんでした。たんまつのあきようりょうをかくにんしてください。",
  主人公と交流: "しゅじんこうとこうりゅう",
  交流: "こうりゅう",
  オリジナル主人公を作る: "オリジナルしゅじんこうをつくる",
  会話の性格: "かいわのせいかく",
  やさしい: "やさしい",
  論理的: "ろんりてき",
  とぼけた: "とぼけた",
  近くの主人公と自動で会話: "ちかくのしゅじんこうとじどうでかいわ",
  "好きな言葉を12個まで覚えます。友好度20で同居、50で結婚を申し込めます。":
    "すきなことばを12こまでおぼえます。ゆうこうど20でどうきょ、50でけっこんをもうしこめます。",
  覚えさせる言葉: "おぼえさせることば",
  言葉を覚える: "ことばをおぼえる",
  言葉を忘れる: "ことばをわすれる",
  主人公に話しかける: "しゅじんこうにはなしかける",
  話す: "はなす",
  同居のお誘い: "どうきょのおさそい",
  結婚のお申し込み: "けっこんのおもうしこみ",
  "承諾すると成立します。いつでも解消できます。":
    "しょうだくするとせいりつします。いつでもかいしょうできます。",
  承諾する: "しょうだくする",
  お断りする: "おことわりする",
  "相手の返事を待っています。": "あいてのへんじをまっています。",
  友好度: "ゆうこうど",
  結婚: "けっこん",
  同居: "どうきょ",
  "近くにいます。": "ちかくにいます。",
  "近くへ移動して会話できます。": "ちかくへいどうしてかいわできます。",
  主人公同士で会話: "しゅじんこうどうしでかいわ",
  同居を申し込む: "どうきょをもうしこむ",
  同居を解消: "どうきょをかいしょう",
  結婚を申し込む: "けっこんをもうしこむ",
  結婚を解消: "けっこんをかいしょう",
  会話の思い出: "かいわのおもいで",
  "友好度・同居・結婚と会話履歴は、この部屋の冒険中に共有されます。":
    "ゆうこうど・どうきょ・けっこんとかいわりれきは、このへやのぼうけんちゅうにきょうゆうされます。",
};
