import {useRpgPreferences} from './preferences';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowLeft,ArrowDown,ArrowRight} from 'lucide-react';
import {trans} from '../utils/textUtils';
import type {LanguageMode} from '../types';
export default function TouchPad({disabled,onMove,languageMode}:{disabled:boolean;onMove:(dx:number,dy:number)=>void;languageMode:LanguageMode}){
 const prefs=useRpgPreferences(),[knob,setKnob]=useState({x:0,y:0});
 const held=useRef<{id:number;dx:number;dy:number}|null>(null),latest=useRef({disabled,onMove});latest.current={disabled,onMove};
 useEffect(()=>{held.current=null;setKnob({x:0,y:0});},[disabled,prefs.control]);
 useEffect(()=>{const stop=()=>{held.current=null;setKnob({x:0,y:0});},timer=setInterval(()=>{const h=held.current;if(h&&!latest.current.disabled)latest.current.onMove(h.dx,h.dy);},prefs.repeat);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);return()=>{clearInterval(timer);window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',stop);};},[prefs.repeat]);
 const stick=(e:React.PointerEvent<HTMLButtonElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width/2),y=(e.clientY-r.top-r.height/2)/(r.height/2),length=Math.hypot(x,y),scale=length>1?1/length:1;setKnob({x:x*scale*34,y:y*scale*34});if(length<prefs.deadZone){held.current=null;return;}const direction=Math.abs(x)>Math.abs(y)?{dx:Math.sign(x),dy:0}:{dx:0,dy:Math.sign(y)};const old=held.current;held.current={id:e.pointerId,...direction};if(!old||old.dx!==direction.dx||old.dy!==direction.dy)latest.current.onMove(direction.dx,direction.dy);};
 const stopStick=()=>{held.current=null;setKnob({x:0,y:0});};
 if(prefs.control==='stick')return <button className="rpg-stick" role="button" aria-label={trans('バーチャルスティック',languageMode)} disabled={disabled} onPointerDown={e=>{if(disabled||!e.isPrimary||e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);stick(e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)&&!disabled)stick(e);}} onPointerUp={stopStick} onPointerCancel={stopStick} onLostPointerCapture={stopStick}><span aria-hidden="true">✥</span><span className="rpg-stick-knob" style={{transform:'translate('+knob.x+'px,'+knob.y+'px)'}}/></button>;
 const button=(dx:number,dy:number,label:string,icon:React.ReactNode)=><button aria-label={trans(label,languageMode)} disabled={disabled} onPointerDown={e=>{if(latest.current.disabled||held.current||!e.isPrimary||e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);held.current={id:e.pointerId,dx,dy};latest.current.onMove(dx,dy);}} onPointerUp={e=>{if(held.current?.id===e.pointerId)held.current=null;}} onPointerCancel={()=>{held.current=null;}} onLostPointerCapture={()=>{held.current=null;}} onClick={e=>{if(e.detail===0&&!latest.current.disabled)latest.current.onMove(dx,dy);}}>{icon}</button>;
 return <div className="rpg-dpad" aria-label={trans('移動ボタン',languageMode)}>{button(0,-1,'上へ移動',<ArrowUp/>)}<div>{button(-1,0,'左へ移動',<ArrowLeft/>)}{button(0,1,'下へ移動',<ArrowDown/>)}{button(1,0,'右へ移動',<ArrowRight/>)}</div></div>;
}
