import React,{useEffect,useRef,useState} from 'react';
import './voxelWorkshop.css';
import type {World} from './engine';
import type {LanguageMode} from '../types';
import {trans} from '../utils/textUtils';
import {VOXEL_CATALOG,CATALOG_BLOCKS,BLOCK_GROUPS,WORKSHOP_RECIPES,ALL_MATERIAL_NAMES,type CatalogBlock,type VoxelItem} from './voxelCatalog';
import {nearbyWorkshop,workshopStatus,activeTools,irrigatedPlot,type WorkshopAction} from './voxelWorkshop';
import {voxelKey} from './voxel';
import {CROPS} from './farm/catalog';
import {plotPosition} from './farm/land';
import {copy} from './town/catalog';
import {assetUrl} from '../utils/assetPaths';

export function VoxelIcon({block}:{block:string}){if(['shovel','axe','pickaxe','hoe'].includes(block))return <img className="voxel-item-icon" src={assetUrl(`images/rpg/workshop/${block}-v1.png`)} alt=""/>;const color=VOXEL_CATALOG[block as CatalogBlock]?.color??'#c3b898';return <svg viewBox="0 0 32 32" aria-hidden="true"><path fill={color} d="M16 2 30 9v15L16 31 2 24V9z"/><path fill="#ffffff55" d="m16 2 14 7-14 7L2 9z"/><path fill="#00000030" d="m16 16 14-7v15l-14 7z"/></svg>;}
export function VoxelWorkshopPanel({world,selfId,languageMode,send,onChoose,onClose,initial='materials'}:{world:World;selfId:string;languageMode:LanguageMode;send:(a:WorkshopAction)=>void;onChoose:(b:CatalogBlock)=>void;onClose:()=>void;initial?:string}){
 const me=world.players[selfId],bag=me.life?.bag??{},farm=world.farm?.people[selfId],root=useRef<HTMLDivElement>(null);
 const [tab,setTab]=useState(initial),[query,setQuery]=useState(''),[group,setGroup]=useState('all'),[owned,setOwned]=useState(false),[batch,setBatch]=useState(1);
 const L=(ja:string,en:string,hi=ja)=>languageMode==='ENGLISH'?en:languageMode==='HIRAGANA'?hi:ja;
 const name=(id:string)=>languageMode==='ENGLISH'?id.replaceAll('_',' ').replace(/([a-z])(plank|wood|glass|slab|stairs|wool|concrete|brick|stone|ore)$/,'$1 $2'):trans(ALL_MATERIAL_NAMES[id as VoxelItem]||id,languageMode);
 const station=(s:string)=>s==='hand'?L('手作業','By hand','てさぎょう'):name(s);
 const purpose=(id:string)=>{
  const special:Record<string,string>={shovel:L('土・砂・雪・粘土・砂利の採掘を省エネルギー化。','Reduces energy for digging soil, sand, snow, clay and gravel.','つち・すな・ゆきなどをすくないエネルギーでほれます。'),axe:L('木材や木製設備の解体を省エネルギー化。','Reduces energy for chopping wood and wooden stations.','きやもくせいのせつびをすくないエネルギーでこわせます。'),pickaxe:L('石材・鉱石の採掘を省エネルギー化。','Reduces energy for mining stone and ores.','いしやこうせきをすくないエネルギーでほれます。'),hoe:L('地面を耕して農地を作る。','Tills ground into farmland.','じめんをたがやしてはたけをつくります。'),workbench:L('道具・建材・設備を加工する作業設備。','Crafting station for tools, blocks and equipment.'),furnace:L('燃料を消費して鉱石や砂などを精錬する。','Smelts ores and sand using fuel.'),chest:L('素材を共有・保管する。','Stores and shares materials.'),composter:L('葉や果実から有機肥料を加工する。','Processes leaves and fruit into fertilizer.'),irrigator:L('近くの水源から周囲の畑に給水する。','Irrigates nearby farmland using a water source.'),fertilizer:L('1個を農園の堆肥3個に変換する。','Converts one item into three farm compost.'),coal:L('精錬の燃料・たいまつの材料。','Smelting fuel and torch ingredient.'),charcoal:L('精錬の燃料・たいまつの材料。','Smelting fuel and torch ingredient.')};
  if(special[id])return special[id];
  const uses=WORKSHOP_RECIPES.filter(r=>Object.hasOwn(r.cost,id));
  const building=Object.hasOwn(VOXEL_CATALOG,id)?L('建築・装飾に設置できます。','Place for building and decoration.','けんちくやかざりにつかえます。'):'';
  return [building,uses.length?L('加工先: ','Used to craft: ','つくれるもの: ')+uses.slice(0,4).map(r=>languageMode==='ENGLISH'?r.id:trans(r.name,languageMode)).join(' / '):''].filter(Boolean).join(' ');
 };
 useEffect(()=>{const previous=document.activeElement as HTMLElement;root.current?.querySelector('input')?.focus();return()=>previous?.focus?.();},[]);
 const chest=nearbyWorkshop(world,me,'chest'),stock=chest?world.voxels?.containers?.[voxelKey(chest.x,chest.y,chest.z)]?.items??{}:{};
 const matches=(s:string)=>s.toLowerCase().includes(query.trim().toLowerCase());
 const statusLabel=(s:string)=>({ready:L('作る','Craft','つくる'),station:L('設備が必要','Station needed','せつびがひつよう'),owned:L('装備済み','Equipped','そうびずみ'),materials:L('素材不足','Need materials','そざいぶそく'),fuel:L('燃料不足','Need fuel','ねんりょうぶそく'),energy:L('エネルギー不足','Need energy','エネルギーぶそく')})[s];
 return <div className="voxel-workshop-overlay" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>{e.stopPropagation();if(e.key==='Escape')onClose();}}><section ref={root} className="voxel-workshop" role="dialog" aria-modal="true" aria-label={L('建築工房','Builder workshop','けんちくこうぼう')}>
  <header><div><small>BUILD • CRAFT • GROW</small><h2>{L('建築工房','Builder workshop','けんちくこうぼう')}</h2></div><button onClick={onClose}>{L('閉じる','Close','とじる')} ×</button></header>
  <nav>{[['materials','建材','Materials','けんざい'],['craft','クラフト','Craft','クラフト'],['storage','収納','Storage','しゅうのう'],['farm','農業','Farming','のうぎょう']].map(([id,ja,en,hi])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{L(ja,en,hi)}</button>)}</nav>
  <div className="voxel-workshop-tools"><input aria-label={L('素材を検索','Search materials','そざいをけんさく')} placeholder={L('名前で検索…','Search by name…','なまえでけんさく…')} value={query} onChange={e=>setQuery(e.target.value)}/>{tab==='materials'&&<><select aria-label={L('素材カテゴリ','Material category','そざいカテゴリ')} value={group} onChange={e=>setGroup(e.target.value)}><option value="all">{L('すべて','All','すべて')}</option>{Object.entries(BLOCK_GROUPS).map(([id,label])=><option value={id} key={id}>{languageMode==='ENGLISH'?id:trans(label,languageMode)}</option>)}</select><label><input type="checkbox" checked={owned} onChange={e=>setOwned(e.target.checked)}/>{L('所持素材','Owned','もっているもの')}</label></>}{tab==='craft'&&<select aria-label={L('作成回数','Craft batches','つくるかいすう')} value={batch} onChange={e=>setBatch(Number(e.target.value))}>{[1,4,16].map(n=><option key={n} value={n}>{n} ×</option>)}</select>}</div>
  <div className="voxel-workshop-scroll">
  {tab==='materials'&&<><p>{L('建材を選ぶと現在のスロットに登録します。回転ボタンで向きを変えられます。','Choose a material for the active slot. Use Rotate to orient it.','けんざいをえらぶとスロットにとうろくします。かいてんでむきをかえられます。')}</p><div className="voxel-material-grid">{CATALOG_BLOCKS.filter(b=>(group==='all'||VOXEL_CATALOG[b].group===group)&&(!owned||(bag[b]||0)>0)&&matches(name(b))).map(b=><button key={b} title={purpose(b)} onClick={()=>{onChoose(b);onClose();}}><VoxelIcon block={b}/><span>{name(b)}</span><b>{bag[b]||0}</b></button>)}</div></>}
  {tab==='craft'&&<><div className="voxel-stations">{['hand','workbench','furnace','composter'].map(s=><span key={s} data-ready={s==='hand'||!!nearbyWorkshop(world,me,s)}>{station(s)} {s==='hand'||nearbyWorkshop(world,me,s)?'✓':'—'}</span>)}</div><p>{L('原木 → 板 → 作業台 → 道具・かまど。設備は設置して近くで使います。精錬は1回につき燃料1個とエネルギー0.1を消費します。','Logs → planks → workbench → tools and furnace. Place stations nearby. Each smelting batch uses one fuel and 0.1 energy.','げんぼく → いた → さぎょうだい → どうぐ・かまど。せつびはおいてちかくでつかいます。せいれん1かいでねんりょう1ことエネルギー0.1をつかいます。')}</p><div className="voxel-recipe-grid">{WORKSHOP_RECIPES.filter(r=>matches(languageMode==='ENGLISH'?r.id:r.name)).map(r=>{const amount=r.tier||r.output==='hoe'?1:batch,status=workshopStatus(world,me,r,amount);return <article key={r.id}><div><VoxelIcon block={r.output}/><strong>{languageMode==='ENGLISH'?r.id.replaceAll('-',' '):trans(r.name,languageMode)} ×{r.count*amount}</strong></div><small>{station(r.station)}</small><p className="voxel-item-purpose">{purpose(r.output)}</p><ul>{Object.entries(r.cost).map(([item,n])=><li key={item} data-enough={(bag[item as VoxelItem]||0)>=n!*amount}>{name(item)} <b>{bag[item as VoxelItem]||0}/{n!*amount}</b></li>)}</ul><button disabled={status!=='ready'} onClick={()=>send({type:'voxel-craft',recipe:r.id,amount})}>{statusLabel(status)}</button></article>;})}</div></>}
  {tab==='storage'&&<><p>{chest?L('近くの共有チェスト · 24種類 × 各64個。中身が残っている間は破壊できません。','Nearby shared chest · 24 stacks of 64. Empty it before breaking.','ちかくのきょうゆうチェスト · 24しゅるい × 64こ。なかみをだしてからこわせます。'):L('チェストを作って設置し、近づいてください。','Craft and place a chest, then stand nearby.','チェストをつくっておき、ちかづいてください。')}</p>{chest&&<div className="voxel-storage-list">{(Object.keys(ALL_MATERIAL_NAMES) as VoxelItem[]).filter(k=>((bag[k]||0)>0||(stock[k]||0)>0)&&matches(name(k))).map(k=><article key={k}><strong>{name(k)}</strong><span>{L('手持ち','Bag','てもち')} {bag[k]||0} · {L('箱','Chest','はこ')} {stock[k]||0}</span>{[1,8].map(n=><React.Fragment key={n}><button disabled={(bag[k]||0)<n||(stock[k]||0)+n>64} onClick={()=>send({type:'voxel-storage',...chest,item:k,amount:n,direction:'deposit'})}>＋{n} →</button><button disabled={(stock[k]||0)<n} onClick={()=>send({type:'voxel-storage',...chest,item:k,amount:n,direction:'withdraw'})}>← {n}</button></React.Fragment>)}</article>)}</div>}</>}
  {tab==='farm'&&<><div className="voxel-farm-guide"><h3>{L('育てて、加工して、また植える','Grow, process and replant','そだてて、かこうして、またうえる')}</h3><p>{L('クワで地上を耕し、農園メニューから種まき・収穫。葉や果実は堆肥箱で有機肥料へ。灌漑タンクは水辺から4マス以内に置くと、周囲3マスの同じ高さの畑に給水します。','Till surface soil with a hoe, then plant and harvest in the farm menu. Compost leaves or fruit. A tank within 4 cells of water irrigates plots within 3 cells at a similar height.','クワでじめんをたがやし、のうえんでたねまき・しゅうかく。はやくだものをたいひばこでひりょうにします。みずべから4マスいないのタンクが、まわり3マスのはたけにみずをあげます。')}</p><button disabled={!(bag.fertilizer!>0)} onClick={()=>send({type:'voxel-compost'})}>{L('有機肥料1個 → 農園の堆肥3個','1 fertilizer → 3 farm compost','ひりょう1こ → のうえんのたいひ3こ')} ({bag.fertilizer||0})</button><p>{L('灌漑中の農地','Irrigated plots','かんがいちゅうのはたけ')}: {farm?.plots.filter(p=>{const xy=plotPosition(farm,p);return xy&&irrigatedPlot(world,xy.x,xy.y);}).length||0}</p></div><h3>{L('収穫物2個から種3個を採る','Turn 2 crops into 3 seeds','しゅうかくぶつ2こからたね3こ')}</h3><div className="voxel-material-grid">{CROPS.filter(c=>(farm?.pantry[c.id]?.normal||0)>=2).map(c=><button key={c.id} onClick={()=>send({type:'voxel-seeds',crop:c.id})}>{copy(c.name,languageMode)} → 🌱3</button>)}</div><p>{Object.entries(activeTools(me)).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p></>}
  </div><footer role="status">{me.message||L('建材を選んで、自由に組み立てよう。','Choose materials and start building.','けんざいをえらんで、じゆうにつくろう。')}</footer>
 </section></div>;
}
