import {migrateCampaign} from './campaign';
import type {Player} from '../types';
import type {World} from './engine';
import {WIDTH,HEIGHT} from './engine';
export interface RpgWorldSave {version:1;savedAt:number;selfId:string;world:World;player:Player}
export function canSaveWorld(world:World,selfId:string,player:Player){const p=world.players[selfId];return !!p&&!!p.profile&&p.profile.hp===player.currentHp&&p.profile.maxHp===player.maxHp&&p.profile.gold===player.gold&&JSON.stringify(p.profile.deck||[])===JSON.stringify(player.deck)&&world.started&&!world.ended&&!world.town?.encounters?.[selfId]&&!world.town?.cooking[selfId]&&!(world.town?.dreams[selfId]&&!world.town.dreams[selfId].finished)&&!p.spectator&&!p.nativeScene&&!p.life?.work&&!p.duelId&&!p.dungeonId&&!p.arcadePending&&!world.activities.trades.some(t=>t.from===selfId||t.to===selfId)&&!Object.values(world.life.games).some(g=>g.phase==='playing')&&(p.mutationRevision||0)===(player.rpgMutationRevision||0);}
export function validateWorldSave(value:unknown):value is RpgWorldSave {const s=value as RpgWorldSave;return !!s&&s.version===1&&Number.isFinite(s.savedAt)&&typeof s.selfId==='string'&&!!s.world&&Array.isArray(s.world.tiles)&&s.world.tiles.length===WIDTH*HEIGHT&&Array.isArray(s.world.sites)&&!!s.world.players?.[s.selfId]&&Array.isArray(s.world.life?.houses)&&!!s.world.life.games&&!!s.world.activities&&Array.isArray(s.world.activities.trades)&&Array.isArray(s.world.activities.dungeons)&&Array.isArray(s.world.duels)&&!!s.world.rankingAwards&&Number.isFinite(s.world.deadlineAt)&&Number.isFinite(s.world.timeLimitMinutes)&&!!s.player&&Array.isArray(s.player.deck)&&Array.isArray(s.player.relics)&&Number.isFinite(s.player.currentHp)&&s.player.maxHp>0;}
export function makeWorldSave(world:World,selfId:string,player:Player,now=Date.now()):RpgWorldSave {if(!canSaveWorld(world,selfId,player))throw new Error('戦闘・採取・ミニゲームが終わってから保存してください。');return structuredClone({version:1 as const,savedAt:now,selfId,world,player});}
export function restoreWorldSave(save:RpgWorldSave,now=Date.now()){if(!validateWorldSave(save))throw new Error('保存データを読み込めませんでした。');const w=structuredClone(save.world),elapsed=Math.max(0,now-save.savedAt);
 // Freeze absolute runtime timers while the app is closed. Historical records retain their original dates.
 const timers=new Set(['deadlineAt','regrowAt','lastTick','now','lastMove','lastAction','lastTalk','lastPlayerTalk','expires','nextEventAt','nextTalk','endsAt','nextAt','target','started','nativeAt']);
 const shift=(v:unknown)=>{if(!v||typeof v!=='object')return;for(const [k,n] of Object.entries(v)){if(typeof n==='number'&&n>1e12&&timers.has(k))(v as Record<string,unknown>)[k]=n+elapsed;else if(n&&typeof n==='object')shift(n);}};shift(w);if(w.town)w.town.encounters={};w.life.now=now;w.life.lastTick=now;w.revision++;return migrateCampaign(w);}
const DB='learning-rogue-rpg-world',STORE='saves';
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('保存機能を開けませんでした。'));});}
export async function readWorldSave():Promise<RpgWorldSave|null>{const db=await database();try{return await new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get('latest');r.onsuccess=()=>{if(r.result===undefined)resolve(null);else if(validateWorldSave(r.result))resolve(r.result);else reject(new Error('保存データを読み込めませんでした。'));};r.onerror=()=>reject(r.error);});}finally{db.close();}}
export async function writeWorldSave(save:RpgWorldSave){if(!validateWorldSave(save))throw new Error('保存データを読み込めませんでした。');const db=await database();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(save,'latest');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
