import {FARM_DISHES} from '../farm/catalog';
import type {Bag} from '../life';
import type {BiomeId} from '../biomes';
export type Copy={ja:string;en:string;hi:string};
export const c=(ja:string,en:string,hi:string):Copy=>({ja,en,hi});
export const copy=(value:Copy,mode:string)=>mode==='ENGLISH'?value.en:mode==='HIRAGANA'?value.hi:value.ja;
export const SEASONS=[c('春','Spring','はる'),c('夏','Summer','なつ'),c('秋','Autumn','あき'),c('冬','Winter','ふゆ')];
export const DAY_SECONDS=180,SEASON_DAYS=7,YEAR_DAYS=28;
const flowerNames=[
[['桜','Cherry blossom','さくら'],['チューリップ','Tulip','ちゅーりっぷ'],['スミレ','Violet','すみれ'],['タンポポ','Dandelion','たんぽぽ'],['スズラン','Lily of the valley','すずらん'],['ワスレナグサ','Forget-me-not','わすれなぐさ'],['アネモネ','Anemone','あねもね'],['菜の花','Rapeseed','なのはな'],['アカツメクサ','Red clover','あかつめくさ'],['サクラソウ','Primrose','さくらそう'],['スイートピー','Sweet pea','すいーとぴー'],['星咲き草','Star blossom','ほしさきそう']],
[['ヒマワリ','Sunflower','ひまわり'],['アジサイ','Hydrangea','あじさい'],['アサガオ','Morning glory','あさがお'],['ハス','Lotus','はす'],['ラベンダー','Lavender','らべんだー'],['ハイビスカス','Hibiscus','はいびすかす'],['ユリ','Lily','ゆり'],['ジャスミン','Jasmine','じゃすみん'],['マリーゴールド','Marigold','まりーごーるど'],['ヤグルマギク','Cornflower','やぐるまぎく'],['スイレン','Water lily','すいれん'],['蛍火の花','Fireflower','ほたるびのはな']],
[['コスモス','Cosmos','こすもす'],['菊','Chrysanthemum','きく'],['彼岸花','Spider lily','ひがんばな'],['リンドウ','Gentian','りんどう'],['キキョウ','Bellflower','ききょう'],['キンモクセイ','Osmanthus','きんもくせい'],['アスター','Aster','あすたー'],['秋バラ','Autumn rose','あきばら'],['紅葉','Maple leaves','もみじ'],['ススキ','Pampas grass','すすき'],['ホオズキ','Lantern plant','ほおずき'],['琥珀月の花','Amber moonflower','こはくづきのはな']],
[['ツバキ','Camellia','つばき'],['スイセン','Daffodil','すいせん'],['梅','Winter plum','うめ'],['シクラメン','Cyclamen','しくらめん'],['ポインセチア','Poinsettia','ぽいんせちあ'],['スノードロップ','Snowdrop','すのーどろっぷ'],['クリスマスローズ','Hellebore','くりすますろーず'],['ロウバイ','Wintersweet','ろうばい'],['氷色のパンジー','Ice pansy','こおりいろのぱんじー'],['白い冬バラ','Winter rose','しろいふゆばら'],['ヒイラギ','Holly','ひいらぎ'],['雪晶花','Crystal snowflower','せっしょうか']]
];
export interface Flower {id:string;name:Copy;season:number;index:number;biome:BiomeId;rarity:1|2|3;meaning:Copy}
const habitats:BiomeId[]=['meadow','forest','wetland','meadow','forest','wetland','desert','meadow','meadow','snow','ruins','ruins'];
const meanings=[c('新しい出会い','New beginnings','あたらしいであい'),c('やさしい気持ち','Kindness','やさしいきもち'),c('約束と友情','Promises and friendship','やくそくとゆうじょう'),c('勇気と希望','Courage and hope','ゆうきときぼう')];
export const FLOWERS:Flower[]=flowerNames.flatMap((names,season)=>names.map(([ja,en,hi],index)=>({id:`flower-${season}-${index}`,name:c(ja,en,hi),season,index,biome:habitats[index],rarity:index===11?3:index>=9?2:1,meaning:meanings[index%4]})));
export const flowerById=(id:string)=>FLOWERS.find(f=>f.id===id);
export const flowerAtlas=(season:number)=>`sprites/rpg/town/flowers-${['spring','summer','autumn','winter'][season]}.webp`;
export type FoodTag='fish'|'sweet'|'herb'|'spicy'|'warm'|'fresh';
export interface Dish {id:string;name:Copy;index:number;tags:FoodTag[];cost:Bag;nourish:number;season?:number;steps:Copy[];farmCost?:Record<string,number>;atlas?:'farm'}
const dishes:Array<[string,string,string,FoodTag[],Bag,number,number?]>=[
['川魚の香草焼き','Herb-grilled fish','かわざかなのこうそうやき',['fish','herb'],{fish:1,herb:1},30],['森のキノコスープ','Forest mushroom soup','もりのきのこすーぷ',['warm','herb'],{herb:2},25],['春の花サラダ','Spring blossom salad','はるのはなさらだ',['fresh','herb'],{herb:2,reed:1},24,0],['若草のおにぎり','Meadow rice balls','わかくさのおにぎり',['fresh'],{herb:1,reed:1},20,0],['ハチミツ風クッキー','Honey-style cookies','はちみつふうくっきー',['sweet'],{herb:2,wood:1},22],['苺色のタルト','Berry tart','いちごいろのたると',['sweet','fresh'],{herb:3},28,0],
['夏野菜の串焼き','Summer skewers','なつやさいのくしやき',['fresh','spicy'],{herb:2,wood:1},30,1],['冷たい川魚麺','Chilled fish noodles','つめたいかわざかなめん',['fish','fresh'],{fish:1,reed:1},32,1],['草原のアイス','Meadow ice cream','そうげんのあいす',['sweet'],{herb:2,frostwood:1},24,1],['砂丘の香辛スープ','Dune spice soup','さきゅうのこうしんすーぷ',['spicy','warm'],{herb:2,crystal:1},34],['蓮葉の蒸し魚','Lotus-steamed fish','はすばのむしざかな',['fish','herb'],{fish:2,reed:1},36],['星空ゼリー','Starlight jelly','ほしぞらぜりー',['sweet','fresh'],{herb:2,crystal:1},28,1],
['秋の炊き込みご飯','Autumn rice','あきのたきこみごはん',['warm','herb'],{herb:2,reed:2},34,2],['焼き芋風パイ','Harvest pie','やきいもふうぱい',['sweet','warm'],{herb:3,wood:1},32,2],['木の実パンケーキ','Forest pancakes','きのみぱんけーき',['sweet'],{herb:2,wood:1},28,2],['魚介の煮込み','Seafood stew','ぎょかいのにこみ',['fish','warm'],{fish:2,herb:1},38],['紅葉のハーブ茶','Autumn herbal tea','もみじのはーぶちゃ',['herb','warm'],{herb:1},14,2],['カボチャ風ポタージュ','Harvest potage','かぼちゃふうぽたーじゅ',['warm'],{herb:3},30,2],
['雪国のシチュー','Snowland stew','ゆきぐにのしちゅー',['warm'],{fish:1,herb:2},40,3],['ホットココア','Hot cocoa','ほっとここあ',['sweet','warm'],{herb:2},26,3],['氷魚のソテー','Icefish sauté','こおりざかなのそてー',['fish'],{fish:2,frostwood:1},36,3],['冬の星型ビスケット','Winter star biscuits','ふゆのほしがたびすけっと',['sweet'],{herb:2,reed:1},26,3],['薬草入り肉団子風','Herbal dumplings','やくそういりにくだんごふう',['herb','spicy'],{herb:3,reed:1},34],['祝宴のごちそう','Celebration banquet','しゅくえんのごちそう',['fish','sweet','warm'],{fish:3,herb:3,reed:2},50]
];
const steps=[c('下ごしらえ','Prepare','したごしらえ'),c('味を整える','Season','あじをととのえる'),c('仕上げる','Finish','しあげる')];
export const DISHES:Dish[]=dishes.map(([ja,en,hi,tags,cost,nourish,season],index)=>({id:`dish-${index}`,name:c(ja,en,hi),tags,cost,nourish,season,index,steps}));
export const ALL_DISHES=[...DISHES,...FARM_DISHES];
export const dishById=(id:string)=>ALL_DISHES.find(d=>d.id===id);
export const PERSONALITIES=[c('おだやかな世話好き','Gentle caregiver','おだやかなせわずき'),c('好奇心いっぱいの探検家','Curious explorer','こうきしんいっぱいのたんけんか'),c('慎重な研究家','Careful researcher','しんちょうなけんきゅうか'),c('陽気なおしゃべり','Cheerful chatterbox','ようきなおしゃべり'),c('きれい好きの職人','Tidy artisan','きれいずきのしょくにん'),c('自由な夢想家','Free-spirited dreamer','じゆうなむそうか'),c('元気な挑戦者','Energetic challenger','げんきなちょうせんしゃ'),c('静かな芸術家','Quiet artist','しずかなげいじゅつか')];
export const ROUTINES=[c('朝の散歩','Morning walk','あさのさんぽ'),c('料理の練習','Cooking practice','りょうりのれんしゅう'),c('釣りと観察','Fishing and observing','つりとかんさつ'),c('花の手入れ','Tending flowers','はなのていれ'),c('読書の時間','Reading time','どくしょのじかん'),c('友達とお茶','Tea with friends','ともだちとおちゃ'),c('部屋の片づけ','Tidying the room','へやのかたづけ'),c('静かな昼寝','Quiet nap','しずかなひるね')];
export const RESIDENTS=[['mina','ミナ','Mina','みな'],['ao','アオ','Ao','あお'],['ren','レン','Ren','れん'],['sui','スイ','Sui','すい'],['saha','サハ','Saha','さは'],['yuki','ユキ','Yuki','ゆき'],['phil','フィル','Phil','ふぃる'],['towa','トワ','Towa','とわ'],['nono','ノノ','Nono','のの'],['kino','キノ','Kino','きの'],['nemu','ネム','Nemu','ねむ'],['mio','ミオ','Mio','みお']].map(([id,ja,en,hi],i)=>({id:`resident-${id}`,name:c(ja,en,hi),portrait:`sprites/rpg/npcs/${id}.webp`,biome:habitats[i],personality:i%8}));
export const DREAMS=[
c('空を泳ぐ魚の湖','Lake of flying fish','そらをおよぐさかなのみずうみ'),c('お菓子の図書館','Library of sweets','おかしのとしょかん'),c('巨人の花園','Garden of giant flowers','きょじんのはなぞの'),c('星を運ぶ列車','Train carrying stars','ほしをはこぶれっしゃ'),c('しゃべるレリックの市','Talking relic market','しゃべるれりっくのいち'),c('逆さまの雪の町','Upside-down snow town','さかさまのゆきのまち'),c('水中の音楽会','Underwater concert','すいちゅうのおんがくかい'),c('雲の上の食卓','Table above the clouds','くものうえのしょくたく'),c('時計をなくした城','Castle without clocks','とけいをなくしたしろ'),c('小さくなった冒険者','Tiny adventurer','ちいさくなったぼうけんしゃ'),c('ぬいぐるみの行進','Plush parade','ぬいぐるみのこうしん'),c('春を探すペンギン','Penguin seeking spring','はるをさがすぺんぎん'),c('夕焼けの紙飛行機','Sunset paper plane','ゆうやけのかみひこうき'),c('月とお茶を飲む森','Tea with the moon','つきとおちゃをのむもり'),c('虹色の川の源','Source of the rainbow river','にじいろのかわのみなもと'),c('明日の自分の家','Home of your future self','あしたのじぶんのいえ')];
export const FESTIVALS=[c('春の花まつり','Spring flower festival','はるのはなまつり'),c('川辺の星あかり祭','Riverside star festival','かわべのほしあかりまつり'),c('秋の収穫感謝祭','Autumn harvest festival','あきのしゅうかくかんしゃさい'),c('冬の灯りと贈り物','Winter lights and gifts','ふゆのあかりとおくりもの')];
export const OUTINGS=[c('花見のピクニック','Blossom picnic','はなみのぴくにっく'),c('川辺の釣り散歩','Riverside fishing walk','かわべのつりさんぽ'),c('遺跡の星見会','Stargazing at the ruins','いせきのほしみかい'),c('森のスケッチ旅','Forest sketching trip','もりのすけっちたび'),c('雪原のお茶会','Snowfield tea party','せつげんのおちゃかい'),c('砂丘のお宝探し','Dune treasure hunt','さきゅうのおたからさがし')];
export const FAMILY_STAGES=[c('赤ちゃん','Baby','あかちゃん'),c('幼児','Toddler','ようじ'),c('子ども','Child','こども'),c('旅立ちの準備','Ready to travel','たびだちのじゅんび')];
export const OUTING_SCENES=[
 [c('花びらの道で、お弁当を広げる場所を探す。','On a petal-lined path, find a place for your picnic.','はなびらのみちで、おべんとうをひろげるばしょをさがす。'),c('風がスケッチ帳をめくった。ふたりで何を描こう？','The breeze turns a sketchbook page. What will you draw together?','かぜがすけっちちょうをめくった。ふたりでなにをえがこう？'),c('帰り道、見つけた花をどうしよう？','What will you do with the flower you found on the way home?','かえりみち、みつけたはなをどうしよう？')],
 [c('川辺に到着。釣り糸を投げる場所を選ぼう。','You reach the river. Choose where to cast.','かわべにとうちゃく。つりいとをなげるばしょをえらぼう。'),c('水面がきらりと光った。魚か、宝物か？','Something flashes in the water. A fish or a treasure?','すいめんがきらりとひかった。さかなか、たからものか？'),c('夕方の川を見ながら、今日の話をしよう。','Share stories beside the river at sunset.','ゆうがたのかわをみながら、きょうのはなしをしよう。')],
 [c('遺跡の階段を上がると、最初の星が見えた。','The first star appears above the ruin steps.','いせきのかいだんをあがると、さいしょのほしがみえた。'),c('古い石に、星座のような模様がある。','An old stone bears a constellation-like pattern.','ふるいいしに、せいざのようなもようがある。'),c('流れ星！ どんな願いを話そう？','A shooting star! What wish will you share?','ながれぼし！どんなねがいをはなそう？')],
 [c('森の小道がふたつに分かれた。','The forest path splits in two.','もりのこみちがふたつにわかれた。'),c('木の陰に、不思議な形のキノコを見つけた。','You find an oddly shaped mushroom in the shade.','きのかげに、ふしぎなかたちのきのこをみつけた。'),c('完成した絵に、ふたりの印を残そう。','Leave both your marks on the finished sketch.','かんせいしたえに、ふたりのしるしをのこそう。')],
 [c('雪の広場で、お茶を飲める場所を探そう。','Find a place for tea in the snowy clearing.','ゆきのひろばで、おちゃをのめるばしょをさがそう。'),c('雪だるまの鼻にぴったりのものは？','What would make a perfect snowman nose?','ゆきだるまのはなにぴったりのものは？'),c('温かいカップを持って、冬の音を聞こう。','Hold a warm cup and listen to winter.','あたたかいかっぷをもって、ふゆのおとをきこう。')],
 [c('砂丘の地図に、古い道しるべが描かれている。','A dune map shows an old trail marker.','さきゅうのちずに、ふるいみちしるべがえがかれている。'),c('砂から小さな箱が見つかった。','A small box emerges from the sand.','すなからちいさなはこがみつかった。'),c('今日のお宝を分け合おう。','Share the treasures you found today.','きょうのおたからをわけあおう。')]
];
export const OUTING_CHOICES=[c('ゆっくり観察する','Observe carefully','ゆっくりかんさつする'),c('一緒に挑戦する','Try it together','いっしょにちょうせんする'),c('面白い話をする','Share a funny story','おもしろいはなしをする')];
export const OUTING_ENDINGS=[c('静かな時間に、お互いの新しい一面を見つけた。','Quiet moments reveal new sides of each other.','しずかなじかんに、おたがいのあたらしいいちめんをみつけた。'),c('ちょっとした冒険を乗り越えて、ふたりの絆が深まった。','A small adventure strengthens your bond.','ちょっとしたぼうけんをのりこえて、ふたりのきずながふかまった。'),c('笑いすぎて、今日の景色まで忘れられない思い出になった。','So much laughter makes the scenery unforgettable.','わらいすぎて、きょうのけしきまでわすれられないおもいでになった。')];
export const QUEST_STORIES:Record<string,Copy[]>={
 food:[c('おなかがすいた住人が、あなたの手料理を楽しみにしている。','A hungry resident is looking forward to your cooking.','おなかがすいたじゅうにんが、あなたのてりょうりをたのしみにしている。'),c('好きな味を探す試食会。新しい料理をひとつ届けよう。','A tasting party seeks new flavors. Bring a freshly prepared dish.','すきなあじをさがすししょくかい。あたらしいりょうりをひとつとどけよう。'),c('忙しい友達のために、今日の食卓を手伝おう。','Help a busy friend put dinner on the table.','いそがしいともだちのために、きょうのしょくたくをてつだおう。')],
 flower:[c('季節の花で、窓辺を明るく飾りたいそうだ。','They want to brighten a windowsill with seasonal flowers.','きせつのはなで、まどべをあかるくかざりたいそうだ。'),c('大切な友達へ贈る花を、一緒に探してほしい。','Help choose a flower for an important friend.','たいせつなともだちへおくるはなを、いっしょにさがしてほしい。'),c('押し花の手帳に、まだない花のページを作ろう。','Make a pressed-flower page for a missing species.','おしばなのてちょうに、まだないはなのぺーじをつくろう。')],
 material:[c('小さな修理の材料が足りない。少し分けてあげよう。','A small repair needs supplies. Share a few materials.','ちいさなしゅうりのざいりょうがたりない。すこしわけてあげよう。'),c('みんなの集まる場所を整える準備が始まった。','Preparations begin to improve a shared gathering place.','みんなのあつまるばしょをととのえるじゅんびがはじまった。'),c('工作の練習に使う材料を探している。','They are looking for materials to practice crafting.','こうさくのれんしゅうにつかうざいりょうをさがしている。')],
 talk:[c('新しい話題を探す住人に、お気に入りの言葉を聞かせよう。','Share a favorite phrase with a resident seeking a new topic.','あたらしいわだいをさがすじゅうにんに、おきにいりのことばをきかせよう。'),c('少しさみしい日は、何気ないおしゃべりがうれしい。','A casual conversation brightens a lonely day.','すこしさみしいひは、なにげないおしゃべりがうれしい。'),c('今日の不思議な出来事を、友達と話してみよう。','Talk with a friend about something unusual today.','きょうのふしぎなできごとを、ともだちとはなしてみよう。')],
 outing:[c('家の外で、いつもと違う景色を一緒に見たい。','See a different view together outside the house.','いえのそとで、いつもとちがうけしきをいっしょにみたい。'),c('三つの小さな選択が、忘れられない思い出になる。','Three small choices can make an unforgettable memory.','みっつのちいさなせんたくが、わすれられないおもいでになる。'),c('行ってみたかった場所へ、友達を誘ってみよう。','Invite a friend somewhere you have always wanted to visit.','いってみたかったばしょへ、ともだちをさそってみよう。')],
 dream:[c('住人は、夢の世界から届く話を聞きたがっている。','A resident wants to hear a story from the dream world.','じゅうにんは、ゆめのせかいからとどくはなしをききたがっている。'),c('夢の道しるべは、順番を守ると道を開くという。','Dream guideposts open a path when visited in order.','ゆめのみちしるべは、じゅんばんをまもるとみちをひらくという。'),c('不思議な景色の中で、今日だけの記念品を探そう。','Find today’s keepsake among strange dream scenery.','ふしぎなけしきのなかで、きょうだけのきねんひんをさがそう。')],
 cook:[c('腕前を磨くため、家の作業台で新しく一皿作ろう。','Improve your skill by cooking a dish at your home workbench.','うでまえをみがくため、いえのさぎょうだいであたらしくひとさらつくろう。'),c('光るタイミングを合わせて、香りのよい料理を仕上げよう。','Time your taps to finish an aromatic dish.','ひかるたいみんぐをあわせて、かおりのよいりょうりをしあげよう。'),c('食卓に新しい話題を増やす、料理の挑戦だ。','Try cooking to bring a new conversation to the dinner table.','しょくたくにあたらしいわだいをふやす、りょうりのちょうせんだ。')],
 decorate:[c('家の空いている場所に、好きな家具を飾ってみよう。','Display a favorite furnishing in an empty part of your house.','いえのあいているばしょに、すきなかぐをかざってみよう。'),c('友達を招く前に、部屋にひとつ彩りを増やしたい。','Add a touch of color before inviting friends over.','ともだちをまねくまえに、へやにひとついろどりをふやしたい。'),c('集めた思い出を、家に飾る形へ変えてみよう。','Turn collected memories into decorations for your home.','あつめたおもいでを、いえにかざるかたちへかえてみよう。')],
 fish:[c('今日の川の様子を、釣果で教えてほしいそうだ。','They want to know how the river is today through your catch.','きょうのかわのようすを、ちょうかでおしえてほしいそうだ。'),c('水辺の静かな時間を楽しみ、新しい一匹を釣ろう。','Enjoy a quiet moment by the water and catch a fish.','みずべのしずかなじかんをたのしみ、あたらしいいっぴきをつろう。'),c('料理の話から、川魚の話題で盛り上がった。','A cooking conversation turned into an interest in river fish.','りょうりのはなしから、かわざかなのわだいでもりあがった。')],
 clean:[c('部屋が散らかって、気分が落ち着かない。順番に片づけよう。','A messy room feels unsettled. Tidy it in order.','へやがちらかって、きぶんがおちつかない。じゅんばんにかたづけよう。'),c('番号を覚えて片づける、頭の体操をしてみよう。','Remember the numbers for a tidying brain teaser.','ばんごうをおぼえてかたづける、あたまのたいそうをしてみよう。'),c('気持ちのよい家で、新しい一日を迎えたい。','Welcome a new day in a comfortable home.','きもちのよいいえで、あたらしいいちにちをむかえたい。')]
};
