import {occupiedCityTile} from '../city/model';
import {residentsOf,type CreatedResident} from './residents';
import {validHero,type CustomHero} from '../customHero';
import {validConversationVoice,type ConversationVoice} from '../conversationVoice';
import {RESIDENTS as BASE_RESIDENTS} from './catalog';
import {validLearnedWord,conversationFromWords,type LearnedWord} from '../learnedWords';
import type {World,Adventurer} from '../engine';
import {WIDTH,HEIGHT} from '../engine';
import {biomeAt} from '../biomes';
import {lifePlayer,isResourceTile,canAfford,interiorOf,lifeWalkable} from '../life';
import {energyOf,GATHER_ENERGY_MAX} from '../energy';
import {socialNear,newSocial,relation} from '../social';
import {pendingMutation} from '../activities';
import {furnishing} from '../homeCatalog';
import {c,FLOWERS,flowerById,DISHES,dishById,RESIDENTS,DREAMS,DAY_SECONDS,SEASON_DAYS,YEAR_DAYS,OUTING_SCENES,OUTING_ENDINGS,type Copy,type FoodTag} from './catalog';
export interface TownPerson {words?:LearnedWord[];id:string;name:string;personality:number;birthday:number;hunger:number;happiness:number;comfort:number;favorite:FoodTag;disliked:FoodTag;tastes:Record<string,number>;flowers:Record<string,number>;flowerBook:Record<string,{count:number;best:number;day:number}>;foods:Record<string,{normal:number;perfect:number}>;cooked:Record<string,number>;souvenirs:number[];routine:number;lastInteraction:number;dreamDay:number;festivalDays:number[];questsDone:number;autoLife:boolean}
export interface TownBond {people:[string,string];friendship:number;lastTalk:number;conflict?:{reason:Copy;day:number;attempts:number};houseId?:string;visitHouse?:{id:string;day:number};marriedDay?:number}
export interface TownNews {id:string;day:number;kind:string;people:string[];headline:Copy;text:Copy;picture?:{kind:'flower'|'food'|'resident'|'dream';id:string};at:number}
export interface GardenPlot {owner:string;slot:number;flower:string;plantedDay:number;wateredDay:number;waterings:number;quality:number}
export interface TownQuest {id:string;owner:string;resident:string;kind:'food'|'flower'|'material'|'talk'|'outing'|'dream'|'cook'|'decorate'|'fish'|'clean';variant:number;day:number;done:boolean;item?:string;amount:number;baseline:number;reward:number}
export interface TownInvite {id:string;from:string;to:string;kind:'outing'|'visit'|'family';outing?:number;expires:number}
export interface TownFamily {id:string;parents:[string,string];name:string;bornDay:number;care:number;careDays:number[];travel?:{route:number;departDay:number;lastLetterDay:number;letters:number;returned?:boolean};claimedStages:number[]}
export interface DreamRun {theme:number;day:number;x:number;y:number;next:number;tiles:number[];order:number[];found:number[];finished:boolean}
export interface CookingRun {dish:string;started:number;step:number;score:number;last:number}
export interface TownOuting {id:string;people:[string,string];route:number;step:number;answers:Record<string,number>;choices:number[];done:boolean}
export interface TownState {customResidents?:CreatedResident[];outings:TownOuting[];version:1;elapsed:number;lastTime:number;bucket:number;day:number;people:Record<string,TownPerson>;bonds:TownBond[];news:TownNews[];memories:Record<string,TownNews[]>;quests:TownQuest[];garden:GardenPlot[];picked:Record<number,number>;invites:TownInvite[];families:TownFamily[];dreams:Record<string,DreamRun>;cooking:Record<string,CookingRun>;cleaning:Record<string,{order:number[];next:number;day:number}>;sequence:number;marriageDays:Record<string,number>;giftDays:Record<string,number>}
export type TownAction=
 |{type:'town-resident-create';name:string;portrait:string;personality:number;birthday:number;hero?:CustomHero;voice:ConversationVoice}
 |{type:'town-resident-edit';id:string;name:string;personality:number;birthday:number;voice:ConversationVoice}
 |{type:'town-word-teach';target:string;word:LearnedWord}|{type:'town-word-forget';target:string;text:string}
 |{type:'town-outing-choice';id:string;choice:number}|{type:'town-outing-leave';id:string}
 |{type:'town-flower-pick';tile:number}
 |{type:'town-plant';flower:string;slot:number}|{type:'town-water'|'town-harvest';slot:number}
 |{type:'town-cook-start';dish:string}|{type:'town-cook-tap'|'town-cook-cancel'}
 |{type:'town-meal';dish:string;target:string}|{type:'town-gift';flower:string;target:string}
 |{type:'town-profile';personality:number;birthday:number;autoLife:boolean}
 |{type:'town-talk'|'town-apologize'|'town-mediate';target:string}
 |{type:'town-quest';id:string}
 |{type:'town-invite';target:string;kind:TownInvite['kind'];outing?:number}
 |{type:'town-answer';id:string;accept:boolean}
 |{type:'town-resident-home'|'town-resident-marry';target:string}
 |{type:'town-resident-end';target:string;kind:'cohabit'|'marry'}
 |{type:'town-dream-start'|'town-dream-exit'}|{type:'town-dream-move';dx:number;dy:number}
 |{type:'town-clean-start'}|{type:'town-clean';index:number}
 |{type:'town-festival'|'town-rest'}
 |{type:'town-family-name';id:string;name:string}|{type:'town-family-care';id:string;activity:'play'|'meal'|'read'}
 |{type:'town-family-travel';id:string;route:number}|{type:'town-family-letter'|'town-family-return';id:string}
 |{type:'town-memory';event:string}|{type:'town-decor';item:string;flower?:string};
export const hash=(value:string,seed=0)=>{let n=seed|0;for(let i=0;i<value.length;i++)n=Math.imul(n^value.charCodeAt(i),16777619);return n>>>0;};
export const newTown=(time=0):TownState=>({version:1,outings:[],elapsed:0,lastTime:time,bucket:-1,day:0,people:{},bonds:[],news:[],memories:{},quests:[],garden:[],picked:{},invites:[],families:[],dreams:{},cooking:{},cleaning:{},sequence:0,marriageDays:{},giftDays:{}});
export function townOf(w:World){return w.town??=newTown(w.life.time);}
export function personOf(w:World,id:string){if(typeof id!=='string'||!id||id.length>80||['__proto__','prototype','constructor'].includes(id))return undefined;const s=townOf(w);s.outings??=[];if(s.people[id]){if(w.players[id])s.people[id].name=w.players[id].hero?.name||w.players[id].name;const child=s.families.find(f=>f.id===id);if(child)s.people[id].name=child.name;return s.people[id];}const npc=residentsOf(w).find(r=>r.id===id),p=Object.hasOwn(w.players,id)?w.players[id]:undefined,child=s.families.find(f=>f.id===id&&s.day-f.bornDay>=12);if(!npc&&!p&&!child)return undefined;const n=hash(id,w.seed),tags:FoodTag[]=['fish','sweet','herb','spicy','warm','fresh'];return s.people[id]={id,name:p?.hero?.name||p?.name||child?.name||npc!.name.ja,personality:npc?.personality??n%8,birthday:child?child.bornDay%YEAR_DAYS:n%YEAR_DAYS,hunger:75,happiness:60,comfort:70,favorite:tags[n%6],disliked:tags[(n%6+3)%6],tastes:{},flowers:{},flowerBook:{},foods:{},cooked:{},souvenirs:[],routine:0,lastInteraction:0,dreamDay:-1,festivalDays:[],questsDone:0,autoLife:true};}
export const calendar=(w:World)=>{const s=w.town,day=s?.day||0;return {day,year:1+Math.floor(day/YEAR_DAYS),season:Math.floor(day/SEASON_DAYS)%4,date:day%SEASON_DAYS+1,phase:Math.floor(((s?.elapsed||0)%DAY_SECONDS)/DAY_SECONDS*4),weather:hash(String(day),w.seed)%5};};
export function flowerAt(w:World,tile:number){if(occupiedCityTile(w,tile))return undefined;if(!isResourceTile(w,tile)||w.tiles[tile]!=='grass')return undefined;const {season,day}=calendar(w),n=hash(String(tile),w.seed);if(n%17!==0||w.town?.picked[tile]===day||w.sites.some(s=>s.x===tile%WIDTH&&s.y===Math.floor(tile/WIDTH))||w.life.houses.some(h=>h.x===tile%WIDTH&&h.y===Math.floor(tile/WIDTH)))return undefined;const biome=biomeAt(tile%WIDTH,Math.floor(tile/WIDTH)).id,options=FLOWERS.filter(f=>f.season===season&&(f.biome===biome||(f.rarity===1&&f.biome==='meadow')));return options[(n>>>8)%options.length];}
export function nearbyFlowers(w:World,p:Adventurer){const results:Array<{tile:number;flower:NonNullable<ReturnType<typeof flowerAt>>}>=[];for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){if(Math.abs(dx)+Math.abs(dy)>2)continue;const tile=(p.y+dy)*WIDTH+p.x+dx,f=flowerAt(w,tile);if(f)results.push({tile,flower:f});}return results;}
function event(w:World,kind:string,people:string[],headline:Copy,text:Copy,picture?:TownNews['picture'],now=w.life.now){people=[...new Set(people)];const s=townOf(w),news={id:`town-news-${++s.sequence}`,day:s.day,kind,people,headline,text,picture,at:now};s.news.push(news);s.news=s.news.slice(-120);for(const id of people){const list=s.memories[id]??=[];list.push(news);s.memories[id]=list.slice(-160);}w.revision++;return news;}
function say(w:World,people:string[],lines:Copy[],now:number){const s=w.social??=newSocial();s.talks.push({id:`town-talk-${++s.sequence}`,at:now,people,quirky:lines.some(l=>/枕|pillow/.test(l.ja)),lines:lines.map((line,i)=>({speaker:people[i%people.length],text:line.ja,english:line.en,hiragana:line.hi}))});s.talks=s.talks.slice(-30);w.revision++;}
function bondOf(w:World,a:string,b:string){const s=townOf(w);let r=s.bonds.find(r=>r.people.includes(a)&&r.people.includes(b));if(!r){r={people:[a,b],friendship:relation(w,a,b)?.friendship||0,lastTalk:0};s.bonds.push(r);}return r;}
function increaseBond(w:World,a:string,b:string,n:number){const r=bondOf(w,a,b);r.friendship=Math.max(0,Math.min(100,r.friendship+n));const old=relation(w,a,b);if(old)old.friendship=Math.max(0,Math.min(100,old.friendship+n));return r;}
export function visibleFriendship(w:World,a:string,b:string){return Math.max(relation(w,a,b)?.friendship||0,w.town?.bonds.find(r=>r.people.includes(a)&&r.people.includes(b))?.friendship||0);}
const questKinds:TownQuest['kind'][]=['food','flower','material','talk','outing','dream','cook','decorate','fish','clean'];
function questsFor(w:World,id:string){const s=townOf(w),person=personOf(w,id)!;if(s.quests.some(q=>q.owner===id&&q.day===s.day))return;for(let i=0;i<4;i++){const n=hash(`${id}:${s.day}:${i}`,w.seed),kind=questKinds[(s.day*4+i)%questKinds.length],resident=residentsOf(w)[n%residentsOf(w).length].id;const item=kind==='flower'?FLOWERS.filter(f=>f.season===calendar(w).season)[n%10].id:kind==='material'?['wood','stone','herb','fish','ore','reed'][n%6]:kind==='food'?DISHES.filter(d=>d.tags.includes(personOf(w,resident)!.favorite))[n%DISHES.filter(d=>d.tags.includes(personOf(w,resident)!.favorite)).length].id:undefined;const baseline=kind==='cook'?Object.values(person.cooked).reduce((a,b)=>a+b,0):kind==='fish'?Object.values(w.players[id]?.life?.fishRecords||{}).reduce((a,b)=>a+b.count,0):kind==='decorate'?w.life.houses.find(h=>h.owner===id)?.interior?.placed.length||0:0;s.quests.push({id:`quest-${id}-${s.day}-${i}`,owner:id,resident,kind,variant:n%6,day:s.day,done:false,item,amount:kind==='material'?2:1,baseline,reward:8+i*2});}s.quests=s.quests.filter(q=>s.day-q.day<7);}
function recordFlower(w:World,id:string,flower:string,quality:number,amount=1){const p=personOf(w,id)!,s=townOf(w);p.flowers[flower]=(p.flowers[flower]||0)+amount;const record=p.flowerBook[flower]??={count:0,best:0,day:s.day};record.count+=amount;record.best=Math.max(record.best,quality);record.day=s.day;}
function consumeFood(p:TownPerson,dish:string){const stack=p.foods[dish];if(!stack)return -1;if(stack.perfect>0){stack.perfect--;return 1;}if(stack.normal>0){stack.normal--;return 0;}return -1;}
export const hasFood=(p:TownPerson|undefined,id:string)=>!!p&&((p.foods[id]?.normal||0)+(p.foods[id]?.perfect||0))>0;
function busy(w:World,p:Adventurer){return !!(p.spectator||p.nativeScene||p.life?.work||p.duelId||p.dungeonId||p.arcadePending||pendingMutation(p)||w.activities.trades.some(t=>t.from===p.id||t.to===p.id)||Object.values(w.life.games).some(g=>g.phase==='playing'&&g.players.includes(p.id)));}
function reachable(w:World,p:Adventurer,id:string){return !!residentsOf(w).find(r=>r.id===id)||!!w.town?.families.some(f=>f.id===id&&f.parents.includes(p.id)&&w.town!.day-f.bornDay>=12)||!!w.players[id]&&socialNear(p,w.players[id]);}
function married(w:World,a:string,b:string){return !!relation(w,a,b)?.married||townOf(w).bonds.some(r=>r.people.includes(a)&&r.people.includes(b)&&r.marriedDay!==undefined);}
function family(w:World,a:string,b:string){const s=townOf(w);if(!married(w,a,b)||s.families.some(f=>f.parents.includes(a)||f.parents.includes(b))||s.families.length>=40)return false;const f:TownFamily={id:`family-${++s.sequence}`,parents:[a,b],name:'ルミ',bornDay:s.day,care:0,careDays:[],claimedStages:[]};s.families.push(f);increaseBond(w,a,f.id,30);increaseBond(w,b,f.id,30);event(w,'family',f.parents,c('新しい家族がやってきた','A new family member arrives','あたらしいかぞくがやってきた'),c('ふたりの家に小さな笑顔。名前を決めて、いっしょに育てよう。','A little smile joins your home. Choose a name and raise the child together.','ふたりのいえにちいさなえがお。なまえをきめて、いっしょにそだてよう。'));return true;}
function completeOuting(w:World,a:string,b:string,route:number){const s=townOf(w);s.outings??=[];if(s.outings.some(o=>!o.done&&(o.people.includes(a)||o.people.includes(b))))return;s.outings.push({id:`outing-${++s.sequence}`,people:[a,b],route,step:0,answers:{},choices:[],done:false});s.outings=s.outings.slice(-60);w.revision++;}
function finishOuting(w:World,a:string,b:string,route:number,ending=0){const s=townOf(w);increaseBond(w,a,b,8);for(const id of [a,b]){const p=personOf(w,id)!;p.happiness=Math.min(100,p.happiness+8);}event(w,'outing',[a,b],c('ふたりのお出かけ','An outing together','ふたりのおでかけ'),OUTING_ENDINGS[ending],{kind:'resident',id:residentsOf(w).find(r=>r.id===b)?.id||a});s.giftDays[`outing:${a}:${b}`]=s.day;for(const q of s.quests)if(q.owner===a&&q.kind==='outing'&&q.day===s.day)q.baseline=1;}
export function applyTown(w:World,p:Adventurer,a:TownAction,now:number):boolean {
 if(!w.started||w.ended||busy(w,p))return false;const s=townOf(w),me=personOf(w,p.id)!;for(const npc of residentsOf(w))personOf(w,npc.id);questsFor(w,p.id);const tell=(ja:string)=>{p.message=ja;w.revision++;return true;};
 // A running dream or cooking sequence owns its input until it is completed or cancelled.
 if(s.dreams[p.id]&&!s.dreams[p.id].finished&&!a.type.startsWith('town-dream'))return false;
 if(s.cooking[p.id]&&!['town-cook-tap','town-cook-cancel'].includes(a.type))return false;
 if(a.type==='town-resident-create'||a.type==='town-resident-edit'){
  if(typeof a.name!=='string'||!a.name.trim()||a.name.length>16||/[\u0000-\u001f]/.test(a.name)||!Number.isInteger(a.personality)||a.personality<0||a.personality>7||!Number.isInteger(a.birthday)||a.birthday<0||a.birthday>=28||!validConversationVoice(a.voice))return false;
  const residents=s.customResidents??=[];if(a.type==='town-resident-create'){if(residents.length>=16||a.hero!==undefined&&!validHero(a.hero)||!(BASE_RESIDENTS.some(r=>r.portrait===a.portrait)||a.hero&&a.portrait===a.hero.portrait))return false;const id=`resident-custom-${++s.sequence}`;const positions=Array.from({length:81},(_,i)=>({x:p.x+i%9-4,y:p.y+Math.floor(i/9)-4})).filter(q=>(q.x!==p.x||q.y!==p.y)&&lifeWalkable(w,q.x,q.y)&&!residents.some(r=>r.x===q.x&&r.y===q.y));positions.sort((a,b)=>Math.abs(a.x-p.x)+Math.abs(a.y-p.y)-Math.abs(b.x-p.x)-Math.abs(b.y-p.y));const spot=positions[0]||p;residents.push({id,owner:p.id,name:a.name.trim(),portrait:a.portrait,personality:a.personality,birthday:a.birthday,hero:a.hero?structuredClone(a.hero):undefined,voice:{...a.voice},x:spot.x,y:spot.y});const person=personOf(w,id)!;person.personality=a.personality;person.birthday=a.birthday;}
  else{const index=residents.findIndex(r=>r.id===a.id&&r.owner===p.id);if(index<0)return false;residents[index]={...residents[index],name:a.name.trim(),personality:a.personality,birthday:a.birthday,voice:{...a.voice}};const person=personOf(w,a.id)!;person.name=a.name.trim();person.personality=a.personality;person.birthday=a.birthday;}
  w.revision++;return true;
 }
 if(a.type==='town-outing-leave'){const outing=s.outings.find(o=>o.id===a.id&&!o.done&&o.people.includes(p.id));if(!outing)return false;outing.done=true;return tell('お出かけを切り上げました。また今度誘ってみましょう。');}
 if(a.type==='town-outing-choice'){const outing=s.outings.find(o=>o.id===a.id&&!o.done&&o.people.includes(p.id));if(!outing||!Number.isInteger(a.choice)||a.choice<0||a.choice>=3||outing.answers[p.id]!==undefined)return false;outing.answers[p.id]=a.choice;for(const id of outing.people)if(residentsOf(w).some(r=>r.id===id)||s.families.some(f=>f.id===id))outing.answers[id]=(personOf(w,id)!.personality+outing.step)%3;if(outing.people.every(id=>outing.answers[id]!==undefined)){outing.choices.push(outing.answers[p.id]);outing.step++;outing.answers={};if(outing.step===3){outing.done=true;finishOuting(w,...outing.people,outing.route,outing.choices.reduce((a,b)=>a+b,0)%3);const lp=lifePlayer(p);lp.bag[outing.route===1?'fish':outing.route===5?'ore':'herb']=(lp.bag[outing.route===1?'fish':outing.route===5?'ore':'herb']||0)+1;}}w.revision++;return true;}
 if(a.type==='town-word-teach'||a.type==='town-word-forget'){
  const target=personOf(w,a.target);if(!target||(a.target!==p.id&&(!reachable(w,p,a.target)||!!w.players[a.target])))return false;
  const words=target.words??=[];
  if(a.type==='town-word-teach'){if(!validLearnedWord(a.word))return false;const word={text:a.word.text.trim(),reading:a.word.reading.trim(),genre:a.word.genre},index=words.findIndex(v=>v.text===word.text);if(index<0&&words.length>=32)return false;if(index>=0)words[index]=word;else words.push(word);}
  else {if(typeof a.text!=='string')return false;const index=words.findIndex(v=>v.text===a.text);if(index<0)return false;words.splice(index,1);}
  w.revision++;return true;
 }
 if(a.type==='town-profile'){if(!Number.isInteger(a.personality)||a.personality<0||a.personality>=8||!Number.isInteger(a.birthday)||a.birthday<0||a.birthday>=YEAR_DAYS||typeof a.autoLife!=='boolean')return false;me.personality=a.personality;me.birthday=a.birthday;me.autoLife=a.autoLife;return tell('暮らしの性格と誕生日を設定しました。');}
 if(a.type==='town-flower-pick'){if(p.life?.indoors||!Number.isInteger(a.tile)||Math.abs(a.tile%WIDTH-p.x)+Math.abs(Math.floor(a.tile/WIDTH)-p.y)>2)return false;const f=flowerAt(w,a.tile),lp=lifePlayer(p);if(!f||energyOf(lp)<1)return tell('花がないか、採取エネルギーが足りません。');lp.energy=energyOf(lp)-1;s.picked[a.tile]=s.day;const first=!me.flowerBook[f.id],quality=60+hash(`${a.tile}:${s.day}`,w.seed)%41;recordFlower(w,p.id,f.id,quality);if(first)event(w,'flower',[p.id],c('花図鑑に新しいページ','A new flower-book page','はなずかんにあたらしいぺーじ'),f.name,{kind:'flower',id:f.id});return tell('花を摘みました。種も残して、花壇で育てられます。');}
 if(a.type==='town-plant'){const f=flowerById(a.flower);if(!f||!Number.isInteger(a.slot)||a.slot<0||a.slot>=6||!w.life.houses.some(h=>h.owner===p.id)||!me.flowers[f.id]||s.garden.some(g=>g.owner===p.id&&g.slot===a.slot))return false;me.flowers[f.id]--;s.garden.push({owner:p.id,slot:a.slot,flower:f.id,plantedDay:s.day,wateredDay:-1,waterings:0,quality:60});return tell('花壇に植えました。季節に合う花は2日、それ以外は3日で育ちます。');}
 if(a.type==='town-water'){const plot=s.garden.find(g=>g.owner===p.id&&g.slot===a.slot);if(!plot||plot.wateredDay===s.day)return false;plot.wateredDay=s.day;plot.waterings++;plot.quality=Math.min(100,60+plot.waterings*12);return tell('花に水をあげました。今日の水やり完了です。');}
 if(a.type==='town-harvest'){const i=s.garden.findIndex(g=>g.owner===p.id&&g.slot===a.slot);if(i<0)return false;const plot=s.garden[i],f=flowerById(plot.flower)!;if(s.day-plot.plantedDay<(f.season===calendar(w).season?2:3)||plot.waterings<2)return false;s.garden.splice(i,1);recordFlower(w,p.id,f.id,plot.quality,plot.quality>=84?3:2);return tell('育てた花を収穫しました。花図鑑の品質記録も更新します。');}
 if(a.type==='town-cook-start'){const dish=dishById(a.dish),lp=lifePlayer(p),home=w.life.houses.find(h=>h.id===lp.indoors);if(!dish||!home||!interiorOf(home).placed.some(f=>['stove','fireplace','workbench'].includes(f.item))||!canAfford(lp.bag,dish.cost)||Object.values(me.foods).reduce((n,x)=>n+x.normal+x.perfect,0)>=60)return tell('家の作業台・ストーブで料理できます。材料と持ち物の空きを確認してください。');for(const [key,n]of Object.entries(dish.cost))lp.bag[key as keyof typeof lp.bag]=(lp.bag[key as keyof typeof lp.bag]||0)-n!;s.cooking[p.id]={dish:dish.id,started:now,step:0,score:0,last:now-300};w.revision++;return true;}
 if(a.type==='town-cook-cancel'){if(!s.cooking[p.id])return false;delete s.cooking[p.id];return tell('調理を中断しました。使った材料は戻りません。');}
 if(a.type==='town-cook-tap'){const run=s.cooking[p.id];if(!run||now-run.last<250)return false;const phase=((now-run.started)%1600)/1600;run.score+=Math.abs(phase-.5)<.16?1:0;run.step++;run.last=now;run.started=now;if(run.step<3){w.revision++;return true;}const perfect=run.score>=2,dish=dishById(run.dish)!,stack=me.foods[dish.id]??={normal:0,perfect:0};if(perfect)stack.perfect++;else stack.normal++;me.cooked[dish.id]=(me.cooked[dish.id]||0)+1;delete s.cooking[p.id];event(w,'cooking',[p.id],c(perfect?'料理が大成功！':'料理ができました',perfect?'Perfect cooking!':'A dish is ready',perfect?'りょうりがだいせいこう！':'りょうりができました'),dish.name,{kind:'food',id:dish.id});return tell('料理ができました。食べたり、住人へ贈ったりできます。');}
 if(a.type==='town-meal'){const dish=dishById(a.dish),target=personOf(w,a.target);if(!dish||!target||(a.target!==p.id&&!reachable(w,p,a.target)))return false;const perfect=consumeFood(me,dish.id);if(perfect<0)return false;const taste=dish.tags.includes(target.favorite)?2:dish.tags.includes(target.disliked)?-1:0;target.tastes[dish.id]=taste;target.hunger=Math.min(100,target.hunger+dish.nourish);target.happiness=Math.max(0,Math.min(100,target.happiness+(taste===2?10:taste===-1?-3:3)+perfect*3));if(a.target!==p.id)increaseBond(w,p.id,a.target,taste===2?6:taste===-1?1:3);const response=taste===2?c('これ、大好物！ また食べたいな。','This is my favorite! I would love it again.','これ、だいこうぶつ！またたべたいな。'):taste<0?c('ちょっと苦手だけど、作ってくれてありがとう。','Not quite my taste, but thank you for cooking.','ちょっとにがてだけど、つくってくれてありがとう。'):c('おいしいね。いっしょに食べるともっと楽しい。','Delicious. Sharing a meal makes it even better.','おいしいね。いっしょにたべるともっとたのしい。');say(w,[p.id,a.target], [dish.name,response],now);event(w,'meal',[p.id,a.target],c('今日の食卓','At the table today','きょうのしょくたく'),response,{kind:'food',id:dish.id});return tell('食事を楽しみました。好みが図鑑に記録されます。');}
 if(a.type==='town-gift'){const f=flowerById(a.flower),target=personOf(w,a.target),key=`gift:${p.id}:${a.target}`;if(!f||!target||a.target===p.id||!reachable(w,p,a.target)||!me.flowers[f.id]||s.giftDays[key]===s.day)return false;me.flowers[f.id]--;s.giftDays[key]=s.day;increaseBond(w,p.id,a.target,f.rarity===3?8:5);target.happiness=Math.min(100,target.happiness+8);event(w,'gift',[p.id,a.target],c('花の贈り物','A gift of flowers','はなのおくりもの'),f.meaning,{kind:'flower',id:f.id});return tell('花を贈りました。贈り物で友好度が上がるのは1日1回です。');}
 if(a.type==='town-talk'){const target=personOf(w,a.target);if(!target||a.target===p.id||!reachable(w,p,a.target))return false;const r=bondOf(w,p.id,a.target);if(now-r.lastTalk<12000)return false;r.lastTalk=now;const quirky=(me.personality+target.personality+s.day)%5===0,phrase=p.memory?.phrases[(s.sequence)%Math.max(1,p.memory.phrases.length)]||'一緒に冒険しよう';const shared=c(`今日は「${phrase}」の話をしよう。`,`Let's talk about “${phrase}” today.`,`きょうは「${phrase}」のはなしをしよう。`),reply=quirky?c('それを枕にしたら、いい夢が見られるかな？','Would it make a nice pillow for good dreams?','それをまくらにしたら、いいゆめがみられるかな？'):[c('いいね。お茶を用意するから、ゆっくり聞かせて。','Sounds good. I will make tea; tell me at your own pace.','いいね。おちゃをよういするから、ゆっくりきかせて。'),c('面白そう！ 実際に見に行ったら、もっと発見がありそう。','Interesting! Visiting in person might lead to more discoveries.','おもしろそう！じっさいにみにいったら、もっとはっけんがありそう。'),c('まず確かめてから、順番に考えてみよう。','Let us check the facts and think it through step by step.','まずたしかめてから、じゅんばんにかんがえてみよう。'),c('その話、みんなにも聞かせたい！ 食事会にしようよ。','Everyone should hear this! Let us have a dinner party.','そのはなし、みんなにもきかせたい！しょくじかいにしようよ。'),c('小さなところを整えると、もっとよくなりそうだね。','Tidying the little details could make it even better.','ちいさなところをととのえると、もっとよくなりそうだね。'),c('夢の中で、それが空を飛んでいた気がするんだ。','I think I saw it flying through the sky in a dream.','ゆめのなかで、それがそらをとんでいたきがするんだ。'),c('一緒に試してみよう！ 失敗しても、次の工夫が見つかるよ。','Let us try together! Even a mistake can inspire a new approach.','いっしょにためしてみよう！しっぱいしても、つぎのくふうがみつかるよ。'),c('その景色を絵にして、忘れないようにしたいな。','I would like to paint that scene so I do not forget it.','そのけしきをえにして、わすれないようにしたいな。')][target.personality];const taught=conversationFromWords(p.id,a.target,me.words||[],target.words||[],s.sequence++,target.personality,quirky);if(taught){const social=w.social??=newSocial();social.talks.push({id:`town-talk-${++social.sequence}`,at:now,people:[p.id,a.target],quirky,lines:taught});social.talks=social.talks.slice(-30);w.revision++;}else say(w,[p.id,a.target],[shared,reply],now);increaseBond(w,p.id,a.target,r.conflict?1:4);me.happiness=Math.min(100,me.happiness+2);for(const q of s.quests)if(q.owner===p.id&&q.kind==='talk'&&q.day===s.day)q.baseline++;if(!r.conflict&&r.friendship>=15&&hash(`${s.day}:${r.people.join(':')}`,w.seed)%13===0&&me.autoLife&&target.autoLife){r.conflict={reason:c('言葉の意味を取り違えてしまった','A misunderstanding of words','ことばのいみをとりちがえてしまった'),day:s.day,attempts:0};increaseBond(w,p.id,a.target,-5);event(w,'conflict',r.people,c('ちょっとした行き違い','A small misunderstanding','ちょっとしたいきちがい'),r.conflict.reason);}return tell('おしゃべりを楽しみました。');}
 if(a.type==='town-apologize'||a.type==='town-mediate'){const r=s.bonds.find(r=>r.people.includes(p.id)&&r.people.includes(a.target));if(!r?.conflict||!reachable(w,p,a.target))return false;const target=personOf(w,a.target)!;r.conflict.attempts++;if(a.type==='town-mediate'){if(!s.bonds.some(b=>b!==r&&b.people.includes(p.id)&&b.friendship>=20))return tell('友好度20以上の別の友達に仲裁を頼めます。');}else if(r.conflict.attempts===1&&target.happiness<40)return tell('今は気持ちを落ち着かせたいようです。食事や休憩のあとにもう一度話そう。');delete r.conflict;increaseBond(w,p.id,a.target,8);event(w,'reconcile',r.people,c('仲直りできた！','Friends again!','なかなおりできた！'),c('気持ちを伝え合い、誤解がほどけた。','You share your feelings and clear up the misunderstanding.','きもちをつたえあい、ごかいがほどけた。'));return tell('仲直りしました。');}
 if(a.type==='town-resident-end'){const r=s.bonds.find(r=>r.people.includes(p.id)&&r.people.includes(a.target));if(!r||!residentsOf(w).some(n=>n.id===a.target)||!['cohabit','marry'].includes(a.kind))return false;if(a.kind==='marry'){if(r.marriedDay===undefined)return false;delete r.marriedDay;}else{if(!r.houseId)return false;delete r.houseId;}return tell('暮らしの関係を見直しました。思い出と家族の記録は残ります。');}
 if(a.type==='town-resident-home'||a.type==='town-resident-marry'){if(!residentsOf(w).some(r=>r.id===a.target))return false;const r=bondOf(w,p.id,a.target),home=w.life.houses.find(h=>h.owner===p.id);if(r.conflict||r.friendship<(a.type==='town-resident-home'?20:50)||!home)return false;if(a.type==='town-resident-home'){if(s.bonds.some(b=>b.houseId&&b!==r&&b.people.includes(a.target)))return false;r.houseId=home.id;}else{if(r.marriedDay!==undefined||s.bonds.some(b=>b.marriedDay!==undefined&&b!==r&&(b.people.includes(p.id)||b.people.includes(a.target)))||w.social?.relations.some(b=>b.married&&b.people.includes(p.id)))return false;r.marriedDay=s.day;r.houseId=home.id;}event(w,'relationship',r.people,c(a.type==='town-resident-home'?'同じ家で暮らそう':'これからも一緒に',a.type==='town-resident-home'?'A shared home':'Together from now on',a.type==='town-resident-home'?'おなじいえでくらそう':'これからもいっしょに'),c('住人がうれしそうにうなずいた。','The resident happily agrees.','じゅうにんがうれしそうにうなずいた。'));return tell('暮らしの関係が進みました。');}
 if(a.type==='town-invite'){if(!['outing','visit','family'].includes(a.kind)||a.target===p.id||!personOf(w,a.target)||s.invites.some(v=>v.from===p.id)||!Number.isInteger(a.outing??0)||(a.outing??0)<0||(a.outing??0)>=6)return false;const npc=residentsOf(w).some(r=>r.id===a.target)||s.families.some(f=>f.id===a.target&&f.parents.includes(p.id)&&s.day-f.bornDay>=12),key=`${a.kind}:${p.id}:${a.target}`;if(s.giftDays[key]===s.day)return false;if(a.kind==='family'&&(!married(w,p.id,a.target)||!w.life.houses.some(h=>h.owner===p.id||h.owner===a.target)))return false;if(a.kind==='visit'&&!w.life.houses.some(h=>h.owner===p.id))return false;if(npc){if(visibleFriendship(w,p.id,a.target)<(a.kind==='family'?50:10))return tell('もう少し仲良くなってから誘いましょう。');if(a.kind==='family'){if(!family(w,p.id,a.target))return false;}else if(a.kind==='outing')completeOuting(w,p.id,a.target,a.outing||0);else{bondOf(w,p.id,a.target).visitHouse={id:w.life.houses.find(h=>h.owner===p.id)!.id,day:s.day};event(w,'visit',[p.id,a.target],c('友達が遊びに来た','A friend comes to visit','ともだちがあそびにきた'),c('お茶とおしゃべりで、家がにぎやかになった。','Tea and conversation make the house lively.','おちゃとおしゃべりで、いえがにぎやかになった。'));}s.giftDays[key]=s.day;return tell('住人と新しい思い出ができました。');}if(!w.players[a.target]||busy(w,w.players[a.target])||s.invites.some(v=>v.to===a.target)||s.invites.length>=40)return false;s.invites.push({id:`town-invite-${++s.sequence}`,from:p.id,to:a.target,kind:a.kind,outing:a.outing,expires:now+60000});return tell('相手にお誘いを送りました。相手が選ぶまで待ちましょう。');}
 if(a.type==='town-answer'){if(typeof a.accept!=='boolean')return false;const inv=s.invites.find(v=>v.id===a.id&&v.to===p.id&&v.expires>now);if(!inv)return false;s.invites=s.invites.filter(v=>v.id!==a.id);if(!a.accept)return tell('今回はお誘いを見送りました。');const from=w.players[inv.from];if(!from||busy(w,from))return false;if(inv.kind==='family'){if(!family(w,inv.from,p.id))return false;}else if(inv.kind==='outing')completeOuting(w,inv.from,p.id,inv.outing||0);else event(w,'visit',[inv.from,p.id],c('家で待ち合わせ','A visit is arranged','いえでまちあわせ'),c('訪問を約束した。家へ歩いて向かおう。','You agree to visit. Walk over to the house.','ほうもんをやくそくした。いえへあるいてむかおう。'));s.giftDays[`${inv.kind}:${inv.from}:${p.id}`]=s.day;return tell('お誘いを受けました。');}
 if(a.type==='town-quest'){const q=s.quests.find(q=>q.id===a.id&&q.owner===p.id&&!q.done&&q.day===s.day);if(!q)return false;const lp=lifePlayer(p);let done=false;if(q.kind==='food')done=consumeFood(me,q.item!)>=0;else if(q.kind==='flower'){done=(me.flowers[q.item!]||0)>=q.amount;if(done)me.flowers[q.item!]-=q.amount;}else if(q.kind==='material'){const key=q.item as keyof typeof lp.bag;done=(lp.bag[key]||0)>=q.amount;if(done)lp.bag[key]=(lp.bag[key]||0)-q.amount;}else if(q.kind==='talk'||q.kind==='outing'||q.kind==='clean')done=q.baseline>=1;else if(q.kind==='dream')done=me.dreamDay===s.day&&!!s.dreams[p.id]?.finished;else if(q.kind==='cook')done=Object.values(me.cooked).reduce((a,b)=>a+b,0)>q.baseline;else if(q.kind==='fish')done=Object.values(lp.fishRecords||{}).reduce((a,b)=>a+b.count,0)>q.baseline;else if(q.kind==='decorate')done=(w.life.houses.find(h=>h.owner===p.id)?.interior?.placed.length||0)>q.baseline;if(!done)return tell('お願いの条件を達成してから報告しましょう。');q.done=true;const recipient=personOf(w,q.resident)!;recipient.happiness=Math.min(100,recipient.happiness+5);if(q.kind==='food')recipient.hunger=Math.min(100,recipient.hunger+(dishById(q.item!)?.nourish||20));me.questsDone++;me.happiness=Math.min(100,me.happiness+q.reward);increaseBond(w,p.id,q.resident,6);const f=FLOWERS[calendar(w).season*12+(q.variant%10)];recordFlower(w,p.id,f.id,80);lp.bag.herb=(lp.bag.herb||0)+1;event(w,'quest',[p.id,q.resident],c('お願いを解決！','A request fulfilled!','おねがいをかいけつ！'),c('お礼の花と薬草を受け取った。住人との距離が縮まった。','You receive a flower and herb. Your bond with the resident grows.','おれいのはなとやくそうをうけとった。じゅうにんとのきょりがちぢまった。'),{kind:'flower',id:f.id});return tell('お願いを達成しました。');}
 if(a.type==='town-dream-start'){if(!p.life?.indoors||me.dreamDay===s.day)return false;const home=w.life.houses.find(h=>h.id===p.life!.indoors);if(!home||!interiorOf(home).placed.some(f=>f.item==='bed'))return tell('家のベッドで夢を見られます。');const theme=hash(`${p.id}:${s.day}`,w.seed)%DREAMS.length,tiles=Array.from({length:81},(_,i)=>i%9===0||i%9===8||i<9||i>=72?1:0),order=[[20,24,60],[56,22,61],[22,58,60],[24,56,61]][theme%4];for(const tile of [30,39,48,32,41,50])tiles[tile]=1;s.dreams[p.id]={theme,day:s.day,x:4,y:7,next:0,tiles,order,found:[],finished:false};me.dreamDay=s.day;w.revision++;return true;}
 if(a.type==='town-dream-exit'){delete s.dreams[p.id];return tell('目を覚ましました。夢は1日に1回楽しめます。');}
 if(a.type==='town-dream-move'){const run=s.dreams[p.id];if(!run||run.finished||!Number.isInteger(a.dx)||!Number.isInteger(a.dy)||Math.abs(a.dx)+Math.abs(a.dy)!==1)return false;const x=run.x+a.dx,y=run.y+a.dy,tile=y*9+x;if(x<0||x>=9||y<0||y>=9||run.tiles[tile])return false;run.x=x;run.y=y;if(tile===run.order[run.next]){run.found.push(tile);run.next++;}if(run.next===3){run.finished=true;me.happiness=Math.min(100,me.happiness+15);if(!me.souvenirs.includes(run.theme))me.souvenirs.push(run.theme);recordFlower(w,p.id,FLOWERS[calendar(w).season*12+11].id,100);event(w,'dream',[p.id],c('不思議な夢のおみやげ','A souvenir from a strange dream','ふしぎなゆめのおみやげ'),DREAMS[run.theme],{kind:'dream',id:String(run.theme)});}w.revision++;return true;}
 if(a.type==='town-clean-start'){if(!p.life?.indoors||s.cleaning[p.id]?.day===s.day)return false;const order=[0,1,2,3,4,5].sort((a,b)=>hash(`${a}:${s.day}`,w.seed)-hash(`${b}:${s.day}`,w.seed));s.cleaning[p.id]={order,next:0,day:s.day};w.revision++;return true;}
 if(a.type==='town-clean'){const run=s.cleaning[p.id];if(!run||run.next>=6||a.index!==run.order[run.next])return false;run.next++;if(run.next===6){me.comfort=Math.min(100,me.comfort+30);me.happiness=Math.min(100,me.happiness+5);for(const q of s.quests)if(q.owner===p.id&&q.kind==='clean'&&q.day===s.day)q.baseline=1;event(w,'clean',[p.id],c('お部屋がすっきり','A tidy room','おへやがすっきり'),c('順番を覚えて片づけた。気持ちよく過ごせそう。','You remember the order and tidy up. The room feels welcoming.','じゅんばんをおぼえてかたづけた。きもちよくすごせそう。'));}w.revision++;return true;}
 if(a.type==='town-festival'){const cal=calendar(w);if(cal.date!==7||me.festivalDays.includes(s.day))return false;me.festivalDays.push(s.day);me.festivalDays=me.festivalDays.slice(-32);me.happiness=Math.min(100,me.happiness+15);const f=FLOWERS[cal.season*12+11];recordFlower(w,p.id,f.id,95);event(w,'festival',[p.id],c('季節のお祭りへ','A seasonal festival','きせつのおまつりへ'),c('花と音楽を楽しみ、特別な花をもらった。','Enjoy flowers and music, and receive a special flower.','はなとおんがくをたのしみ、とくべつなはなをもらった。'),{kind:'flower',id:f.id});return tell('お祭りに参加しました。');}
 if(a.type==='town-rest'){if(Object.values(w.players).filter(p=>!p.spectator).length!==1||!p.life?.indoors||Object.values(w.life.games).some(g=>g.phase==='playing')||s.cooking[p.id]||s.dreams[p.id]&&!s.dreams[p.id].finished)return false;s.elapsed=(s.day+1)*DAY_SECONDS;updateDays(w);me.hunger=Math.max(25,me.hunger);me.comfort=Math.min(100,me.comfort+10);return tell('家で休み、次の日になりました。');}
 if(a.type==='town-family-name'){const f=s.families.find(f=>f.id===a.id&&f.parents.includes(p.id));if(!f||typeof a.name!=='string'||!a.name.trim()||a.name.length>16||/[\u0000-\u001f]/.test(a.name))return false;f.name=a.name.trim();w.revision++;return true;}
 if(a.type==='town-family-care'){const f=s.families.find(f=>f.id===a.id&&f.parents.includes(p.id));if(!f||f.travel&&!f.travel.returned||f.careDays.includes(s.day)||!['play','meal','read'].includes(a.activity))return false;if(a.activity==='meal'){const food=Object.keys(me.foods).find(id=>hasFood(me,id));if(!food||consumeFood(me,food)<0)return tell('食事のお世話には料理をひとつ用意しましょう。');}f.care+=a.activity==='meal'?3:2;f.careDays.push(s.day);f.careDays=f.careDays.slice(-64);me.happiness=Math.min(100,me.happiness+5);event(w,'family',f.parents,c('家族で過ごす時間','Family time','かぞくですごすじかん'),c(`${f.name}の笑顔が増えた。`,`${f.name} smiles a little more.`,`${f.name}のえがおがふえた。`));return tell('家族のお世話をしました。1日に1回成長を応援できます。');}
 if(a.type==='town-family-travel'){const f=s.families.find(f=>f.id===a.id&&f.parents.includes(p.id));if(!f||s.day-f.bornDay<20||f.care<8||f.travel&&!f.travel.returned||!Number.isInteger(a.route)||a.route<0||a.route>=6)return false;f.travel={route:a.route,departDay:s.day,lastLetterDay:s.day,letters:0};event(w,'travel',f.parents,c('家族の旅立ち','A family member sets off','かぞくのたびだち'),c('新しい景色を探しに出発した。手紙とおみやげを待とう。','They set off to discover new scenery. Look forward to letters and souvenirs.','あたらしいけしきをさがしにしゅっぱつした。てがみとおみやげをまとう。'));return tell('旅立ちを見送りました。');}
 if(a.type==='town-family-letter'){const f=s.families.find(f=>f.id===a.id&&f.parents.includes(p.id)),travel=f?.travel;if(!f||!travel||travel.returned||s.day-travel.lastLetterDay<2)return false;travel.lastLetterDay=s.day;travel.letters++;const flower=FLOWERS[(travel.route*7+travel.letters)%48];recordFlower(w,p.id,flower.id,90);event(w,'letter',f.parents,c('旅先からの手紙','A letter from the road','たびさきからのてがみ'),c(`${f.name}より：知らない花を見つけたよ。帰ったら一緒に飾ろう！`,`${f.name}: I found an unfamiliar flower. Let's display it when I return!`,`${f.name}より：しらないはなをみつけたよ。かえったらいっしょにかざろう！`),{kind:'flower',id:flower.id});return tell('手紙とおみやげを受け取りました。');}
 if(a.type==='town-family-return'){const f=s.families.find(f=>f.id===a.id&&f.parents.includes(p.id));if(!f?.travel||f.travel.returned||s.day-f.travel.departDay<3)return false;f.travel.returned=true;event(w,'family',f.parents,c('おかえり！','Welcome home!','おかえり！'),c('旅の話で食卓がにぎわう。また新しい日々が始まる。','Travel stories fill the dinner table. New days begin together.','たびのはなしでしょくたくがにぎわう。またあたらしいひびがはじまる。'));return tell('旅から帰ってきました。');}
 if(a.type==='town-memory'){const news=s.news.find(e=>e.id===a.event&&e.people.includes(p.id));if(!news)return false;const list=s.memories[p.id]??=[];if(list.some(e=>e.id===news.id))return false;list.push(news);s.memories[p.id]=list.slice(-160);w.revision++;return true;}
 if(a.type==='town-decor'){const f=furnishing(a.item),home=w.life.houses.find(h=>h.owner===p.id&&h.id===p.life?.indoors);if(!f||!home||!f.id.startsWith('season')||!canAfford(lifePlayer(p).bag,f.cost))return false;const flower=a.flower&&flowerById(a.flower);if(f.id.startsWith('seasonVase')&&(!flower||!me.flowers[flower.id]))return false;if(f.id==='seasonDreamGlobe'&&!me.souvenirs.length)return false;if(f.id==='seasonPhotoFrame'&&!(s.memories[p.id]?.length))return false;const room=interiorOf(home);if(Object.values(room.stock).reduce((a,b)=>a+b,0)>=40)return false;for(const [key,n]of Object.entries(f.cost))lifePlayer(p).bag[key as keyof typeof p.life.bag]=(lifePlayer(p).bag[key as keyof typeof p.life.bag]||0)-n!;if(flower)me.flowers[flower.id]--;room.stock[f.id]=(room.stock[f.id]||0)+1;return tell('思い出の家具を作りました。家の持ち物から飾れます。');}
 return false;
}
function updateDays(w:World){const s=townOf(w),next=Math.floor(s.elapsed/DAY_SECONDS);if(next===s.day)return;const previous=s.day;s.day=next;s.picked={};for(const p of Object.values(s.people)){p.hunger=Math.max(15,p.hunger-12*(next-previous));p.comfort=Math.max(20,p.comfort-4*(next-previous));if(p.birthday===next%YEAR_DAYS){p.happiness=Math.min(100,p.happiness+10);event(w,'birthday',[p.id],c('今日は誕生日！','A birthday today!','きょうはたんじょうび！'),c('おめでとう。食事や花でお祝いしよう。','Happy birthday! Celebrate with food and flowers.','おめでとう。しょくじやはなでおいわいしよう。'));}if(w.players[p.id])questsFor(w,p.id);}for(const r of [...(w.social?.relations||[]).filter(r=>r.married).map(r=>({people:r.people,day:s.marriageDays[r.people.join(':')]??=previous})),...s.bonds.filter(r=>r.marriedDay!==undefined).map(r=>({people:r.people,day:r.marriedDay!}))])if(next>r.day&&(next-r.day)%YEAR_DAYS===0)event(w,'anniversary',r.people,c('ふたりの記念日','An anniversary together','ふたりのきねんび'),c('一緒に歩いた日々をお祝いしよう。','Celebrate the days you have shared.','いっしょにあるいたひびをおいわいしよう。'));for(const f of s.families){const age=next-f.bornDay,stage=age>=20?3:age>=12?2:age>=5?1:0;if(!f.claimedStages.includes(stage)){f.claimedStages.push(stage);event(w,'growth',f.parents,c('家族の成長','A growing family','かぞくのせいちょう'),c(`${f.name}が新しいことを覚えた。`,`${f.name} learns something new.`,`${f.name}があたらしいことをおぼえた。`));}}w.revision++;}
export function advanceTown(w:World,now:number){const s=townOf(w),elapsed=Math.max(0,Math.min(1,w.life.time-s.lastTime));s.lastTime=w.life.time;if(!w.started||w.ended)return;s.elapsed+=elapsed;const bucket=Math.floor(s.elapsed/15);if(bucket===s.bucket)return;s.bucket=bucket;for(const p of Object.values(w.players))if(!p.spectator){personOf(w,p.id);questsFor(w,p.id);}for(const r of residentsOf(w))personOf(w,r.id);for(const f of s.families)if(s.day-f.bornDay>=12)personOf(w,f.id);s.invites=s.invites.filter(v=>v.expires>now&&w.players[v.from]&&w.players[v.to]);for(const [id,run]of Object.entries(s.cooking))if(now-run.started>20000)delete s.cooking[id];updateDays(w);const phase=calendar(w).phase;for(const p of Object.values(s.people))p.routine=(phase*2+p.personality)%8;
 // Residents live independently; active human players are never moved or committed to relationships by this clock.
 if(bucket%4===0){const resident=residentsOf(w)[hash(String(bucket),w.seed)%residentsOf(w).length],person=s.people[resident.id];if(person.autoLife&&person.hunger<50){person.hunger=Math.min(100,person.hunger+20);person.happiness=Math.min(100,person.happiness+2);}const players=Object.values(w.players).filter(p=>!busy(w,p)&&s.people[p.id]?.autoLife);const p=players[bucket%Math.max(1,players.length)];if(p){const target=s.people[resident.id];if(visibleFriendship(w,p.id,resident.id)>=10){const line=c(`${target.name}より：今日は花を見ながら散歩したいな。お時間ある？`,`${target.name}: I'd love a walk among the flowers today. Do you have time?`,`${target.name}より：きょうははなをみながらさんぽしたいな。おじかんある？`);event(w,'invitation',[p.id,resident.id],c('住人からのお便り','A note from a resident','じゅうにんからのおたより'),line,{kind:'resident',id:resident.id});}}}w.revision++;}
