export const TOWN_ENGLISH:Record<string,string>={
"主人公のプロフィールを更新しました。":"Your hero’s profile has been updated.",
"暮らしの指標と時間の説明":"Life indicators and time explained",
"日課はあなたの主人公の今の気分です。達成ノルマではありません。プロフィールから性格・誕生日・自動交流を設定できます。":"The routine is your hero’s current mood, not a required task. Set personality, birthday and automatic social activity in the profile.",
"あなたの主人公":"Your hero",
"主人公の性格":"Hero personality",
"主人公のプロフィールを設定":"Set your hero’s profile",
"操作中の主人公に設定する、暮らし用のキャラクター性です。日課や交流会話の反応に使われます。戦闘能力やデッキには影響しません。":"This is the personality of the hero you control in daily life. It shapes their routine and responses in social conversations. It does not change combat abilities or the deck.",
"この主人公の性格":"This hero’s personality",
"この主人公の誕生日":"This hero’s birthday",
"この主人公に言葉を教える":"Teach words to this hero",

"暮らしの状態":"Life status",
"暮らしの状態とプロフィール":"Life status and profile",
"おなかは食事、幸福度は会話や贈り物、居心地は休憩や家の片づけで整います。戦闘のHPとは別の暮らしの指標です。":"Food restores hunger, conversations and gifts improve happiness, and rest or tidying improves comfort. These life indicators are separate from battle HP.",
"日課は住人の今の気分を表します。達成ノルマではありません。下で性格・誕生日・自然な交流を設定できます。":"The routine describes a resident’s current mood; it is not a required task. Set personality, birthday and automatic social activity below.",
"1日は活動時間で3分、1季節は7日です。画面を閉じている間は進みません。":"One day is three active minutes; each season lasts seven days. Time pauses while the game is closed.",

 "料理の贈り物を届けました。":"Your food gift has been sent.",
 "贈り物を返しました。":"The gift was returned.",
 "料理の贈り物が思い出になりました。":"Your food gift became a shared memory.",
  "四季とみんなの暮らし": "Seasons and shared lives",
  "暮らし": "Daily life",
  "今日": "Today",
  "お願い": "Requests",
  "花と花壇": "Flowers and garden",
  "料理": "Cooking",
  "住人": "Residents",
  "夢": "Dreams",
  "ニュース": "News",
  "家族": "Family",
  "年目": "Year",
  "日": "Day",
  "朝": "Morning",
  "昼": "Afternoon",
  "夕方": "Evening",
  "夜": "Night",
  "晴れ": "Clear",
  "風": "Wind",
  "雨": "Rain",
  "雪": "Snow",
  "おなか": "Appetite",
  "幸福度": "Happiness",
  "居心地": "Comfort",
  "今日の日課": "Today's routine",
  "暮らしの性格": "Lifestyle personality",
  "誕生日": "Birthday",
  "住人からのお便りと自然な交流を楽しむ": "Enjoy notes and natural interactions from residents",
  "季節のお祭り": "Seasonal festival",
  "お祭りに参加": "Join the festival",
  "家でひと休み": "Rest at home",
  "次の日まで休む": "Rest until tomorrow",
  "片づけミニゲーム": "Tidying minigame",
  "この順番で片づけよう": "Tidy in this order",
  "片づける": "Tidy up",
  "料理を届けよう": "Deliver a dish",
  "季節の花を届けよう": "Deliver a seasonal flower",
  "材料を届けよう": "Deliver materials",
  "住人と話そう": "Talk with a resident",
  "友達とお出かけしよう": "Go out with a friend",
  "夢の道しるべを集めよう": "Collect dream guideposts",
  "新しく料理を作ろう": "Cook a new dish",
  "家に家具を飾ろう": "Place furniture at home",
  "魚を1匹釣ろう": "Catch a fish",
  "部屋を片づけよう": "Tidy your room",
  "お礼": "Reward",
  "季節の花と薬草": "A seasonal flower and an herb",
  "達成済み": "Completed",
  "条件を確認して報告": "Check conditions and report",
  "花図鑑": "Flower collection",
  "品質": "Quality",
  "所持": "Owned",
  "本": "flowers",
  "未収集": "Not collected",
  "生息地": "Habitat",
  "草原": "Meadow",
  "森": "Forest",
  "湿原": "Wetland",
  "砂丘": "Dunes",
  "雪原": "Snowfield",
  "遺跡": "Ruins",
  "贈る相手": "Gift recipient",
  "花を贈る": "Give a flower",
  "自分の花壇": "Your garden",
  "花壇": "Garden plot",
  "育成": "Growth",
  "水やり": "Water",
  "収穫": "Harvest",
  "選んだ花を植える": "Plant selected flower",
  "花と記念品の家具": "Flower and keepsake furniture",
  "家で作る": "Craft at home",
  "食べる人": "Meal recipient",
  "全レシピ": "All recipes",
  "作れるもの": "Affordable recipes",
  "料理の持ち物": "Prepared dishes",
  "いつでも": "Any season",
  "満腹": "Appetite restored",
  "大成功": "Perfect",
  "好み": "Preference",
  "まだ知らない": "Not yet discovered",
  "大好物": "Favorite",
  "ちょっと苦手": "Disliked",
  "好き": "Liked",
  "料理する": "Cook",
  "食べる": "Eat",
  "ごちそうする": "Serve a meal",
  "友好度": "Friendship",
  "同じ家": "Shared home",
  "友達": "Friend",
  "ケンカ中": "In a disagreement",
  "おしゃべり": "Chat",
  "気持ちを伝える": "Share your feelings",
  "友達に仲裁を頼む": "Ask a friend to mediate",
  "訪問とお出かけ": "Visits and outings",
  "行き先": "Destination",
  "お出かけに誘う": "Invite on an outing",
  "家に招く": "Invite home",
  "住人と暮らす": "Live with a resident",
  "同居を申し込む": "Ask to live together",
  "結婚を申し込む": "Propose marriage",
  "最近のおしゃべり": "Recent conversations",
  "ベッドから不思議な世界へ": "From your bed to a strange world",
  "夢を見る": "Dream",
  "夢の記念品を手に入れました！": "You found a dream keepsake!",
  "道しるべを番号順に集めよう": "Collect guideposts in numerical order",
  "夢のマップ": "Dream map",
  "夢のマス": "Dream tile",
  "夢で移動": "Move in the dream",
  "目を覚ます": "Wake up",
  "夢の思い出図鑑": "Dream keepsake collection",
  "発見済み": "Discovered",
  "まだ夢の中": "Yet to dream",
  "住人ニュース": "Resident news",
  "思い出帳": "Memory album",
  "家族を迎える相手": "Family partner",
  "家族を迎える相談": "Discuss welcoming a child",
  "お世話": "Care",
  "成長": "Growth",
  "名前": "Name",
  "名前を決める": "Choose a name",
  "一緒に遊ぶ": "Play together",
  "食事のお世話": "Serve a meal",
  "絵本を読む": "Read a picture book",
  "旅の行き先": "Journey destination",
  "旅立ちを見送る": "See them off",
  "帰宅しました": "Returned home",
  "旅の途中": "On a journey",
  "手紙とおみやげを受け取る": "Receive a letter and souvenir",
  "帰宅を迎える": "Welcome them home",
  "調理のタイミング": "Cooking timing",
  "光る範囲で画面のどこかをタップ！": "Tap anywhere when the marker reaches the glowing zone!",
  "調理を中断": "Cancel cooking",
  "家族を迎えるお誘い": "Invitation to welcome a child",
  "家へのお誘い": "Invitation home",
  "お出かけのお誘い": "Invitation on an outing",
  "受ける": "Accept",
  "今回は見送る": "Not this time",
  "暮らしの切り替え": "Choose a daily-life activity",
  "暮らしを準備しています…": "Preparing daily life…",
  "近くの花": "Nearby flowers",
  "花を摘む": "Pick a flower",
  "春の花の花瓶": "Spring flower vase",
  "夏の花の花瓶": "Summer flower vase",
  "秋の花の花瓶": "Autumn flower vase",
  "冬の花の花瓶": "Winter flower vase",
  "友情の写真立て": "Friendship photo frame",
  "夢のスノードーム": "Dream snow globe",
  "家族のゆりかご": "Family cradle",
  "旅のおみやげ箱": "Travel keepsake trunk",
  "押し花の手帳": "Pressed-flower journal",
  "家族のお茶セット": "Family tea set",
  "四季の灯り": "Seasonal lantern",
  "花のリース": "Flower wreath",
  "空腹や気分は戦闘HPに影響しません。食事と交流で暮らしを楽しもう。": "Appetite and mood do not affect battle HP. Enjoy meals and friendships.",
  "ひとり用では家で休むと次の日へ進めます。オンラインの日数はみんなで共有します。": "In solo play, resting at home advances the day. Online players share the same calendar.",
  "各季節の最終日に、珍しい花をもらえます。": "Receive a rare flower on the last day of each season.",
  "毎日4件。採取・料理・釣り・会話・夢・家具などでお願いを解決しよう。": "Four requests each day. Fulfill them through gathering, cooking, fishing, conversations, dreams and furniture.",
  "品質の最高記録も保存されます。": "Your best quality records are saved too.",
  "家を建てると6区画の花壇を使えます。2日分の水やりで育ち、品質が高いほど収穫が増えます。": "Build a house to unlock six garden plots. Water on two days; better quality yields more flowers.",
  "家の作業台・ストーブで3回タイミングを合わせよう。2回成功すると大成功の料理になります。": "Time three taps at your home workbench or stove. Two successful taps make a perfect dish.",
  "参加者のお誘いは相手が受けた時だけ成立します。住人は友好度10から誘えます。": "Player invitations require acceptance. Invite residents from friendship 10.",
  "友好度20で同居、50で結婚。自分の家を用意しましょう。": "Live together at friendship 20 and propose at 50. You need your own house.",
  "1日に1回、家のベッドで夢を見ます。3つの道しるべを番号順に集めると、珍しい花と夢の記念品を持ち帰れます。": "Dream once per day in a home bed. Collect three guideposts in order to earn a rare flower and dream keepsake.",
  "出来事は日付と絵で記録されます。保存・再開後も読み返せます。": "Events are recorded with dates and pictures. Read them again after saving and resuming.",
  "花を集めたり、住人に話しかけたりして思い出を作ろう。": "Collect flowers and talk with residents to make memories.",
  "結婚後、ふたりで家族を迎えられます。参加者同士では相手の承諾が必要です。": "After marriage, welcome a child together. Player couples require both partners' consent.",
  "5日で幼児、12日で子ども、20日で旅立ちの準備。お世話8以上で旅に出られます。": "Toddler at 5 days, child at 12, ready to travel at 20. At least 8 care points unlock a journey.",
  "おしゃべりを楽しみました。": "You enjoyed a conversation.",
  "お祭りに参加しました。": "You joined the festival.",
  "お誘いを受けました。": "You accepted the invitation.",
  "お願いの条件を達成してから報告しましょう。": "Complete the request conditions before reporting.",
  "お願いを達成しました。": "Request completed.",
  "もう少し仲良くなってから誘いましょう。": "Become a little closer before inviting them.",
  "今は気持ちを落ち着かせたいようです。食事や休憩のあとにもう一度話そう。": "They need a moment to calm down. Talk again after a meal or a rest.",
  "今回はお誘いを見送りました。": "You declined this invitation.",
  "仲直りしました。": "You made up.",
  "住人と新しい思い出ができました。": "You made a new memory with a resident.",
  "友好度20以上の別の友達に仲裁を頼めます。": "A different friend with friendship 20 can mediate.",
  "家で休み、次の日になりました。": "You rested at home until the next day.",
  "家のベッドで夢を見られます。": "You can dream in a home bed.",
  "家の作業台・ストーブで料理できます。材料と持ち物の空きを確認してください。": "Cook at a home workbench or stove. Check ingredients and inventory space.",
  "家族のお世話をしました。1日に1回成長を応援できます。": "You cared for your family. Support their growth once each day.",
  "思い出の家具を作りました。家の持ち物から飾れます。": "A keepsake furnishing is ready. Place it from your home inventory.",
  "手紙とおみやげを受け取りました。": "You received a letter and souvenir.",
  "料理ができました。食べたり、住人へ贈ったりできます。": "A dish is ready. Eat it or serve it to a resident.",
  "旅から帰ってきました。": "They returned from the journey.",
  "旅立ちを見送りました。": "You saw them off on their journey.",
  "暮らしの性格と誕生日を設定しました。": "Lifestyle personality and birthday updated.",
  "暮らしの関係が進みました。": "Your relationship has progressed.",
  "目を覚ましました。夢は1日に1回楽しめます。": "You woke up. Dream once each day.",
  "相手にお誘いを送りました。相手が選ぶまで待ちましょう。": "Invitation sent. Wait for their decision.",
  "育てた花を収穫しました。花図鑑の品質記録も更新します。": "You harvested your flowers. The flower-book quality record is updated.",
  "花がないか、採取エネルギーが足りません。": "No flower is available, or gathering energy is too low.",
  "花に水をあげました。今日の水やり完了です。": "Flowers watered for today.",
  "花を摘みました。種も残して、花壇で育てられます。": "You picked a flower. Plant it in your garden to grow more.",
  "花を贈りました。贈り物で友好度が上がるのは1日1回です。": "Flower gifted. Gift friendship rewards apply once per day.",
  "花壇に植えました。季節に合う花は2日、それ以外は3日で育ちます。": "Flower planted. It grows in 2 days in its season, otherwise 3.",
  "調理を中断しました。使った材料は戻りません。": "Cooking cancelled. Used ingredients are not returned.",
  "食事のお世話には料理をひとつ用意しましょう。": "Prepare a dish before feeding the family.",
  "食事を楽しみました。好みが図鑑に記録されます。": "Meal enjoyed. The taste preference is recorded.",
  "花と記念品の家具は暮らしの画面で作れます。": "Craft flower and keepsake furniture on the daily-life screen.",
  "相手の選択を待っています。": "Waiting for your partner’s choice.",
  "暮らしの関係を見直しました。思い出と家族の記録は残ります。": "Relationship updated. Memories and family records are retained.",
  "同居を解消する": "Stop living together",
  "結婚を解消する": "End marriage",
  "お出かけを切り上げました。また今度誘ってみましょう。": "You ended the outing. Invite them again another time.",
  "今回は帰る": "Return for now",
  "雪化粧の木": "Snow-covered tree",
  "町で準備を整え、道に沿って探索しよう。": "Prepare in town, then follow the paths to explore.",
  "冒険者": "Adventurer"
};
export const TOWN_HIRAGANA:Record<string,string>={
"主人公のプロフィールを更新しました。":"しゅじんこうの プロフィールを こうしんしました。",
"暮らしの指標と時間の説明":"くらしの しひょうと じかんの せつめい",
"日課はあなたの主人公の今の気分です。達成ノルマではありません。プロフィールから性格・誕生日・自動交流を設定できます。":"にっかは あなたの しゅじんこうの いまの きぶんです。たっせいノルマでは ありません。プロフィールから せいかく・たんじょうび・じどうこうりゅうを せっていできます。",
"あなたの主人公":"あなたの しゅじんこう",
"主人公の性格":"しゅじんこうの せいかく",
"主人公のプロフィールを設定":"しゅじんこうの プロフィールを せってい",
"操作中の主人公に設定する、暮らし用のキャラクター性です。日課や交流会話の反応に使われます。戦闘能力やデッキには影響しません。":"そうさちゅうの しゅじんこうに せっていする、くらしようの キャラクターせいです。にっかや こうりゅうかいわの はんのうに つかわれます。せんとうのうりょくや デッキには えいきょうしません。",
"この主人公の性格":"この しゅじんこうの せいかく",
"この主人公の誕生日":"この しゅじんこうの たんじょうび",
"この主人公に言葉を教える":"この しゅじんこうに ことばを おしえる",

"暮らしの状態":"くらしのじょうたい",
"暮らしの状態とプロフィール":"くらしのじょうたいとぷろふぃーる",
"おなかは食事、幸福度は会話や贈り物、居心地は休憩や家の片づけで整います。戦闘のHPとは別の暮らしの指標です。":"おなかはしょくじ、こうふくどはかいわやおくりもの、いごこちはきゅうけいやいえのかたづけでととのいます。せんとうのえいちぴーとはべつのくらしのしひょうです。",
"日課は住人の今の気分を表します。達成ノルマではありません。下で性格・誕生日・自然な交流を設定できます。":"にっかはじゅうにんのいまのきぶんをあらわします。たっせいのるまではありません。したでせいかく・たんじょうび・しぜんなこうりゅうをせっていできます。",
"1日は活動時間で3分、1季節は7日です。画面を閉じている間は進みません。":"いちにちはかつどうじかんでさんぷん、ひときせつはなのかです。がめんをとじているあいだはすすみません。",

 "料理の贈り物を届けました。":"りょうりのおくりものをとどけました。",
 "贈り物を返しました。":"おくりものをかえしました。",
 "料理の贈り物が思い出になりました。":"りょうりのおくりものがおもいでになりました。",
  "四季とみんなの暮らし": "しきとみんなのくらし",
  "暮らし": "くらし",
  "今日": "きょう",
  "お願い": "おねがい",
  "花と花壇": "はなとかだん",
  "料理": "りょうり",
  "住人": "じゅうにん",
  "夢": "ゆめ",
  "ニュース": "にゅーす",
  "家族": "かぞく",
  "年目": "ねんめ",
  "日": "にち",
  "朝": "あさ",
  "昼": "ひる",
  "夕方": "ゆうがた",
  "夜": "よる",
  "晴れ": "はれ",
  "風": "かぜ",
  "雨": "あめ",
  "雪": "ゆき",
  "おなか": "おなか",
  "幸福度": "こうふくど",
  "居心地": "いごこち",
  "今日の日課": "きょうのにっか",
  "暮らしの性格": "くらしのせいかく",
  "誕生日": "たんじょうび",
  "住人からのお便りと自然な交流を楽しむ": "じゅうにんからのおたよりとしぜんなこうりゅうをたのしむ",
  "季節のお祭り": "きせつのおまつり",
  "お祭りに参加": "おまつりにさんか",
  "家でひと休み": "いえでひとやすみ",
  "次の日まで休む": "つぎのにちまでやすむ",
  "片づけミニゲーム": "かたづけみにげーむ",
  "この順番で片づけよう": "このじゅんばんでかたづけよう",
  "片づける": "かたづける",
  "料理を届けよう": "りょうりをとどけよう",
  "季節の花を届けよう": "きせつのはなをとどけよう",
  "材料を届けよう": "ざいりょうをとどけよう",
  "住人と話そう": "じゅうにんとはなそう",
  "友達とお出かけしよう": "ともだちとおでかけしよう",
  "夢の道しるべを集めよう": "ゆめのみちしるべをあつめよう",
  "新しく料理を作ろう": "あたらしくりょうりをつくろう",
  "家に家具を飾ろう": "いえにかぐをかざろう",
  "魚を1匹釣ろう": "さかなを1ひきつろう",
  "部屋を片づけよう": "へやをかたづけよう",
  "お礼": "おれい",
  "季節の花と薬草": "きせつのはなとやくそう",
  "達成済み": "たっせいすみ",
  "条件を確認して報告": "じょうけんをかくにんしてほうこく",
  "花図鑑": "はなずかん",
  "品質": "ひんしつ",
  "所持": "しょじ",
  "本": "ほん",
  "未収集": "みしゅうしゅう",
  "生息地": "せいそくち",
  "草原": "そうげん",
  "森": "もり",
  "湿原": "しつげん",
  "砂丘": "さきゅう",
  "雪原": "せつげん",
  "遺跡": "いせき",
  "贈る相手": "おくるあいて",
  "花を贈る": "はなをおくる",
  "自分の花壇": "じぶんのかだん",
  "花壇": "かだん",
  "育成": "いくせい",
  "水やり": "みずやり",
  "収穫": "しゅうかく",
  "選んだ花を植える": "えらんだはなをうえる",
  "花と記念品の家具": "はなときねんひんのかぐ",
  "家で作る": "いえでつくる",
  "食べる人": "たべるにん",
  "全レシピ": "ぜんれしぴ",
  "作れるもの": "つくれるもの",
  "料理の持ち物": "りょうりのもちもの",
  "いつでも": "いつでも",
  "満腹": "まんぷく",
  "大成功": "だいせいこう",
  "好み": "このみ",
  "まだ知らない": "まだしらない",
  "大好物": "だいこうぶつ",
  "ちょっと苦手": "ちょっとにがて",
  "好き": "すき",
  "料理する": "りょうりする",
  "食べる": "たべる",
  "ごちそうする": "ごちそうする",
  "友好度": "ゆうこうど",
  "同じ家": "おなじいえ",
  "友達": "ともだち",
  "ケンカ中": "けんかなか",
  "おしゃべり": "おしゃべり",
  "気持ちを伝える": "きもちをつたえる",
  "友達に仲裁を頼む": "ともだちにちゅうさいをたのむ",
  "訪問とお出かけ": "ほうもんとおでかけ",
  "行き先": "いきさき",
  "お出かけに誘う": "おでかけにさそう",
  "家に招く": "いえにまねく",
  "住人と暮らす": "じゅうにんとくらす",
  "同居を申し込む": "どうきょをもうしこむ",
  "結婚を申し込む": "けっこんをもうしこむ",
  "最近のおしゃべり": "さいきんのおしゃべり",
  "ベッドから不思議な世界へ": "べっどからふしぎなせかいへ",
  "夢を見る": "ゆめをみる",
  "夢の記念品を手に入れました！": "ゆめのきねんひんをてにいれました！",
  "道しるべを番号順に集めよう": "みちしるべをばんごうじゅんにあつめよう",
  "夢のマップ": "ゆめのまっぷ",
  "夢のマス": "ゆめのます",
  "夢で移動": "ゆめでいどう",
  "目を覚ます": "めをさます",
  "夢の思い出図鑑": "ゆめのおもいでずかん",
  "発見済み": "はっけんすみ",
  "まだ夢の中": "まだゆめのなか",
  "住人ニュース": "じゅうにんにゅーす",
  "思い出帳": "おもいでちょう",
  "家族を迎える相手": "かぞくをむかえるあいて",
  "家族を迎える相談": "かぞくをむかえるそうだん",
  "お世話": "おせわ",
  "成長": "せいちょう",
  "名前": "なまえ",
  "名前を決める": "なまえをきめる",
  "一緒に遊ぶ": "いっしょにあそぶ",
  "食事のお世話": "しょくじのおせわ",
  "絵本を読む": "えほんをよむ",
  "旅の行き先": "たびのいきさき",
  "旅立ちを見送る": "たびだちをみおくる",
  "帰宅しました": "きたくしました",
  "旅の途中": "たびのとちゅう",
  "手紙とおみやげを受け取る": "てがみとおみやげをうけとる",
  "帰宅を迎える": "きたくをむかえる",
  "調理のタイミング": "ちょうりのたいみんぐ",
  "光る範囲で画面のどこかをタップ！": "ひかるはんいでがめんのどこかをたっぷ！",
  "調理を中断": "ちょうりをちゅうだん",
  "家族を迎えるお誘い": "かぞくをむかえるおさそい",
  "家へのお誘い": "いえへのおさそい",
  "お出かけのお誘い": "おでかけのおさそい",
  "受ける": "うける",
  "今回は見送る": "こんかいはみおくる",
  "暮らしの切り替え": "くらしのきりかえ",
  "暮らしを準備しています…": "くらしをじゅんびしています…",
  "近くの花": "ちかくのはな",
  "花を摘む": "はなをつむ",
  "春の花の花瓶": "はるのはなのかびん",
  "夏の花の花瓶": "なつのはなのかびん",
  "秋の花の花瓶": "あきのはなのかびん",
  "冬の花の花瓶": "ふゆのはなのかびん",
  "友情の写真立て": "ゆうじょうのしゃしんたて",
  "夢のスノードーム": "ゆめのすのーどーむ",
  "家族のゆりかご": "かぞくのゆりかご",
  "旅のおみやげ箱": "たびのおみやげはこ",
  "押し花の手帳": "おしばなのてちょう",
  "家族のお茶セット": "かぞくのおちゃせっと",
  "四季の灯り": "しきのあかり",
  "花のリース": "はなのりーす",
  "空腹や気分は戦闘HPに影響しません。食事と交流で暮らしを楽しもう。": "くうふくやきぶんはせんとうHPにえいきょうしません。しょくじとこうりゅうでくらしをたのしもう。",
  "ひとり用では家で休むと次の日へ進めます。オンラインの日数はみんなで共有します。": "ひとりようではいえでやすむとつぎのにちへすすめます。おんらいんのにっすうはみんなできょうゆうします。",
  "各季節の最終日に、珍しい花をもらえます。": "かくきせつのさいしゅうびに、めずらしいはなをもらえます。",
  "毎日4件。採取・料理・釣り・会話・夢・家具などでお願いを解決しよう。": "まいにち4けん。さいしゅ・りょうり・つり・かいわ・ゆめ・かぐなどでおねがいをかいけつしよう。",
  "品質の最高記録も保存されます。": "ひんしつのさいこうきろくもほぞんされます。",
  "家を建てると6区画の花壇を使えます。2日分の水やりで育ち、品質が高いほど収穫が増えます。": "いえをたてると6くかくのかだんをつかえます。2にちぶんのみずやりでそだち、ひんしつがたかいほどしゅうかくがふえます。",
  "家の作業台・ストーブで3回タイミングを合わせよう。2回成功すると大成功の料理になります。": "いえのさぎょうだい・すとーぶで3かいたいみんぐをあわせよう。2かいせいこうするとだいせいこうのりょうりになります。",
  "参加者のお誘いは相手が受けた時だけ成立します。住人は友好度10から誘えます。": "さんかしゃのおさそいはあいてがうけたときだけせいりつします。じゅうにんはゆうこうど10からさそえます。",
  "友好度20で同居、50で結婚。自分の家を用意しましょう。": "ゆうこうど20でどうきょ、50でけっこん。じぶんのいえをよういしましょう。",
  "1日に1回、家のベッドで夢を見ます。3つの道しるべを番号順に集めると、珍しい花と夢の記念品を持ち帰れます。": "1にちに1かい、いえのべっどでゆめをみます。3つのみちしるべをばんごうじゅんにあつめると、めずらしいはなとゆめのきねんひんをもちかえれます。",
  "出来事は日付と絵で記録されます。保存・再開後も読み返せます。": "できごとはひづけとえできろくされます。ほぞん・さいかいごもよみかえせます。",
  "花を集めたり、住人に話しかけたりして思い出を作ろう。": "はなをあつめたり、じゅうにんにはなしかけたりしておもいでをつくろう。",
  "結婚後、ふたりで家族を迎えられます。参加者同士では相手の承諾が必要です。": "けっこんご、ふたりでかぞくをむかえられます。さんかしゃどうしではあいてのしょうだくがひつようです。",
  "5日で幼児、12日で子ども、20日で旅立ちの準備。お世話8以上で旅に出られます。": "5にちでようじ、12にちでこども、20にちでたびだちのじゅんび。おせわ8いじょうでたびにでられます。",
  "おしゃべりを楽しみました。": "おしゃべりをたのしみました。",
  "お祭りに参加しました。": "おまつりにさんかしました。",
  "お誘いを受けました。": "おさそいをうけました。",
  "お願いの条件を達成してから報告しましょう。": "おねがいのじょうけんをたっせいしてからほうこくしましょう。",
  "お願いを達成しました。": "おねがいをたっせいしました。",
  "もう少し仲良くなってから誘いましょう。": "もうすこしなかよくなってからさそいましょう。",
  "今は気持ちを落ち着かせたいようです。食事や休憩のあとにもう一度話そう。": "いまはきもちをおちつかせたいようです。しょくじやきゅうけいのあとにもういちどはなそう。",
  "今回はお誘いを見送りました。": "こんかいはおさそいをみおくりました。",
  "仲直りしました。": "なかなおりしました。",
  "住人と新しい思い出ができました。": "じゅうにんとあたらしいおもいでができました。",
  "友好度20以上の別の友達に仲裁を頼めます。": "ゆうこうど20いじょうのべつのともだちにちゅうさいをたのめます。",
  "家で休み、次の日になりました。": "いえでやすみ、つぎのにちになりました。",
  "家のベッドで夢を見られます。": "いえのべっどでゆめをみられます。",
  "家の作業台・ストーブで料理できます。材料と持ち物の空きを確認してください。": "いえのさぎょうだい・すとーぶでりょうりできます。ざいりょうともちもののあきをかくにんしてください。",
  "家族のお世話をしました。1日に1回成長を応援できます。": "かぞくのおせわをしました。1にちに1かいせいちょうをおうえんできます。",
  "思い出の家具を作りました。家の持ち物から飾れます。": "おもいでのかぐをつくりました。いえのもちものからかざれます。",
  "手紙とおみやげを受け取りました。": "てがみとおみやげをうけとりました。",
  "料理ができました。食べたり、住人へ贈ったりできます。": "りょうりができました。たべたり、じゅうにんへおくったりできます。",
  "旅から帰ってきました。": "たびからかえってきました。",
  "旅立ちを見送りました。": "たびだちをみおくりました。",
  "暮らしの性格と誕生日を設定しました。": "くらしのせいかくとたんじょうびをせっていしました。",
  "暮らしの関係が進みました。": "くらしのかんけいがすすみました。",
  "目を覚ましました。夢は1日に1回楽しめます。": "めをさましました。ゆめは1にちに1かいたのしめます。",
  "相手にお誘いを送りました。相手が選ぶまで待ちましょう。": "あいてにおさそいをおくりました。あいてがえらぶまでまちましょう。",
  "育てた花を収穫しました。花図鑑の品質記録も更新します。": "そだてたはなをしゅうかくしました。はなずかんのひんしつきろくもこうしんします。",
  "花がないか、採取エネルギーが足りません。": "はながないか、さいしゅえねるぎーがたりません。",
  "花に水をあげました。今日の水やり完了です。": "はなにみずをあげました。きょうのみずやりかんりょうです。",
  "花を摘みました。種も残して、花壇で育てられます。": "はなをつみました。たねものこして、かだんでそだてられます。",
  "花を贈りました。贈り物で友好度が上がるのは1日1回です。": "はなをおくりました。おくりものでゆうこうどがあがるのは1にち1かいです。",
  "花壇に植えました。季節に合う花は2日、それ以外は3日で育ちます。": "かだんにうえました。きせつにあうはなは2にち、それいがいは3にちでそだちます。",
  "調理を中断しました。使った材料は戻りません。": "ちょうりをちゅうだんしました。つかったざいりょうはもどりません。",
  "食事のお世話には料理をひとつ用意しましょう。": "しょくじのおせわにはりょうりをひとつよういしましょう。",
  "食事を楽しみました。好みが図鑑に記録されます。": "しょくじをたのしみました。このみがずかんにきろくされます。",
  "花と記念品の家具は暮らしの画面で作れます。": "はなときねんひんのかぐはくらしのがめんでつくれます。",
  "相手の選択を待っています。": "あいてのせんたくをまっています。",
  "暮らしの関係を見直しました。思い出と家族の記録は残ります。": "くらしのかんけいをみなおしました。おもいでとかぞくのきろくはのこります。",
  "同居を解消する": "どうきょをかいしょうする",
  "結婚を解消する": "けっこんをかいしょうする",
  "お出かけを切り上げました。また今度誘ってみましょう。": "おでかけをきりあげました。またこんどさそってみましょう。",
  "今回は帰る": "こんかいはかえる",
  "雪化粧の木": "ゆきげしょうのき",
  "町で準備を整え、道に沿って探索しよう。": "まちでじゅんびをととのえ、みちにそってたんさくしよう。",
  "冒険者": "ぼうけんしゃ"
};
