import type { Copy, Dish } from "../town/catalog";
const c = (ja: string, en: string, hi: string): Copy => ({ ja, en, hi });
export interface Crop {
  id: string;
  name: Copy;
  index: number;
  season: number;
  days: number;
  yield: number;
  regrow: number;
  price: number;
  value: number;
  family: number;
}
export const CROPS: Crop[] = [
  {
    id: "turnip",
    name: c("カブ", "Turnip", "かぶ"),
    index: 0,
    season: 0,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 0,
  },
  {
    id: "carrot",
    name: c("ニンジン", "Carrot", "にんじん"),
    index: 1,
    season: 0,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "cabbage",
    name: c("キャベツ", "Cabbage", "きゃべつ"),
    index: 2,
    season: 0,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "potato",
    name: c("ジャガイモ", "Potato", "じゃがいも"),
    index: 3,
    season: 0,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 3,
  },
  {
    id: "strawberry",
    name: c("イチゴ", "Strawberry", "いちご"),
    index: 4,
    season: 0,
    days: 3,
    yield: 2,
    regrow: 1,
    price: 11,
    value: 20,
    family: 0,
  },
  {
    id: "pea",
    name: c("エンドウ", "Peas", "えんどう"),
    index: 5,
    season: 0,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "asparagus",
    name: c("アスパラガス", "Asparagus", "あすぱらがす"),
    index: 6,
    season: 0,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "radish",
    name: c("ラディッシュ", "Radish", "らでぃっしゅ"),
    index: 7,
    season: 0,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 3,
  },
  {
    id: "tomato",
    name: c("トマト", "Tomato", "とまと"),
    index: 8,
    season: 1,
    days: 1,
    yield: 2,
    regrow: 1,
    price: 7,
    value: 12,
    family: 0,
  },
  {
    id: "corn",
    name: c("トウモロコシ", "Corn", "とうもろこし"),
    index: 9,
    season: 1,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "cucumber",
    name: c("キュウリ", "Cucumber", "きゅうり"),
    index: 10,
    season: 1,
    days: 3,
    yield: 2,
    regrow: 1,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "eggplant",
    name: c("ナス", "Eggplant", "なす"),
    index: 11,
    season: 1,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 3,
  },
  {
    id: "watermelon",
    name: c("スイカ", "Watermelon", "すいか"),
    index: 12,
    season: 1,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 0,
  },
  {
    id: "pineapple",
    name: c("パイナップル", "Pineapple", "ぱいなっぷる"),
    index: 13,
    season: 1,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "pepper",
    name: c("パプリカ", "Bell pepper", "ぱぷりか"),
    index: 14,
    season: 1,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "chili",
    name: c("トウガラシ", "Chili", "とうがらし"),
    index: 15,
    season: 1,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 3,
  },
  {
    id: "pumpkin",
    name: c("カボチャ", "Pumpkin", "かぼちゃ"),
    index: 16,
    season: 2,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 0,
  },
  {
    id: "sweetpotato",
    name: c("サツマイモ", "Sweet potato", "さつまいも"),
    index: 17,
    season: 2,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "grape",
    name: c("ブドウ", "Grapes", "ぶどう"),
    index: 18,
    season: 2,
    days: 3,
    yield: 2,
    regrow: 1,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "apple",
    name: c("リンゴ", "Apple", "りんご"),
    index: 19,
    season: 2,
    days: 2,
    yield: 2,
    regrow: 1,
    price: 9,
    value: 16,
    family: 3,
  },
  {
    id: "mushroom",
    name: c("キノコ", "Mushrooms", "きのこ"),
    index: 20,
    season: 2,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 0,
  },
  {
    id: "rice",
    name: c("米", "Rice", "こめ"),
    index: 21,
    season: 2,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "wheat",
    name: c("小麦", "Wheat", "こむぎ"),
    index: 22,
    season: 2,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "soy",
    name: c("大豆", "Soybeans", "だいず"),
    index: 23,
    season: 2,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 3,
  },
  {
    id: "broccoli",
    name: c("ブロッコリー", "Broccoli", "ぶろっこりー"),
    index: 24,
    season: 3,
    days: 1,
    yield: 3,
    regrow: 0,
    price: 7,
    value: 12,
    family: 0,
  },
  {
    id: "spinach",
    name: c("ホウレンソウ", "Spinach", "ほうれんそう"),
    index: 25,
    season: 3,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "leek",
    name: c("長ネギ", "Leek", "ながねぎ"),
    index: 26,
    season: 3,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "beet",
    name: c("ビーツ", "Beetroot", "びーつ"),
    index: 27,
    season: 3,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 3,
  },
  {
    id: "snowberry",
    name: c("雪ベリー", "Snowberry", "ゆきべりー"),
    index: 28,
    season: 3,
    days: 3,
    yield: 2,
    regrow: 1,
    price: 11,
    value: 20,
    family: 0,
  },
  {
    id: "onion",
    name: c("タマネギ", "Onion", "たまねぎ"),
    index: 29,
    season: 3,
    days: 2,
    yield: 3,
    regrow: 0,
    price: 9,
    value: 16,
    family: 1,
  },
  {
    id: "garlic",
    name: c("ニンニク", "Garlic", "にんにく"),
    index: 30,
    season: 3,
    days: 3,
    yield: 3,
    regrow: 0,
    price: 11,
    value: 20,
    family: 2,
  },
  {
    id: "tea",
    name: c("茶葉", "Tea leaves", "ちゃば"),
    index: 31,
    season: 3,
    days: 1,
    yield: 2,
    regrow: 1,
    price: 7,
    value: 12,
    family: 3,
  },
];
export const cropById = (id: string) => CROPS.find((x) => x.id === id);
export interface LivestockKind {
  id: string;
  name: Copy;
  index: number;
  product: string;
  price: number;
  days: number;
}
export const LIVESTOCK: LivestockKind[] = [
  {
    id: "chicken",
    name: c("ニワトリ", "Chicken", "にわとり"),
    index: 0,
    product: "egg",
    price: 35,
    days: 1,
  },
  {
    id: "cow",
    name: c("ウシ", "Cow", "うし"),
    index: 1,
    product: "milk",
    price: 100,
    days: 2,
  },
  {
    id: "sheep",
    name: c("ヒツジ", "Sheep", "ひつじ"),
    index: 2,
    product: "wool",
    price: 80,
    days: 2,
  },
  {
    id: "goat",
    name: c("ヤギ", "Goat", "やぎ"),
    index: 3,
    product: "cheese",
    price: 90,
    days: 2,
  },
  {
    id: "duck",
    name: c("アヒル", "Duck", "あひる"),
    index: 4,
    product: "duckegg",
    price: 60,
    days: 1,
  },
  {
    id: "alpaca",
    name: c("アルパカ", "Alpaca", "あるぱか"),
    index: 5,
    product: "yarn",
    price: 140,
    days: 3,
  },
  {
    id: "pig",
    name: c("ブタ", "Pig", "ぶた"),
    index: 6,
    product: "truffle",
    price: 150,
    days: 3,
  },
  {
    id: "bees",
    name: c("ミツバチ", "Bees", "みつばち"),
    index: 7,
    product: "honey",
    price: 70,
    days: 2,
  },
];
export const animalById = (id: string) => LIVESTOCK.find((x) => x.id === id);
export const PRODUCTS = [
  { id: "egg", name: c("卵", "Eggs", "たまご"), index: 8, value: 18 },
  { id: "milk", name: c("ミルク", "Milk", "みるく"), index: 9, value: 24 },
  { id: "wool", name: c("羊毛", "Wool", "ようもう"), index: 10, value: 30 },
  {
    id: "cheese",
    name: c("ヤギのチーズ", "Goat cheese", "やぎのちーず"),
    index: 11,
    value: 32,
  },
  {
    id: "duckegg",
    name: c("アヒルの卵", "Duck eggs", "あひるのたまご"),
    index: 12,
    value: 22,
  },
  {
    id: "yarn",
    name: c("アルパカの毛糸", "Alpaca yarn", "あるぱかのけいと"),
    index: 13,
    value: 45,
  },
  {
    id: "truffle",
    name: c("トリュフ", "Truffles", "とりゅふ"),
    index: 14,
    value: 55,
  },
  {
    id: "honey",
    name: c("ハチミツ", "Honey", "はちみつ"),
    index: 15,
    value: 28,
  },
];
export const PET_SPECIES = [
  {
    id: "shiba",
    name: c("柴犬", "Shiba inu", "しばいぬ"),
    index: 16,
    price: 35,
    talent: "seeds",
  },
  {
    id: "corgi",
    name: c("コーギー", "Corgi", "こーぎー"),
    index: 17,
    price: 40,
    talent: "herbs",
  },
  {
    id: "poodle",
    name: c("プードル", "Poodle", "ぷーどる"),
    index: 18,
    price: 45,
    talent: "coins",
  },
  {
    id: "husky",
    name: c("ハスキー", "Husky", "はすきー"),
    index: 19,
    price: 50,
    talent: "seeds",
  },
  {
    id: "calico",
    name: c("三毛猫", "Calico cat", "みけねこ"),
    index: 20,
    price: 55,
    talent: "seeds",
  },
  {
    id: "tabby",
    name: c("茶トラ猫", "Ginger cat", "ちゃとらねこ"),
    index: 21,
    price: 60,
    talent: "herbs",
  },
  {
    id: "blackcat",
    name: c("黒猫", "Black cat", "くろねこ"),
    index: 22,
    price: 65,
    talent: "coins",
  },
  {
    id: "whitecat",
    name: c("白猫", "White cat", "しろねこ"),
    index: 23,
    price: 70,
    talent: "seeds",
  },
  {
    id: "rabbit",
    name: c("ウサギ", "Rabbit", "うさぎ"),
    index: 24,
    price: 75,
    talent: "seeds",
  },
  {
    id: "hamster",
    name: c("ハムスター", "Hamster", "はむすたー"),
    index: 25,
    price: 80,
    talent: "herbs",
  },
  {
    id: "hedgehog",
    name: c("ハリネズミ", "Hedgehog", "はりねずみ"),
    index: 26,
    price: 85,
    talent: "coins",
  },
  {
    id: "fox",
    name: c("キツネ", "Fox", "きつね"),
    index: 27,
    price: 90,
    talent: "seeds",
  },
  {
    id: "parrot",
    name: c("インコ", "Parrot", "いんこ"),
    index: 28,
    price: 95,
    talent: "seeds",
  },
  {
    id: "tit",
    name: c("シマエナガ", "Long-tailed tit", "しまえなが"),
    index: 29,
    price: 100,
    talent: "herbs",
  },
  {
    id: "otter",
    name: c("カワウソ", "Otter", "かわうそ"),
    index: 30,
    price: 105,
    talent: "coins",
  },
  {
    id: "dragon",
    name: c("ちびドラゴン", "Baby dragon", "ちびどらごん"),
    index: 31,
    price: 110,
    talent: "seeds",
  },
];
export const petById = (id: string) => PET_SPECIES.find((x) => x.id === id);
export const ingredientById = (id: string) =>
  cropById(id) || PRODUCTS.find((x) => x.id === id);
export const FARM_DISHES: Dish[] = [
  {
    id: "farm-dish-0",
    name: c("彩り野菜サラダ", "Garden salad", "いろどりやさいさらだ"),
    index: 0,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { turnip: 1, carrot: 1, cabbage: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-1",
    name: c("ニンジンのスープ", "Carrot soup", "にんじんのすーぷ"),
    index: 1,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { carrot: 2, milk: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-2",
    name: c("ポテトコロッケ", "Potato croquettes", "ぽてところっけ"),
    index: 2,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { potato: 2, egg: 1, wheat: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-3",
    name: c("ロールキャベツ", "Cabbage rolls", "ろーるきゃべつ"),
    index: 3,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { cabbage: 2, rice: 1, tomato: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-4",
    name: c("イチゴのタルト", "Strawberry tart", "いちごのたると"),
    index: 4,
    atlas: "farm",
    tags: ["sweet", "fresh"],
    cost: {},
    farmCost: { strawberry: 2, wheat: 1, egg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-5",
    name: c("豆のオムレツ", "Pea omelette", "まめのおむれつ"),
    index: 5,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { pea: 1, egg: 2 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-6",
    name: c("アスパラのチーズ焼き", "Cheesy asparagus", "あすぱらのちーずやき"),
    index: 6,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { asparagus: 2, cheese: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-7",
    name: c(
      "ラディッシュのピクルス",
      "Radish pickles",
      "らでぃっしゅのぴくるす",
    ),
    index: 7,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { radish: 2, cucumber: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-8",
    name: c("トマトパスタ", "Tomato pasta", "とまとぱすた"),
    index: 8,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { tomato: 2, wheat: 1, garlic: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-9",
    name: c("バターコーン", "Creamy corn", "ばたーこーん"),
    index: 9,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { corn: 2, milk: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-10",
    name: c("キュウリサンド", "Cucumber sandwich", "きゅうりさんど"),
    index: 10,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { cucumber: 2, wheat: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-11",
    name: c("ナスのグラタン", "Eggplant gratin", "なすのぐらたん"),
    index: 11,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { eggplant: 2, cheese: 1, milk: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-12",
    name: c("スイカジュース", "Watermelon juice", "すいかじゅーす"),
    index: 12,
    atlas: "farm",
    tags: ["sweet", "fresh"],
    cost: {},
    farmCost: { watermelon: 2 },
    nourish: 34,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-13",
    name: c("パイナップルパイ", "Pineapple pie", "ぱいなっぷるぱい"),
    index: 13,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { pineapple: 2, wheat: 1, egg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-14",
    name: c("パプリカ炒め", "Pepper stir-fry", "ぱぷりかいため"),
    index: 14,
    atlas: "farm",
    tags: ["fresh", "spicy"],
    cost: {},
    farmCost: { pepper: 2, soy: 1, garlic: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-15",
    name: c("野菜カレー", "Vegetable curry", "やさいかれー"),
    index: 15,
    atlas: "farm",
    tags: ["spicy", "warm"],
    cost: {},
    farmCost: { chili: 1, potato: 1, carrot: 1, rice: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-16",
    name: c("カボチャスープ", "Pumpkin soup", "かぼちゃすーぷ"),
    index: 16,
    atlas: "farm",
    tags: ["warm", "sweet"],
    cost: {},
    farmCost: { pumpkin: 2, milk: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-17",
    name: c("スイートポテト", "Sweet potato cake", "すいーとぽてと"),
    index: 17,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { sweetpotato: 2, egg: 1, milk: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-18",
    name: c("ブドウジャムトースト", "Grape jam toast", "ぶどうじゃむとーすと"),
    index: 18,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { grape: 2, wheat: 1, honey: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-19",
    name: c("アップルパイ", "Apple pie", "あっぷるぱい"),
    index: 19,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { apple: 2, wheat: 1, egg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-20",
    name: c("キノコリゾット", "Mushroom risotto", "きのこりぞっと"),
    index: 20,
    atlas: "farm",
    tags: ["herb", "warm"],
    cost: {},
    farmCost: { mushroom: 2, rice: 1, milk: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-21",
    name: c("おにぎり定食", "Rice-ball meal", "おにぎりていしょく"),
    index: 21,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { rice: 2, leek: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-22",
    name: c("焼きたてパン", "Fresh bread", "やきたてぱん"),
    index: 22,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { wheat: 2, milk: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-23",
    name: c("豆腐サラダ", "Tofu salad", "とうふさらだ"),
    index: 23,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { soy: 2, cucumber: 1, tomato: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-24",
    name: c(
      "ブロッコリーのチーズ焼き",
      "Broccoli cheese bake",
      "ぶろっこりーのちーずやき",
    ),
    index: 24,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { broccoli: 2, cheese: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-25",
    name: c(
      "ホウレンソウのキッシュ",
      "Spinach quiche",
      "ほうれんそうのきっしゅ",
    ),
    index: 25,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { spinach: 2, egg: 1, wheat: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-26",
    name: c("ネギのスープ", "Leek soup", "ねぎのすーぷ"),
    index: 26,
    atlas: "farm",
    tags: ["warm", "herb"],
    cost: {},
    farmCost: { leek: 2, potato: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-27",
    name: c("ボルシチ", "Borscht", "ぼるしち"),
    index: 27,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { beet: 2, cabbage: 1, onion: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-28",
    name: c("雪ベリーパフェ", "Snowberry parfait", "ゆきべりーぱふぇ"),
    index: 28,
    atlas: "farm",
    tags: ["sweet", "fresh"],
    cost: {},
    farmCost: { snowberry: 2, milk: 1, honey: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-29",
    name: c("オニオンスープ", "Onion soup", "おにおんすーぷ"),
    index: 29,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { onion: 2, cheese: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-30",
    name: c("ガーリックトースト", "Garlic toast", "がーりっくとーすと"),
    index: 30,
    atlas: "farm",
    tags: ["spicy"],
    cost: {},
    farmCost: { garlic: 1, wheat: 2, milk: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-31",
    name: c("緑茶プリン", "Green tea pudding", "りょくちゃぷりん"),
    index: 31,
    atlas: "farm",
    tags: ["sweet", "herb"],
    cost: {},
    farmCost: { tea: 1, milk: 1, egg: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-32",
    name: c("野菜たっぷり鍋", "Vegetable hotpot", "やさいたっぷりなべ"),
    index: 32,
    atlas: "farm",
    tags: ["warm", "herb"],
    cost: {},
    farmCost: { cabbage: 1, leek: 1, mushroom: 1, soy: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-33",
    name: c("トリュフオムレツ", "Truffle omelette", "とりゅふおむれつ"),
    index: 33,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { truffle: 1, egg: 2, cheese: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-34",
    name: c("ハチミツパンケーキ", "Honey pancakes", "はちみつぱんけーき"),
    index: 34,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { honey: 1, wheat: 1, milk: 1, duckegg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-35",
    name: c(
      "魚と野菜の香草焼き",
      "Garden fish grill",
      "さかなとやさいのこうそうやき",
    ),
    index: 35,
    atlas: "farm",
    tags: ["fish", "herb"],
    cost: { fish: 1, herb: 1 },
    farmCost: { pepper: 1, onion: 1, garlic: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-36",
    name: c("フルーツ盛り合わせ", "Fruit platter", "ふるーつもりあわせ"),
    index: 36,
    atlas: "farm",
    tags: ["sweet", "fresh"],
    cost: {},
    farmCost: { strawberry: 1, watermelon: 1, apple: 1, grape: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-37",
    name: c("収穫祭のごちそう", "Harvest feast", "しゅうかくさいのごちそう"),
    index: 37,
    atlas: "farm",
    tags: ["warm", "sweet"],
    cost: {},
    farmCost: { pumpkin: 1, corn: 1, rice: 1, egg: 1, milk: 1 },
    nourish: 49,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-38",
    name: c("冬のチーズフォンデュ", "Winter fondue", "ふゆのちーずふぉんでゅ"),
    index: 38,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { cheese: 2, broccoli: 1, potato: 1, wheat: 1 },
    nourish: 49,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-39",
    name: c("春の豆ごはん", "Spring pea rice", "はるのまめごはん"),
    index: 39,
    atlas: "farm",
    tags: ["fresh"],
    cost: {},
    farmCost: { pea: 2, rice: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-40",
    name: c("夏のピリ辛麺", "Summer spicy noodles", "なつのぴりからめん"),
    index: 40,
    atlas: "farm",
    tags: ["spicy", "fresh"],
    cost: {},
    farmCost: { chili: 1, cucumber: 1, wheat: 1, duckegg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-41",
    name: c(
      "秋のキノコ炊き込み",
      "Autumn mushroom rice",
      "あきのきのこたきこみ",
    ),
    index: 41,
    atlas: "farm",
    tags: ["warm", "herb"],
    cost: {},
    farmCost: { mushroom: 1, sweetpotato: 1, rice: 2 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-42",
    name: c("ミルクティー", "Milk tea", "みるくてぃー"),
    index: 42,
    atlas: "farm",
    tags: ["sweet", "warm", "herb"],
    cost: {},
    farmCost: { tea: 1, milk: 1, honey: 1 },
    nourish: 39,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-43",
    name: c("ベリーヨーグルト", "Berry yogurt", "べりーよーぐると"),
    index: 43,
    atlas: "farm",
    tags: ["sweet", "fresh"],
    cost: {},
    farmCost: { snowberry: 1, strawberry: 1, milk: 2 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-44",
    name: c(
      "養蜂家のビスケット",
      "Beekeeper biscuits",
      "ようほうかのびすけっと",
    ),
    index: 44,
    atlas: "farm",
    tags: ["sweet"],
    cost: {},
    farmCost: { honey: 2, wheat: 1, egg: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-45",
    name: c(
      "牧場のクリームシチュー",
      "Ranch cream stew",
      "ぼくじょうのくりーむしちゅー",
    ),
    index: 45,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { milk: 2, potato: 1, carrot: 1, broccoli: 1 },
    nourish: 49,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-46",
    name: c(
      "大豆とコーンのスープ",
      "Soy and corn soup",
      "だいずとこーんのすーぷ",
    ),
    index: 46,
    atlas: "farm",
    tags: ["warm"],
    cost: {},
    farmCost: { soy: 1, corn: 2, onion: 1 },
    nourish: 44,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
  {
    id: "farm-dish-47",
    name: c("四季の特製弁当", "Four-season lunchbox", "しきのとくせいべんとう"),
    index: 47,
    atlas: "farm",
    tags: ["fresh", "warm"],
    cost: {},
    farmCost: { rice: 2, egg: 1, carrot: 1, spinach: 1, apple: 1 },
    nourish: 54,
    steps: [
      c("切る・混ぜる", "Prepare", "きる・まぜる"),
      c("火加減を合わせる", "Control the heat", "ひかげんをあわせる"),
      c("盛りつける", "Plate", "もりつける"),
    ],
  },
];
