export const RPG_RHYTHM_ENGLISH: Record<string, string> = {
  音ゲー筐体: "Rhythm arcade cabinet",
  学ロリズム: "Gakuro Rhythm",
  "全曲で遊べる4レーン音ゲー。D・F・J・K、矢印キー、または画面下のボタンで演奏。長いノーツは終わりまで押して離します。":
    "Play every song on four lanes. Use D/F/J/K, arrow keys, or the buttons below. Hold long notes until their end, then release.",
  スコア対戦: "Score battle",
  準備OK: "Ready",
  準備待ち: "Waiting for readiness",
  スコア: "Score",
  一時停止: "Pause",
  再開: "Resume",
  退出: "Leave",
  演奏ゲージ: "Performance gauge",
  音ゲーの4レーン: "Four rhythm lanes",
  レーン: "Lane",
  一時停止中: "Paused",
  かんたん: "Easy",
  ふつう: "Normal",
  むずかしい: "Expert",
  難易度: "Difficulty",
  曲の長さ: "Song length",
  フル演奏: "Full song",
  "90秒モード": "90-second mode",
  ノーツ速度: "Note speed",
  タイミング調整: "Timing offset",
  "楽曲を再生できませんでした。読み込み直して準備してください。":
    "Could not play this song. Reload it and prepare again.",
  楽曲を読み込み中: "Loading song",
  楽曲読み込み完了: "Song loaded",
  楽曲を試聴: "Preview song",
  試聴を止める: "Stop preview",
  準備する: "Get ready",
  演奏を開始: "Start performance",
  読み込み直す: "Reload song",
  "クリア！": "Cleared!",
  "もう一度挑戦！": "Try again!",
  最大コンボ: "Max combo",
  達成率: "Achievement",
  自己ベスト: "Personal best",
  ノーツ: "Notes",
  楽曲を選ぶ: "Choose song",
  曲を検索: "Search songs",
  編を選ぶ: "Choose chapter",
  BGMの種類: "BGM edition",
  "演奏が終わりました！": "Performance finished!",
  "音ゲー設定を更新しました。": "Rhythm settings updated.",
  "全員の楽曲読み込みを待っています。":
    "Waiting for everyone to load the song.",
  高校編: "High school",
  "マジック編・女性": "Magic · female",
  "マジック編・男性": "Magic · male",
  マジック編: "Magic",
  "共通・小学校編": "Common · elementary",
  新BGM: "New BGM",
  旧BGM: "Classic BGM",
  通常戦闘: "Battle",
  ボス戦: "Boss battle",
  中ボス戦: "Mid-boss battle",
  最終決戦: "Final battle",
  メニュー: "Menu",
  冒険マップ: "Adventure map",
  お店: "Shop",
  休憩: "Rest",
  イベント: "Event",
  学習問題: "Study questions",
  報酬: "Rewards",
  勝利: "Victory",
  ゲームオーバー: "Game over",
  レリック選択: "Relic selection",
  学校探索: "School exploration",
  体育館: "Gym",
  理科室: "Science room",
  音楽室: "Music room",
  図書室: "Library",
  屋上: "Rooftop",
  ダンジョンボス: "Dungeon boss",
  校長戦の準備: "Principal battle setup",
  校長との戦闘: "Principal battle",
  校長との決戦: "Principal showdown",
  ポーカー: "Poker",
  ポーカーのお店: "Poker shop",
  サバイバル: "Survival",
  紙飛行機の準備: "Paper plane setup",
  紙飛行機バトル: "Paper plane battle",
  紙飛行機の休暇: "Paper plane vacation",
};
export const RPG_RHYTHM_HIRAGANA: Record<string, string> = {
  音ゲー筐体: "おとげー きょうたい",
  学ロリズム: "がくろりずむ",
  "全曲で遊べる4レーン音ゲー。D・F・J・K、矢印キー、または画面下のボタンで演奏。長いノーツは終わりまで押して離します。":
    "ぜんきょくで あそべる よんれーん おとげー。D・F・J・K、やじるしきー、または がめんしたの ぼたんで えんそう。ながい のーつは おわりまで おして はなします。",
  スコア対戦: "すこあたいせん",
  準備OK: "じゅんびOK",
  準備待ち: "じゅんびまち",
  スコア: "すこあ",
  一時停止: "いちじていし",
  再開: "さいかい",
  退出: "たいしゅつ",
  演奏ゲージ: "えんそうげーじ",
  音ゲーの4レーン: "おとげーの よんれーん",
  レーン: "れーん",
  一時停止中: "いちじていしちゅう",
  かんたん: "かんたん",
  ふつう: "ふつう",
  むずかしい: "むずかしい",
  難易度: "なんいど",
  曲の長さ: "きょくの ながさ",
  フル演奏: "ふるえんそう",
  "90秒モード": "90びょうもーど",
  ノーツ速度: "のーつそくど",
  タイミング調整: "たいみんぐちょうせい",
  "楽曲を再生できませんでした。読み込み直して準備してください。":
    "がっきょくを さいせいできませんでした。よみこみなおして じゅんびしてください。",
  楽曲を読み込み中: "がっきょくを よみこみちゅう",
  楽曲読み込み完了: "がっきょく よみこみかんりょう",
  楽曲を試聴: "がっきょくを しちょう",
  試聴を止める: "しちょうを とめる",
  準備する: "じゅんびする",
  演奏を開始: "えんそうを かいし",
  読み込み直す: "よみこみなおす",
  "クリア！": "くりあ！",
  "もう一度挑戦！": "もういちど ちょうせん！",
  最大コンボ: "さいだいこんぼ",
  達成率: "たっせいりつ",
  自己ベスト: "じこべすと",
  ノーツ: "のーつ",
  楽曲を選ぶ: "がっきょくを えらぶ",
  曲を検索: "きょくを けんさく",
  編を選ぶ: "へんを えらぶ",
  BGMの種類: "BGMの しゅるい",
  "演奏が終わりました！": "えんそうが おわりました！",
  "音ゲー設定を更新しました。": "おとげーせっていを こうしんしました。",
  "全員の楽曲読み込みを待っています。":
    "ぜんいんの がっきょくよみこみを まっています。",
  高校編: "こうこうへん",
  "マジック編・女性": "まじっくへん・じょせい",
  "マジック編・男性": "まじっくへん・だんせい",
  マジック編: "まじっくへん",
  "共通・小学校編": "きょうつう・しょうがっこうへん",
  新BGM: "しんBGM",
  旧BGM: "きゅうBGM",
  通常戦闘: "つうじょうせんとう",
  ボス戦: "ぼすせん",
  中ボス戦: "ちゅうぼすせん",
  最終決戦: "さいしゅうけっせん",
  メニュー: "めにゅー",
  冒険マップ: "ぼうけんまっぷ",
  お店: "おみせ",
  休憩: "きゅうけい",
  イベント: "いべんと",
  学習問題: "がくしゅうもんだい",
  報酬: "ほうしゅう",
  勝利: "しょうり",
  ゲームオーバー: "げーむおーばー",
  レリック選択: "れりっくせんたく",
  学校探索: "がっこうたんさく",
  体育館: "たいいくかん",
  理科室: "りかしつ",
  音楽室: "おんがくしつ",
  図書室: "としょしつ",
  屋上: "おくじょう",
  ダンジョンボス: "だんじょんぼす",
  校長戦の準備: "こうちょうせんの じゅんび",
  校長との戦闘: "こうちょうとの せんとう",
  校長との決戦: "こうちょうとの けっせん",
  ポーカー: "ぽーかー",
  ポーカーのお店: "ぽーかーの おみせ",
  サバイバル: "さばいばる",
  紙飛行機の準備: "かみひこうきの じゅんび",
  紙飛行機バトル: "かみひこうきばとる",
  紙飛行機の休暇: "かみひこうきの きゅうか",
};
