import { trans } from '../../utils/textUtils';
import type { LanguageMode } from '../../types';
import React from 'react';
import { ACCESSORIES, AVATAR_COLORS, AVATAR_SPECIES, BODY_COLORS, HAIR_COLORS, HAIR_STYLES, KART_SHAPES, EXPRESSIONS, EXPRESSION_ICONS, FACE_SHAPES, FACE_STYLES, EYE_STYLES, EYE_COLORS, type KartAvatar } from './avatar';
export default function AvatarCreator({ value, onChange, languageMode, activity = 'kart' }: { value: KartAvatar; onChange: (avatar: KartAvatar) => void; languageMode: LanguageMode; activity?: 'kart' | 'golf' | 'vr' }) {
  const t = (text: string) => trans(text, languageMode);
  const options=(label:string,key:'faceShape'|'faceStyle'|'eyeStyle',values:readonly string[]) => <fieldset><legend>{t(label)}</legend><div className={`gk-avatar-options gk-${key}`}>{values.map((name,i)=><button type="button" key={name} aria-pressed={(value[key]??0)===i} onClick={()=>onChange({...value,[key]:i})}>{t(name)}</button>)}</div></fieldset>;
  const colors = (label: string, key: 'body' | 'outfit' | 'hair', palette: string[]) => <fieldset><legend>{t(label)}</legend><div className="gk-avatar-swatches">{palette.map((color, i) => <button type="button" key={color} aria-label={`${t(label)} ${i + 1}`} aria-pressed={value[key] === i} style={{ '--swatch': color } as React.CSSProperties} onClick={() => onChange({ ...value, [key]: i })}><span />{value[key] === i && <b aria-hidden="true">✓</b>}</button>)}</div></fieldset>;
  return <section className="gk-avatar-editor" aria-label={t('キャラクタークリエイト')}><div className="gk-avatar-heading"><span>{activity === 'vr' ? 'YOUR VR AGENT' : activity === 'golf' ? 'YOUR GOLFER' : 'YOUR DRIVER'}</span><h3>{t('キャラクタークリエイト')}</h3></div><p>{activity === 'vr' ? (languageMode === 'ENGLISH' ? 'Your character is shared by solo and online training.' : 'ソロ・オンライン共通の主人公を作成します。') : t(activity === 'golf' ? 'ラウンド開始前まで自由に変更できます。' : 'レース開始前まで自由に変更できます。')}</p>
    <fieldset><legend>{t('キャラクターの種類')}</legend><div className="gk-avatar-species">{AVATAR_SPECIES.map((s, i) => <button type="button" key={s.id} aria-pressed={value.species === i} onClick={() => onChange({ ...value, species: i, accessory:i!==0&&value.accessory>3?0:value.accessory })}><span aria-hidden="true">{s.icon}</span><b>{t(s.name)}</b></button>)}</div></fieldset>
    <fieldset><legend>{t('表情')}</legend><div className="gk-avatar-options gk-expressions">{EXPRESSIONS.map((expression, i) => <button type="button" key={expression} aria-pressed={value.expression === i} onClick={() => onChange({ ...value, expression: i })}><span aria-hidden="true">{EXPRESSION_ICONS[i]}</span> {t(expression)}</button>)}</div></fieldset>
    {value.species === 0 && <fieldset><legend>{t('髪型')}</legend><div className="gk-avatar-options gk-hairstyles">{HAIR_STYLES.map((style, i) => <button type="button" key={style} aria-pressed={value.hairStyle === i} onClick={() => onChange({ ...value, hairStyle: i })}>{t(style)}</button>)}</div></fieldset>}
    {activity === 'kart' && <fieldset><legend>{t('カートの形')}</legend><div className="gk-avatar-options gk-kart-shapes">{KART_SHAPES.map((shape, i) => <button type="button" key={shape} aria-pressed={value.kart === i} onClick={() => onChange({ ...value, kart: i })}>{t(shape)}</button>)}</div><small>{t('形は見た目のみ変わります。走行性能は共通です。')}</small></fieldset>}
    {colors('体・肌の色', 'body', BODY_COLORS)}{colors(activity !== 'kart' ? '服の色' : '服・カートの色', 'outfit', AVATAR_COLORS)}{value.species === 0 && value.hairStyle !== 11 && colors('髪の色', 'hair', HAIR_COLORS)}
    {value.species === 0 && value.accessory === 2 && <p>{t('ヘルメットを外すと選んだ髪型が見えます。')}</p>}
    {value.species===0&&<>{options('顔の輪郭','faceShape',FACE_SHAPES)}{options('顔つき','faceStyle',FACE_STYLES)}{options('目の形','eyeStyle',EYE_STYLES)}<fieldset><legend>{t('瞳の色')}</legend><div className="gk-avatar-swatches">{EYE_COLORS.map((color,i)=><button type="button" key={color} aria-label={`${t('瞳の色')} ${i+1}`} aria-pressed={(value.eyeColor??0)===i} style={{'--swatch':color} as React.CSSProperties} onClick={()=>onChange({...value,eyeColor:i})}><span/>{(value.eyeColor??0)===i&&<b aria-hidden="true">✓</b>}</button>)}</div></fieldset></>}
    <fieldset><legend>{t('アクセサリー')}</legend><div className="gk-avatar-accessories">{ACCESSORIES.map((a, i) => (value.species===0||i<4)&&<button type="button" key={a} aria-pressed={value.accessory === i} onClick={() => onChange({ ...value, accessory: i })}>{t(a)}</button>)}</div></fieldset>
    <small>{t('作成したキャラクターは次回も使えます。')}</small>
  </section>;
}
