const copy: [string, string, string][] = [
  ["カートの問題選択", "Choose kart questions", "カートの もんだいせんたく"],
  ["4択固定・スタート直線で3問", "Four choices · Three questions on the starting straight", "4たくこてい・スタートちょくせんで3もん"],
  ["配信課題を選ぶ", "Choose an assignment", "はいしんかだいを えらぶ"],
  ["受け取り済みの課題", "Received assignment", "うけとりずみの かだい"],
  ["問題とコースを準備中…", "Preparing questions and course…", "もんだいと コースを じゅんびちゅう…"],
  ["学習電光掲示板", "Learning scoreboard", "がくしゅう でんこうけいじばん"],
  ["クラッシュ！", "CRASH!", "クラッシュ！"],
  ["減速…", "SLOWDOWN…", "げんそく…"],
  ["そのままレースへ", "RACE ON", "そのまま レースへ"],
  ["全問正解！ブースト！", "PERFECT! BOOST!", "ぜんもんせいかい！ブースト！"],
  ["正しいレーンでゲートを通過", "Cross the gate in the correct lane", "ただしいレーンで ゲートをつうか"],
  ["問題を選び直す", "Change questions", "もんだいを えらびなおす"],
  ["問題の図", "Question diagram", "もんだいのず"],
  ["正答", "Correct answer", "せいとう"],
  ["この範囲には出題できる問題がありません。", "No questions are available for this selection.", "このはんいには しゅつだいできる もんだいがありません。"],
  ["問題データが大きすぎます。別の範囲を選んでください。", "These questions are too large. Choose another selection.", "もんだいデータが おおきすぎます。べつのはんいを えらんでください。"],

  ['40人オンラインレース', '40-player online racing', '40にん オンラインレース'],
  ['放課後を、ぶっちぎれ。', 'Leave the school day in your dust.', 'ほうかごを、ぶっちぎれ。'],
  ['走る準備は、いい？', 'Ready for the grid?', 'はしる じゅんびは、いい？'],
  ['40台でレース', 'Race a 40-kart grid', '40だいで レース'],
  ['参加 →', 'Join →', 'さんか →'],
  ['ひとりでも39台のライバル。オンラインは最大40人。', '39 CPU rivals in solo. Up to 40 players online.', 'ひとりでも39だいの ライバル。オンラインは さいだい40にん。'],
  ['曲がって、ためる。', 'Carve. Charge. Launch.', 'まがって、ためる。'],
  ['左右でハンドル。カーブでドリフトを押し続け、離してターボ。長くためるほど強く加速。', 'Steer left and right. Hold drift in a corner, then release for a turbo. Longer charges give stronger boosts.', 'さゆうで ハンドル。カーブで ドリフトを おしつづけ、はなして ターボ。ながく ためるほど つよく かそく。'],
  ['背中を追って、抜く。', 'Draft. Jump. Overtake.', 'せなかを おって、ぬく。'],
  ['前の車の真後ろでスリップストリーム。加速パネルとジャンプ台をつなぎ、ライバルを抜き去ろう。', 'Draft directly behind a rival. Chain boost pads and jumps to fly past the field.', 'まえの くるまの まうしろで スリップストリーム。かそくパネルと ジャンプだいを つなぎ、ライバルを ぬきさろう。'],
  ['最後まで、逆転。', 'Fight for the finish.', 'さいごまで、ぎゃくてん。'],
  ['光るクリスタルでアイテム獲得。ニトロ、防御、前方へのパルス、追い上げロケット。勝負は3周。', 'Collect glowing crystals for nitro, shields, forward pulses or comeback rockets. Three laps decide the winner.', 'ひかる クリスタルで アイテムかくとく。ニトロ、ぼうぎょ、ぜんぽうへの パルス、おいあげ ロケット。しょうぶは3しゅう。'],
  ['スターティンググリッド', 'Starting grid', 'スターティンググリッド'],
  ['ホストは画面を開いたままプレイしてください。', 'The host must keep this screen open while racing.', 'ホストは がめんを ひらいたまま プレイしてください。'],
  ['空き枠をCPUで埋める', 'Fill empty slots with CPU racers', 'あきわくをCPUで うめる'],
  ['レースを開始 →', 'Start the race →', 'レースを かいし →'],
  ['ホストのスタートを待っています。', 'Waiting for the host to start.', 'ホストの スタートを まっています。'],
  ['全員のゴールを待っています。', 'Waiting for the rest of the grid to finish.', 'ぜんいんの ゴールを まっています。'],
  ['もう一度レース', 'Restart the race', 'もういちど レース'],
  ['ホストの再戦を待っています。', 'Waiting for the host to restart.', 'ホストの さいせんを まっています。'],
  ['ネオン・キャンパス', 'Neon Campus', 'ネオン・キャンパス'],
  ['クラウド・ガーデン', 'Cloud Garden', 'クラウド・ガーデン'],
  ['ソーラー・ワークス', 'Solar Works', 'ソーラー・ワークス'],
  ['ホストの画面が戻るまで一時停止しています。', 'Paused until the host returns to the race.', 'ホストの がめんが もどるまで いちじていししています。'],
  ['通信が途切れました。部屋に入り直してください。', 'Connection lost. Please rejoin the room.', 'つうしんが とぎれました。へやに はいりなおしてください。'],
];
export const KART_ENGLISH = Object.fromEntries(copy.map(([jp, en]) => [jp, en]));
export const KART_HIRAGANA = Object.fromEntries(copy.map(([jp, , hira]) => [jp, hira]));
