const copy: [string, string, string][] = [
 ["拡大・縮小","Zoom in / out","かくだい・しゅくしょう"],
 ["編集する点","Point to edit","へんしゅうするてん"],
 ["配置物を選ぶ","Select object","はいちぶつをえらぶ"],
  ["オリジナルコース作成", "Create custom course", "オリジナルコースさくせい"],
  ["オリジナルコース", "Custom course", "オリジナルコース"],
  ["問題のストレートは固定。点を動かして、その先のコースを作ろう。", "The quiz straight is fixed. Move points to design the track beyond it.", "もんだいのストレートはこてい。てんをうごかして、そのさきのコースをつくろう。"],
  ["コースを動かす", "Move track points", "コースをうごかす"],
  ["ブースト板", "Boost pad", "ブーストばん"],
  ["ジャンプ台", "Jump ramp", "ジャンプだい"],
  ["アイテム箱", "Item box", "アイテムばこ"],
  ["コースの点", "Track point", "コースのてん"],
  ["水色の点をドラッグ。配置ツールを選んで道をタッチ。金色は変更できない区間です。", "Drag cyan points. Select a placement tool and tap the road. Gold marks the fixed section.", "みずいろのてんをドラッグ。はいちツールをえらんでみちをタッチ。きんいろはへんこうできないくかんです。"],
  ["コース編集マップ", "Course editor map", "コースへんしゅうマップ"],
  ["コース名", "Course name", "コースめい"],
  ["背景テーマ", "Scenery theme", "はいけいテーマ"],
  ["コース上の位置", "Position along track", "コースじょうのいち"],
  ["左右の位置", "Lane position", "さゆうのいち"],
  ["配置物を削除", "Delete object", "はいちぶつをさくじょ"],
  ["横位置", "Horizontal position", "よこいち"],
  ["高さ", "Height", "たかさ"],
  ["縦位置", "Vertical position", "たていち"],
  ["保存したコース", "Saved courses", "ほぞんしたコース"],
  ["保存コースを削除", "Delete saved course", "ほぞんコースをさくじょ"],
  ["基本形に戻す", "Reset to template", "きほんけいにもどす"],
  ["ファイルに書き出す", "Export course file", "ファイルにかきだす"],
  ["ファイルを読み込む", "Import course file", "ファイルをよみこむ"],
  ["この端末に保存", "Save on this device", "このたんまつにほぞん"],
  ["このコースで遊ぶ", "Use this course", "このコースであそぶ"],
  ["コースを保存しました。", "Course saved.", "コースをほぞんしました。"],
  ["保存できませんでした。", "Could not save.", "ほぞんできませんでした。"],
  ["コースファイルが不正です。", "Invalid course file.", "コースファイルがふせいです。"],
  ["コースデータが不正です。", "Invalid course data.", "コースデータがふせいです。"],
  ["コースの範囲を超えています。", "Outside course bounds.", "コースのはんいをこえています。"],
  ["問題のストレートと接続部分は変更できません。", "The quiz straight and lap connection cannot be changed.", "もんだいのストレートとせつぞくぶぶんはへんこうできません。"],
  ["コースの点を60m以上離してください。", "Keep track points at least 60 m apart.", "コースのてんを60mいじょうはなしてください。"],
  ["配置物が不正です。", "Invalid track object.", "はいちぶつがふせいです。"],
  ["走行できるコースに調整してください。", "Adjust the course to a driveable length and shape.", "そうこうできるコースにちょうせいしてください。"],
  ["配置物は問題のストレートの後に置いてください。", "Place objects after the quiz straight.", "はいちぶつはもんだいのストレートのあとにおいてください。"],
  ["元に戻す", "Undo", "もとにもどす"],
  ["やり直す", "Redo", "やりなおす"],
  ["招待リンク", "Invitation link", "しょうたいリンク"],
  ["約3秒スピードアップ", "Speed boost for ~3s", "やく3びょう スピードアップ"],
  ["6秒間防御＋減速を解除", "6s shield + clear slowdown", "6びょうかん ぼうぎょ＋げんそくを かいじょ"],
  ["前方の最大3台を減速", "Slow up to 3 racers ahead", "ぜんぽうの さいだい3だいを げんそく"],
  ["約5秒加速＋攻撃を防ぐ", "~5s boost + attack shield", "やく5びょう かそく＋こうげきを ふせぐ"],
  ["次のコース", "Next course", "つぎの コース"],
  ["参加者とキャラクターを引き継いで走れます。", "Keep the same racers and characters for the next race.", "さんかしゃと キャラクターを ひきついで はしれます。"],
  ["周回数", "Laps per course", "しゅうかいすう"],
  ["ホストが設定した周回数です。", "Lap count selected by the host.", "ホストが せっていした しゅうかいすうです。"],
  ["このレースで走る周回数を設定します（1〜5周）。", "Choose the number of laps for this race (1–5).", "このレースで はしる しゅうかいすうを せっていします（1〜5しゅう）。"],
  ["1周", "1 lap", "1しゅう"], ["2周", "2 laps", "2しゅう"], ["3周", "3 laps", "3しゅう"], ["4周", "4 laps", "4しゅう"], ["5周", "5 laps", "5しゅう"],
  ["図書館ループ", "Library Loop", "としょかんループ"],
  ["森の教室", "Forest Classroom", "もりの きょうしつ"],
  ["海辺の学校", "Harbor School", "うみべの がっこう"],
  ["オーロラ研究所", "Aurora Lab", "オーロラけんきゅうじょ"],
  ["放課後スタジアム", "After-school Stadium", "ほうかごスタジアム"],
  ["順位・タイム確定！結果がそろうまで自由に走れます。", "Result locked! Keep driving until all results are ready.", "じゅんい・タイムかくてい！けっかが そろうまで じゆうに はしれます。"],
  ["表情", "Expression", "ひょうじょう"],
  ["ふつう", "Neutral", "ふつう"],
  ["にっこり", "Smile", "にっこり"],
  ["大笑い", "Laughing", "おおわらい"],
  ["真剣", "Focused", "しんけん"],
  ["怒り顔", "Angry", "おこりがお"],
  ["びっくり", "Surprised", "びっくり"],
  ["ウインク", "Wink", "ウインク"],
  ["ねむそう", "Sleepy", "ねむそう"],
  ["髪型", "Hairstyle", "かみがた"],
  ["カートの形", "Kart shape", "カートの かたち"],
  ["ショート", "Short", "ショート"],
  ["ボブ", "Bob", "ボブ"],
  ["ロング", "Long", "ロング"],
  ["ポニーテール", "Ponytail", "ポニーテール"],
  ["ツインテール", "Twin tails", "ツインテール"],
  ["おだんご", "Hair bun", "おだんご"],
  ["アフロ", "Afro", "アフロ"],
  ["モヒカン", "Mohawk", "モヒカン"],
  ["スパイキー", "Spiky", "スパイキー"],
  ["七三分け", "Side part", "しちさんわけ"],
  ["三つ編み", "Braid", "みつあみ"],
  ["スキンヘッド", "Bald", "スキンヘッド"],
  ["スタンダード", "Standard", "スタンダード"],
  ["フォーミュラ", "Formula", "フォーミュラ"],
  ["バギー", "Buggy", "バギー"],
  ["スポーツカー", "Sports car", "スポーツカー"],
  ["ロケット", "Rocket", "ロケット"],
  ["ホバー", "Hover", "ホバー"],
  ["スクールバス", "School bus", "スクールバス"],
  ["ピックアップ", "Pickup", "ピックアップ"],
  ["形は見た目のみ変わります。走行性能は共通です。", "Shapes change appearance only. Handling is shared.", "かたちは みためのみ かわります。そうこうせいのうは きょうつうです。"],
  ["ヘルメットを外すと選んだ髪型が見えます。", "Remove the helmet to see your chosen hairstyle.", "ヘルメットを はずすと えらんだ かみがたが みえます。"],
  ["キャラクタークリエイト", "Create your character", "キャラクタークリエイト"],
  ["レース開始前まで自由に変更できます。", "Customize freely until the race starts.", "レースかいしまえまで じゆうに へんこうできます。"],
  ["キャラクターの種類", "Character type", "キャラクターの しゅるい"],
  ["体・肌の色", "Body / skin color", "からだ・はだの いろ"],
  ["服・カートの色", "Outfit / kart color", "ふく・カートの いろ"],
  ["髪の色", "Hair color", "かみの いろ"],
  ["アクセサリー", "Accessories", "アクセサリー"],
  ["人間", "Human", "にんげん"],
  ["猫", "Cat", "ねこ"],
  ["犬", "Dog", "いぬ"],
  ["ウサギ", "Rabbit", "ウサギ"],
  ["キツネ", "Fox", "キツネ"],
  ["パンダ", "Panda", "パンダ"],
  ["ペンギン", "Penguin", "ペンギン"],
  ["ロボット", "Robot", "ロボット"],
  ["なし", "None", "なし"],
  ["ゴーグル", "Goggles", "ゴーグル"],
  ["レーサーヘルメット", "Racing helmet", "レーサーヘルメット"],
  ["王冠", "Crown", "おうかん"],
  ["作成したキャラクターは次回も使えます。", "Your character is saved for next time.", "つくった キャラクターは じかいも つかえます。"],
  ["4択固定・各周のスタート直線で3問", "Four choices · Three questions at the start of each lap", "4たくこてい・かくしゅうの スタートちょくせんで3もん"],
  ["カートの問題選択", "Choose kart questions", "カートの もんだいせんたく"],
  ["4択固定・スタート直線で3問", "Four choices · Three questions on the starting straight", "4たくこてい・スタートちょくせんで3もん"],
  ["配信課題を選ぶ", "Choose an assignment", "はいしんかだいを えらぶ"],
  ["受け取り済みの課題", "Received assignment", "うけとりずみの かだい"],
  ["問題とコースを準備中…", "Preparing questions and course…", "もんだいと コースを じゅんびちゅう…"],
  ["学習電光掲示板", "Learning scoreboard", "がくしゅう でんこうけいじばん"],
  ["クラッシュ！", "CRASH!", "クラッシュ！"],
  ["減速…", "SLOWDOWN…", "げんそく…"],
  ["そのままレースへ", "RACE ON", "そのまま レースへ"],
  ["全問正解！ブースト！", "PERFECT! BOOST!", "ぜんもんせいかい！ブースト！"],
  ["正しいレーンでゲートを通過", "Cross the gate in the correct lane", "ただしいレーンで ゲートをつうか"],
  ["問題を選び直す", "Change questions", "もんだいを えらびなおす"],
  ["問題の図", "Question diagram", "もんだいのず"],
  ["正答", "Correct answer", "せいとう"],
  ["この範囲には出題できる問題がありません。", "No questions are available for this selection.", "このはんいには しゅつだいできる もんだいがありません。"],
  ["問題データが大きすぎます。別の範囲を選んでください。", "These questions are too large. Choose another selection.", "もんだいデータが おおきすぎます。べつのはんいを えらんでください。"],

  ['40人オンラインレース', '40-player online racing', '40にん オンラインレース'],
  ['放課後を、ぶっちぎれ。', 'Leave the school day in your dust.', 'ほうかごを、ぶっちぎれ。'],
  ['走る準備は、いい？', 'Ready for the grid?', 'はしる じゅんびは、いい？'],
  ['40台でレース', 'Race a 40-kart grid', '40だいで レース'],
  ['参加 →', 'Join →', 'さんか →'],
  ['ひとりでも39台のライバル。オンラインは最大40人。', '39 CPU rivals in solo. Up to 40 players online.', 'ひとりでも39だいの ライバル。オンラインは さいだい40にん。'],
  ['曲がって、ためる。', 'Carve. Charge. Launch.', 'まがって、ためる。'],
  ['左右でハンドル。カーブでドリフトを押し続け、離してターボ。長くためるほど強く加速。', 'Steer left and right. Hold drift in a corner, then release for a turbo. Longer charges give stronger boosts.', 'さゆうで ハンドル。カーブで ドリフトを おしつづけ、はなして ターボ。ながく ためるほど つよく かそく。'],
  ['背中を追って、抜く。', 'Draft. Jump. Overtake.', 'せなかを おって、ぬく。'],
  ['前の車の真後ろでスリップストリーム。加速パネルとジャンプ台をつなぎ、ライバルを抜き去ろう。', 'Draft directly behind a rival. Chain boost pads and jumps to fly past the field.', 'まえの くるまの まうしろで スリップストリーム。かそくパネルと ジャンプだいを つなぎ、ライバルを ぬきさろう。'],
  ['最後まで、逆転。', 'Fight for the finish.', 'さいごまで、ぎゃくてん。'],
  ['光るクリスタルでアイテム獲得。ニトロ、防御、前方へのパルス、追い上げロケット。周回数はホストが決める。', 'Collect glowing crystals for nitro, shields, forward pulses or comeback rockets. The host sets the lap count.', 'ひかる クリスタルで アイテムかくとく。ニトロ、ぼうぎょ、ぜんぽうへの パルス、おいあげ ロケット。しゅうかいすうは ホストが きめる。'],
  ['スターティンググリッド', 'Starting grid', 'スターティンググリッド'],
  ['ホストは画面を開いたままプレイしてください。', 'The host must keep this screen open while racing.', 'ホストは がめんを ひらいたまま プレイしてください。'],
  ['空き枠をCPUで埋める', 'Fill empty slots with CPU racers', 'あきわくをCPUで うめる'],
  ['レースを開始 →', 'Start the race →', 'レースを かいし →'],
  ['ホストのスタートを待っています。', 'Waiting for the host to start.', 'ホストの スタートを まっています。'],
  ['全員のゴールを待っています。', 'Waiting for the rest of the grid to finish.', 'ぜんいんの ゴールを まっています。'],
  ['もう一度レース', 'Restart the race', 'もういちど レース'],
  ['ホストの再戦を待っています。', 'Waiting for the host to restart.', 'ホストの さいせんを まっています。'],
  ['ネオン・キャンパス', 'Neon Campus', 'ネオン・キャンパス'],
  ['クラウド・ガーデン', 'Cloud Garden', 'クラウド・ガーデン'],
  ['ソーラー・ワークス', 'Solar Works', 'ソーラー・ワークス'],
  ['ホストの画面が戻るまで一時停止しています。', 'Paused until the host returns to the race.', 'ホストの がめんが もどるまで いちじていししています。'],
  ['通信が途切れました。部屋に入り直してください。', 'Connection lost. Please rejoin the room.', 'つうしんが とぎれました。へやに はいりなおしてください。'],
];
export const KART_ENGLISH = Object.fromEntries(copy.map(([jp, en]) => [jp, en]));
export const KART_HIRAGANA = Object.fromEntries(copy.map(([jp, , hira]) => [jp, hira]));
