"""Analyze every original soundtrack file (ffmpeg + numpy); web-audio copies are codecs of these same songs.
Run: python scripts/generate-rpg-rhythm-catalog.py
The committed catalogue lets browsers stream one song without downloading/decoding the whole library.
"""
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import subprocess, json, numpy as np
root = Path(__file__).resolve().parents[1]
files = sorted(p for folder in ['bgm', 'bgm-new'] for p in (root/'public'/folder).rglob('*.mp3'))
def analyze(path):
    pcm = subprocess.check_output(['ffmpeg','-v','error','-i',str(path),'-f','f32le','-ac','1','-ar','11025','pipe:1'])
    x = np.frombuffer(pcm, dtype='<f4'); duration = len(x)/11025
    if len(x)<1024: x=np.pad(x,(0,1024-len(x)))
    frames=np.lib.stride_tricks.sliding_window_view(x,1024)[::256]
    spec=np.abs(np.fft.rfft(frames*np.hanning(1024),axis=1))
    flux=np.maximum(0,np.diff(np.log1p(spec),axis=0)).mean(axis=1)
    flux=np.convolve(flux,[.2,.6,.2],mode='same')
    centered=flux-flux.mean(); n=1<<(len(centered)*2-1).bit_length()
    corr=np.fft.irfft(np.abs(np.fft.rfft(centered,n))**2,n)[:len(centered)]
    lo=int(11025/256*60/185); hi=min(len(corr)-1,int(11025/256*60/75))
    lag=max(range(lo,hi+1),key=lambda k:corr[k]) if hi>=lo else 22
    bpm=round(60*11025/256/lag,2); step=60/bpm
    phaseScores=[]
    for phase in np.linspace(0,step,80,endpoint=False):
        ix=np.round((np.arange(phase,duration,step)*11025-512)/256).astype(int)
        ix=ix[(ix>=0)&(ix<len(flux))]
        phaseScores.append(float(flux[ix].sum()) if len(ix) else 0)
    offset=round(int(np.argmax(phaseScores))*step/80,3)
    threshold=flux.mean()+flux.std()*.2; peaks=[]; peakPower=[]
    for i in range(1,len(flux)-1):
        t=(i*256+512)/11025
        if flux[i]>threshold and flux[i]>=flux[i-1] and flux[i]>flux[i+1] and (not peaks or t-peaks[-1]/1000>.115):
            peaks.append(round(t*1000)); peakPower.append(round(float(flux[i]/max(.000001,flux.max()))*100))
    rel=path.relative_to(root/'public').as_posix()
    return dict(id=rel.removesuffix('.mp3').replace('/',':'),path=rel,duration=round(duration,3),bpm=bpm,offset=offset,onsets=peaks,power=peakPower)
with ThreadPoolExecutor(max_workers=4) as pool: songs=list(pool.map(analyze,files))
target=root/'src/rpg/rhythm/catalog.generated.ts'
def base36(n):
    digits='0123456789abcdefghijklmnopqrstuvwxyz'; result=''
    while n: result=digits[n%36]+result; n//=36
    return result or '0'
def write_catalog(songs):
    packed=[]
    for song in songs:
        previous=0; entries=[]
        for ms, power in zip(song['onsets'],song['power']):
            entries.append(base36(ms-previous)+':'+base36(power)); previous=ms
        packed.append({k:v for k,v in song.items() if k not in ['onsets','power']}|{'beats':','.join(entries)})
    target.write_text('// Generated by scripts/generate-rpg-rhythm-catalog.py. Delta/base36 strings keep the soundtrack out of the TypeScript AST.\nexport interface RhythmSong {id:string;path:string;duration:number;bpm:number;offset:number;onsets:number[];power:number[]}\nexport const RHYTHM_SONGS:RhythmSong[] = '+json.dumps(packed,ensure_ascii=False,separators=(',',':'))+""".map(source=>{
 const {beats,...song}=source;let ms=0;const onsets:number[]=[],power:number[]=[];
 for(const entry of beats.split(',')){if(!entry)continue;const [delta,level]=entry.split(':');ms+=parseInt(delta,36);onsets.push(ms);power.push(parseInt(level,36));}
 return {...song,onsets,power};
});
""")
write_catalog(songs)
print(f'Analyzed all {len(songs)} songs; {sum(len(s["onsets"]) for s in songs)} musical onsets.')
