export interface EnglishUnitOption {
  id: string;
  name: string;
  mode: string;
}

export const ENGLISH_GRADE_UNITS: Record<number, EnglishUnitOption[]> = {
  3: [
    { id: 'E3_U01', name: 'あいさつ', mode: 'ENGLISH_G3_U01' },
    { id: 'E3_U02', name: 'じこしょうかい', mode: 'ENGLISH_G3_U02' },
    { id: 'E3_U03', name: 'すきなもの', mode: 'ENGLISH_G3_U03' },
    { id: 'E3_U04', name: 'かぞく', mode: 'ENGLISH_G3_U04' },
    { id: 'E3_U05', name: 'いろ', mode: 'ENGLISH_G3_U05' },
    { id: 'E3_U06', name: 'かず（1〜20）', mode: 'ENGLISH_G3_U06' },
    { id: 'E3_U07', name: 'どうぶつ', mode: 'ENGLISH_G3_U07' },
    { id: 'E3_U08', name: 'くだもの・たべもの', mode: 'ENGLISH_G3_U08' },
    { id: 'E3_U09', name: 'きぶん', mode: 'ENGLISH_G3_U09' },
    { id: 'E3_U10', name: 'からだのぶぶん', mode: 'ENGLISH_G3_U10' },
    { id: 'E3_U11', name: 'リスニング総仕上げ', mode: 'ENGLISH_G3_U11' },
    { id: 'E3_U12', name: '発声総仕上げ', mode: 'ENGLISH_G3_U12' },
  ],
  4: [
    { id: 'E4_U01', name: 'あいさつと会話', mode: 'ENGLISH_G4_U01' },
    { id: 'E4_U02', name: 'すきな教科', mode: 'ENGLISH_G4_U02' },
    { id: 'E4_U03', name: '一日の生活', mode: 'ENGLISH_G4_U03' },
    { id: 'E4_U04', name: '天気', mode: 'ENGLISH_G4_U04' },
    { id: 'E4_U05', name: '時こく', mode: 'ENGLISH_G4_U05' },
    { id: 'E4_U06', name: '文ぼうぐ', mode: 'ENGLISH_G4_U06' },
    { id: 'E4_U07', name: '場所', mode: 'ENGLISH_G4_U07' },
    { id: 'E4_U08', name: '学校の中', mode: 'ENGLISH_G4_U08' },
    { id: 'E4_U09', name: 'すきな食べ物', mode: 'ENGLISH_G4_U09' },
    { id: 'E4_U10', name: '日本の文化しょうかい', mode: 'ENGLISH_G4_U10' },
    { id: 'E4_U11', name: 'リスニング総仕上げ', mode: 'ENGLISH_G4_U11' },
    { id: 'E4_U12', name: '発声総仕上げ', mode: 'ENGLISH_G4_U12' },
  ],
  5: [
    { id: 'E5_U01', name: 'アルファベット', mode: 'ENGLISH_G5_U01' },
    { id: 'E5_U02', name: '自己紹介', mode: 'ENGLISH_G5_U02' },
    { id: 'E5_U03', name: '家族', mode: 'ENGLISH_G5_U03' },
    { id: 'E5_U04', name: '誕生日', mode: 'ENGLISH_G5_U04' },
    { id: 'E5_U05', name: '好きなもの', mode: 'ENGLISH_G5_U05' },
    { id: 'E5_U06', name: '学校生活', mode: 'ENGLISH_G5_U06' },
    { id: 'E5_U07', name: '曜日', mode: 'ENGLISH_G5_U07' },
    { id: 'E5_U08', name: '時こく', mode: 'ENGLISH_G5_U08' },
    { id: 'E5_U09', name: 'できること（can）', mode: 'ENGLISH_G5_U09' },
    { id: 'E5_U10', name: '行きたい場所', mode: 'ENGLISH_G5_U10' },
    { id: 'E5_U11', name: 'リスニング総仕上げ', mode: 'ENGLISH_G5_U11' },
    { id: 'E5_U12', name: '発声総仕上げ', mode: 'ENGLISH_G5_U12' },
  ],
  6: [
    { id: 'E6_U01', name: '自己紹介', mode: 'ENGLISH_G6_U01' },
    { id: 'E6_U02', name: '将来の夢', mode: 'ENGLISH_G6_U02' },
    { id: 'E6_U03', name: '日常生活', mode: 'ENGLISH_G6_U03' },
    { id: 'E6_U04', name: '日本文化紹介', mode: 'ENGLISH_G6_U04' },
    { id: 'E6_U05', name: '行きたい国', mode: 'ENGLISH_G6_U05' },
    { id: 'E6_U06', name: '思い出', mode: 'ENGLISH_G6_U06' },
    { id: 'E6_U07', name: '過去の出来事', mode: 'ENGLISH_G6_U07' },
    { id: 'E6_U08', name: '好きなもの', mode: 'ENGLISH_G6_U08' },
    { id: 'E6_U09', name: '世界の文化', mode: 'ENGLISH_G6_U09' },
    { id: 'E6_U10', name: '将来の計画', mode: 'ENGLISH_G6_U10' },
    { id: 'E6_U11', name: 'リスニング総仕上げ', mode: 'ENGLISH_G6_U11' },
    { id: 'E6_U12', name: '発声総仕上げ', mode: 'ENGLISH_G6_U12' },
  ],
  7: [
    { id: 'E7_U01', name: 'アルファベット', mode: 'ENGLISH_G7_U01' },
    { id: 'E7_U02', name: 'be動詞', mode: 'ENGLISH_G7_U02' },
    { id: 'E7_U03', name: '一般動詞', mode: 'ENGLISH_G7_U03' },
    { id: 'E7_U04', name: '疑問文', mode: 'ENGLISH_G7_U04' },
    { id: 'E7_U05', name: '否定文', mode: 'ENGLISH_G7_U05' },
    { id: 'E7_U06', name: '命令文', mode: 'ENGLISH_G7_U06' },
    { id: 'E7_U07', name: 'can', mode: 'ENGLISH_G7_U07' },
    { id: 'E7_U08', name: '現在進行形', mode: 'ENGLISH_G7_U08' },
    { id: 'E7_U09', name: '三人称単数', mode: 'ENGLISH_G7_U09' },
    { id: 'E7_U10', name: '前置詞', mode: 'ENGLISH_G7_U10' },
    { id: 'E7_U11', name: '複数形', mode: 'ENGLISH_G7_U11' },
    { id: 'E7_U12', name: '代名詞', mode: 'ENGLISH_G7_U12' },
    { id: 'E7_U13', name: 'リスニング総仕上げ', mode: 'ENGLISH_G7_U13' },
    { id: 'E7_U14', name: '発声総仕上げ', mode: 'ENGLISH_G7_U14' },
  ],
  8: [
    { id: 'E8_U01', name: '過去形', mode: 'ENGLISH_G8_U01' },
    { id: 'E8_U02', name: '過去進行形', mode: 'ENGLISH_G8_U02' },
    { id: 'E8_U03', name: '未来表現（will / be going to）', mode: 'ENGLISH_G8_U03' },
    { id: 'E8_U04', name: '助動詞（must / have to / may など）', mode: 'ENGLISH_G8_U04' },
    { id: 'E8_U05', name: '不定詞', mode: 'ENGLISH_G8_U05' },
    { id: 'E8_U06', name: '動名詞', mode: 'ENGLISH_G8_U06' },
    { id: 'E8_U07', name: '接続詞', mode: 'ENGLISH_G8_U07' },
    { id: 'E8_U08', name: '比較（比較級・最上級）', mode: 'ENGLISH_G8_U08' },
    { id: 'E8_U09', name: '受動態', mode: 'ENGLISH_G8_U09' },
    { id: 'E8_U10', name: 'リスニング総仕上げ', mode: 'ENGLISH_G8_U10' },
    { id: 'E8_U11', name: '発声総仕上げ', mode: 'ENGLISH_G8_U11' },
  ],
  9: [
    { id: 'E9_U01', name: '現在完了', mode: 'ENGLISH_G9_U01' },
    { id: 'E9_U02', name: '現在完了進行形', mode: 'ENGLISH_G9_U02' },
    { id: 'E9_U03', name: '関係代名詞', mode: 'ENGLISH_G9_U03' },
    { id: 'E9_U04', name: '間接疑問文', mode: 'ENGLISH_G9_U04' },
    { id: 'E9_U05', name: '仮定法', mode: 'ENGLISH_G9_U05' },
    { id: 'E9_U06', name: '分詞', mode: 'ENGLISH_G9_U06' },
    { id: 'E9_U07', name: '比較の応用', mode: 'ENGLISH_G9_U07' },
    { id: 'E9_U08', name: '長文読解', mode: 'ENGLISH_G9_U08' },
    { id: 'E9_U09', name: '英作文', mode: 'ENGLISH_G9_U09' },
    { id: 'E9_U10', name: 'スピーチ', mode: 'ENGLISH_G9_U10' },
    { id: 'E9_U11', name: 'リスニング総仕上げ', mode: 'ENGLISH_G9_U11' },
    { id: 'E9_U12', name: '発声総仕上げ', mode: 'ENGLISH_G9_U12' },
  ],
};
