
import { GameMode, GameScreen } from './types';

export type SubjectCategoryType = 'MATH' | 'MATH_GRADES' | 'KOKUGO_GRADES' | 'KANJI' | 'KANKEN' | 'HARD_KANJI' | 'LIFE' | 'SCIENCE' | 'SOCIAL' | 'ENGLISH' | 'SUMMARY' | 'MAP_PREF' | 'IT_INFO' | 'UPPER_MODERN' | 'UPPER_CLASSICS' | 'UPPER_ENGLISH' | 'UPPER_INFORMATION' | 'UPPER_TRIVIA' | 'UPPER_MATH' | 'UPPER_SCIENCE' | 'UPPER_SOCIETY' | 'UPPER_ESSAY' | 'UPPER_PRACTICAL';

export interface SubModeConfig {
    id: string;
    name: string;
    mode: GameMode;
}

export interface SubjectCategoryConfig {
    id: SubjectCategoryType;
    name: string;
    color: string;
    // 選択UIのタイプ: 
    // 'grid': 単純なグリッド一覧
    // 'grade_term': 学年と学期を選択するタイプ
    // 'english_mixed': 英語専用（単語と会話）
    uiType: 'grid' | 'grade_term' | 'english_mixed';
    subModes: SubModeConfig[];
}

// どのGameModeがどのチャレンジ画面を表示すべきかのマッピング
const MODE_TO_SCREEN: Record<string, GameScreen> = {
    // 算数系（動的生成）
    [GameMode.ADDITION]: GameScreen.MATH_CHALLENGE,
    [GameMode.SUBTRACTION]: GameScreen.MATH_CHALLENGE,
    [GameMode.MULTIPLICATION]: GameScreen.MATH_CHALLENGE,
    [GameMode.DIVISION]: GameScreen.MATH_CHALLENGE,
    [GameMode.MIXED]: GameScreen.MATH_CHALLENGE,
    [GameMode.ADD_1DIGIT]: GameScreen.MATH_CHALLENGE,
    [GameMode.ADD_1DIGIT_CARRY]: GameScreen.MATH_CHALLENGE,
    [GameMode.SUB_1DIGIT]: GameScreen.MATH_CHALLENGE,
    [GameMode.SUB_1DIGIT_BORROW]: GameScreen.MATH_CHALLENGE,
    
    // 算数・数学系（静的データ）
    [GameMode.MATH_G1_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G1_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G1_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G2_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G2_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G2_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G3_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G3_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G3_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G4_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G4_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G4_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G5_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G5_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G5_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G6_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G6_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G6_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G7_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G7_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G7_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G8_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G8_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G8_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G9_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G9_2]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.MATH_G9_3]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G1_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G2_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G3_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G4_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G5_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G6_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G7_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G8_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.KOKUGO_G9_1]: GameScreen.GENERAL_CHALLENGE,

    // 漢字系
    [GameMode.KANJI_1]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_2]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_3]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_4]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_5]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_6]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_7]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_8]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_9]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_10]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_11]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_12]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANJI_MIXED]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_10]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_9]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_8]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_7]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_6]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_5]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_4]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_3]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_PRE2]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_2]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_PRE1]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_1]: GameScreen.KANJI_CHALLENGE,
    [GameMode.KANKEN_MIXED]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_JUKUJIKUN]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_FLORA_FAUNA]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_ATEJI]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_PLACE_NAMES]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_KOKUJI]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_CLASSICS]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_YOJUKUGO]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_HISTORY]: GameScreen.KANJI_CHALLENGE,
    [GameMode.HARD_KANJI_MIXED]: GameScreen.KANJI_CHALLENGE,
    [GameMode.UPPER_MODERN_VOCAB]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_CLASSICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_WORDS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_ACADEMIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_DAILY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_BUSINESS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_SCIENCE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_TECH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_EXAM]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_SOCIAL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ENGLISH_TRAVEL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_INFORMATION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_TRIVIA]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_BOARD_GAMES]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_TRPG]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_CARD_GAMES]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_SHOGI]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_GO]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_CHESS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_MAHJONG]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_FISHING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_CAMPING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_HIKING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_PHOTOGRAPHY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_VIDEO]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_MUSIC_LISTENING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_INSTRUMENTS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_GARDENING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_COOKING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_BAKING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_HANDICRAFT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_PLASTIC_MODELS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_RAILWAY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_BICYCLE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_ASTRONOMY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_INSECTS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_AQUARIUM_FISH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.HOBBY_ZOO_ANIMALS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_NUM_EXPR]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_QUADRATIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_GEOMETRY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_PROB_STATS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_PHYSICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_CHEMISTRY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_BIOLOGY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_EARTH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_JAPAN_HISTORY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_WORLD_HISTORY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_GEOGRAPHY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_CIVICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_VOCAB]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_LOGIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_DATA_READING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_RESEARCH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_MONEY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_LAW]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_HEALTH]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_SAFETY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_TRIGONOMETRY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_SEQUENCE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_VECTOR]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_CALCULUS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_MECHANICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ELECTROMAGNETISM]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ORGANIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_GENETICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_MODERN_JAPAN]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_MODERN_WORLD]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_GIS_MAP]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_ETHICS_PUBLIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_ISSUE_FINDING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_DATA_ANALYSIS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_PRESENTATION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_REPORT_WRITING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_TAX_SOCIAL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_WORK_CAREER]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_HOUSING_CONTRACT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_NET_SAFETY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_EXP_LOG]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_COMPLEX]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_ADV_PROB]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_STAT_INFERENCE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_MATH_HISTORY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ENVIRONMENT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ASTRONOMY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_LAB]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_MEDICAL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ENGINEERING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_LAW_RIGHTS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_ECONOMICS_ADV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_INTL_RELATIONS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_REGIONAL_STUDIES]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_CURRENT_AFFAIRS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_DEBATE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_DESIGN_THINKING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_MEDIA_LITERACY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_ACADEMIC_WORDS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_INTERVIEW_FIELD]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_COOK_NUTRITION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_COMMUNICATION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_DIGITAL_PRODUCTIVITY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_CHILD_WELFARE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_ENTREPRENEURSHIP]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_LINEAR_ALGEBRA]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_ANALYTIC_GEOMETRY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_OPTIMIZATION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_DISCRETE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_FINANCE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_THERMODYNAMICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_WAVES_OPTICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_INORGANIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ECOLOGY_ADV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_GEO_WEATHER]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_ANCIENT_WORLD]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_MEDIEVAL_WORLD]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_CULTURE_HISTORY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_POLITICAL_THOUGHT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_JAPAN_GEOGRAPHY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_CREATIVE_WRITING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_POLICY_PROPOSAL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_SOURCE_CRITIQUE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_CAREER_ADMISSION]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_STATEMENT_LOGIC]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_TIME_MANAGEMENT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_EMERGENCY_FIRSTAID]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_CONSUMER_TROUBLE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_PUBLIC_SERVICES]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_RELATIONSHIP]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_DERIVATIVE_APP]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_INTEGRAL_APP]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_PROOF_ADV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_FUNCTION_MIX]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_MATH_DATA_SCIENCE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_ATOMIC_QUANTUM]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_MATERIALS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_FOOD]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_OCEAN]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SCIENCE_DISASTER]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_WORLD_GEO_ADV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_JAPAN_POLITICS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_LOCAL_GOV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_MEDIA_SOCIAL]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_SOCIETY_ENV_POLICY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_LOGIC_PUZZLE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_BOOK_READING]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_SUMMARY]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_COMPARATIVE_CULTURE]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_ESSAY_PROJECT_MANAGEMENT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_BUDGET_ADV]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_INVESTMENT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_TRAVEL_TRANSPORT]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_CEREMONY_MANNERS]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.UPPER_PRACTICAL_CARE_NURSING]: GameScreen.GENERAL_CHALLENGE,
    
    // 英語系
    [GameMode.ENGLISH_ES]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_J1]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_J2]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_J3]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_MIXED]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_CONV_1]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_CONV_2]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_CONV_3]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_CONV_4]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_CONV_5]: GameScreen.ENGLISH_CHALLENGE,
    [GameMode.ENGLISH_G3_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G4_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G5_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G6_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G7_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G8_1]: GameScreen.GENERAL_CHALLENGE,
    [GameMode.ENGLISH_G9_1]: GameScreen.GENERAL_CHALLENGE,
};

// 指定されたモードに対応するチャレンジ画面を取得する（デフォルトは汎用チャレンジ）
export const getChallengeScreenForMode = (mode: GameMode): GameScreen => {
    return MODE_TO_SCREEN[mode] || GameScreen.GENERAL_CHALLENGE;
};

export const SUBJECT_CATEGORIES: SubjectCategoryConfig[] = [
  { 
    id: 'MATH', 
    name: '計算', 
    color: 'emerald',
    uiType: 'grid',
    subModes: [
        { id: 'ADD_1DIGIT', name: '1ケタのたし算', mode: GameMode.ADD_1DIGIT },
        { id: 'ADD_1DIGIT_CARRY', name: 'たし算（くりあがり）', mode: GameMode.ADD_1DIGIT_CARRY },
        { id: 'SUB_1DIGIT', name: '1ケタのひき算', mode: GameMode.SUB_1DIGIT },
        { id: 'SUB_1DIGIT_BORROW', name: 'ひき算（くりさがり）', mode: GameMode.SUB_1DIGIT_BORROW },
        { id: 'ADDITION', name: '2ケタのたし算', mode: GameMode.ADDITION },
        { id: 'SUBTRACTION', name: '2ケタのひき算', mode: GameMode.SUBTRACTION },
        { id: 'MULTIPLICATION', name: 'かけ算九九', mode: GameMode.MULTIPLICATION },
        { id: 'DIVISION', name: 'わり算', mode: GameMode.DIVISION },
        { id: 'MIXED', name: 'ミックス', mode: GameMode.MIXED },
    ]
  },
  { 
    id: 'MATH_GRADES', 
    name: '算数・数学', 
    color: 'emerald',
    uiType: 'grade_term',
    subModes: [
        { id: 'M1_1', name: '算 小1 1学期', mode: GameMode.MATH_G1_1 },
        { id: 'M1_2', name: '算 小1 2学期', mode: GameMode.MATH_G1_2 },
        { id: 'M1_3', name: '算 小1 3学期', mode: GameMode.MATH_G1_3 },
        { id: 'M2_1', name: '算 小2 1学期', mode: GameMode.MATH_G2_1 },
        { id: 'M2_2', name: '算 小2 2学期', mode: GameMode.MATH_G2_2 },
        { id: 'M2_3', name: '算 小2 3学期', mode: GameMode.MATH_G2_3 },
        { id: 'M3_1', name: '算 小3 1学期', mode: GameMode.MATH_G3_1 },
        { id: 'M3_2', name: '算 小3 2学期', mode: GameMode.MATH_G3_2 },
        { id: 'M3_3', name: '算 小3 3学期', mode: GameMode.MATH_G3_3 },
        { id: 'M4_1', name: '算 小4 1学期', mode: GameMode.MATH_G4_1 },
        { id: 'M4_2', name: '算 小4 2学期', mode: GameMode.MATH_G4_2 },
        { id: 'M4_3', name: '算 小4 3学期', mode: GameMode.MATH_G4_3 },
        { id: 'M5_1', name: '算 小5 1学期', mode: GameMode.MATH_G5_1 },
        { id: 'M5_2', name: '算 小5 2学期', mode: GameMode.MATH_G5_2 },
        { id: 'M5_3', name: '算 小5 3学期', mode: GameMode.MATH_G5_3 },
        { id: 'M6_1', name: '算 小6 1学期', mode: GameMode.MATH_G6_1 },
        { id: 'M6_2', name: '算 小6 2学期', mode: GameMode.MATH_G6_2 },
        { id: 'M6_3', name: '算 小6 3学期', mode: GameMode.MATH_G6_3 },
        { id: 'M7_1', name: '数 中1 1学期', mode: GameMode.MATH_G7_1 },
        { id: 'M7_2', name: '数 中1 2学期', mode: GameMode.MATH_G7_2 },
        { id: 'M7_3', name: '数 中1 3学期', mode: GameMode.MATH_G7_3 },
        { id: 'M8_1', name: '数 中2 1学期', mode: GameMode.MATH_G8_1 },
        { id: 'M8_2', name: '数 中2 2学期', mode: GameMode.MATH_G8_2 },
        { id: 'M8_3', name: '数 中2 3学期', mode: GameMode.MATH_G8_3 },
        { id: 'M9_1', name: '数 中3 1学期', mode: GameMode.MATH_G9_1 },
        { id: 'M9_2', name: '数 中3 2学期', mode: GameMode.MATH_G9_2 },
        { id: 'M9_3', name: '数 中3 3学期', mode: GameMode.MATH_G9_3 },
    ]
  },
  { 
    id: 'KOKUGO_GRADES',
    name: '国語',
    color: 'cyan',
    uiType: 'grade_term',
    subModes: [
        { id: 'J1_1', name: '国 小1', mode: GameMode.KOKUGO_G1_1 },
        { id: 'J2_1', name: '国 小2', mode: GameMode.KOKUGO_G2_1 },
        { id: 'J3_1', name: '国 小3', mode: GameMode.KOKUGO_G3_1 },
        { id: 'J4_1', name: '国 小4', mode: GameMode.KOKUGO_G4_1 },
        { id: 'J5_1', name: '国 小5', mode: GameMode.KOKUGO_G5_1 },
        { id: 'J6_1', name: '国 小6', mode: GameMode.KOKUGO_G6_1 },
        { id: 'J7_1', name: '国 中1', mode: GameMode.KOKUGO_G7_1 },
        { id: 'J8_1', name: '国 中2', mode: GameMode.KOKUGO_G8_1 },
        { id: 'J9_1', name: '国 中3', mode: GameMode.KOKUGO_G9_1 },
    ]
  },
  { 
    id: 'KANJI', 
    name: '漢字', 
    color: 'cyan',
    uiType: 'grid',
    subModes: [
        { id: 'K1', name: '小学1年', mode: GameMode.KANJI_1 },
        { id: 'K2', name: '小学2年', mode: GameMode.KANJI_2 },
        { id: 'K3', name: '小学3年', mode: GameMode.KANJI_3 },
        { id: 'K4', name: '小学4年', mode: GameMode.KANJI_4 },
        { id: 'K5', name: '小学5年', mode: GameMode.KANJI_5 },
        { id: 'K6', name: '小学6年', mode: GameMode.KANJI_6 },
        { id: 'K7', name: '中学1年', mode: GameMode.KANJI_7 },
        { id: 'K8', name: '中学2年', mode: GameMode.KANJI_8 },
        { id: 'K9', name: '中学3年', mode: GameMode.KANJI_9 },
        { id: 'K10', name: '高校基礎', mode: GameMode.KANJI_10 },
        { id: 'K11', name: '高校標準', mode: GameMode.KANJI_11 },
        { id: 'K12', name: '高校発展', mode: GameMode.KANJI_12 },
        { id: 'K_MIXED', name: 'ミックス', mode: GameMode.KANJI_MIXED },
    ]
  },
  {
    id: 'KANKEN',
    name: '漢検・難読',
    color: 'cyan',
    uiType: 'grid',
    subModes: [
        { id: 'KK10', name: '10級', mode: GameMode.KANKEN_10 },
        { id: 'KK9', name: '9級', mode: GameMode.KANKEN_9 },
        { id: 'KK8', name: '8級', mode: GameMode.KANKEN_8 },
        { id: 'KK7', name: '7級', mode: GameMode.KANKEN_7 },
        { id: 'KK6', name: '6級', mode: GameMode.KANKEN_6 },
        { id: 'KK5', name: '5級', mode: GameMode.KANKEN_5 },
        { id: 'KK4', name: '4級', mode: GameMode.KANKEN_4 },
        { id: 'KK3', name: '3級', mode: GameMode.KANKEN_3 },
        { id: 'KK_PRE2', name: '準2級', mode: GameMode.KANKEN_PRE2 },
        { id: 'KK2', name: '2級', mode: GameMode.KANKEN_2 },
        { id: 'KK_PRE1', name: '準1級', mode: GameMode.KANKEN_PRE1 },
        { id: 'KK1', name: '1級', mode: GameMode.KANKEN_1 },
        { id: 'KK_MIXED', name: 'ミックス', mode: GameMode.KANKEN_MIXED },
        { id: 'HK_JUKUJIKUN', name: '超難読 熟字訓', mode: GameMode.HARD_KANJI_JUKUJIKUN },
        { id: 'HK_FLORA', name: '動植物 極', mode: GameMode.HARD_KANJI_FLORA_FAUNA },
        { id: 'HK_ATEJI', name: '当て字・外来語 極', mode: GameMode.HARD_KANJI_ATEJI },
        { id: 'HK_PLACE', name: '地名・国名 難読', mode: GameMode.HARD_KANJI_PLACE_NAMES },
        { id: 'HK_KOKUJI', name: '国字・和製漢字', mode: GameMode.HARD_KANJI_KOKUJI },
        { id: 'HK_CLASSICS', name: '仏教・神道・古典語', mode: GameMode.HARD_KANJI_CLASSICS },
        { id: 'HK_YOJI', name: '四字熟語 極', mode: GameMode.HARD_KANJI_YOJUKUGO },
        { id: 'HK_HISTORY', name: '古典表記・歴史語彙', mode: GameMode.HARD_KANJI_HISTORY },
        { id: 'HK_MIXED', name: 'ミックス', mode: GameMode.HARD_KANJI_MIXED },
    ]
  },
  { 
    id: 'ENGLISH', 
    name: '英語', 
    color: 'indigo',
    uiType: 'grade_term',
    subModes: [
        { id: 'E3_1', name: '英 小3', mode: GameMode.ENGLISH_G3_1 },
        { id: 'E4_1', name: '英 小4', mode: GameMode.ENGLISH_G4_1 },
        { id: 'E5_1', name: '英 小5', mode: GameMode.ENGLISH_G5_1 },
        { id: 'E6_1', name: '英 小6', mode: GameMode.ENGLISH_G6_1 },
        { id: 'E7_1', name: '英 中1', mode: GameMode.ENGLISH_G7_1 },
        { id: 'E8_1', name: '英 中2', mode: GameMode.ENGLISH_G8_1 },
        { id: 'E9_1', name: '英 中3', mode: GameMode.ENGLISH_G9_1 },
    ]
  },
  { 
    id: 'LIFE', 
    name: '生活', 
    color: 'amber',
    uiType: 'grade_term',
    subModes: [
        { id: 'L1_1', name: '生 小1 1学期', mode: GameMode.LIFE_1_1 },
        { id: 'L1_2', name: '生 小1 2学期', mode: GameMode.LIFE_1_2 },
        { id: 'L1_3', name: '生 小1 3学期', mode: GameMode.LIFE_1_3 },
        { id: 'L2_1', name: '生 小2 1学期', mode: GameMode.LIFE_2_1 },
        { id: 'L2_2', name: '生 小2 2学期', mode: GameMode.LIFE_2_2 },
        { id: 'L2_3', name: '生 小2 3学期', mode: GameMode.LIFE_2_3 },
    ]
  },
  { 
    id: 'SCIENCE', 
    name: '理科', 
    color: 'amber',
    uiType: 'grade_term',
    subModes: [
        { id: 'S3_1', name: '理 小3 1学期', mode: GameMode.SCIENCE_3_1 },
        { id: 'S3_2', name: '理 小3 2学期', mode: GameMode.SCIENCE_3_2 },
        { id: 'S3_3', name: '理 小3 3学期', mode: GameMode.SCIENCE_3_3 },
        { id: 'S4_1', name: '理 小4 1学期', mode: GameMode.SCIENCE_4_1 },
        { id: 'S4_2', name: '理 小4 2学期', mode: GameMode.SCIENCE_4_2 },
        { id: 'S4_3', name: '理 小4 3学期', mode: GameMode.SCIENCE_4_3 },
        { id: 'S5_1', name: '理 小5 1学期', mode: GameMode.SCIENCE_5_1 },
        { id: 'S5_2', name: '理 小5 2学期', mode: GameMode.SCIENCE_5_2 },
        { id: 'S5_3', name: '理 小5 3学期', mode: GameMode.SCIENCE_5_3 },
        { id: 'S6_1', name: '理 小6 1学期', mode: GameMode.SCIENCE_6_1 },
        { id: 'S6_2', name: '理 小6 2学期', mode: GameMode.SCIENCE_6_2 },
        { id: 'S6_3', name: '理 小6 3学期', mode: GameMode.SCIENCE_6_3 },
        { id: 'S7_1', name: '理 中1 1学期', mode: GameMode.SCIENCE_7_1 },
        { id: 'S7_2', name: '理 中1 2学期', mode: GameMode.SCIENCE_7_2 },
        { id: 'S7_3', name: '理 中1 3学期', mode: GameMode.SCIENCE_7_3 },
        { id: 'S8_1', name: '理 中2 1学期', mode: GameMode.SCIENCE_8_1 },
        { id: 'S8_2', name: '理 中2 2学期', mode: GameMode.SCIENCE_8_2 },
        { id: 'S8_3', name: '理 中2 3学期', mode: GameMode.SCIENCE_8_3 },
        { id: 'S9_1', name: '理 中3 1学期', mode: GameMode.SCIENCE_9_1 },
        { id: 'S9_2', name: '理 中3 2学期', mode: GameMode.SCIENCE_9_2 },
        { id: 'S9_3', name: '理 中3 3学期', mode: GameMode.SCIENCE_9_3 },
    ]
  },
  { 
    id: 'SOCIAL', 
    name: '社会', 
    color: 'orange',
    uiType: 'grade_term',
    subModes: [
        { id: 'SO3_1', name: '社 小3 1学期', mode: GameMode.SOCIAL_3_1 },
        { id: 'SO3_2', name: '社 小3 2学期', mode: GameMode.SOCIAL_3_2 },
        { id: 'SO3_3', name: '社 小3 3学期', mode: GameMode.SOCIAL_3_3 },
        { id: 'SO4_1', name: '社 小4 1学期', mode: GameMode.SOCIAL_4_1 },
        { id: 'SO4_2', name: '社 小4 2学期', mode: GameMode.SOCIAL_4_2 },
        { id: 'SO4_3', name: '社 小4 3学期', mode: GameMode.SOCIAL_4_3 },
        { id: 'SO5_1', name: '社 小5 1学期', mode: GameMode.SOCIAL_5_1 },
        { id: 'SO5_2', name: '社 小5 2学期', mode: GameMode.SOCIAL_5_2 },
        { id: 'SO5_3', name: '社 小5 3学期', mode: GameMode.SOCIAL_5_3 },
        { id: 'SO6_1', name: '社 小6 1学期', mode: GameMode.SOCIAL_6_1 },
        { id: 'SO6_2', name: '社 小6 2学期', mode: GameMode.SOCIAL_6_2 },
        { id: 'SO6_3', name: '社 小6 3学期', mode: GameMode.SOCIAL_6_3 },
        { id: 'SO7_1', name: '社 中1 1学期', mode: GameMode.SOCIAL_7_1 },
        { id: 'SO7_2', name: '社 中1 2学期', mode: GameMode.SOCIAL_7_2 },
        { id: 'SO7_3', name: '社 中1 3学期', mode: GameMode.SOCIAL_7_3 },
        { id: 'SO8_1', name: '社 中2 1学期', mode: GameMode.SOCIAL_8_1 },
        { id: 'SO8_2', name: '社 中2 2学期', mode: GameMode.SOCIAL_8_2 },
        { id: 'SO8_3', name: '社 中2 3学期', mode: GameMode.SOCIAL_8_3 },
        { id: 'SO9_1', name: '社 中3 1学期', mode: GameMode.SOCIAL_9_1 },
        { id: 'SO9_2', name: '社 中3 2学期', mode: GameMode.SOCIAL_9_2 },
        { id: 'SO9_3', name: '社 中3 3学期', mode: GameMode.SOCIAL_9_3 },
    ]
  },
  {
    id: 'SUMMARY',
    name: 'まとめ',
    color: 'amber',
    uiType: 'grade_term',
    subModes: [
        { id: 'SUMMARY_GRADE', name: '学年別総まとめ', mode: GameMode.MATH_G1_1 },
    ]
  },
  { 
    id: 'MAP_PREF', 
    name: '地図・日本', 
    color: 'rose',
    uiType: 'grid',
    subModes: [
        { id: 'MS', name: '地図記号', mode: GameMode.MAP_SYMBOLS },
        { id: 'PF', name: '都道府県', mode: GameMode.PREFECTURES },
        { id: 'PC', name: '県庁所在地', mode: GameMode.PREF_CAPITALS },
        { id: 'PREF_HOKKAIDO', name: '北海道', mode: GameMode.PREF_HOKKAIDO },
        { id: 'PREF_AOMORI', name: '青森県', mode: GameMode.PREF_AOMORI },
        { id: 'PREF_IWATE', name: '岩手県', mode: GameMode.PREF_IWATE },
        { id: 'PREF_MIYAGI', name: '宮城県', mode: GameMode.PREF_MIYAGI },
        { id: 'PREF_AKITA', name: '秋田県', mode: GameMode.PREF_AKITA },
        { id: 'PREF_YAMAGATA', name: '山形県', mode: GameMode.PREF_YAMAGATA },
        { id: 'PREF_FUKUSHIMA', name: '福島県', mode: GameMode.PREF_FUKUSHIMA },
        { id: 'PREF_IBARAKI', name: '茨城県', mode: GameMode.PREF_IBARAKI },
        { id: 'PREF_TOCHIGI', name: '栃木県', mode: GameMode.PREF_TOCHIGI },
        { id: 'PREF_GUNMA', name: '群馬県', mode: GameMode.PREF_GUNMA },
        { id: 'PREF_SAITAMA', name: '埼玉県', mode: GameMode.PREF_SAITAMA },
        { id: 'PREF_CHIBA', name: '千葉県', mode: GameMode.PREF_CHIBA },
        { id: 'PREF_TOKYO', name: '東京都', mode: GameMode.PREF_TOKYO },
        { id: 'PREF_KANAGAWA', name: '神奈川県', mode: GameMode.PREF_KANAGAWA },
        { id: 'PREF_NIIGATA', name: '新潟県', mode: GameMode.PREF_NIIGATA },
        { id: 'PREF_TOYAMA', name: '富山県', mode: GameMode.PREF_TOYAMA },
        { id: 'PREF_ISHIKAWA', name: '石川県', mode: GameMode.PREF_ISHIKAWA },
        { id: 'PREF_FUKUI', name: '福井県', mode: GameMode.PREF_FUKUI },
        { id: 'PREF_YAMANASHI', name: '山梨県', mode: GameMode.PREF_YAMANASHI },
        { id: 'PREF_NAGANO', name: '長野県', mode: GameMode.PREF_NAGANO },
        { id: 'PREF_GIFU', name: '岐阜県', mode: GameMode.PREF_GIFU },
        { id: 'PREF_SHIZUOKA', name: '静岡県', mode: GameMode.PREF_SHIZUOKA },
        { id: 'PREF_AICHI', name: '愛知県', mode: GameMode.PREF_AICHI },
        { id: 'PREF_MIE', name: '三重県', mode: GameMode.PREF_MIE },
        { id: 'PREF_SHIGA', name: '滋賀県', mode: GameMode.PREF_SHIGA },
        { id: 'PREF_KYOTO', name: '京都府', mode: GameMode.PREF_KYOTO },
        { id: 'PREF_OSAKA', name: '大阪府', mode: GameMode.PREF_OSAKA },
        { id: 'PREF_HYOGO', name: '兵庫県', mode: GameMode.PREF_HYOGO },
        { id: 'PREF_NARA', name: '奈良県', mode: GameMode.PREF_NARA },
        { id: 'PREF_WAKAYAMA', name: '和歌山県', mode: GameMode.PREF_WAKAYAMA },
        { id: 'PREF_TOTTORI', name: '鳥取県', mode: GameMode.PREF_TOTTORI },
        { id: 'PREF_SHIMANE', name: '島根県', mode: GameMode.PREF_SHIMANE },
        { id: 'PREF_OKAYAMA', name: '岡山県', mode: GameMode.PREF_OKAYAMA },
        { id: 'PREF_HIROSHIMA', name: '広島県', mode: GameMode.PREF_HIROSHIMA },
        { id: 'PREF_YAMAGUCHI', name: '山口県', mode: GameMode.PREF_YAMAGUCHI },
        { id: 'PREF_TOKUSHIMA', name: '徳島県', mode: GameMode.PREF_TOKUSHIMA },
        { id: 'PREF_KAGAWA', name: '香川県', mode: GameMode.PREF_KAGAWA },
        { id: 'PREF_EHIME', name: '愛媛県', mode: GameMode.PREF_EHIME },
        { id: 'PREF_KOCHI', name: '高知県', mode: GameMode.PREF_KOCHI },
        { id: 'PREF_FUKUOKA', name: '福岡県', mode: GameMode.PREF_FUKUOKA },
        { id: 'PREF_SAGA', name: '佐賀県', mode: GameMode.PREF_SAGA },
        { id: 'PREF_NAGASAKI', name: '長崎県', mode: GameMode.PREF_NAGASAKI },
        { id: 'PREF_KUMAMOTO', name: '熊本県', mode: GameMode.PREF_KUMAMOTO },
        { id: 'PREF_OITA', name: '大分県', mode: GameMode.PREF_OITA },
        { id: 'PREF_MIYAZAKI', name: '宮崎県', mode: GameMode.PREF_MIYAZAKI },
        { id: 'PREF_KAGOSHIMA', name: '鹿児島県', mode: GameMode.PREF_KAGOSHIMA },
        { id: 'PREF_OKINAWA', name: '沖縄県', mode: GameMode.PREF_OKINAWA },
    ]
  },
  {
    id: 'IT_INFO',
    name: 'ICT・情報',
    color: 'indigo',
    uiType: 'grid',
    subModes: [
        { id: 'IT_WIN', name: 'Windows', mode: GameMode.IT_WINDOWS },
        { id: 'IT_IPAD', name: 'iPad', mode: GameMode.IT_IPAD },
        { id: 'IT_CHROME', name: 'Chromebook', mode: GameMode.IT_CHROMEBOOK },
        { id: 'IT_NET', name: 'スマホ・ネット', mode: GameMode.IT_INTERNET },
        { id: 'IT_LIT', name: '情報リテラシー', mode: GameMode.IT_LITERACY },
        { id: 'IT_PROG', name: 'プログラミング', mode: GameMode.IT_PROGRAMMING },
        { id: 'IT_SEC', name: 'モラル・セキュリティ', mode: GameMode.IT_SECURITY },
    ]
  }
];
