const COPY: [string,string,string][] = [
  ["移動操作", "Movement controls", "いどうそうさ"],
  ["タッチでの移動操作", "Touch movement controls", "タッチでのいどうそうさ"],
  ["十字ボタン", "Directional buttons", "じゅうじボタン"],
  ["バーチャルスティック", "Virtual joystick", "バーチャルスティック"],
  ["スティックを倒した方向へ移動。軽く倒すとゆっくり、指を離すと停止します。", "Move in the direction you push the stick. Push gently to walk slowly; release to stop.", "スティックをたおしたほうこうへいどう。かるくたおすとゆっくり、ゆびをはなすとていしします。"],
  ["選んだ操作方法は、この端末に保存されます。", "Your control choice is saved on this device.", "えらんだそうさほうほうは、このたんまつにほぞんされます。"],
  ["矢印キー・WASD、または画面左下の十字ボタン・スティックで移動。", "Move using arrow keys, WASD, or the directional buttons or joystick at the bottom left.", "やじるしキー・WASD、またはがめんひだりしたのじゅうじボタン・スティックでいどう。"],
  ["柴犬", "Shiba Inu", "しばいぬ"],
  ["コーギー", "Corgi", "コーギー"],
  ["トイプードル", "Toy poodle", "トイプードル"],
  ["三毛猫", "Calico cat", "みけねこ"],
  ["サバトラ猫", "Silver tabby cat", "サバトラねこ"],
  ["黒猫", "Black cat", "くろねこ"],
  ["ウサギ", "Rabbit", "ウサギ"],
  ["ハムスター", "Hamster", "ハムスター"],
  ["シマエナガ", "Long-tailed tit", "シマエナガ"],
  ["交流度", "Bond", "こうりゅうど"],
  ["おなかを見せています", "Showing its belly", "おなかをみせています"],
  ["交流度100で、おなかを見せるしぐさが解放されます。", "A bond of 100 unlocks the belly-up pose.", "こうりゅうど100で、おなかをみせるしぐさがかいほうされます。"],
  ["一緒に暮らすペットを選ぶ", "Choose your home companion", "いっしょにくらすペットをえらぶ"],
  ["一緒に暮らすペットの名前", "Your companion’s name", "いっしょにくらすペットのなまえ"],
  ["ペットは家の中で暮らします。名前はあとから変更できます。", "Your pet lives indoors. You can rename it later.", "ペットはいえのなかでくらします。なまえはあとからへんこうできます。"],
  ["ペットを選んでください。", "Choose a pet.", "ペットをえらんでください。"],
  ["台をタップして引っ張り、離すとショット。引いた向きと逆に進み、長く引くほど強くなります。", "Tap the table, pull back, and release to shoot. The shot travels opposite your pull; a longer pull gives more power.", "だいをタップしてひっぱり、はなすとショット。ひいたむきとぎゃくにすすみ、ながくひくほどつよくなります。"],
  ["くまのぬいぐるみ", "Teddy bear", "くまのぬいぐるみ"],
  ["うさぎのぬいぐるみ", "Plush bunny", "うさぎのぬいぐるみ"],
  ["ダーツ台", "Darts cabinet", "ダーツだい"],
  ["ビリヤード台", "Pool table", "ビリヤードだい"],
  ["ゲーム機", "Arcade cabinet", "ゲームき"],
  ["ミケ", "Mike", "ミケ"],
  ["友達の家", "A friend’s home", "ともだちのいえ"],
  ["家の入口に近づいてください。", "Move closer to the home entrance.", "いえのいりぐちにちかづいてください。"],
  ["家具の編集は家の持ち主だけができます。", "Only the homeowner can edit furniture.", "かぐのへんしゅうはいえのもちぬしだけができます。"],
  ["対戦中の家具は変更できません。", "Furniture cannot be changed during a match.", "たいせんちゅうのかぐはへんこうできません。"],
  ["ペットの名前を変えました。", "Pet renamed.", "ペットのなまえをかえました。"],
  ["ペットは今ごきげんです。少し待ちましょう。", "Your pet is happy. Wait a little before petting again.", "ペットはいまごきげんです。すこしまちましょう。"],
  ["ペットをなでました！", "Your pet enjoyed a stroke!", "ペットをなでました！"],
  ["おうちのペット", "Your home pet", "おうちのペット"],
  ["ペットの名前", "Pet name", "ペットのなまえ"],
  ["なでる", "Pet", "なでる"],
  ["名前をつける", "Name your pet", "なまえをつける"],
  ["歩いています", "Walking", "あるいています"],
  ["毛づくろい中", "Grooming", "けづくろいちゅう"],
  ["お昼寝中", "Napping", "おひるねちゅう"],
  ["遊んでいます", "Playing", "あそんでいます"],
  ["家の中で趣味家具を選びましょう。", "Choose hobby furniture inside a home.", "いえのなかでしゅみかぐをえらびましょう。"],
  ["参加中の対戦から退出してください。", "Leave your current match first.", "さんかちゅうのたいせんからたいしゅつしてください。"],
  ["友達を待っています。", "Waiting for friends.", "ともだちをまっています。"],
  ["対戦中か、4人そろっています。", "Match in progress or all four seats are taken.", "たいせんちゅうか、4にんそろっています。"],
  ["対戦に参加しました！", "Joined the match!", "たいせんにさんかしました！"],
  ["対戦から退出しました。", "Left the match.", "たいせんからたいしゅつしました。"],
  ["対戦開始！", "Match started!", "たいせんかいし！"],
  ["ダブルでフィニッシュ！", "Double checkout!", "ダブルでフィニッシュ！"],
  ["バースト！この手番の得点は無効です。", "Bust! This turn’s score is cancelled.", "バースト！このてばんのとくてんはむこうです。"],
  ["ダーツを投げました。", "Dart thrown.", "ダーツをなげました。"],
  ["残り得点で決着しました。", "Decided by remaining points.", "のこりとくてんでけっちゃくしました。"],
  ["ショット！", "Shot!", "ショット！"],
  ["参加者が退出しました。もう一度開始できます。", "A player left. Start again when ready.", "さんかしゃがたいしゅつしました。もういちどかいしできます。"],
  ["8ボールを沈めて勝利！", "Eight ball potted: victory!", "8ボールをしずめてしょうり！"],
  ["8ボールのファウルです。", "Eight-ball foul.", "8ボールのファウルです。"],
  ["ファウル。次の人は手玉を置けます。", "Foul. The next player gets ball in hand.", "ファウル。つぎのひとはてだまをおけます。"],
  ["ポケット成功！続けてショット。", "Ball potted! Shoot again.", "ポケットせいこう！つづけてショット。"],
  ["次のプレイヤーの手番です。", "Next player’s turn.", "つぎのプレイヤーのてばんです。"],
  ["タイムアップ！", "Time up!", "タイムアップ！"],
  ["時間切れ。次の手番です。", "Time expired. Next turn.", "じかんぎれ。つぎのてばんです。"],
  ["ゲーム終了！", "Game over!", "ゲームしゅうりょう！"],
  ["ダーツ301", "Darts 301", "ダーツ301"],
  ["8ボール", "Eight ball", "8ボール"],
  ["コズミックブレイク", "Cosmic Break", "コズミックブレイク"],
  ["趣味家具を飾ると、友達と4人までで遊べます。", "Place hobby furniture to play with up to four friends.", "しゅみかぐをかざると、ともだちと4にんまでであそべます。"],
  ["みんなのゲームルーム", "Shared game room", "みんなのゲームルーム"],
  ["同じ家の家具から参加。1人で練習、最大4人で対戦できます。", "Join through furniture in the same home. Practice alone or play with up to four players.", "おなじいえのかぐからさんか。1にんでれんしゅう、さいだい4にんでたいせんできます。"],
  ["チームA", "Team A", "チームA"],
  ["チームB", "Team B", "チームB"],
  ["勝者", "Winner", "しょうしゃ"],
  ["今回は勝者なし", "No winner this time", "こんかいはしょうしゃなし"],
  ["もう一度遊ぶ", "Play again", "もういちどあそぶ"],
  ["ゲーム開始", "Start game", "ゲームかいし"],
  ["対戦から退出", "Leave match", "たいせんからたいしゅつ"],
  ["残り時間", "Time remaining", "のこりじかん"],
  ["手番", "Turn", "てばん"],
  ["残り投数", "Darts remaining", "のこりとうすう"],
  ["ダーツの的", "Dartboard", "ダーツのまと"],
  ["ダーツを投げる", "Throw dart", "ダーツをなげる"],
  ["ソリッド", "Solids", "ソリッド"],
  ["ストライプ", "Stripes", "ストライプ"],
  ["未決定", "Not assigned", "みけってい"],
  ["ビリヤードの台", "Billiards table", "ビリヤードのだい"],
  ["ショットの角度", "Shot angle", "ショットのかくど"],
  ["ショットの強さ", "Shot power", "ショットのつよさ"],
  ["ショットする", "Shoot", "ショットする"],
  ["手玉を置く", "Place cue ball", "てだまをおく"],
  ["ブロック崩しのコート", "Breakout court", "ブロックくずしのコート"],
  ["301点から減らし、最後はダブルで0点。1手番3投。狙いをタップし、照準を見て投げましょう。", "Count down from 301 with a double checkout. Three darts per turn. Tap to aim and time your throw.", "301てんからへらし、さいごはダブルで0てん。1てばん3とう。ねらいをタップし、しょうじゅんをみてなげましょう。"],
  ["2チームで8ボール。自分の色をすべて沈めてから8番。ファウル時は次の人が手玉を置けます。", "Two-team eight ball: clear your group before potting eight. Fouls give the next player ball in hand.", "2チームで8ボール。じぶんのいろをすべてしずめてから8ばん。ファウルじはつぎのひとがてだまをおけます。"],
  ["75秒のブロック崩し対戦。指でパドルを動かすか左右キーで操作。3回ミスすると終了。", "A 75-second breakout match. Drag your paddle or use left/right keys. Three misses end your game.", "75びょうのブロックくずしたいせん。ゆびでパドルをうごかすかさゆうキーでそうさ。3かいミスするとしゅうりょう。"],

  ["ベッド", "Bed", "ベッド"],
  ["ソファ", "Sofa", "ソファ"],
  ["学習机", "Study desk", "がくしゅうづくえ"],
  ["本棚", "Bookshelf", "ほんだな"],
  ["キッチン", "Kitchen", "キッチン"],
  ["作業台", "Workbench", "さぎょうだい"],
  ["クローゼット", "Wardrobe", "クローゼット"],
  ["チェア", "Chair", "チェア"],
  ["テーブル", "Table", "テーブル"],
  ["ラグ", "Rug", "ラグ"],
  ["置き時計", "Clock", "おきどけい"],
  ["水槽", "Aquarium", "すいそう"],
  ["ピアノ", "Piano", "ピアノ"],
  ["クッション", "Cushion", "クッション"],
  ["観葉植物", "Houseplant", "かんようしょくぶつ"],
  ["絵画スタンド", "Painting stand", "かいがスタンド"],
  ["キャビネット", "Cabinet", "キャビネット"],
  ["バスタブ", "Bathtub", "バスタブ"],
  ["家の中", "Inside your home", "いえのなか"],
  ["自分だけの部屋", "Your own room", "じぶんだけのへや"],
  ["家具をつくりました！", "Furniture crafted!", "かぐをつくりました！"],
  ["家具の向きを変えました。", "Furniture rotated.", "かぐのむきをかえました。"],
  ["家具を移動しました。", "Furniture moved.", "かぐをいどうしました。"],
  ["次の休息まで少し待ちましょう。", "Wait a little before resting again.", "つぎのきゅうそくまですこしまちましょう。"],
  ["休息して足取りが軽くなりました！", "Rested: movement speed increased!", "きゅうそくしてあしどりがかるくなりました！"],
  ["今日はもう使いました。", "Already used today.", "きょうはもうつかいました。"],
  ["家具から木の床を2個つくりました。", "Made two wooden floor pieces.", "かぐからきのゆかを2こつくりました。"],
  ["料理ができました！", "Meal prepared!", "りょうりができました！"],
  ["音楽で気分が上がりました！", "Music lifted your spirits!", "おんがくできぶんがあがりました！"],
  ["お気に入りの家具を楽しんでいます。", "Enjoying your favorite furniture.", "おきにいりのかぐをたのしんでいます。"],
  ["マスを選んで配置。家具を選ぶと向き・場所・使い方を変更できます。", "Select a tile to arrange furniture. Change its position, direction, or use it.", "マスをえらんではいち。かぐをえらぶとむき・ばしょ・つかいかたをへんこうできます。"],
  ["選んだ家具", "Selected furniture", "えらんだかぐ"],
  ["家具をつくる", "Craft furniture", "かぐをつくる"],
  ["向きを変える", "Rotate", "むきをかえる"],
  ["家具を使う", "Use furniture", "かぐをつかう"],
  ["選んだ家具をここへ移動", "Move selected furniture here", "えらんだかぐをここへいどう"],
  ["休息は60秒ごとに移動速度アップ。作業家具は島の1日ごとに木の床2個。キッチンは材料から料理できます。", "Rest every 60 seconds for a speed boost. Work furniture produces two floor pieces per island day. Kitchens turn ingredients into meals.", "きゅうそくは60びょうごとにいどうそくどアップ。さぎょうかぐはしまの1にちごとにきのゆか2こ。キッチンはざいりょうからりょうりできます。"],

  ['学ロクラフト','Gakuro Craft','がくろクラフト'],
  ['40人で島づくり','Build an island with 40 players','40にんでしまづくり'],
  ['学んで、つくって、みんなで暮らす。','Learn, build, and live together.','まなんで、つくって、みんなでくらす。'],
  ['最大40人','Up to 40 players','さいだい40にん'],['共有の島','Shared island','きょうゆうのしま'],['開発中','In development','かいはつちゅう'],
  ['名前','Name','なまえ'],['カラー','Color','カラー'],['みんなの島を開く','Host an island','みんなのしまをひらく'],['ひとりで遊ぶ','Play solo','ひとりであそぶ'],
  ['保存した島を続ける','Continue saved island','ほぞんしたしまをつづける'],['招待コード','Invite code','しょうたいコード'],['島に参加','Join island','しまにさんか'],
  ['島と問題を準備中…','Preparing the island and questions…','しまともんだいをじゅんびちゅう…'],['タイトルへ戻る','Back to title','タイトルへもどる'],
  ['クラフトの問題選択','Craft question selection','クラフトのもんだいせんたく'],['4択の問題に正解するとエネルギーが30回復','Answer a multiple-choice question to restore 30 energy','4たくのもんだいにせいかいするとエネルギーが30かいふく'],
  ['配信課題を選ぶ','Select an assignment','はいしんかだいをえらぶ'],['受け取り済みの課題','Received assignment','うけとりずみのかだい'],
  ['エネルギー','Energy','エネルギー'],['問題で回復','Answer to recharge','もんだいでかいふく'],['正解ごとに +30','+30 per correct answer','せいかいごとに +30'],
  ['正解でエネルギー +30。不正解でも減りません。','Correct answers restore 30 energy. Mistakes cost nothing.','せいかいでエネルギー +30。ふせいかいでもへりません。'],
  ['正解！エネルギー回復','Correct! Energy restored','せいかい！エネルギーかいふく'],['正答を確認しましょう','Check the correct answer','せいとうをかくにんしましょう'],
  ['次の問題','Next question','つぎのもんだい'],['島に戻る','Back to island','しまにもどる'],['好きなときに島に戻れます。','You can return to the island anytime.','すきなときにしまにもどれます。'],
  ['聞く','Listen','きく'],['閉じる','Close','とじる'],['戻る','Back','もどる'],['遊び方','How to play','あそびかた'],['退出','Leave','たいしゅつ'],
  ['木材','Wood','もくざい'],['石','Stone','いし'],['種','Seeds','たね'],['作物','Crops','さくもつ'],['魚','Fish','さかな'],['木の床','Wooden floor','きのゆか'],['石のブロック','Stone block','いしのブロック'],['花壇','Flower bed','かだん'],['ランタン','Lantern','ランタン'],['ベンチ','Bench','ベンチ'],
  ['採集','Gather','さいしゅう'],['種まき','Plant','たねまき'],['水やり','Water','みずやり'],['収穫','Harvest','しゅうかく'],['釣り','Fish','つり'],['建築','Build','けんちく'],['片づけ','Remove','かたづけ'],
  ['島のみんなの記録','Island achievements','しまのみんなのきろく'],['広場に作物か魚を納品すると種がもらえます。','Donate crops or fish in the plaza to earn seeds.','ひろばにさくもつかさかなをのうひんするとたねがもらえます。'],['広場で納品','Donate at plaza','ひろばでのうひん'],
  ['持ち物とクラフト','Inventory & crafting','もちものとクラフト'],['招待','Invite','しょうたい'],['縮小','Zoom out','しゅくしょう'],['拡大','Zoom in','かくだい'],
  ['移動','Move','いどう'],['上','Up','うえ'],['下','Down','した'],['左','Left','ひだり'],['右','Right','みぎ'],
  ['近くのマスをタップして選択','Tap a nearby tile to select it','ちかくのマスをタップしてせんたく'],['選んだ場所で作業','Work on selected tile','えらんだばしょでさぎょう'],['材料からつくる','Craft with materials','ざいりょうからつくる'],['つくる','Craft','つくる'],['置く','Place','おく'],
  ['このリンクからはデバッグ設定なしで参加できます。','This link lets players join without debug mode.','このリンクからはデバッグせっていなしでさんかできます。'],['招待リンク','Invitation link','しょうたいリンク'],['招待URLをコピー','Copy invite URL','しょうたいURLをコピー'],['コピーしました','Copied','コピーしました'],['リンクを選択してコピーしてください。','Select and copy the link.','リンクをせんたくしてコピーしてください。'],
  ['ホストの画面を開いたまま遊んでください。','Keep the host screen open while playing.','ホストのがめんをひらいたままあそんでください。'],
  ['矢印キー・WASD、または画面左下の矢印で移動。','Move with arrow keys, WASD, or the on-screen arrows.','やじるしキー・WASD、またはがめんひだりしたのやじるしでいどう。'],
  ['近くのマスを選び、道具を選んで「選んだ場所で作業」を押します。','Select a nearby tile, choose a tool, then press Work on selected tile.','ちかくのマスをえらび、どうぐをえらんで「えらんだばしょでさぎょう」をおします。'],
  ['木や石を採集してクラフト。床は橋になり、ブロックは4段まで積めます。','Gather wood and stone to craft. Floors make bridges; stack up to four blocks.','きやいしをさいしゅうしてクラフト。ゆかははしになり、ブロックは4だんまでつめます。'],
  ['種は90秒で成長。水やりで45秒に短縮。海や川では釣りができます。','Crops grow in 90 seconds, or 45 when watered. Fish in the sea and river.','たねは90びょうでせいちょう。みずやりで45びょうにたんしゅく。うみやかわではつりができます。'],
  ['エネルギーがなくなっても「問題で回復」で再開できます。','Out of energy? Answer a question to recharge and keep playing.','エネルギーがなくなっても「もんだいでかいふく」でさいかいできます。'],
  ['島はホストの端末に自動保存。次回は「保存した島を続ける」を選べます。','The island saves on the host device. Choose Continue saved island next time.','しまはホストのたんまつにじどうほぞん。じかいは「ほぞんしたしまをつづける」をえらべます。'],
  ['ホストが戻るまで一時停止中です。','Paused until the host returns.','ホストがもどるまでいちじていしちゅうです。'],
  ['材料が足りません。','Not enough materials.','ざいりょうがたりません。'],['問題に正解してエネルギーを回復しましょう。','Answer a question correctly to restore energy.','もんだいにせいかいしてエネルギーをかいふくしましょう。'],['クラフトしました！','Crafted!','クラフトしました！'],
  ['島の中央の広場で納品できます。','Donate at the plaza in the island center.','しまのちゅうおうのひろばでのうひんできます。'],['作物か魚を納品しましょう。','Bring crops or fish to donate.','さくもつかさかなをのうひんしましょう。'],['納品ありがとう！種を2個受け取りました。','Thank you! You received two seeds.','のうひんありがとう！たねを2こうけとりました。'],
  ['もう少し近づいてください。','Move a little closer.','もうすこしちかづいてください。'],['素材を集めました！','Materials gathered!','そざいをあつめました！'],
  ['種が足りません。木を採集するか、広場へ納品しましょう。','Need seeds? Gather trees or donate at the plaza.','たねがたりません。きをさいしゅうするか、ひろばへのうひんしましょう。'],
  ['種をまきました。水やりで早く育ちます。','Seeds planted. Water them to grow faster.','たねをまきました。みずやりではやくそだちます。'],['水をあげました！','Watered!','みずをあげました！'],['収穫しました！','Harvested!','しゅうかくしました！'],
  ['釣りは3秒おきにできます。','Wait three seconds between catches.','つりは3びょうおきにできます。'],['魚が釣れました！','Fish caught!','さかながつれました！'],
  ['ほかの人の建築は変更できません。','You cannot change another player’s building.','ほかのひとのけんちくはへんこうできません。'],['中央の広場は空けておきましょう。','Keep the central plaza clear.','ちゅうおうのひろばはあけておきましょう。'],['水の上には木の床で橋を架けられます。','Use wooden floors to build a bridge over water.','みずのうえにはきのゆかではしをかけられます。'],['飾りの上には積めません。','You cannot stack blocks on decorations.','かざりのうえにはつめません。'],
  ['人がいる場所には置けません。','A player is standing there.','ひとがいるばしょにはおけません。'],['建築しました！','Built!','けんちくしました！'],['人がいる場所は片づけられません。','Wait for the player to move before removing this.','ひとがいるばしょはかたづけられません。'],['片づけました。素材が戻りました。','Removed and materials returned.','かたづけました。そざいがもどりました。'],['この場所ではその作業はできません。','That action cannot be used on this tile.','このばしょではそのさぎょうはできません。'],
  ['島を保存できませんでした。端末の空き容量を確認してください。','Could not save the island. Check device storage.','しまをほぞんできませんでした。たんまつのあきようりょうをかくにんしてください。'],['接続がタイムアウトしました。','Connection timed out.','せつぞくがタイムアウトしました。'],['接続できませんでした。もう一度お試しください。','Could not connect. Please try again.','せつぞくできませんでした。もういちどおためしください。'],['接続を終了しました。','Connection closed.','せつぞくをしゅうりょうしました。'],['通信エラーが発生しました。','A connection error occurred.','つうしんエラーがはっせいしました。'],['部屋が満員か、参加できません。','The room is full or unavailable.','へやがまんいんか、さんかできません。'],['6文字の招待コードを入力してください。','Enter a six-character invite code.','6もじのしょうたいコードをにゅうりょくしてください。'],['部屋が見つからないか、接続できません。','Room not found or connection unavailable.','へやがみつからないか、せつぞくできません。'],['ホストとの接続が終了しました。','The host connection closed.','ホストとのせつぞくがしゅうりょうしました。'],['通信が途切れました。部屋に入り直してください。','Connection lost. Please rejoin the room.','つうしんがとぎれました。へやにはいりなおしてください。'],
  ["キャラクタープレビュー","Character preview","キャラクタープレビュー"],
  ["肌","Skin","はだ"],
  ["髪","Hair","かみ"],
  ["服","Clothes","ふく"],
  ["ズボン","Trousers","ズボン"],
  ["服の形","Outfit","ふくのかたち"],
  ["帽子","Hat","ぼうし"],
  ["シャツ","Shirt","シャツ"],
  ["オーバーオール","Overalls","オーバーオール"],
  ["パーカー","Hoodie","パーカー"],
  ["なし","None","なし"],
  ["麦わら帽子","Straw hat","むぎわらぼうし"],
  ["キャップ","Cap","キャップ"],
  ["キャラクタークリエイト","Create your character","キャラクタークリエイト"],
  ["見た目","Appearance","みため"],
  ["この見た目にする","Use this appearance","このみためにする"],
  ["屋根","Roof","やね"],
  ["フェンス","Fence","フェンス"],
  ["窓","Window","まど"],
  ["たき火","Campfire","たきび"],
  ["果実","Fruit","かじつ"],
  ["料理","Meal","りょうり"],
  ["果実摘み","Pick fruit","かじつつみ"],
  ["食べる","Eat","たべる"],
  ["広場のお店","Village shop","ひろばのおみせ"],
  ["納品でコインを集めて、広場で買い物。","Earn coins with deliveries and shop in the square.","のうひんでコインをあつめて、ひろばでかいもの。"],
  ["作業ボタンを長押しで連続作業","Hold the action button to work repeatedly","さぎょうボタンをながおしでれんぞくさぎょう"],
  ["屋根・窓・フェンスで家づくり。木の果実を摘んだり、たき火で料理して移動速度を上げられます。","Build a home with roofs, windows and fences. Pick fruit and cook at a campfire for a movement boost.","やね・まど・フェンスでいえづくり。きのかじつをつんだり、たきびでりょうりしていどうそくどをあげられます。"],
  ["見た目を変更しました。","Appearance updated.","みためをへんこうしました。"],
  ["料理がありません。","You have no meals.","りょうりがありません。"],
  ["おいしい！60秒間、移動が速くなります。","Delicious! Move faster for 60 seconds.","おいしい！60びょうかん、いどうがはやくなります。"],
  ["島の中央の広場で買い物できます。","Shop in the central square.","しまのちゅうおうのひろばでかいものできます。"],
  ["コインが足りません。納品で集めましょう。","Not enough coins. Earn some with deliveries.","コインがたりません。のうひんであつめましょう。"],
  ["買い物しました！","Purchase complete!","かいものしました！"],
  ["たき火の近くで料理できます。","Cook near a campfire.","たきびのちかくでりょうりできます。"],
  ["納品ありがとう！種2個と3コインを受け取りました。","Thanks! You received 2 seeds and 3 coins.","のうひんありがとう！たね2こと3コインをうけとりました。"],
  ["果実は45秒で実ります。","Fruit regrows in 45 seconds.","かじつは45びょうでみのります。"],
  ["果実を摘みました！","Fruit picked!","かじつをつみました！"],
  ["浮きが沈んだら、もう一度作業ボタン！","Press the action button again when the float sinks!","うきがしずんだら、もういちどさぎょうボタン！"],
  ["魚が逃げました。沈んだ瞬間に引き上げましょう。","The fish escaped. Reel in just as the float sinks.","さかながにげました。しずんだしゅんかんにひきあげましょう。"],
  ["大成功！魚を2匹釣りました！","Perfect catch! Two fish!","だいせいこう！さかなを2ひきつりました！"],
  ["引き上げる","Reel in","ひきあげる"],
  ["今！引き上げよう！","Now! Reel in!","いま！ひきあげよう！"],
  ["魚を待っています…","Waiting for a bite…","さかなをまっています…"],
  ["釣りは浮きが沈むタイミングで引き上げると大成功。雨の日は畑に自然と水が入ります。","Reel in as the float sinks for a perfect catch. Rain waters your crops.","つりはうきがしずむタイミングでひきあげるとだいせいこう。あめのひははたけにしぜんとみずがはいります。"],
  ["キャラクターの種類","Character type","キャラクターのしゅるい"],
  ["人間","Human","にんげん"],
  ["ねこ","Cat","ねこ"],
  ["いぬ","Dog","いぬ"],
  ["うさぎ","Rabbit","うさぎ"],
  ["きつね","Fox","きつね"],
  ["くま","Bear","くま"],
  ["パンダ","Panda","パンダ"],
  ["ことり","Bird","ことり"],
  ["かえる","Frog","かえる"],
  ["髪型","Hairstyle","かみがた"],
  ["表情","Expression","ひょうじょう"],
  ["小物","Accessories","こもの"],
  ["毛色","Fur color","けいろ"],
  ["おまかせ","Randomize","おまかせ"],
  ["ショート","Short","ショート"],
  ["ボブ","Bob","ボブ"],
  ["ロング","Long","ロング"],
  ["ポニーテール","Ponytail","ポニーテール"],
  ["ツインテール","Twin tails","ツインテール"],
  ["スパイキー","Spiky","スパイキー"],
  ["くるくる","Curly","くるくる"],
  ["みつあみ","Braids","みつあみ"],
  ["横分け","Side part","よこわけ"],
  ["坊主","Buzz cut","ぼうず"],
  ["にっこり","Smile","にっこり"],
  ["元気","Bright","げんき"],
  ["おだやか","Calm","おだやか"],
  ["大笑い","Laughing","おおわらい"],
  ["ウインク","Wink","ウインク"],
  ["びっくり","Surprised","びっくり"],
  ["きりっと","Determined","きりっと"],
  ["ねむたい","Sleepy","ねむたい"],
  ["てれ顔","Blushing","てれがお"],
  ["むすっと","Grumpy","むすっと"],
  ["制服","School uniform","せいふく"],
  ["ワンピース","Dress","ワンピース"],
  ["コート","Coat","コート"],
  ["探検家","Explorer","たんけんか"],
  ["コック","Chef","コック"],
  ["魔法使い","Wizard","まほうつかい"],
  ["忍者","Ninja","にんじゃ"],
  ["騎士","Knight","きし"],
  ["レインコート","Raincoat","レインコート"],
  ["ニット帽","Beanie","ニットぼう"],
  ["ベレー帽","Beret","ベレーぼう"],
  ["リボン","Ribbon","リボン"],
  ["王冠","Crown","おうかん"],
  ["花かざり","Flower wreath","はなかざり"],
  ["ヘルメット","Helmet","ヘルメット"],
  ["四角めがね","Square glasses","しかくめがね"],
  ["丸めがね","Round glasses","まるめがね"],
  ["マフラー","Scarf","マフラー"],
  ["リュック","Backpack","リュック"],
  ["ヘッドホン","Headphones","ヘッドホン"],
  ["キャンプ地","Campsite","キャンプち"],
  ["小さな集落","Small settlement","ちいさなしゅうらく"],
  ["にぎやかな村","Lively village","にぎやかなむら"],
  ["学園の町","Academy town","がくえんのまち"],
  ["緑の学園都市","Green academy city","みどりのがくえんとし"],
  ["広場の掲示板","Village noticeboard","ひろばのけいじばん"],
  ["資材のお店","Materials shop","しざいのおみせ"],
  ["家具のお店","Furniture shop","かぐのおみせ"],
  ["建築資材のお店","Building shop","けんちくしざいのおみせ"],
  ["花いっぱいのお店","Flower shop","はないっぱいのおみせ"],
  ["土地を探す","Find a home site","とちをさがす"],
  ["小さな家","Small home","ちいさないえ"],
  ["広い家","Spacious home","ひろいいえ"],
  ["工房つきの家","Home with a workshop","こうぼうつきのいえ"],
  ["ソラ","Sora","そら"],
  ["ミドリ","Midori","みどり"],
  ["ミナト","Minato","みなと"],
  ["はじめての素材集め","Gather your first materials","はじめてのそざいあつめ"],
  ["木や石を2回採集しよう。","Gather wood or stone twice.","きやいしを2かいさいしゅうしよう。"],
  ["自分でつくってみよう","Make it yourself","じぶんでつくってみよう"],
  ["材料から2回クラフトしよう。","Craft twice using materials.","ざいりょうから2かいクラフトしよう。"],
  ["畑のある暮らし","Life with a garden","はたけのあるくらし"],
  ["畑の作物を2回収穫しよう。","Harvest crops twice.","はたけのさくもつを2かいしゅうかくしよう。"],
  ["釣りびより","A day for fishing","つりびより"],
  ["魚を3匹釣ろう。","Catch three fish.","さかなを3びきつろう。"],
  ["みんなの広場へ","To the shared square","みんなのひろばへ"],
  ["広場へ3回納品しよう。","Make three deliveries to the square.","ひろばへ3かいのうひんしよう。"],
  ["わたしの家をつくろう","Build your own home","わたしのいえをつくろう"],
  ["島に自分の家の入口を建てよう。","Build your home entrance on the island.","しまにじぶんのいえのいりぐちをたてよう。"],
  ["お気に入りの部屋","Your favorite room","おきにいりのへや"],
  ["家の中に家具を3個飾ろう。","Place three furnishings inside your home.","いえのなかにかぐを3こかざろう。"],
  ["工房のある暮らし","Life with a workshop","こうぼうのあるくらし"],
  ["家を工房つきの家まで拡張しよう。","Expand your home to include a workshop.","いえをこうぼうつきのいえまでかくちょうしよう。"],
  ["今日の収穫のお手伝い","Today’s harvest help","きょうのしゅうかくのおてつだい"],
  ["今日、畑の作物を1回収穫しよう。","Harvest crops once today.","きょう、はたけのさくもつを1かいしゅうかくしよう。"],
  ["今日の魚の便り","Today’s fishing task","きょうのさかなのたより"],
  ["今日、魚を2匹釣ろう。","Catch two fish today.","きょう、さかなを2ひきつろう。"],
  ["今日の広場のお手伝い","Today’s village help","きょうのひろばのおてつだい"],
  ["今日、広場へ2回納品しよう。","Make two deliveries today.","きょう、ひろばへ2かいのうひんしよう。"],
  ["発展ポイント","Development points","はってんポイント"],
  ["納品で3、収穫で2、新しい建築マスで2ポイント。","Deliveries earn 3 points, harvests 2, and each new building tile 2.","のうひんで3、しゅうかくで2、あたらしいけんちくマスで2ポイント。"],
  ["住民の依頼","Resident requests","じゅうみんのいらい"],
  ["常設依頼は3件まで受注できます。日替わり依頼は島の1日ごとに更新。","Accept up to three permanent requests. Daily requests refresh each island day.","じょうせついらいは3けんまでじゅちゅうできます。ひがわりいらいはしまの1にちごとにこうしん。"],
  ["日替わり","Daily","ひがわり"],
  ["達成済み","Completed","たっせいずみ"],
  ["島の発展で解放","Unlock through island growth","しまのはってんでかいほう"],
  ["報告して報酬を受け取る","Report and claim reward","ほうこくしてほうしゅうをうけとる"],
  ["挑戦中","In progress","ちょうせんちゅう"],
  ["依頼を受ける","Accept request","いらいをうける"],
  ["島の発展と依頼","Island growth and requests","しまのはってんといらい"],
  ["自分の家","Your home","じぶんのいえ"],
  ["広場から離れた空いた草地に、自分の家の入口を建てましょう。","Build your home entrance on empty grass away from the square.","ひろばからはなれたあいたくさちに、じぶんのいえのいりぐちをたてましょう。"],
  ["建築費はコイン不要","No coins needed to build","けんちくひはコインふよう"],
  ["空き地を選ぶ","Choose a site","あきちをえらぶ"],
  ["選んだ場所に家を建てる","Build home on selected tile","えらんだばしょにいえをたてる"],
  ["家の入口","Home entrance","いえのいりぐち"],
  ["入口の近くまで移動して、自分の家に入りましょう。","Move near your entrance to enter your home.","いりぐちのちかくまでいどうして、じぶんのいえにはいりましょう。"],
  ["家に入る","Enter home","いえにはいる"],
  ["マスを選び、持ち物の家具を飾れます。","Select a square and place furnishings from your inventory.","マスをえらび、もちもののかぐをかざれます。"],
  ["部屋のマス","Room square","へやのマス"],
  ["家具を飾る","Place furnishing","かぐをかざる"],
  ["家具を戻す","Return furnishing","かぐをもどす"],
  ["家を拡張","Expand home","いえをかくちょう"],
  ["島を発展させて拡張","Grow the island to expand","しまをはってんさせてかくちょう"],
  ["家を拡張する","Expand your home","いえをかくちょうする"],
  ["最大まで拡張しました。自由に家具を飾りましょう！","Your home is fully expanded. Furnish it however you like!","さいだいまでかくちょうしました。じゆうにかぐをかざりましょう！"],
  ["家を出る","Leave home","いえをでる"],
  ["島が発展すると受けられる依頼です。","Grow the island to unlock this request.","しまがはってんするとうけられるいらいです。"],
  ["受注できる依頼は3件までです。","You can accept up to three requests.","じゅちゅうできるいらいは3けんまでです。"],
  ["依頼を受けました！","Request accepted!","いらいをうけました！"],
  ["依頼の条件を達成してから報告しましょう。","Meet the request conditions before reporting.","いらいのじょうけんをたっせいしてからほうこくしましょう。"],
  ["依頼達成！報酬を受け取りました。","Request completed! Reward received.","いらいたっせい！ほうしゅうをうけとりました。"],
  ["自分の家はすでにあります。","You already have a home.","じぶんのいえはすでにあります。"],
  ["近くの空いた草地を選びましょう。","Select nearby empty grass.","ちかくのあいたくさちをえらびましょう。"],
  ["広場から離れた空き地に家を建てましょう。","Build on empty land away from the square.","ひろばからはなれたあきちにいえをたてましょう。"],
  ["自分の家ができました！入口の近くで入れます。","Your home is ready! Enter from near the entrance.","じぶんのいえができました！いりぐちのちかくではいれます。"],
  ["自分の家の入口に近づいてください。","Move closer to your home entrance.","じぶんのいえのいりぐちにちかづいてください。"],
  ["おかえりなさい！","Welcome home!","おかえりなさい！"],
  ["家は最大まで拡張されています。","Your home is fully expanded.","いえはさいだいまでかくちょうされています。"],
  ["家に入ってから拡張しましょう。","Enter your home before expanding.","いえにはいってからかくちょうしましょう。"],
  ["島を発展させると家を拡張できます。","Grow the island to expand your home.","しまをはってんさせるといえをかくちょうできます。"],
  ["拡張に必要な材料とコインが足りません。","Not enough materials and coins to expand.","かくちょうにひつようなざいりょうとコインがたりません。"],
  ["家が広くなりました！","Your home is larger!","いえがひろくなりました！"],
  ["家の中のマスを選んでください。","Select a square inside your home.","いえのなかのマスをえらんでください。"],
  ["家具を持ち物に戻しました。","Furnishing returned to your inventory.","かぐをもちものにもどしました。"],
  ["家具を置ける空いたマスを選びましょう。","Choose an empty square for the furnishing.","かぐをおけるあいたマスをえらびましょう。"],
  ["家具を飾りました！","Furnishing placed!","かぐをかざりました！"],
  ["島の作業は家を出てから行いましょう。","Leave your home before working on the island.","しまのさぎょうはいえをでてからおこないましょう。"],
  ["島が発展すると買える品物です。","Grow the island to buy this item.","しまがはってんするとかえるしなものです。"],
  ["家の入口は片づけたり建築したりできません。","You cannot remove or build over a home entrance.","いえのいりぐちはかたづけたりけんちくしたりできません。"],
  ["島の発展と依頼で目標を確認。自分の家は入口を建て、家具を飾り、島の発展に合わせて拡張できます。","Check your goals in Island growth and requests. Build your home entrance, furnish it, and expand as the island grows.","しまのはってんといらいでもくひょうをかくにん。じぶんのいえはいりぐちをたて、かぐをかざり、しまのはってんにあわせてかくちょうできます。"],
  ['島の1日は4分です。','An island day lasts four minutes.','しまの1にちは4ふんです。'],
];
export const CRAFT_ENGLISH = Object.fromEntries(COPY.map(([ja,en])=>[ja,en]));
export const CRAFT_HIRAGANA = Object.fromEntries(COPY.map(([ja,,hi])=>[ja,hi]));
