const COPY: [string,string,string][] = [
  ['学ロクラフト','Gakuro Craft','がくろクラフト'],
  ['40人で島づくり','Build an island with 40 players','40にんでしまづくり'],
  ['学んで、つくって、みんなで暮らす。','Learn, build, and live together.','まなんで、つくって、みんなでくらす。'],
  ['最大40人','Up to 40 players','さいだい40にん'],['共有の島','Shared island','きょうゆうのしま'],['開発中','In development','かいはつちゅう'],
  ['名前','Name','なまえ'],['カラー','Color','カラー'],['みんなの島を開く','Host an island','みんなのしまをひらく'],['ひとりで遊ぶ','Play solo','ひとりであそぶ'],
  ['保存した島を続ける','Continue saved island','ほぞんしたしまをつづける'],['招待コード','Invite code','しょうたいコード'],['島に参加','Join island','しまにさんか'],
  ['島と問題を準備中…','Preparing the island and questions…','しまともんだいをじゅんびちゅう…'],['タイトルへ戻る','Back to title','タイトルへもどる'],
  ['クラフトの問題選択','Craft question selection','クラフトのもんだいせんたく'],['4択の問題に正解するとエネルギーが30回復','Answer a multiple-choice question to restore 30 energy','4たくのもんだいにせいかいするとエネルギーが30かいふく'],
  ['配信課題を選ぶ','Select an assignment','はいしんかだいをえらぶ'],['受け取り済みの課題','Received assignment','うけとりずみのかだい'],
  ['エネルギー','Energy','エネルギー'],['問題で回復','Answer to recharge','もんだいでかいふく'],['正解ごとに +30','+30 per correct answer','せいかいごとに +30'],
  ['正解でエネルギー +30。不正解でも減りません。','Correct answers restore 30 energy. Mistakes cost nothing.','せいかいでエネルギー +30。ふせいかいでもへりません。'],
  ['正解！エネルギー回復','Correct! Energy restored','せいかい！エネルギーかいふく'],['正答を確認しましょう','Check the correct answer','せいとうをかくにんしましょう'],
  ['次の問題','Next question','つぎのもんだい'],['島に戻る','Back to island','しまにもどる'],['好きなときに島に戻れます。','You can return to the island anytime.','すきなときにしまにもどれます。'],
  ['聞く','Listen','きく'],['閉じる','Close','とじる'],['戻る','Back','もどる'],['遊び方','How to play','あそびかた'],['退出','Leave','たいしゅつ'],
  ['木材','Wood','もくざい'],['石','Stone','いし'],['種','Seeds','たね'],['作物','Crops','さくもつ'],['魚','Fish','さかな'],['木の床','Wooden floor','きのゆか'],['石のブロック','Stone block','いしのブロック'],['花壇','Flower bed','かだん'],['ランタン','Lantern','ランタン'],['ベンチ','Bench','ベンチ'],
  ['採集','Gather','さいしゅう'],['種まき','Plant','たねまき'],['水やり','Water','みずやり'],['収穫','Harvest','しゅうかく'],['釣り','Fish','つり'],['建築','Build','けんちく'],['片づけ','Remove','かたづけ'],
  ['島のみんなの記録','Island achievements','しまのみんなのきろく'],['広場に作物か魚を納品すると種がもらえます。','Donate crops or fish in the plaza to earn seeds.','ひろばにさくもつかさかなをのうひんするとたねがもらえます。'],['広場で納品','Donate at plaza','ひろばでのうひん'],
  ['持ち物とクラフト','Inventory & crafting','もちものとクラフト'],['招待','Invite','しょうたい'],['縮小','Zoom out','しゅくしょう'],['拡大','Zoom in','かくだい'],
  ['移動','Move','いどう'],['上','Up','うえ'],['下','Down','した'],['左','Left','ひだり'],['右','Right','みぎ'],
  ['近くのマスをタップして選択','Tap a nearby tile to select it','ちかくのマスをタップしてせんたく'],['選んだ場所で作業','Work on selected tile','えらんだばしょでさぎょう'],['材料からつくる','Craft with materials','ざいりょうからつくる'],['つくる','Craft','つくる'],['置く','Place','おく'],
  ['このリンクからはデバッグ設定なしで参加できます。','This link lets players join without debug mode.','このリンクからはデバッグせっていなしでさんかできます。'],['招待リンク','Invitation link','しょうたいリンク'],['招待URLをコピー','Copy invite URL','しょうたいURLをコピー'],['コピーしました','Copied','コピーしました'],['リンクを選択してコピーしてください。','Select and copy the link.','リンクをせんたくしてコピーしてください。'],
  ['ホストの画面を開いたまま遊んでください。','Keep the host screen open while playing.','ホストのがめんをひらいたままあそんでください。'],
  ['矢印キー・WASD、または画面左下の矢印で移動。','Move with arrow keys, WASD, or the on-screen arrows.','やじるしキー・WASD、またはがめんひだりしたのやじるしでいどう。'],
  ['近くのマスを選び、道具を選んで「選んだ場所で作業」を押します。','Select a nearby tile, choose a tool, then press Work on selected tile.','ちかくのマスをえらび、どうぐをえらんで「えらんだばしょでさぎょう」をおします。'],
  ['木や石を採集してクラフト。床は橋になり、ブロックは4段まで積めます。','Gather wood and stone to craft. Floors make bridges; stack up to four blocks.','きやいしをさいしゅうしてクラフト。ゆかははしになり、ブロックは4だんまでつめます。'],
  ['種は90秒で成長。水やりで45秒に短縮。海や川では釣りができます。','Crops grow in 90 seconds, or 45 when watered. Fish in the sea and river.','たねは90びょうでせいちょう。みずやりで45びょうにたんしゅく。うみやかわではつりができます。'],
  ['エネルギーがなくなっても「問題で回復」で再開できます。','Out of energy? Answer a question to recharge and keep playing.','エネルギーがなくなっても「もんだいでかいふく」でさいかいできます。'],
  ['島はホストの端末に自動保存。次回は「保存した島を続ける」を選べます。','The island saves on the host device. Choose Continue saved island next time.','しまはホストのたんまつにじどうほぞん。じかいは「ほぞんしたしまをつづける」をえらべます。'],
  ['ホストが戻るまで一時停止中です。','Paused until the host returns.','ホストがもどるまでいちじていしちゅうです。'],
  ['材料が足りません。','Not enough materials.','ざいりょうがたりません。'],['問題に正解してエネルギーを回復しましょう。','Answer a question correctly to restore energy.','もんだいにせいかいしてエネルギーをかいふくしましょう。'],['クラフトしました！','Crafted!','クラフトしました！'],
  ['島の中央の広場で納品できます。','Donate at the plaza in the island center.','しまのちゅうおうのひろばでのうひんできます。'],['作物か魚を納品しましょう。','Bring crops or fish to donate.','さくもつかさかなをのうひんしましょう。'],['納品ありがとう！種を2個受け取りました。','Thank you! You received two seeds.','のうひんありがとう！たねを2こうけとりました。'],
  ['もう少し近づいてください。','Move a little closer.','もうすこしちかづいてください。'],['素材を集めました！','Materials gathered!','そざいをあつめました！'],
  ['種が足りません。木を採集するか、広場へ納品しましょう。','Need seeds? Gather trees or donate at the plaza.','たねがたりません。きをさいしゅうするか、ひろばへのうひんしましょう。'],
  ['種をまきました。水やりで早く育ちます。','Seeds planted. Water them to grow faster.','たねをまきました。みずやりではやくそだちます。'],['水をあげました！','Watered!','みずをあげました！'],['収穫しました！','Harvested!','しゅうかくしました！'],
  ['釣りは3秒おきにできます。','Wait three seconds between catches.','つりは3びょうおきにできます。'],['魚が釣れました！','Fish caught!','さかながつれました！'],
  ['ほかの人の建築は変更できません。','You cannot change another player’s building.','ほかのひとのけんちくはへんこうできません。'],['中央の広場は空けておきましょう。','Keep the central plaza clear.','ちゅうおうのひろばはあけておきましょう。'],['水の上には木の床で橋を架けられます。','Use wooden floors to build a bridge over water.','みずのうえにはきのゆかではしをかけられます。'],['飾りの上には積めません。','You cannot stack blocks on decorations.','かざりのうえにはつめません。'],
  ['人がいる場所には置けません。','A player is standing there.','ひとがいるばしょにはおけません。'],['建築しました！','Built!','けんちくしました！'],['人がいる場所は片づけられません。','Wait for the player to move before removing this.','ひとがいるばしょはかたづけられません。'],['片づけました。素材が戻りました。','Removed and materials returned.','かたづけました。そざいがもどりました。'],['この場所ではその作業はできません。','That action cannot be used on this tile.','このばしょではそのさぎょうはできません。'],
  ['島を保存できませんでした。端末の空き容量を確認してください。','Could not save the island. Check device storage.','しまをほぞんできませんでした。たんまつのあきようりょうをかくにんしてください。'],['接続がタイムアウトしました。','Connection timed out.','せつぞくがタイムアウトしました。'],['接続できませんでした。もう一度お試しください。','Could not connect. Please try again.','せつぞくできませんでした。もういちどおためしください。'],['接続を終了しました。','Connection closed.','せつぞくをしゅうりょうしました。'],['通信エラーが発生しました。','A connection error occurred.','つうしんエラーがはっせいしました。'],['部屋が満員か、参加できません。','The room is full or unavailable.','へやがまんいんか、さんかできません。'],['6文字の招待コードを入力してください。','Enter a six-character invite code.','6もじのしょうたいコードをにゅうりょくしてください。'],['部屋が見つからないか、接続できません。','Room not found or connection unavailable.','へやがみつからないか、せつぞくできません。'],['ホストとの接続が終了しました。','The host connection closed.','ホストとのせつぞくがしゅうりょうしました。'],['通信が途切れました。部屋に入り直してください。','Connection lost. Please rejoin the room.','つうしんがとぎれました。へやにはいりなおしてください。'],
];
export const CRAFT_ENGLISH = Object.fromEntries(COPY.map(([ja,en])=>[ja,en]));
export const CRAFT_HIRAGANA = Object.fromEntries(COPY.map(([ja,,hi])=>[ja,hi]));
