export const GAME_ROOM_ENGLISH:Record<string,string>={
  "一戦対戦": "Single match",
  "5階層の冒険": "Five-floor expedition",
  "アレンジ個人戦": "Free-for-all rules",
  "通常ルール": "Classic rules",
  "階層": "Floor",
  "共有ライフ": "Shared lives",
  "目標冒険点": "Target expedition points",
  "冒険ルールとレリック": "Expedition rules and relics",
  "レリックを1つ選ぶ": "Choose one relic",
  "仲間のレリック選択を待っています": "Waiting for friends to choose relics",
  "選択完了": "Choices ready",
  "次の階層へ": "Next floor",
  "静かな階層": "Quiet floor",
  "急ぐ階層": "Haste floor",
  "試練の階層": "Trial floor",
  "全員の冒険点の平均で階層を攻略。目標未達成で共有ライフが減少。各階層後に3択レリックを獲得し、5階層を生き抜こう。総冒険点で個人順位も決まります。": "Clear floors using the average expedition points of all players. Missing the target costs a shared life. Choose one of three relics after each floor and survive five floors. Total points also determine individual standings.",
  "急ぐ階層では手番時間が短縮、試練の階層では目標が上昇。音ゲーの譜面と判定は変わりません。": "Haste floors shorten turn timers. Trial floors raise the target. Rhythm charts and judgement windows stay the same.",
  "時の砂時計": "Hourglass of time",
  "勝負師の紋章": "Challenger crest",
  "守りの羽": "Guardian feather",
  "癒しの灯": "Healing lantern",
  "連勝の王冠": "Victory crown",
  "星読みの羅針盤": "Astral compass",
  "手番の制限時間を8秒延長。冒険点も5%増加。": "Adds eight seconds to turn timers and 5% to expedition points.",
  "各階層の冒険点が20%増加。": "Adds 20% to expedition points on every floor.",
  "未達成時に一度だけ共有ライフの減少を防ぐ。": "Prevents one shared life loss when a target is missed.",
  "獲得すると共有ライフを1回復。最大3。": "Restores one shared life when chosen, up to three.",
  "その階層で勝者になると冒険点が30%増加。": "Adds 30% to expedition points when you win a floor.",
  "毎階層の冒険点に120点を加算。": "Adds 120 expedition points on every floor.",
  "冒険を踏破しました！": "Expedition complete!",
  "冒険はここまで。もう一度挑戦！": "Expedition ended. Try again!",
  "階層クリア！レリックを選んで次へ。": "Floor cleared! Choose a relic to continue.",
  "目標未達成。レリックを選んで立て直そう。": "Target missed. Choose a relic and recover.",
  "冒険設定を更新しました。": "Expedition settings updated.",
  "全員のレリック選択を待っています。": "Waiting for everyone to choose a relic.",
  "同じ家の家具から参加。最大4人で対戦できます。アレンジ個人戦と5階層の冒険を選べます。盤面ゲームは2〜4人、その他は1人でも練習できます。": "Join furniture in the same home. Up to four players can choose free-for-all rules or a five-floor expedition. Board games need two to four players; other games support solo practice.",
  "2〜4人の個人戦。各プレイヤーが自分の色で競います。リバーシは他の色を挟んで取り、四目並べは自分の色を4個つなげます。": "Two to four players compete with individual colors. In Reversi, capture other colors between your pieces; in Connect Four, link four of your own pieces.",
  "1〜4人の得点対戦。1手番3投、全5ラウンド。合計得点で勝負！": "One to four players: three darts per turn for five rounds. Highest total wins!",
  "1〜4人の個人戦。どの色の球も1点、8番は3点。全て沈めて得点で決着。ファウルは1点減点。": "One to four players compete individually. Any colored ball is one point; the eight ball is three. Clear the table to finish. Fouls cost one point.",
  "安全に進む": "Play it safe",
  "大胆に進む": "Take a risk",
  "1〜4人の宝探し。ペアを連続で見つけると2〜5点に増加。外すと連続ボーナスがリセット。": "One to four treasure hunters. Consecutive pairs increase rewards from two to five points; a mismatch resets the streak.",
  "1〜4人の冒険レース。安全なサイコロは2〜4、大胆なサイコロは1〜8。加速と後退のマスを読み、40マス先のゴールを目指そう。": "One to four racers. Safe dice roll two to four, risky dice one to eight. Plan around boosts and setbacks to reach space forty.",
  "1〜4人で5フレームの短期決戦。ストライクとスペアの加点は本格ルール。5フレーム目にボーナス投球あり。": "One to four players compete over five frames. Full strike and spare scoring, with bonus rolls in frame five.",
  "1〜4人で16ラウンド。合図から1.4秒の勝負。連続成功で最大30点の追加ボーナス。": "One to four players over sixteen rounds. React within 1.4 seconds; consecutive correct reactions add up to thirty bonus points.",
  "1〜4人のブロック崩し。装甲ブロックは2回当てて破壊。指か左右キーで操作し、75秒の得点で勝負。": "One to four breakout players. Armored blocks take two hits. Move with touch or left/right keys and compete for points over seventy-five seconds.",
  "今回の冒険点": "This floor’s expedition points"
};
export const GAME_ROOM_HIRAGANA:Record<string,string>={
  "一戦対戦": "いっせんたいせん",
  "5階層の冒険": "5かいそうのぼうけん",
  "アレンジ個人戦": "あれんじこじんせん",
  "通常ルール": "つうじょうるーる",
  "階層": "かいそう",
  "共有ライフ": "きょうゆうらいふ",
  "目標冒険点": "もくひょうぼうけんてん",
  "冒険ルールとレリック": "ぼうけんるーるとれりっく",
  "レリックを1つ選ぶ": "れりっくを1つえらぶ",
  "仲間のレリック選択を待っています": "なかまのれりっくせんたくをまっています",
  "選択完了": "せんたくかんりょう",
  "次の階層へ": "つぎのかいそうへ",
  "静かな階層": "しずかなかいそう",
  "急ぐ階層": "いそぐかいそう",
  "試練の階層": "しれんのかいそう",
  "全員の冒険点の平均で階層を攻略。目標未達成で共有ライフが減少。各階層後に3択レリックを獲得し、5階層を生き抜こう。総冒険点で個人順位も決まります。": "ぜんいんのぼうけんてんのへいきんでかいそうをこうりゃく。もくひょうみたっせいできょうゆうらいふがげんしょう。かくかいそうごに3たくれりっくをかくとくし、5かいそうをいきぬこう。そうぼうけんてんでこじんじゅんいもきまります。",
  "急ぐ階層では手番時間が短縮、試練の階層では目標が上昇。音ゲーの譜面と判定は変わりません。": "いそぐかいそうではてばんじかんがたんしゅく、しれんのかいそうではもくひょうがじょうしょう。おとげーのふめんとはんていはかわりません。",
  "時の砂時計": "ときのすなどけい",
  "勝負師の紋章": "しょうぶしのもんしょう",
  "守りの羽": "まもりのはね",
  "癒しの灯": "いやしのあかり",
  "連勝の王冠": "れんしょうのおうかん",
  "星読みの羅針盤": "ほしよみのらしんばん",
  "手番の制限時間を8秒延長。冒険点も5%増加。": "てばんのせいげんじかんを8びょうえんちょう。ぼうけんてんも5%ぞうか。",
  "各階層の冒険点が20%増加。": "かくかいそうのぼうけんてんが20%ぞうか。",
  "未達成時に一度だけ共有ライフの減少を防ぐ。": "みたっせいじにいちどだけきょうゆうらいふのげんしょうをふせぐ。",
  "獲得すると共有ライフを1回復。最大3。": "かくとくするときょうゆうらいふを1かいふく。さいだい3。",
  "その階層で勝者になると冒険点が30%増加。": "そのかいそうでしょうしゃになるとぼうけんてんが30%ぞうか。",
  "毎階層の冒険点に120点を加算。": "まいかいそうのぼうけんてんに120てんをかさん。",
  "冒険を踏破しました！": "ぼうけんをとうはしました！",
  "冒険はここまで。もう一度挑戦！": "ぼうけんはここまで。もういちどちょうせん！",
  "階層クリア！レリックを選んで次へ。": "かいそうくりあ！れりっくをえらんでつぎへ。",
  "目標未達成。レリックを選んで立て直そう。": "もくひょうみたっせい。れりっくをえらんでたてなおそう。",
  "冒険設定を更新しました。": "ぼうけんせっていをこうしんしました。",
  "全員のレリック選択を待っています。": "ぜんいんのれりっくせんたくをまっています。",
  "同じ家の家具から参加。最大4人で対戦できます。アレンジ個人戦と5階層の冒険を選べます。盤面ゲームは2〜4人、その他は1人でも練習できます。": "おなじいえのかぐからさんか。さいだい4にんでたいせんできます。あれんじこじんせんと5かいそうのぼうけんをえらべます。ばんめんげーむは2〜4にん、そのたは1にんでもれんしゅうできます。",
  "2〜4人の個人戦。各プレイヤーが自分の色で競います。リバーシは他の色を挟んで取り、四目並べは自分の色を4個つなげます。": "2〜4にんのこじんせん。かくぷれいやーがじぶんのいろできそいます。りばーしはほかのいろをはさんでとり、よんもくならべはじぶんのいろを4こつなげます。",
  "1〜4人の得点対戦。1手番3投、全5ラウンド。合計得点で勝負！": "1〜4にんのとくてんたいせん。1てばん3とう、ぜん5らうんど。ごうけいとくてんでしょうぶ！",
  "1〜4人の個人戦。どの色の球も1点、8番は3点。全て沈めて得点で決着。ファウルは1点減点。": "1〜4にんのこじんせん。どのいろのたまも1てん、8ばんは3てん。すべてしずめてとくてんでけっちゃく。ふぁうるは1てんげんてん。",
  "安全に進む": "あんぜんにすすむ",
  "大胆に進む": "だいたんにすすむ",
  "1〜4人の宝探し。ペアを連続で見つけると2〜5点に増加。外すと連続ボーナスがリセット。": "1〜4にんのたからさがし。ぺあをれんぞくでみつけると2〜5てんにぞうか。はずすとれんぞくぼーなすがりせっと。",
  "1〜4人の冒険レース。安全なサイコロは2〜4、大胆なサイコロは1〜8。加速と後退のマスを読み、40マス先のゴールを目指そう。": "1〜4にんのぼうけんれーす。あんぜんなさいころは2〜4、だいたんなさいころは1〜8。かそくとこうたいのますをよみ、40ますさきのごーるをめざそう。",
  "1〜4人で5フレームの短期決戦。ストライクとスペアの加点は本格ルール。5フレーム目にボーナス投球あり。": "1〜4にんで5ふれーむのたんきけっせん。すとらいくとすぺあのかてんはほんかくるーる。5ふれーむめにぼーなすとうきゅうあり。",
  "1〜4人で16ラウンド。合図から1.4秒の勝負。連続成功で最大30点の追加ボーナス。": "1〜4にんで16らうんど。あいずから1.4びょうのしょうぶ。れんぞくせいこうでさいだい30てんのついかぼーなす。",
  "1〜4人のブロック崩し。装甲ブロックは2回当てて破壊。指か左右キーで操作し、75秒の得点で勝負。": "1〜4にんのぶろっくくずし。そうこうぶろっくは2かいあててはかい。ゆびかさゆうきーでそうさし、75びょうのとくてんでしょうぶ。",
  "今回の冒険点": "こんかいのぼうけんてん"
};
