import {MAP_WIDTH} from './map';
import {DEFAULT_PET,PETS,PET_KINDS,petKindOf,type PetKind} from './pets';
import {PetPortrait} from './PetSprite';
import HobbyGamesPanel from './HobbyGamesPanel';
import {roomHome,roomTile} from './homeSocial';
import {petPose} from './PetSprite';
import HomeView from './HomeView';
import {HOME_ITEMS} from './progression';
import React,{useState} from 'react';
import type {Command,Material,Player,World} from './engine';
import {FURNITURE,HOME_COINS,HOME_COSTS,HOME_NAMES,HOME_SIZES,questRows,STAGES,village} from './progression';
type Props={world:World;me:Player;t:(s:string)=>string;send:(c:Command)=>void;items:Record<Material,[string,string]>};
export function GoalsPanel({world,me,t,send,items}:Props){const v=village(world);return <>
 <div className="gc-village-summary"><b>🌿 {t(v.stage.name)}</b><span>{v.score} / {v.next?.need??v.score} {t('発展ポイント')}</span><progress max={v.next?.need||Math.max(1,v.score)} value={v.score}/><p>{t('納品で3、収穫で2、新しい建築マスで2ポイント。')}</p></div>
 <div className="gc-stages">{STAGES.map((s,i)=><div key={s.name} className={v.level>=i?'unlocked':''}><b>{v.level>=i?'✓':'🔒'} {t(s.name)}</b><small>{t(s.facility)} · {s.need}</small></div>)}</div>
 <h3>{t('住民の依頼')}</h3><p>{t('常設依頼は3件まで受注できます。日替わり依頼は島の1日ごとに更新。')} {t('島の1日は4分です。')}</p>
 <div className="gc-quests">{questRows(world,me).map(q=>{const locked=v.level<q.stage;return <article key={q.id} className={q.claimed?'complete':''}><div className="gc-quest-resident">{q.resident==='ソラ'?'🛠':q.resident==='ミドリ'?'🌱':'🎣'} {t(q.resident)}{q.daily&&<small>{t('日替わり')}</small>}</div><h4>{t(q.title)}</h4><p>{t(q.description)}</p><progress max={q.target} value={Math.min(q.value,q.target)}/><small>{Math.min(q.value,q.target)} / {q.target} · 🪙{q.coins} {Object.entries(q.reward).map(([k,n])=>`${items[k as Material][0]}×${n}`).join(' ')}</small><button disabled={q.claimed||locked||(q.accepted&&q.value<q.target)||(!q.accepted&&me.progress.active.length>=3)} onClick={()=>send({type:q.accepted?'quest_claim':'quest_accept',id:q.id})}>{t(q.claimed?'達成済み':locked?'島の発展で解放':q.accepted?q.value>=q.target?'報告して報酬を受け取る':'挑戦中':'依頼を受ける')}</button></article>;})}</div>
 </>;}
export function HomePanel({world,me,t,send,items,selected,onChooseLand,onStudy,onDress}:Props&{selected:number;onChooseLand:()=>void;onStudy:()=>void;onDress:()=>void}){
 const home=me.progress.home,v=village(world),[slot,setSlot]=useState(-1),[sourceSlot,setSourceSlot]=useState(-1),[furniture,setFurniture]=useState<(typeof FURNITURE)[number]>('bench'),size=HOME_SIZES[home.level];
 const visiting=me.indoors&&roomTile(me)!==home.tile,shown=roomHome(world,me)||home,people=Object.values(world.players).filter(p=>p.indoors&&roomTile(p)===shown.tile&&p.id!==me.id),[petName,setPetName]=useState(''),[adoptKind,setAdoptKind]=useState<PetKind>(DEFAULT_PET),[adoptName,setAdoptName]=useState<string>(PETS[DEFAULT_PET].name);
 const petControls=<section className="gc-pet-panel"><h3>{PETS[petKindOf(shown.pet?.kind)].emoji} {t('おうちのペット')}</h3><p>{shown.pet?.name||t('ミケ')} · {t(PETS[petKindOf(shown.pet?.kind)].label)} · {t('交流度')} ♥{shown.pet?.affection??30}/100 · {t(petPose(shown,world.time).behavior)}</p><p>{t('交流度100で、おなかを見せるしぐさが解放されます。')}</p><button disabled={world.paused} onClick={()=>send({type:'pet_care'})}>{t('なでる')}</button>{!visiting&&<div className="gc-row"><input aria-label={t('ペットの名前')} maxLength={16} value={petName} onChange={e=>setPetName(e.target.value)} placeholder={shown.pet?.name||t('ミケ')}/><button disabled={!petName.trim()||world.paused} onClick={()=>send({type:'pet_name',name:petName})}>{t('名前をつける')}</button></div>}</section>;
 if(visiting)return <><h3>🏡 {t('友達の家')}</h3><p>{people.map(p=>p.name).join(' · ')}</p><HomeView home={shown} slot={slot} onSelect={setSlot} t={t} avatar={me.avatar} time={world.time} visitors={people}/>{petControls}<HobbyGamesPanel world={world} me={me} home={shown} t={t} send={send}/><button className="gc-primary" onClick={onStudy}>⚡ {t('問題で回復')}</button><button onClick={()=>send({type:'home_leave'})}>{t('家を出る')}</button></>;
 const cost=HOME_COSTS[home.level],coins=HOME_COINS[home.level],blocked=!!cost&&(me.coins<coins||Object.entries(cost).some(([k,n])=>me.bag[k as Material]<n!));
 return <><h3>🏡 {t(HOME_NAMES[home.level])}</h3>{!home.level?<><p>{t('広場から離れた空いた草地に、自分の家の入口を建てましょう。')}</p><p>🪵6 · 🪨4 · {t('建築費はコイン不要')}</p><fieldset className="gc-pet-adoption"><legend>{t('一緒に暮らすペットを選ぶ')}</legend><div className="gc-pet-choices">{PET_KINDS.map(kind=><button type="button" key={kind} aria-pressed={kind===adoptKind} onClick={()=>{setAdoptKind(kind);if(!adoptName.trim()||adoptName===PETS[adoptKind].name)setAdoptName(PETS[kind].name);}}><PetPortrait kind={kind} label={t(PETS[kind].label)}/><span>{t(PETS[kind].label)}</span></button>)}</div><label>{t('一緒に暮らすペットの名前')}<input aria-label={t('一緒に暮らすペットの名前')} maxLength={16} value={adoptName} onChange={e=>setAdoptName(e.target.value)}/></label><p>{t('ペットは家の中で暮らします。名前はあとから変更できます。')}</p></fieldset><div className="gc-row"><button onClick={onChooseLand}>{t('空き地を選ぶ')}</button><button disabled={!adoptName.trim()||selected<0||me.bag.wood<6||me.bag.stone<4||world.paused} onClick={()=>send({type:'home_claim',tile:selected,petKind:adoptKind,petName:adoptName.trim()})}>{t('選んだ場所に家を建てる')}</button></div></>:<>
 <p>{t('家の入口')} · {home.tile%MAP_WIDTH}, {Math.floor(home.tile/MAP_WIDTH)} · {size}×{size}</p>
 {!me.indoors?<><p>{t('入口の近くまで移動して、自分の家に入りましょう。')}</p><button className="gc-primary" onClick={()=>send({type:'home_enter'})}>{t('家に入る')}</button></>:<>
 <p>{t('マスを選んで配置。家具を選ぶと向き・場所・使い方を変更できます。')}</p><HomeView home={home} slot={slot} onSelect={n=>{setSlot(n);const f=home.furniture.find(f=>f.slot===n);if(f){setFurniture(f.item);setSourceSlot(n);}}} t={t} avatar={me.avatar} time={world.time} visitors={people}/>
 <div className="gc-furniture">{FURNITURE.map(b=><button key={b} aria-pressed={b===furniture} onClick={()=>{setFurniture(b);setSourceSlot(home.furniture.find(f=>f.item===b)?.slot??-1);}}>{HOME_ITEMS[b][1]} {t(HOME_ITEMS[b][0])} ×{['bench','lamp','flower','campfire'].includes(b)?me.bag[b as Material]:home.stock?.[b]||0}</button>)}</div>
 <p>{t('選んだ家具')}：{t(HOME_ITEMS[furniture][0])} · 🪵{HOME_ITEMS[furniture][2]} · 🪙{HOME_ITEMS[furniture][2]}</p>
 <div className="gc-row"><button disabled={world.paused||me.bag.wood<HOME_ITEMS[furniture][2]||me.coins<HOME_ITEMS[furniture][2]} onClick={()=>send({type:'home_make',item:furniture})}>{t('家具をつくる')}</button><button disabled={slot<0||home.furniture.some(f=>f.slot===slot)||world.paused} onClick={()=>send({type:'home_place',slot,item:furniture})}>{t('家具を飾る')}</button><button disabled={!home.furniture.some(f=>f.slot===slot)||world.paused} onClick={()=>send({type:'home_remove',slot})}>{t('家具を戻す')}</button><button disabled={!home.furniture.some(f=>f.slot===slot)||world.paused} onClick={()=>send({type:'home_rotate',slot})}>{t('向きを変える')}</button></div>
 <div className="gc-row"><button disabled={!home.furniture.some(f=>f.slot===slot)||world.paused} onClick={()=>{const f=home.furniture.find(f=>f.slot===slot);if(!f)return;const effect=HOME_ITEMS[f.item][3];if(effect==='study')onStudy();else if(effect==='dress')onDress();else if(effect==='game')send({type:'game_join',slot});else send({type:'home_use',slot});}}>{t('家具を使う')}</button><button disabled={slot<0||world.paused} onClick={()=>{const source=home.furniture.find(f=>f.slot===sourceSlot);if(source){send({type:'home_move',slot:source.slot,target:slot});setSourceSlot(slot);}}}>{t('選んだ家具をここへ移動')}</button></div>
 <p>{t('休息は60秒ごとに移動速度アップ。作業家具は島の1日ごとに木の床2個。キッチンは材料から料理できます。')}</p><button className="gc-primary" onClick={onStudy}>⚡ {t('問題で回復')}</button>
 {cost?<div className="gc-home-upgrade"><h3>{t('家を拡張')}</h3><p>{t(HOME_NAMES[home.level+1])} · {HOME_SIZES[home.level+1]}×{HOME_SIZES[home.level+1]}</p><p>🪙{coins} · {Object.entries(cost).map(([k,n])=>`${t(items[k as Material][1])} ×${n}`).join(' / ')}</p><button disabled={blocked||v.level<home.level||world.paused} onClick={()=>{setSlot(-1);send({type:'home_upgrade'});}}>{t(v.level<home.level?'島を発展させて拡張':'家を拡張する')}</button></div>:<p>{t('最大まで拡張しました。自由に家具を飾りましょう！')}</p>}
 {petControls}<HobbyGamesPanel world={world} me={me} home={home} t={t} send={send}/>
 <button onClick={()=>send({type:'home_leave'})}>{t('家を出る')}</button></>}
 </>}
 </>;
}
