import React,{useEffect,useRef,useState} from 'react';
import type {HomeGameWorld as World,HomeGamePlayer as Player,GameCommand as Command} from './homeGames';
import type {Home} from './progression';
import {HOME_ITEMS} from './progression';
import {gameOf} from './homeGames';
type Pull={pointerId:number;key:string;turn:number;x:number;y:number;endX:number;endY:number;screenX:number;screenY:number};
const labels={darts:'ダーツ301',billiards:'8ボール',arcade:'コズミックブレイク'};
const colors=['#ef986b','#78bacb','#b69bdb','#e5c367'];
export default function HobbyGamesPanel({world,me,home,t,send}:{world:World;me:Player;home:Home;t:(s:string)=>string;send:(c:Command)=>void}){
 const g=gameOf(world,me.id),[angle,setAngle]=useState(0),[power,setPower]=useState(0),[placing,setPlacing]=useState(false),[aim,setAim]=useState({x:0,y:0}),[reticle,setReticle]=useState({x:0,y:0});const previous=useRef(''),aimRef=useRef(aim),activeRef=useRef(g),paddleAt=useRef(0);aimRef.current=aim;activeRef.current=g;
 const [pull,setPull]=useState<Pull|null>(null),pullRef=useRef<Pull|null>(null),pausedRef=useRef(world.paused);pausedRef.current=world.paused;
 const cancelPull=()=>{pullRef.current=null;setPull(null);setPower(0);};
 const poolPoint=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*840,y:(e.clientY-r.top)/r.height*440};};
 const canPull=(p:Pull)=>{const game=activeRef.current;return !!game&&game.key===p.key&&game.kind==='billiards'&&game.phase==='playing'&&game.turn===p.turn&&game.players[game.turn]===me.id&&!game.pool?.moving&&!pausedRef.current;};
 const updatePull=(e:React.PointerEvent<SVGSVGElement>)=>{const p=pullRef.current;if(!p||p.pointerId!==e.pointerId)return null;if(!canPull(p)){cancelPull();return null;}const point=poolPoint(e),next={...p,endX:point.x,endY:point.y};pullRef.current=next;setPull(next);setAngle(Math.atan2(p.y-point.y,p.x-point.x)*180/Math.PI);setPower(Math.min(1,Math.hypot(p.x-point.x,p.y-point.y)/240));return next;};
 useEffect(()=>{cancelPull();setPlacing(false);},[g?.key,g?.turn,g?.phase,g?.pool?.moving,world.paused]);
 useEffect(()=>{const cancel=()=>cancelPull();window.addEventListener('blur',cancel);return()=>window.removeEventListener('blur',cancel);},[]);
 useEffect(()=>{let frame=0;const move=(now:number)=>{const a=aimRef.current;setReticle({x:a.x+Math.sin(now*.0031)*.11,y:a.y+Math.cos(now*.0037)*.11});frame=requestAnimationFrame(move);};if(g?.kind==='darts'&&g.phase==='playing')frame=requestAnimationFrame(move);return()=>cancelAnimationFrame(frame);},[g?.key,g?.kind,g?.phase]);
 useEffect(()=>{if(!g)return;const marker=g.key+':'+g.revision+':'+g.scores.join();if(previous.current&&previous.current!==marker){window.dispatchEvent(new CustomEvent('craft-hobby-sound',{detail:g.phase==='finished'?'donate':'ui'}));}previous.current=marker;},[g?.key,g?.revision,g?.scores.join(),g?.phase]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const game=activeRef.current;if(!game||game.kind!=='arcade'||game.phase!=='playing'||['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;const seat=game.players.indexOf(me.id),court=game.courts?.[seat];if(!court||!['ArrowLeft','ArrowRight','a','d'].includes(e.key))return;e.preventDefault();send({type:'game_paddle',key:game.key,x:court.target+(['ArrowLeft','a'].includes(e.key)?-.08:.08)});};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[send,me.id]);
 const hobbies=home.furniture.filter(f=>['darts','billiards','arcade'].includes(f.item));
 if(!hobbies.length)return <p>{t('趣味家具を飾ると、友達と4人までで遊べます。')}</p>;
 const seat=g?.players.indexOf(me.id)??-1,myTurn=g?.phase==='playing'&&g.turn===seat&&!world.paused,deadline=Math.max(0,Math.ceil((g?.deadline||0)-world.time));
 return <section className="gc-hobby"><h3>{t('みんなのゲームルーム')}</h3><p>{t('同じ家の家具から参加。1人で練習、最大4人で対戦できます。')}</p>
 {!g?<div className="gc-row">{hobbies.map(f=><button key={f.slot} disabled={world.paused} onClick={()=>send({type:'game_join',slot:f.slot})}>{HOME_ITEMS[f.item][1]} {t(HOME_ITEMS[f.item][0])} · {Object.values(world.games||{}).find(g=>g.homeTile===home.tile&&g.slot===f.slot)?.players.length||0}/4</button>)}</div>:<>
 <h4>{t(labels[g.kind])} · {g.players.length}/4</h4><div className="gc-game-seats">{g.players.map((id,i)=><div key={id} className={g.turn===i&&g.phase==='playing'?'current':''} style={{borderColor:colors[i]}}><b>{g.names[i]}{id===me.id?' ★':''}</b><span>{g.scores[i]??0}{g.kind==='billiards'&&<small> · {t(i%2===0?'チームA':'チームB')}</small>}</span></div>)}</div>
 {g.phase!=='playing'?<><p>{t(g.message)}</p>{g.phase==='finished'&&<strong>{t('勝者')}：{g.winner.map(i=>g.names[i]).join(' / ')||t('今回は勝者なし')}</strong>}<div className="gc-row"><button disabled={g.players[0]!==me.id||world.paused} onClick={()=>send({type:'game_start',key:g.key})}>{t(g.phase==='finished'?'もう一度遊ぶ':'ゲーム開始')}</button><button onClick={()=>send({type:'game_leave',key:g.key})}>{t('対戦から退出')}</button></div></>:<>
 <p className="gc-game-status">{g.kind==='arcade'?t('残り時間'):g.names[g.turn]+' · '+t('手番')} · {deadline}s</p>
 {g.kind==='darts'&&<><p>{t('301点から減らし、最後はダブルで0点。1手番3投。狙いをタップし、照準を見て投げましょう。')} · {t('残り投数')} {g.darts?.left}</p><svg className="gc-darts-board" tabIndex={0} viewBox="-120 -120 240 240" role="group" aria-label={t('ダーツの的')} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();setAim({x:Math.max(-1.1,Math.min(1.1,(e.clientX-r.left)/r.width*2.4-1.2)),y:Math.max(-1.1,Math.min(1.1,(e.clientY-r.top)/r.height*2.4-1.2))});}}>
 {Array.from({length:20},(_,i)=>{const a=(i*18-99)*Math.PI/180,b=(i*18-81)*Math.PI/180,path=(r:number)=>'M0 0 L'+Math.cos(a)*r+' '+Math.sin(a)*r+' A'+r+' '+r+' 0 0 1 '+Math.cos(b)*r+' '+Math.sin(b)*r+'Z',ring=(inner:number,outer:number)=>'M'+Math.cos(a)*inner+' '+Math.sin(a)*inner+' L'+Math.cos(a)*outer+' '+Math.sin(a)*outer+' A'+outer+' '+outer+' 0 0 1 '+Math.cos(b)*outer+' '+Math.sin(b)*outer+' L'+Math.cos(b)*inner+' '+Math.sin(b)*inner+' A'+inner+' '+inner+' 0 0 0 '+Math.cos(a)*inner+' '+Math.sin(a)*inner+'Z';return <g key={i}><path d={path(100)} fill={i%2?'#eadfbe':'#303d3b'} stroke="#b9baa8"/><path d={ring(92,100)} fill={i%2?'#6c9c78':'#c67165'}/><path d={ring(56,64)} fill={i%2?'#6c9c78':'#c67165'}/><text x={Math.cos((a+b)/2)*110} y={Math.sin((a+b)/2)*110+3} textAnchor="middle" fontSize="9" fill="#354e44">{[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5][i]}</text></g>;})}<circle r="9" fill="#6c9c78"/><circle r="3.5" fill="#c67165"/>{g.darts?.throws.map((d,i)=><g key={i} transform={'translate('+d.x*100+','+d.y*100+')'}><path d="M-3 -3L3 3M3 -3L-3 3" stroke="#ffbc4f" strokeWidth="2"/></g>)}{myTurn&&<g transform={'translate('+reticle.x*100+','+reticle.y*100+')'}><circle r="6" fill="none" stroke="#58bfea" strokeWidth="1.5"/><path d="M-9 0H9M0 -9V9" stroke="#58bfea"/></g>}</svg><button className="gc-primary" disabled={!myTurn} onClick={()=>send({type:'game_dart',key:g.key,x:reticle.x,y:reticle.y})}>{t('ダーツを投げる')}</button></>}
 {g.kind==='billiards'&&g.pool&&<><p>{t('2チームで8ボール。自分の色をすべて沈めてから8番。ファウル時は次の人が手玉を置けます。')}</p><p>{t('チームA')}：{t(g.pool.groups[0]===1?'ソリッド':g.pool.groups[0]===2?'ストライプ':'未決定')} · {t('チームB')}：{t(g.pool.groups[1]===1?'ソリッド':g.pool.groups[1]===2?'ストライプ':'未決定')}</p>
 <svg className="gc-pool-table" tabIndex={0} viewBox="0 0 840 440" role="group" aria-label={t('ビリヤードの台')} onPointerDown={e=>{if(!myTurn||g.pool!.moving||!e.isPrimary||e.button!==0||pullRef.current)return;e.preventDefault();const point=poolPoint(e);if(placing&&g.pool!.ballInHand){send({type:'game_cue',key:g.key,x:(point.x-20)/800,y:(point.y-20)/400});setPlacing(false);return;}const p={pointerId:e.pointerId,key:g.key,turn:g.turn,x:point.x,y:point.y,endX:point.x,endY:point.y,screenX:e.clientX,screenY:e.clientY};pullRef.current=p;setPull(p);setPower(0);e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={updatePull} onPointerUp={e=>{const p=updatePull(e);if(!p)return;const valid=canPull(p),distance=Math.hypot(p.x-p.endX,p.y-p.endY),moved=Math.hypot(e.clientX-p.screenX,e.clientY-p.screenY);cancelPull();if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(valid&&moved>=8)send({type:'game_shot',key:p.key,angle:Math.atan2(p.y-p.endY,p.x-p.endX),power:Math.max(.1,Math.min(1,distance/240))});}}
 onPointerCancel={e=>{if(pullRef.current?.pointerId===e.pointerId)cancelPull();}} onLostPointerCapture={e=>{if(pullRef.current?.pointerId===e.pointerId)cancelPull();}}>
 <rect width="840" height="440" rx="24" fill="#846349"/><rect x="20" y="20" width="800" height="400" rx="14" fill="#35816f"/>{[[20,20],[420,20],[820,20],[20,420],[420,420],[820,420]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="18" fill="#193c35"/>)}
 {myTurn&&!g.pool.moving&&pull&&power>0&&<line x1={20+g.pool.balls[0].x*800} y1={20+g.pool.balls[0].y*400} x2={20+g.pool.balls[0].x*800+Math.cos(angle*Math.PI/180)*(100+power*180)} y2={20+g.pool.balls[0].y*400+Math.sin(angle*Math.PI/180)*(100+power*180)} stroke="#e8dfad" strokeDasharray="8 6"/>}
 {pull&&<g pointerEvents="none"><line x1={pull.x} y1={pull.y} x2={pull.endX} y2={pull.endY} stroke="#ffe5a4" strokeWidth="4"/><circle cx={pull.x} cy={pull.y} r="10" fill="none" stroke="#ffe5a4" strokeWidth="3"/><circle cx={pull.endX} cy={pull.endY} r="12" fill="#ffe5a4" fillOpacity=".65"/></g>}
 {g.pool.balls.filter(b=>!b.potted).map(b=><g key={b.id} style={{transition:'transform .13s linear'}} transform={'translate('+(20+b.x*800)+','+(20+b.y*400)+')'}><circle r="7.2" fill={b.id===0?'#fff9ec':b.id===8?'#222e2c':['#e3ba42','#5b89c4','#ba6259','#916fb3','#dd9664','#5fa585','#925b5b'][(b.id-1)%8]} stroke={b.id>8?'#fff9ec':'#213f35'} strokeWidth={b.id>8?4:1}/>{!!b.id&&<text y="2.5" textAnchor="middle" fontSize="6" fill="#fff">{b.id}</text>}</g>)}
 </svg><p>{t('台をタップして引っ張り、離すとショット。引いた向きと逆に進み、長く引くほど強くなります。')}</p><label>{t('ショットの強さ')} <progress max="1" value={power}/><span>{Math.round(power*100)}%</span></label><div className="gc-row">{g.pool.ballInHand&&<button disabled={!myTurn||g.pool.moving} aria-pressed={placing} onClick={()=>{cancelPull();setPlacing(!placing);}}>{t('手玉を置く')}</button>}</div></>}

 {g.kind==='arcade'&&<><p>{t('75秒のブロック崩し対戦。指でパドルを動かすか左右キーで操作。3回ミスすると終了。')}</p><div className="gc-break-courts">{g.courts?.map((c,i)=>({c,i})).sort((a,b)=>a.i===seat?-1:b.i===seat?1:a.i-b.i).map(({c,i})=><div key={g.players[i]} className={i===seat?'mine':''}><b>{g.names[i]} · ♥{c.lives}</b><svg tabIndex={0} viewBox="0 0 300 420" aria-label={t('ブロック崩しのコート')} style={{touchAction:'none'}} onPointerDown={e=>{if(i!==seat||world.paused)return;e.currentTarget.setPointerCapture(e.pointerId);send({type:'game_paddle',key:g.key,x:(e.clientX-e.currentTarget.getBoundingClientRect().left)/e.currentTarget.getBoundingClientRect().width});}} onPointerMove={e=>{if(i!==seat||!e.buttons||world.paused||performance.now()-paddleAt.current<70)return;paddleAt.current=performance.now();send({type:'game_paddle',key:g.key,x:(e.clientX-e.currentTarget.getBoundingClientRect().left)/e.currentTarget.getBoundingClientRect().width});}}><rect width="300" height="420" rx="14" fill="#213c4b"/>{c.bricks.map((alive,k)=>alive?<rect key={k} x={(.04+k%8*.115)*300} y={(.12+Math.floor(k/8)*.065)*420} width="29" height="19" rx="3" fill={colors[Math.floor(k/8)]}/>:null)}<rect x={c.x*300-36} y="380" width="72" height="8" rx="4" fill={colors[i]}/>{c.lives>0&&<circle cx={c.ball.x*300} cy={c.ball.y*420} r="6" fill="#fff1ba"/>}</svg></div>)}</div></>}
 <p>{t(g.message)}</p><button onClick={()=>send({type:'game_leave',key:g.key})}>{t('対戦から退出')}</button>
 </>}
 </>}
 </section>;
}
