import BowlingSwipe from './BowlingSwipe';
import SportsView from './SportsView';
import React,{useEffect,useState} from 'react';
import type {HomeGame,HomeGameWorld,GameCommand} from './homeGames';
import {GAME_RULES,ARRANGED_RULES,boardColor,isPartyKind,legalReversi,RACE_EFFECTS,RACE_EXTRA,PIN_POSITIONS,bowlingTotals} from './partyGames';
import './partyGames.css';
const COLORS=['#f7bd68','#70d8db','#caa0f4','#f28d9b'];
const TREASURES=['💎','🌻','🗝','🍄','🐚','⭐','🍎','🦋','🌙','🍀','🪶','🔔'];
export default function PartyGamesPanel({world,g,selfId,t,send}:{world:HomeGameWorld;g:HomeGame;selfId:string;t:(s:string)=>string;send:(c:GameCommand)=>void}){
 const [aim,setAim]=useState(0),[power,setPower]=useState(.75),[spin,setSpin]=useState(0),[clock,setClock]=useState(world.time),s=g.party,seat=g.players.indexOf(selfId),mine=g.phase==='playing'&&seat===g.turn&&!g.party?.cpuTurn&&!world.paused;
 useEffect(()=>{setClock(world.time);if(g.kind!=='reaction'&&g.kind!=='bowling'||world.paused)return;const start=performance.now(),timer=setInterval(()=>setClock(world.time+(performance.now()-start)/1000),50);return()=>clearInterval(timer);},[world.time,g.kind,world.paused]);
 useEffect(()=>{if(g.kind!=='reaction')return;const key=(e:KeyboardEvent)=>{if(world.paused||g.phase!=='playing'||g.party?.signal?.acted[seat]||!['1','2','3','4'].includes(e.key)||['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;e.preventDefault();send({type:'game_react',key:g.key,round:g.round,target:Number(e.key)-1});};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[g.kind,g.phase,g.round,world.paused,seat,send]);
 if(!s||!isPartyKind(g.kind))return null;
 const boardSend=(cell:number)=>send({type:'game_board',key:g.key,cell,round:g.round});
 const team=boardColor(g,g.turn),legal=g.kind==='reversi'?legalReversi(s.board!,team):[],signal=s.signal,live=!!signal&&clock>=signal.at&&clock<=g.deadline,shot=s.shot;
 const bowling=s.lanes?.[g.turn],frame=bowling?.frames.at(-1),shotProgress=shot?Math.max(0,Math.min(1,(clock-shot.start)/1.7)):0;
 return <div className="gc-party">{s.solo&&<p>CPU · {s.cpuScore||0} · {t(s.cpuTurn?'CPUが考えています':'あなたの手番')}</p>}<details className="gc-party-rules"><summary>{t('ルールと操作')}</summary><p>{t(s.solo?'ひとりでCPUと対戦。置ける場所を選び、リバーシは石の数、四目並べは縦・横・斜めの4個で勝負。':g.arranged?ARRANGED_RULES[g.kind]:GAME_RULES[g.kind])}</p></details>
 {(g.kind==='reversi'||g.kind==='connectfour')&&<>{g.phase==='playing'&&<p>{g.arranged?g.names[g.turn]:t(team===1?'チームA':'チームB')} · {g.arranged?t('手番'):t(g.kind==='reversi'?team===1?'黒の手番':'白の手番':team===1?'赤の手番':'黄の手番')}</p>}
 {g.kind==='connectfour'&&<div className="gc-party-columns">{Array.from({length:7},(_,i)=><button key={i} aria-label={t('列を選ぶ')+' '+(i+1)} disabled={!mine||!!s.board![i]} onClick={()=>boardSend(i)}>↓</button>)}</div>}
 <div className={'gc-party-board '+(g.kind==='reversi'?'reversi':'connectfour')} role="group" aria-label={t(g.kind==='reversi'?'リバーシの盤面':'四目並べの盤面')}>
 {s.board!.map((v,i)=><button key={i} className={s.last?.includes(i)?'last':''} aria-label={t('マス')+' '+(i+1)+' · '+(v?(s.solo?(v===1?g.names[0]:'CPU'):g.arranged?g.names[v-1]:t(v===1?'チームA':'チームB')):t('空きマス'))} disabled={!mine||(g.kind==='reversi'?!legal.includes(i):!!s.board![i%7])} onClick={()=>boardSend(g.kind==='reversi'?i:i%7)}>{v?<i className={'piece piece-'+v}/>:g.kind==='reversi'&&legal.includes(i)?<span className="legal">·</span>:null}</button>)}
 </div></>}
 {g.kind==='memory'&&<div className="gc-memory-board" role="group" aria-label={t('宝物のカード')}>
 {s.cards!.map((v,i)=>{const visible=s.matched![i]||s.open!.includes(i);return <button key={i} className={(visible?'open ':'')+(s.matched![i]?'matched':'')} aria-label={visible?TREASURES[v]:t('裏向きのカード')+' '+(i+1)} disabled={!mine||visible||!!s.revealUntil} onClick={()=>boardSend(i)}>{visible?TREASURES[v]:<span>✦<small>{i+1}</small></span>}</button>;})}</div>}
 {g.kind==='race'&&<><div className="gc-race-board" role="group" aria-label={t('すごろくの道')}>{Array.from({length:41},(_,i)=><div key={i} className={(RACE_EFFECTS[i]>0?'boost':RACE_EFFECTS[i]<0?'back':RACE_EXTRA.includes(i)?'extra':'')+' '+(i===40?'goal':'')}><small>{i===40?'🏁':i}</small><b>{RACE_EFFECTS[i]>0?'+'+RACE_EFFECTS[i]:RACE_EFFECTS[i]|| (RACE_EXTRA.includes(i)?'★':'')}</b><div>{s.positions!.map((pos,j)=>pos===i?<span key={j} title={g.names[j]} style={{background:COLORS[j]}}>{j+1}</span>:null)}</div></div>)}</div><div className="gc-party-action"><span className="gc-die">{s.die?(s.die<=6?['⚀','⚁','⚂','⚃','⚄','⚅'][s.die-1]:s.die):'🎲'}</span><button className="gc-primary" disabled={!mine} onClick={()=>send({type:'game_roll',key:g.key,round:g.round})}>{t(g.arranged?'大胆に進む':'サイコロを振る')}</button>{g.arranged&&<button disabled={!mine} onClick={()=>send({type:'game_roll',key:g.key,round:g.round,style:'safe'})}>{t('安全に進む')}</button>}</div></>}
 {g.kind==='bowling'&&bowling&&<><p>{t('フレーム')} {bowling.frames.length}/{g.arranged?5:10} · {t('投球')} {(frame?.length||0)+1}</p><div className="gc-bowling-layout"><BowlingSwipe g={g} mine={mine} paused={world.paused} t={t} send={send} onPreview={(a,p,s)=>{setAim(a);setPower(p);setSpin(s);}}><SportsView kind="bowling" t={t} lane={bowling} shot={shot} progress={shotProgress} aim={aim} spin={spin} color={COLORS[g.turn]} paused={world.paused}><svg className="gc-bowling-lane" viewBox="0 0 300 460" role="img" aria-label={t('ボウリングレーン')}>
 <defs><linearGradient id={'lane-'+g.slot}><stop stopColor="#b7834c"/><stop offset=".5" stopColor="#e6bf7e"/><stop offset="1" stopColor="#b7834c"/></linearGradient></defs><rect width="300" height="460" rx="18" fill="#162f35"/><path d="M45 440L90 30H210L255 440Z" fill={'url(#lane-'+g.slot+')'}/>{Array.from({length:7},(_,i)=><path key={i} d={'M'+(50+i*33)+' 440L'+(92+i*19)+' 30'} stroke="#80593255"/>)}
 {PIN_POSITIONS.map((p,i)=>bowling.pins[i]&&(!shot||shotProgress<.85||!shot.pins.includes(i))?<g key={i} transform={'translate('+(150+p.x*90)+','+(75-p.y*55)+')'}><ellipse cy="8" rx="7" ry="3" fill="#0004"/><path d="M-5 7Q-8 0-3 -7L-3 -13Q-6 -21 0 -21Q6 -21 3 -13L3 -7Q8 0 5 7Z" fill="#fff5d9" stroke="#fff"/><path d="M-3 -10H3M-3 -7H3" stroke="#ce5f63" strokeWidth="2"/></g>:null)}
 {!shot&&<path d={'M'+(150+aim*90)+' 410Q'+(150+aim*55)+' 235 '+(150+(aim*.72+spin*.24)*90)+' 78'} fill="none" stroke="#fff0c3" strokeDasharray="7 7" strokeWidth="2"/>}
 <circle cx={shot?150+shot.aim*90*(1-shotProgress)+(shot.aim*.72+shot.spin*.24*shotProgress)*90*shotProgress:150+aim*90} cy={shot?410-shotProgress*335:410} r={shot?12-shotProgress*5:12} fill={COLORS[g.turn]} stroke="#314b56" strokeWidth="3"/>
 </svg></SportsView></BowlingSwipe></div>
 <div className="gc-bowling-scores">{s.lanes!.map((lane,i)=>{const totals=bowlingTotals(lane.rolls,g.arranged?5:10);return <div key={g.players[i]}><b>{g.names[i]} · {totals.total}</b><div className="gc-bowling-frames">{Array.from({length:g.arranged?5:10},(_,f)=>{const r=lane.frames[f]||[];return <div key={f}><small>{f+1}</small><span>{r.map((n,j)=>n===10?'X':j>0&&r[j-1]+n===10?'/':n===0?'–':n).join(' ')||'·'}</span><strong>{totals.frames[f]?.complete?totals.frames[f].total:'·'}</strong></div>;})}</div></div>;})}</div></>}
 {g.kind==='reaction'&&signal&&<><div className="gc-reaction-status" aria-live="polite"><b>{t('ラウンド')} {g.round}/{g.arranged?16:12}</b><strong>{t(signal.acted[seat]?'結果を待っています':live?'光ったボタンを押す！':'合図を待とう')}</strong></div><div className="gc-reaction-buttons">{COLORS.map((color,i)=><button key={i} style={{'--lamp':color} as React.CSSProperties} className={live&&signal.target===i?'lit':''} aria-label={t('ライト')+' '+(i+1)} disabled={g.phase!=='playing'||world.paused||signal.acted[seat]} onClick={()=>send({type:'game_react',key:g.key,target:i,round:g.round})}>{i+1}</button>)}</div><div className="gc-reaction-times">{g.names.map((name,i)=><span key={g.players[i]}>{name} · {signal.times[i]>=0?signal.times[i]+' ms':signal.times[i]===-2?t('お手つき！'):'…'}</span>)}</div></>}
 </div>;
}
