export const PARTY_ENGLISH:Record<string,string> = {
 "ルールと操作":"Rules & controls",
  "料理用ストーブ": "Cooking stove",
  "流し台": "Sink cabinet",
  "木の冷蔵庫": "Wooden refrigerator",
  "ダイニングカウンター": "Dining counter",
  "ロッキングチェア": "Rocking chair",
  "書きもの机": "Writing desk",
  "姿見": "Standing mirror",
  "くつの棚": "Shoe cabinet",
  "コート掛け": "Coat rack",
  "吊りランタン": "Hanging lantern",
  "編み込みラグ": "Woven rug",
  "ひつじのぬいぐるみ": "Sheep plush",
  "ドラゴンのぬいぐるみ": "Dragon plush",
  "ふくろうのぬいぐるみ": "Owl plush",
  "パンダのぬいぐるみ": "Panda plush",
  "おおかみのぬいぐるみ": "Wolf plush",
  "かえるのぬいぐるみ": "Frog plush",
  "きのこのぬいぐるみ": "Mushroom plush",
  "宝箱": "Treasure chest",
  "天体望遠鏡": "Telescope",
  "地球儀": "Globe",
  "盆栽": "Bonsai",
  "小さな噴水": "Small fountain",
  "スノードーム": "Snow globe",
  "リバーシ台": "Reversi table",
  "四目並べ台": "Four-in-a-row board",
  "神経衰弱テーブル": "Memory game table",
  "すごろくテーブル": "Dice race table",
  "ボウリングレーン": "Bowling lane",
  "反応ゲーム機": "Reaction game cabinet",
  "アップライトピアノ": "Upright piano",
  "ハープ": "Harp",
  "チームリバーシ": "Team Reversi",
  "チーム四目並べ": "Team Four in a Row",
  "宝物の神経衰弱": "Treasure Memory",
  "星のすごろく": "Star Dice Race",
  "テンピンボウリング": "Tenpin Bowling",
  "ライトリアクション": "Light Reaction",
  "このゲームは2人または4人で開始できます。": "This game needs two or four players.",
  "2人または4人。黒と白の2チームで交互に置き、挟んだ石を裏返します。置ける場所は光ります。置けない手番は自動パス。最後に石が多いチームの勝ち。": "Two or four players on black and white teams. Take turns placing a disc and flipping enclosed opposing discs. Legal moves glow. Turns without legal moves pass automatically. The team with more discs wins.",
  "2人または4人。2チームで交互に列を選び、下から駒を積みます。縦・横・斜めに4個つながったチームの勝ち。": "Two or four players on two teams. Take turns selecting a column to drop a disc. Connect four vertically, horizontally or diagonally to win.",
  "1〜4人。24枚から同じ宝物を2枚見つけましょう。ペアなら2点でもう一度、不一致なら次の人へ。12ペアで終了。": "One to four players. Find matching treasures among 24 cards. A pair scores two points and gives another turn; a mismatch passes the turn. The game ends after all 12 pairs are found.",
  "1〜4人。サイコロで40マスの星の道を進みます。青は加速、赤は後退、金はもう一度。最初にゴールした人の勝ち。": "One to four players. Roll the die along a 40-space star path. Blue spaces boost, red spaces move you back, and gold spaces give an extra turn. First to finish wins.",
  "1〜4人。狙い・強さ・カーブを調整して10フレーム対戦。ストライクは次の2投、スペアは次の1投が加点。10フレーム目はボーナス投球あり。": "One to four players over ten frames. Adjust aim, power and curve. Strikes add the next two rolls; spares add the next roll. The tenth frame includes bonus rolls.",
  "1〜4人。合図が出たら光ったボタンを押します。12ラウンドの合計点で勝負。早押しほど高得点、合図前や違うボタンは減点。": "One to four players over 12 rounds. Press the lit button after the signal. Faster reactions score more; pressing too early or the wrong button loses points.",
  "最大4人で対戦できます。リバーシと四目並べは2人か4人、その他は1人でも練習できます。": "Play with up to four players. Reversi and Four in a Row need two or four; other games also support solo practice.",
  "置ける場所がなく自動パス。": "No legal move. Turn passed automatically.",
  "引き分け！": "Draw!",
  "お手つき！": "False start or wrong button!",
  "ナイス反応！": "Great reaction!",
  "石を置きました。": "Disc placed.",
  "駒を置きました。": "Disc dropped.",
  "四目達成！": "Four in a row!",
  "ペア発見！もう一度。": "Pair found! Take another turn.",
  "覚えて、次の人へ。": "Remember these cards. Next player's turn.",
  "ゴール！": "Finished!",
  "ラッキーマス！もう一度。": "Lucky space! Roll again.",
  "加速マス！": "Boost space!",
  "後退マス！": "Move back!",
  "サイコロを振りました。": "Die rolled.",
  "ストライク！": "Strike!",
  "スペア！": "Spare!",
  "投球完了！": "Roll complete!",
  "黒の手番": "Black's turn",
  "白の手番": "White's turn",
  "赤の手番": "Red's turn",
  "黄の手番": "Yellow's turn",
  "列を選ぶ": "Choose column",
  "リバーシの盤面": "Reversi board",
  "四目並べの盤面": "Four in a Row board",
  "マス": "Space",
  "空きマス": "Empty space",
  "宝物のカード": "Treasure cards",
  "裏向きのカード": "Face-down card",
  "すごろくの道": "Dice race path",
  "サイコロを振る": "Roll die",
  "フレーム": "Frame",
  "投球": "Roll",
  "狙い": "Aim",
  "強さ": "Power",
  "カーブ": "Curve",
  "ボールが転がっています": "Ball rolling",
  "投球する": "Bowl",
  "ラウンド": "Round",
  "結果を待っています": "Waiting for results",
  "光ったボタンを押す！": "Press the lit button!",
  "合図を待とう": "Wait for the signal",
  "ライト": "Light",
  "対戦中": "Playing"
};
export const PARTY_HIRAGANA:Record<string,string> = {
 "ルールと操作":"るーるとそうさ",
  "料理用ストーブ": "りょうりようすとーぶ",
  "流し台": "ながしだい",
  "木の冷蔵庫": "きのれいぞうこ",
  "ダイニングカウンター": "だいにんぐかうんたー",
  "ロッキングチェア": "ろっきんぐちぇあ",
  "書きもの机": "かきものづくえ",
  "姿見": "すがたみ",
  "くつの棚": "くつのたな",
  "コート掛け": "こーとかけ",
  "吊りランタン": "つりらんたん",
  "編み込みラグ": "あみこみらぐ",
  "ひつじのぬいぐるみ": "ひつじのぬいぐるみ",
  "ドラゴンのぬいぐるみ": "どらごんのぬいぐるみ",
  "ふくろうのぬいぐるみ": "ふくろうのぬいぐるみ",
  "パンダのぬいぐるみ": "ぱんだのぬいぐるみ",
  "おおかみのぬいぐるみ": "おおかみのぬいぐるみ",
  "かえるのぬいぐるみ": "かえるのぬいぐるみ",
  "きのこのぬいぐるみ": "きのこのぬいぐるみ",
  "宝箱": "たからばこ",
  "天体望遠鏡": "てんたいぼうえんきょう",
  "地球儀": "ちきゅうぎ",
  "盆栽": "ぼんさい",
  "小さな噴水": "ちいさなふんすい",
  "スノードーム": "すのーどーむ",
  "リバーシ台": "りばーしだい",
  "四目並べ台": "よんもくならべだい",
  "神経衰弱テーブル": "しんけいすいじゃくてーぶる",
  "すごろくテーブル": "すごろくてーぶる",
  "ボウリングレーン": "ぼうりんぐれーん",
  "反応ゲーム機": "はんのうげーむき",
  "アップライトピアノ": "あっぷらいとぴあの",
  "ハープ": "はーぷ",
  "チームリバーシ": "ちーむりばーし",
  "チーム四目並べ": "ちーむよんもくならべ",
  "宝物の神経衰弱": "たからもののしんけいすいじゃく",
  "星のすごろく": "ほしのすごろく",
  "テンピンボウリング": "てんぴんぼうりんぐ",
  "ライトリアクション": "らいとりあくしょん",
  "このゲームは2人または4人で開始できます。": "このげーむは2にんまたは4にんでかいしできます。",
  "2人または4人。黒と白の2チームで交互に置き、挟んだ石を裏返します。置ける場所は光ります。置けない手番は自動パス。最後に石が多いチームの勝ち。": "2にんまたは4にん。くろとしろの2ちーむでこうごにおき、はさんだいしをうらがえします。おけるばしょはひかります。おけないてばんはじどうぱす。さいごにいしがおおいちーむのかち。",
  "2人または4人。2チームで交互に列を選び、下から駒を積みます。縦・横・斜めに4個つながったチームの勝ち。": "2にんまたは4にん。2ちーむでこうごにれつをえらび、したからこまをつみます。たて・よこ・ななめに4こつながったちーむのかち。",
  "1〜4人。24枚から同じ宝物を2枚見つけましょう。ペアなら2点でもう一度、不一致なら次の人へ。12ペアで終了。": "1〜4にん。24まいからおなじたからものを2まいみつけましょう。ぺあなら2てんでもういちど、ふいっちならつぎのひとへ。12ぺあでしゅうりょう。",
  "1〜4人。サイコロで40マスの星の道を進みます。青は加速、赤は後退、金はもう一度。最初にゴールした人の勝ち。": "1〜4にん。さいころで40ますのほしのみちをすすみます。あおはかそく、あかはこうたい、きんはもういちど。さいしょにごーるしたひとのかち。",
  "1〜4人。狙い・強さ・カーブを調整して10フレーム対戦。ストライクは次の2投、スペアは次の1投が加点。10フレーム目はボーナス投球あり。": "1〜4にん。ねらい・つよさ・かーぶをちょうせいして10ふれーむたいせん。すとらいくはつぎの2とう、すぺあはつぎの1とうがかてん。10ふれーむめはぼーなすとうきゅうあり。",
  "1〜4人。合図が出たら光ったボタンを押します。12ラウンドの合計点で勝負。早押しほど高得点、合図前や違うボタンは減点。": "1〜4にん。あいずがでたらひかったぼたんをおします。12らうんどのごうけいてんでしょうぶ。はやおしほどこうとくてん、あいずまえやちがうぼたんはげんてん。",
  "最大4人で対戦できます。リバーシと四目並べは2人か4人、その他は1人でも練習できます。": "さいだい4にんでたいせんできます。りばーしとよんもくならべは2にんか4にん、そのたは1にんでもれんしゅうできます。",
  "置ける場所がなく自動パス。": "おけるばしょがなくじどうぱす。",
  "引き分け！": "ひきわけ！",
  "お手つき！": "おてつき！",
  "ナイス反応！": "ないすはんのう！",
  "石を置きました。": "いしをおきました。",
  "駒を置きました。": "こまをおきました。",
  "四目達成！": "よんもくたっせい！",
  "ペア発見！もう一度。": "ぺあはっけん！もういちど。",
  "覚えて、次の人へ。": "おぼえて、つぎのひとへ。",
  "ゴール！": "ごーる！",
  "ラッキーマス！もう一度。": "らっきーます！もういちど。",
  "加速マス！": "かそくます！",
  "後退マス！": "こうたいます！",
  "サイコロを振りました。": "さいころをふりました。",
  "ストライク！": "すとらいく！",
  "スペア！": "すぺあ！",
  "投球完了！": "とうきゅうかんりょう！",
  "黒の手番": "くろのてばん",
  "白の手番": "しろのてばん",
  "赤の手番": "あかのてばん",
  "黄の手番": "きのてばん",
  "列を選ぶ": "れつをえらぶ",
  "リバーシの盤面": "りばーしのばんめん",
  "四目並べの盤面": "よんもくならべのばんめん",
  "マス": "ます",
  "空きマス": "あきます",
  "宝物のカード": "たからもののかーど",
  "裏向きのカード": "うらむきのかーど",
  "すごろくの道": "すごろくのみち",
  "サイコロを振る": "さいころをふる",
  "フレーム": "ふれーむ",
  "投球": "とうきゅう",
  "狙い": "ねらい",
  "強さ": "つよさ",
  "カーブ": "かーぶ",
  "ボールが転がっています": "ぼーるがころがっています",
  "投球する": "とうきゅうする",
  "ラウンド": "らうんど",
  "結果を待っています": "けっかをまっています",
  "光ったボタンを押す！": "ひかったぼたんをおす！",
  "合図を待とう": "あいずをまとう",
  "ライト": "らいと",
  "対戦中": "たいせんちゅう"
};
