export const LAUNCH_ENGLISH:Record<string,string>={
 "この冒険は終了しました。新しい冒険を始めましょう。":"This adventure has ended. Start a new adventure.",
 "木漏れ日のフロンティア":"Sunlit Frontier",
 "異世界転生したら学力で無双した件":"Reborn in Another World: Unstoppable with Knowledge",
 "学習ローグRPG":"Learning Rogue RPG",
 "スーパー学ロカート":"Super Gakuro Kart",
  "学び、冒険し、自分だけの暮らしをつくろう。": "Learn, explore, and build a life of your own.",
  "ひとりで遊ぶ": "Play solo",
  "オンラインで遊ぶ": "Play online",
  "ひとりでレース": "Solo race",
  "学んで加速。40台のグランプリへ。": "Learn and accelerate into a 40-racer grand prix.",
  "保存データを確認中…": "Checking saved adventure…",
  "この端末に保存した冒険はまだありません。": "No adventure is saved on this device yet.",
  "ひとり用ワールドは自動保存。制限時間なしで遊べます。": "Solo worlds save automatically. You can play without a time limit.",
  "ひとり用の冒険": "Solo adventure",
  "主人公ビルダー": "Hero builder",
  "冒険の遊び方": "Adventure mode",
  "制限時間なし": "No time limit",
  "ワールドと主人公をこの端末へ自動保存します。": "The world and your hero save automatically on this device.",
  "最大40人・チームは最大4人。ホストの画面を開いたままにしてください。": "Up to 40 players and four per team. Keep the host screen open.",
  "招待されたワールドで、仲間と冒険しよう。": "Join your friends in the world you were invited to.",
  "ワールドの保存": "World save",
  "ワールドを保存する": "Save world",
  "保存してRPGタイトルへ": "Save and return to RPG title",
  "探索中は30秒ごとに自動保存します。": "Saves automatically every 30 seconds while exploring.",
  "戦闘・採取・ミニゲームが終わってから保存してください。": "Save after finishing the battle, gathering action, or minigame.",
  "ワールドを保存しました。": "World saved.",
  "保存したワールドを再開しました。": "Saved world resumed.",
  "保存データを読み込めませんでした。": "Could not load the saved adventure.",
  "ひとり用 · 通信なし": "Solo · Offline",
  "コースを選ぶ": "Choose course",
  "問題を選んでレースへ": "Choose questions and race",
  "招待コードを入力すると参加できます。": "Enter an invitation code to join.",
  "操作ガイド": "Controls guide",
  "左右でハンドル。ドリフトをためてターボ。アイテムで逆転を狙おう。": "Steer left and right. Charge a drift for turbo, and use items to turn the race around."
};
export const LAUNCH_HIRAGANA:Record<string,string>={
 "この冒険は終了しました。新しい冒険を始めましょう。":"このぼうけんはしゅうりょうしました。あたらしいぼうけんをはじめましょう。",
 "木漏れ日のフロンティア":"こもれびのふろんてぃあ",
 "異世界転生したら学力で無双した件":"いせかいてんせいしたら がくりょくでむそうしたけん",
 "学習ローグRPG":"がくしゅうローグRPG",
 "スーパー学ロカート":"すーぱーがくろかーと",
  "学び、冒険し、自分だけの暮らしをつくろう。": "まなび、ぼうけんし、じぶんだけのくらしをつくろう。",
  "ひとりで遊ぶ": "ひとりであそぶ",
  "オンラインで遊ぶ": "おんらいんであそぶ",
  "ひとりでレース": "ひとりでれーす",
  "学んで加速。40台のグランプリへ。": "まなんでかそく。40だいのぐらんぷりへ。",
  "保存データを確認中…": "ほぞんでーたをかくにんちゅう…",
  "この端末に保存した冒険はまだありません。": "このたんまつにほぞんしたぼうけんはまだありません。",
  "ひとり用ワールドは自動保存。制限時間なしで遊べます。": "ひとりようわーるどはじどうほぞん。せいげんじかんなしであそべます。",
  "ひとり用の冒険": "ひとりようのぼうけん",
  "主人公ビルダー": "しゅじんこうびるだー",
  "冒険の遊び方": "ぼうけんのあそびかた",
  "制限時間なし": "せいげんじかんなし",
  "ワールドと主人公をこの端末へ自動保存します。": "わーるどとしゅじんこうをこのたんまつへじどうほぞんします。",
  "最大40人・チームは最大4人。ホストの画面を開いたままにしてください。": "さいだい40にん・ちーむはさいだい4にん。ほすとのがめんをひらいたままにしてください。",
  "招待されたワールドで、仲間と冒険しよう。": "しょうたいされたわーるどで、なかまとぼうけんしよう。",
  "ワールドの保存": "わーるどのほぞん",
  "ワールドを保存する": "わーるどをほぞんする",
  "保存してRPGタイトルへ": "ほぞんしてRPGたいとるへ",
  "探索中は30秒ごとに自動保存します。": "たんさくちゅうは30びょうごとにじどうほぞんします。",
  "戦闘・採取・ミニゲームが終わってから保存してください。": "せんとう・さいしゅ・みにげーむがおわってからほぞんしてください。",
  "ワールドを保存しました。": "わーるどをほぞんしました。",
  "保存したワールドを再開しました。": "ほぞんしたわーるどをさいかいしました。",
  "保存データを読み込めませんでした。": "ほぞんでーたをよみこめませんでした。",
  "ひとり用 · 通信なし": "ひとりよう · つうしんなし",
  "コースを選ぶ": "こーすをえらぶ",
  "問題を選んでレースへ": "もんだいをえらんでれーすへ",
  "招待コードを入力すると参加できます。": "しょうたいこーどをにゅうりょくするとさんかできます。",
  "操作ガイド": "そうさがいど",
  "左右でハンドル。ドリフトをためてターボ。アイテムで逆転を狙おう。": "さゆうではんどる。どりふとをためてたーぼ。あいてむでぎゃくてんをねらおう。"
};
