import React,{useEffect} from 'react';
import {useServerAvailability} from './useServerAvailability';
import type {OnlineGameEndpoint} from '../../services/serverAvailability';
import type {LanguageMode} from '../../types';
import type {OnlineTransport} from '../../services/onlineTransport';
export default function TransportPicker({value,onChange,disabled=false,languageMode='JAPANESE',game}:{game:OnlineGameEndpoint;value:OnlineTransport;onChange:(v:OnlineTransport)=>void;disabled?:boolean;languageMode?:LanguageMode}){
 const {state,recheck}=useServerAvailability(game);
 useEffect(()=>{if(state!=='available'&&value==='server'&&!disabled)onChange('host');},[state,value,disabled,onChange]);
 const en=languageMode==='ENGLISH',hi=languageMode==='HIRAGANA';return <fieldset className="online-transport"><legend>{en?'Connection type':hi?'つうしんほうしき':'通信方式'}</legend><div>{(['host','server'] as const).map(v=><button type="button" key={v} disabled={disabled||(v==='server'&&state!=='available')} aria-pressed={value===v} onClick={()=>onChange(v)}>{v==='host'?(en?'Host connection':hi?'ほすとつうしん':'ホスト通信'):(en?'Server connection · beta':hi?'さーばーつうしん・べーた':'サーバー通信 · beta')}</button>)}</div><small>{value==='host'?(en?'For small groups. Keep the host screen open.':hi?'しょうにんずうむけ。ほすとはがめんをひらいたままにします。':'少人数向け。ホストは画面を開いたままにしてください。'):(en?'Experimental. Not recommended for large groups. First startup may take up to 3 minutes.':hi?'しけんうんよう。おおにんずうにはすいしょうしません。しょかいきどうはさいだい3ぷんまちます。':'試験運用中。大人数には推奨しません。初回起動は最大3分待機します。')}</small><small role="status">{state==='checking'?(en?'Checking server connection…':hi?'さーばーせつぞくをかくにんちゅう…':'サーバー接続を確認中…'):state==='unavailable'?(en?'Server connection unavailable. Startup can take up to 3 minutes; retrying automatically.':hi?'さーばーにつながりません。きどうにさいだい3ぷんかかります。じどうでさいかくにんします。':'サーバーに接続できません。起動に最大3分かかる場合があります。自動で再確認します。'):(en?'Server connection available.':hi?'さーばーにつながります。':'サーバー接続可能です。')}</small>{state!=='available'&&<button type="button" className="online-server-recheck" disabled={disabled} onClick={recheck}>{en?'Check again':hi?'さいかくにん':'再確認'}</button>}</fieldset>;
}
