import EquipmentBar from './EquipmentBar';
import {useVrBgm,createRunAudio,cue} from './audio';
import React, {useEffect,useRef,useState} from 'react';
import {createScene,type ViewMode} from './scene';
import {VrRoom} from './network';
import type {OnlineWorld} from './onlineEngine';
import {quizLesson,safeRadius,readyToExtract} from './onlineRules';
import {MISSIONS,WEAPONS,type Input} from './engine';
import Quiz from './Quiz';
export default function OnlineGame({room,world,onBack,en,onConfigure,editing=false}:{room:VrRoom;world:OnlineWorld;onBack:()=>void;en:boolean;onConfigure?:()=>void;editing?:boolean}) {
  const editingRef=useRef(editing);editingRef.current=editing;
  useVrBgm(world.phase==='result'?'clear':world.mode==='royale'?'royale':'training',world.missionId,30);
  const host=useRef<HTMLDivElement>(null),latest=useRef(world);latest.current=world;
  const [mode,setMode]=useState<ViewMode>('overhead'),view=useRef({mode:'overhead' as ViewMode,yaw:Math.PI});
  const input=useRef<Input&{reload?:boolean}>({x:0,z:0,crouch:false,interact:false,decoy:false});
  const keys=useRef(new Set<string>()),drag=useRef<number|null>(null),[quizDone,setQuizDone]=useState('');
  const p=world.players[room.selfId],others=Object.values(world.players).filter(p=>p.id!==room.selfId);
  useEffect(()=>{
    if(!host.current)return;const ids=Object.keys(world.players),index=ids.indexOf(room.selfId),columns=Math.ceil(Math.sqrt(ids.length)),rows=Math.ceil(ids.length/columns),base=MISSIONS[world.missionId-1];
    const renderMission=world.mode==='coop'?{...world.mission,defend:base.defend?{...base.defend,x:base.defend.x+(index%columns-(columns-1)/2)*(2*(base.size??8)+1),z:base.defend.z+(Math.floor(index/columns)-(rows-1)/2)*(2*(base.size??8)+1)}:undefined,exit:{x:base.exit.x+(index%columns-(columns-1)/2)*(2*(base.size??8)+1),z:base.exit.z+(Math.floor(index/columns)-(rows-1)/2)*(2*(base.size??8)+1)}}:world.mission;
    const scene=createScene(host.current,renderMission,world.players[room.selfId]?.avatar);let frame=0,last=performance.now(),sent=0;
    const down=(e:KeyboardEvent)=>{if(editingRef.current||(e.target instanceof HTMLElement&&e.target.closest('select,input,textarea')))return;if(['KeyW','KeyA','KeyS','KeyD','KeyC','KeyE','KeyF','KeyR','KeyT','KeyQ','KeyJ','KeyL','KeyX','KeyB','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();e.stopPropagation();keys.current.add(e.code);if(!e.repeat){if(e.code==='KeyC')input.current.crouch=!input.current.crouch;if(e.code==='KeyB')room.supply();if(e.code==='KeyX')input.current.useItem=true;if(e.code==='KeyR')input.current.shoot=true;if(e.code==='KeyT')input.current.reload=true;if(e.code==='KeyQ')input.current.decoy=true;}}};
    const up=(e:KeyboardEvent)=>keys.current.delete(e.code),blur=()=>{keys.current.clear();input.current={x:0,z:0,crouch:true,interact:false,decoy:false};room.input(input.current);};
    window.addEventListener('keydown',down,true);window.addEventListener('keyup',up,true);window.addEventListener('blur',blur);
    const sounds=createRunAudio();let priorHits=0,priorReload=0;const loop=(now:number)=>{const w=latest.current,own=w.players[room.selfId];if(!own)return;const dt=Math.min(.05,(now-last)/1000);last=now;
      const k=keys.current;let x=Number(k.has('KeyD')||k.has('ArrowRight'))-Number(k.has('KeyA')||k.has('ArrowLeft'))||input.current.x,z=Number(k.has('KeyS')||k.has('ArrowDown'))-Number(k.has('KeyW')||k.has('ArrowUp'))||input.current.z;
      if(view.current.mode!=='overhead'){view.current.yaw-=(Number(k.has('KeyL'))-Number(k.has('KeyJ')))*dt*1.9;const a=view.current.yaw,r=x,f=-z;x=-Math.cos(a)*r+Math.sin(a)*f;z=Math.sin(a)*r+Math.cos(a)*f;}
      if(now-sent>50){const disabled=editingRef.current||own.quiz||w.paused;room.input({...input.current,x:disabled?0:x,z:disabled?0:z,facing:view.current.mode==='overhead'?undefined:view.current.yaw,hold:!disabled&&(input.current.hold||k.has('KeyF')),interact:!disabled&&(input.current.interact||k.has('KeyE')),shoot:!disabled&&input.current.shoot,useItem:!disabled&&input.current.useItem,decoy:!disabled&&input.current.decoy,reload:!disabled&&input.current.reload});input.current.shoot=false;input.current.useItem=false;input.current.reload=false;input.current.decoy=false;sent=now;}
      sounds(own.run);if(own.hits>priorHits)cue('fail');if(own.reloading>priorReload+.5)cue('reload');priorHits=own.hits;priorReload=own.reloading;const displayRun=w.mode==='coop'?{...own.run,collected:Object.values(w.players).flatMap(p=>p.run.collected)}:own.run;
      scene.draw(displayRun,{...view.current,safeZone:w.mode==='royale'?safeRadius(w):undefined,supplies:w.mode==='royale'?w.supplies.filter(s=>s.readyAt<=w.time):[],exitReady:w.mode==='coop'&&readyToExtract(w,own),others:Object.values(w.players).filter(q=>q.id!==room.selfId).map(q=>({id:q.id,name:q.name,player:q.run.player,out:q.run.status==='caught',avatar:q.avatar,stealth:q.run.stealth}))});frame=requestAnimationFrame(loop);
    };frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);scene.dispose();window.removeEventListener('keydown',down,true);window.removeEventListener('keyup',up,true);window.removeEventListener('blur',blur);};
  },[world.seed,JSON.stringify(p?.avatar)]);
  const t=(ja:string,eng:string)=>en?eng:ja;
  const quizKey=`${world.round}:${p?.quizRound}`;
  if(!p)return null;
  return <div className="gear-shell"><header className="gear-header"><button onClick={onBack}>{t('退室','Leave')}</button><strong>GAKURO VR</strong>{onConfigure&&<button onClick={()=>{keys.current.clear();input.current={x:0,z:0,crouch:false,interact:false,decoy:false};room.input(input.current);onConfigure();}}>{t('キャラクタークリエイト','Character creator')}</button>}<span>{world.mode==='coop'?t('協力','CO-OP'):t('バトルロイヤル','BATTLE ROYALE')} · {Math.ceil(Math.max(0,world.limit-world.time))}s</span></header><div className="gear-equipment">{world.mode==='royale'?<><span>{t('被弾','HITS')} {p.out?p.respawnHits:p.hits}/3</span><span>ENERGY {p.energy}/100</span><span>{p.invulnerable>0&&`${t('保護','PROTECTED')} ${Math.ceil(p.invulnerable)}s`}</span><span>{p.run.stealth>0&&`${t('透明','STEALTH')} ${Math.ceil(p.run.stealth)}s`}</span><span>{t('エリア','ZONE')} {safeRadius(world).toFixed(1)}m {p.zoneExposure>0&&`⚠ ${Math.ceil(6-p.zoneExposure)}s`}</span><span>{t('弾薬','AMMO')} {p.run.ammo} {p.reloading>0?t('装填中','RELOADING'):''}</span></>:<span>{t('資料','FILES')} {p.run.collected.filter(Boolean).length}/{p.run.collected.length} · {t('警戒','ALERT')} {Math.round(p.run.detection)}%</span>}</div><nav className="gear-viewbar">{(['overhead','first','third'] as ViewMode[]).map((m,i)=><button key={m} aria-pressed={mode===m} onClick={()=>{view.current={mode:m,yaw:p.run.player.angle};setMode(m);}}>{t(['俯瞰','一人称','三人称'][i],['Overhead','First','Third'][i])}</button>)}<small>{t('WASD 移動 / J・Lまたは画面ドラッグで旋回','WASD move / J·L or drag to turn')}</small></nav><div className="gear-field">{<EquipmentBar run={p.run} stageId={world.missionId} en={en} onInput={v=>{if(!p.quiz&&world.phase==='playing'&&!world.paused)Object.assign(input.current,v);}}/>}<div ref={host} className="gear-canvas" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current=e.clientX;}} onPointerMove={e=>{if(drag.current!==null){view.current.yaw-=(e.clientX-drag.current)*.007;drag.current=e.clientX;}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>
    <details className="gear-online-roster"><summary>{t('参加者','Players')} {Object.keys(world.players).length}</summary><div>{Object.values(world.players).map(q=><div key={q.id}>{q.name}: {q.out?t('復活・勝敗確定','RESPAWNED / ELIMINATED'):q.quiz?t('問題中','QUIZ'):world.mode==='coop'?q.run.status==='clear'?t('クリア・支援中','CLEAR / HELPING'):`${q.run.collected.filter(Boolean).length}/${q.run.collected.length}`:`${q.hits}/3`} {q.stats?.assists?` · ${t('支援','HELP')} ${q.stats.assists}`:''} {!q.connected&&t('（切断）','(disconnected)')}</div>)}</div></details>
    <svg className="gear-radar" viewBox={`${-(world.mission.size??8)} ${-(world.mission.size??8)} ${(world.mission.size??8)*2} ${(world.mission.size??8)*2}`} aria-label={t('レーダー','Radar')}><rect x={-(world.mission.size??8)} y={-(world.mission.size??8)} width={(world.mission.size??8)*2} height={(world.mission.size??8)*2} fill="#071e20"/>{world.mission.obstacles.map((b,i)=><rect key={i} x={b.x-b.w/2} y={b.z-b.d/2} width={b.w} height={b.d} fill="#667b6f"/>)}{world.mode==='royale'&&<circle cx={0} cy={0} r={safeRadius(world)} fill="none" stroke="#72f7bd" strokeWidth={.25}/>} {world.supplies.filter(s=>s.readyAt<=world.time).map(s=><circle key={`supply-${s.id}`} cx={s.x} cy={s.z} r={.45} fill={s.kind==='ammo'?'#ffd36e':s.kind==='energy'?'#70dfff':'#ff92bb'}/>)}{world.mission.targets.map((q,i)=>!Object.values(world.players).flatMap(p=>p.run.collected)[i]&&<circle key={`target-${i}`} cx={q.x} cy={q.z} r={.4} fill="#70eaff"/>)}{Object.values(world.players).map(q=><circle key={q.id} cx={q.run.player.x} cy={q.run.player.z} r={.55} fill={q.id===room.selfId?'white':q.out?'#566165':'#ed9fff'}/>)} </svg>
    {world.mode==='coop'&&<div className="gear-objective">{p.run.status==='clear'?t('担当クリア：他のプレイヤーの資料回収・見回りの睡眠を支援できます','Cleared: help collect others’ files or put patrols to sleep'):t('自分の目標を達成して出口へ。クリア後に隣室への扉が開き、仲間を支援できます','Complete your objectives and reach the exit. Your room doors unlock after clearing, so you can help allies')} · {world.mission.defend&&`⚑ ${p.run.defended.toFixed(1)}/${world.mission.defend.seconds}s`} {p.helpProgress>0&&<progress max={1.5} value={p.helpProgress}/>} · F {p.run.holds}/{world.mission.requiredHolds} · R {p.run.shots}/{world.mission.requiredShots}</div>}
    {world.mode==='royale'&&!p.out&&<div className="gear-objective">{p.zoneExposure>0?t('エリア外！緑の円へ戻ろう。6秒ごとに被弾','Outside zone! Return to the green circle. Damage every 6 seconds'):t('緑の円が縮小。黄＝弾薬・青＝エネルギー・桃＝被弾回復','The green zone shrinks. Yellow: ammo / blue: energy / pink: repair')}</div>}{p.out&&<div className="gear-objective">{t('復活：勝敗は確定。脱落した仲間同士でプレイを続けられます','Respawned: result locked. Keep playing with other eliminated players')}</div>}
    {world.paused&&<div className="gear-overlay"><section>{t('ホストが戻るまで一時停止','Paused until host returns')}</section></div>}
    {p.quiz&&quizDone!==quizKey&&<Quiz key={`${world.round}:${p.run.status}:${p.energy}`} lesson={quizLesson(world,p)} en={en} onAnswer={c=>room.answer(c)} onComplete={()=>{room.completeQuiz();setQuizDone(quizKey);}}/>}
    {world.mode==='coop'&&!p.quiz&&['caught','timeout'].includes(p.run.status)&&world.phase==='playing'&&<div className="gear-overlay"><section><h2>{t('再挑戦','RETRY')}</h2><p>{t('回収・課題の進捗を保って再開できます。近くの仲間がEを長押しすると、その場で救助もできます。','Retry keeps your objectives. A nearby ally can hold E to revive you in place.')}</p><button onClick={()=>room.retry()}>{t('進捗を保って再挑戦','Retry with progress kept')}</button></section></div>}
    {world.phase==='result'&&!p.quiz&&<div className="gear-overlay"><section><h2>{t('終了','RESULT')}</h2><p>{world.winner.map(id=>world.players[id]?.name).join(' / ')||t('クリアなし','No clears')}</p><div className="gear-report"><table><thead><tr><th>{t('参加者','Player')}</th><th>{world.mode==='coop'?t('回収','Tasks'):t('命中 / 被弾','Hits / taken')}</th><th>{t('支援 / 救助','Help / revive')}</th><th>{t('正解','Correct')}</th><th>{t('勝利','Wins')}</th></tr></thead><tbody>{Object.values(world.players).map(q=><tr key={q.id}><td>{q.name}</td><td>{world.mode==='coop'?`${q.run.collected.filter(Boolean).length}/${q.run.collected.length}`:`${q.stats.hits} / ${q.hits}`}</td><td>{q.stats.assists} / {q.stats.rescues}</td><td>{q.stats.correct}</td><td>{q.wins}</td></tr>)}</tbody></table></div>{room.host?<><button className="gear-primary" disabled={Object.values(world.players).some(q=>q.connected&&q.quiz)} onClick={()=>room.rematch()}>{t('同じ部屋で再戦','Rematch in this room')}</button>{world.mode==='coop'&&world.missionId<MISSIONS.length&&<button disabled={Object.values(world.players).some(q=>q.connected&&q.quiz)} onClick={()=>room.rematch(true)}>{t('次のステージへ','Next stage')}</button>}</>:<p>{t('ホストが再戦・次のステージを選べます','Host can select a rematch or next stage')}</p>}<button onClick={onBack}>{t('タイトルへ','Title')}</button></section></div>}
    </div><footer className="gear-controls">{[['↑',0,-1],['←',-1,0],['↓',0,1],['→',1,0]].map(([label,x,z])=><button disabled={p.quiz||world.paused||world.phase!=='playing'} key={String(label)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.x=Number(x);input.current.z=Number(z);}} onPointerUp={()=>{input.current.x=input.current.z=0;}} onPointerCancel={()=>{input.current.x=input.current.z=0;}}>{label}</button>)}<button disabled={p.quiz||world.paused||world.phase!=='playing'} onClick={()=>{input.current.crouch=!input.current.crouch;}}>{t('しゃがむ','Crouch')} C</button><button disabled={p.quiz||world.paused||world.phase!=='playing'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.hold=true;}} onPointerUp={()=>{input.current.hold=false;}} onPointerCancel={()=>{input.current.hold=false;}}>{t('ホールド','Hold')} F</button>{world.mode==='royale'?<button disabled={WEAPONS[p.run.weapon].melee||p.quiz||world.paused||world.phase!=='playing'} onClick={()=>{input.current.reload=true;}}>{t('装填','Reload')} T</button>:<button disabled={p.quiz||world.paused||world.phase!=='playing'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.interact=true;}} onPointerUp={()=>{input.current.interact=false;}} onPointerCancel={()=>{input.current.interact=false;}}>{t('回収・支援','Collect / help')} E</button>}<button disabled={world.phase!=='playing'||world.paused||p.quiz||world.time<p.nextSupplyAt} onClick={()=>room.supply()}>{t('問題で補給','Learn & resupply')}<small>B {world.time<p.nextSupplyAt?`${Math.ceil(p.nextSupplyAt-world.time)}s`:t('3問','3 questions')}</small></button></footer></div>;
}
