import EquipmentBar from './EquipmentBar';
import {useVrBgm,createRunAudio,cue} from './audio';
import React, {useEffect,useRef,useState} from 'react';
import {createScene,type ViewMode} from './scene';
import {VrRoom} from './network';
import type {OnlineWorld} from './onlineEngine';
import {MISSIONS,type Input} from './engine';
import Quiz from './Quiz';
export default function OnlineGame({room,world,onBack,en,onConfigure,editing=false}:{room:VrRoom;world:OnlineWorld;onBack:()=>void;en:boolean;onConfigure?:()=>void;editing?:boolean}) {
  const editingRef=useRef(editing);editingRef.current=editing;
  useVrBgm(world.phase==='result'?'clear':world.mode==='royale'?'royale':'training',world.missionId,30);
  const host=useRef<HTMLDivElement>(null),latest=useRef(world);latest.current=world;
  const [mode,setMode]=useState<ViewMode>('overhead'),view=useRef({mode:'overhead' as ViewMode,yaw:Math.PI});
  const input=useRef<Input&{reload?:boolean}>({x:0,z:0,crouch:false,interact:false,decoy:false});
  const keys=useRef(new Set<string>()),drag=useRef<number|null>(null),[quizDone,setQuizDone]=useState('');
  const p=world.players[room.selfId],others=Object.values(world.players).filter(p=>p.id!==room.selfId);
  useEffect(()=>{
    if(!host.current)return;const ids=Object.keys(world.players),index=ids.indexOf(room.selfId),columns=Math.ceil(Math.sqrt(ids.length)),rows=Math.ceil(ids.length/columns),base=MISSIONS[world.missionId-1];
    const renderMission=world.mode==='coop'?{...world.mission,defend:base.defend?{...base.defend,x:base.defend.x+(index%columns-(columns-1)/2)*(2*(base.size??8)+1),z:base.defend.z+(Math.floor(index/columns)-(rows-1)/2)*(2*(base.size??8)+1)}:undefined,exit:{x:base.exit.x+(index%columns-(columns-1)/2)*(2*(base.size??8)+1),z:base.exit.z+(Math.floor(index/columns)-(rows-1)/2)*(2*(base.size??8)+1)}}:world.mission;
    const scene=createScene(host.current,renderMission,world.players[room.selfId]?.avatar);let frame=0,last=performance.now(),sent=0;
    const down=(e:KeyboardEvent)=>{if(editingRef.current||(e.target instanceof HTMLElement&&e.target.closest('select,input,textarea')))return;if(['KeyW','KeyA','KeyS','KeyD','KeyC','KeyE','KeyF','KeyR','KeyT','KeyQ','KeyJ','KeyL','KeyX','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();e.stopPropagation();keys.current.add(e.code);if(!e.repeat){if(e.code==='KeyC')input.current.crouch=!input.current.crouch;if(e.code==='KeyX')input.current.useItem=true;if(e.code==='KeyR')input.current.shoot=true;if(e.code==='KeyT')input.current.reload=true;if(e.code==='KeyQ')input.current.decoy=true;}}};
    const up=(e:KeyboardEvent)=>keys.current.delete(e.code),blur=()=>{keys.current.clear();input.current={x:0,z:0,crouch:true,interact:false,decoy:false};room.input(input.current);};
    window.addEventListener('keydown',down,true);window.addEventListener('keyup',up,true);window.addEventListener('blur',blur);
    const sounds=createRunAudio();let priorHits=0,priorReload=0;const loop=(now:number)=>{const w=latest.current,own=w.players[room.selfId];if(!own)return;const dt=Math.min(.05,(now-last)/1000);last=now;
      const k=keys.current;let x=Number(k.has('KeyD')||k.has('ArrowRight'))-Number(k.has('KeyA')||k.has('ArrowLeft'))||input.current.x,z=Number(k.has('KeyS')||k.has('ArrowDown'))-Number(k.has('KeyW')||k.has('ArrowUp'))||input.current.z;
      if(view.current.mode!=='overhead'){view.current.yaw-=(Number(k.has('KeyL'))-Number(k.has('KeyJ')))*dt*1.9;const a=view.current.yaw,r=x,f=-z;x=-Math.cos(a)*r+Math.sin(a)*f;z=Math.sin(a)*r+Math.cos(a)*f;}
      if(now-sent>50){const disabled=editingRef.current||own.quiz||own.out||w.paused;room.input({...input.current,x:disabled?0:x,z:disabled?0:z,facing:view.current.mode==='overhead'?undefined:view.current.yaw,hold:!disabled&&(input.current.hold||k.has('KeyF')),interact:!disabled&&(input.current.interact||k.has('KeyE')),shoot:!disabled&&input.current.shoot,reload:!disabled&&input.current.reload});input.current.shoot=false;input.current.useItem=false;input.current.reload=false;input.current.decoy=false;sent=now;}
      sounds(own.run);if(own.hits>priorHits)cue('fail');if(own.reloading>priorReload+.5)cue('reload');priorHits=own.hits;priorReload=own.reloading;const displayRun=w.mode==='coop'?{...own.run,collected:Object.values(w.players).flatMap(p=>p.run.collected)}:own.run;
      scene.draw(displayRun,{...view.current,exitReady:w.mode==='coop'&&own.run.collected.every(Boolean)&&own.run.holds>=base.requiredHolds&&own.run.shots>=base.requiredShots,others:Object.values(w.players).filter(q=>q.id!==room.selfId).map(q=>({id:q.id,name:q.name,player:q.run.player,out:q.out,avatar:q.avatar}))});frame=requestAnimationFrame(loop);
    };frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);scene.dispose();window.removeEventListener('keydown',down,true);window.removeEventListener('keyup',up,true);window.removeEventListener('blur',blur);};
  },[world.seed,JSON.stringify(p?.avatar)]);
  const t=(ja:string,eng:string)=>en?eng:ja;
  const quizKey=`${world.round}:${p?.answers.length}:${p?.energy}`;
  if(!p)return null;
  return <div className="gear-shell"><header className="gear-header"><button onClick={onBack}>{t('退室','Leave')}</button><strong>GAKURO VR</strong>{onConfigure&&<button onClick={()=>{keys.current.clear();input.current={x:0,z:0,crouch:false,interact:false,decoy:false};room.input(input.current);onConfigure();}}>{t('キャラクタークリエイト','Character creator')}</button>}<span>{world.mode==='coop'?t('協力','CO-OP'):t('バトルロイヤル','BATTLE ROYALE')} · {Math.ceil(Math.max(0,world.limit-world.time))}s</span></header><div className="gear-equipment">{world.mode==='royale'?<><span>{t('被弾','HITS')} {p.hits}/3</span><span>ENERGY {p.energy}/100</span><span>{t('シャボン','BUBBLES')} {p.run.ammo} {p.reloading>0?t('装填中','RELOADING'):''}</span></>:<span>{t('資料','FILES')} {p.run.collected.filter(Boolean).length}/{p.run.collected.length} · {t('警戒','ALERT')} {Math.round(p.run.detection)}%</span>}</div><nav className="gear-viewbar">{(['overhead','first','third'] as ViewMode[]).map((m,i)=><button key={m} aria-pressed={mode===m} onClick={()=>{view.current={mode:m,yaw:p.run.player.angle};setMode(m);}}>{t(['俯瞰','一人称','三人称'][i],['Overhead','First','Third'][i])}</button>)}<small>{t('WASD 移動 / J・Lまたは画面ドラッグで旋回','WASD move / J·L or drag to turn')}</small></nav><div className="gear-field"><EquipmentBar run={p.run} stageId={world.missionId} en={en} onInput={v=>Object.assign(input.current,v)}/><div ref={host} className="gear-canvas" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current=e.clientX;}} onPointerMove={e=>{if(drag.current!==null){view.current.yaw-=(e.clientX-drag.current)*.007;drag.current=e.clientX;}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>
    <details className="gear-online-roster"><summary>{t('参加者','Players')} {Object.keys(world.players).length}</summary><div>{Object.values(world.players).map(q=><div key={q.id}>{q.name}: {q.out?t('アウト・観戦中','OUT / WATCHING'):q.quiz?t('問題中','QUIZ'):world.mode==='coop'?q.run.status==='clear'?t('クリア・支援中','CLEAR / HELPING'):`${q.run.collected.filter(Boolean).length}/${q.run.collected.length}`:`${q.hits}/3`} {!q.connected&&t('（切断）','(disconnected)')}</div>)}</div></details>
    <svg className="gear-radar" viewBox={`${-(world.mission.size??8)} ${-(world.mission.size??8)} ${(world.mission.size??8)*2} ${(world.mission.size??8)*2}`} aria-label={t('レーダー','Radar')}><rect x={-(world.mission.size??8)} y={-(world.mission.size??8)} width={(world.mission.size??8)*2} height={(world.mission.size??8)*2} fill="#071e20"/>{world.mission.obstacles.map((b,i)=><rect key={i} x={b.x-b.w/2} y={b.z-b.d/2} width={b.w} height={b.d} fill="#667b6f"/>)}{world.mission.targets.map((q,i)=>!Object.values(world.players).flatMap(p=>p.run.collected)[i]&&<circle key={`target-${i}`} cx={q.x} cy={q.z} r={.4} fill="#70eaff"/>)}{Object.values(world.players).map(q=><circle key={q.id} cx={q.run.player.x} cy={q.run.player.z} r={.55} fill={q.id===room.selfId?'white':q.out?'#566165':'#ed9fff'}/>)} </svg>
    {world.mode==='coop'&&<div className="gear-objective">{p.run.status==='clear'?t('担当クリア：他のプレイヤーの資料回収・見回りの睡眠を支援できます','Cleared: help collect others’ files or put patrols to sleep'):t('資料を回収し、自分のエリアの緑の出口へ','Collect files and reach your zone’s green exit')} · {world.mission.defend&&`⚑ ${p.run.defended.toFixed(1)}/${world.mission.defend.seconds}s`} · F {p.run.holds}/{world.mission.requiredHolds} · R {p.run.shots}/{world.mission.requiredShots}</div>}
    {p.out&&<div className="gear-objective">{t('アウト：ゲームに残って観戦できます','Out: remain in the game to watch')}</div>}
    {world.paused&&<div className="gear-overlay"><section>{t('ホストが戻るまで一時停止','Paused until host returns')}</section></div>}
    {p.quiz&&quizDone!==quizKey&&<Quiz key={`${world.round}:${p.run.status}:${p.energy}`} lesson={{...world.lesson,questions:Array.from({length:3},(_,i)=>world.lesson.questions[(p.quizRound*3+i)%world.lesson.questions.length])}} en={en} onAnswer={c=>room.answer(c)} onComplete={()=>setQuizDone(quizKey)}/>}
    {world.mode==='coop'&&!p.quiz&&['caught','timeout'].includes(p.run.status)&&world.phase==='playing'&&<div className="gear-overlay"><section><h2>{t('再挑戦','RETRY')}</h2><button onClick={()=>room.retry()}>{t('担当ミッションを再開','Restart your mission')}</button></section></div>}
    {world.phase==='result'&&!p.quiz&&<div className="gear-overlay"><section><h2>{t('終了','RESULT')}</h2><p>{world.winner.map(id=>world.players[id]?.name).join(' / ')||t('クリアなし','No clears')}</p><button onClick={onBack}>{t('タイトルへ','Title')}</button></section></div>}
    </div><footer className="gear-controls">{[['↑',0,-1],['←',-1,0],['↓',0,1],['→',1,0]].map(([label,x,z])=><button key={String(label)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.x=Number(x);input.current.z=Number(z);}} onPointerUp={()=>{input.current.x=input.current.z=0;}} onPointerCancel={()=>{input.current.x=input.current.z=0;}}>{label}</button>)}<button onClick={()=>{input.current.crouch=!input.current.crouch;}}>{t('しゃがむ','Crouch')} C</button><button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.hold=true;}} onPointerUp={()=>{input.current.hold=false;}} onPointerCancel={()=>{input.current.hold=false;}}>{t('ホールド','Hold')} F</button>{world.mode==='royale'?<button onClick={()=>{input.current.reload=true;}}>{t('装填','Reload')} T</button>:<button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.interact=true;}} onPointerUp={()=>{input.current.interact=false;}} onPointerCancel={()=>{input.current.interact=false;}}>{t('回収・支援','Collect / help')} E</button>}</footer></div>;
}
