import {useVrBgm,cue} from './audio';
import {audioService} from '../../services/audioService';
import React,{useEffect,useRef,useState} from 'react';
import type {MiniGameComponentProps} from '../../components/MiniGameRouter';
import GameTitleScreen from '../shared/GameTitleScreen';
import ModeSelectionScreen from '../../components/ModeSelectionScreen';
import AvatarCreator from '../gakuro-kart/AvatarCreator';
import {buildLesson,type LessonSelection} from '../gakuro-kart/questions';
import type {KartLesson} from '../gakuro-kart/learning';
import type {KartAvatar} from '../gakuro-kart/avatar';
import {loadVrAvatar,saveVrAvatar} from './character';
import {createScene} from './scene';
import {MISSIONS,createRun} from './engine';
import GakuroGear from './GakuroGear';
import OnlineGame from './OnlineGame';
import {VrRoom} from './network';
import type {OnlineMode,OnlineWorld} from './onlineEngine';
import '../gakuro-kart/kart.css';
import './gakurogear.css';
function AvatarPreview({avatar}:{avatar:KartAvatar}){const host=useRef<HTMLDivElement>(null);useEffect(()=>{if(!host.current)return;const mission={...MISSIONS[0],routes:[],cameras:[],targets:[],obstacles:[]};const s=createRun(mission);s.player={x:0,z:0,angle:0};const view=createScene(host.current,mission,avatar);view.draw(s,{mode:'third',yaw:Math.PI});return()=>view.dispose();},[avatar]);return <div ref={host} style={{height:250,width:'100%'}}/>;}
export default function VrTitle(props:MiniGameComponentProps){const language=props.languageMode??'JAPANESE',en=language==='ENGLISH',t=(ja:string,eng:string)=>en?eng:ja;
 const [entry,setEntry]=useState<'title'|'lesson'|'solo'|'online'|'avatar'>('title'),[intent,setIntent]=useState<'solo'|'create'|'join'>('solo');
 const [mode,setMode]=useState<OnlineMode>('coop'),[mission,setMission]=useState(1),[limit,setLimit]=useState(300),[name,setName]=useState('Player'),[code,setCode]=useState(''),[lesson,setLesson]=useState<KartLesson|null>(null),[world,setWorld]=useState<OnlineWorld|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[avatar,setAvatar]=useState(loadVrAvatar);
 useVrBgm(entry==='avatar'?'avatar':entry==='lesson'?'lesson':entry==='online'?'lobby':'title',mission,20);
 const room=useRef<VrRoom|null>(null);useEffect(()=>()=>room.current?.close(),[]);
 const leave=()=>{room.current?.close();room.current=null;setWorld(null);setEntry('title');setError('');};
 const choose=async(selection:LessonSelection)=>{void audioService.unlockAudio();cue('select');try{setBusy(true);setError('');const questions=buildLesson(selection,15);setLesson(questions);if(intent==='solo'){setEntry('solo');return;}const r=new VrRoom(setWorld,setError);room.current=r;await r.create(name,mode,mission,questions,limit,avatar);setEntry('online');}catch(e){setError(String((e as Error).message));room.current?.close();}finally{setBusy(false);}};
 const join=async()=>{void audioService.unlockAudio();cue('select');try{setBusy(true);setError('');const r=new VrRoom(setWorld,setError);room.current=r;await r.join(name,code,avatar);setEntry('online');}catch(e){setError((e as Error).message);room.current?.close();}finally{setBusy(false);}};
 if(entry==='solo'&&lesson)return <GakuroGear {...props} onBack={()=>setEntry('title')} lesson={lesson} avatar={avatar}/>;
 if(entry==='avatar')return <div className="gear-shell" style={{overflow:'auto'}}><header className="gear-header"><button onClick={()=>setEntry('title')}>{t('完了','Done')}</button><strong>{t('主人公を作る','Create your character')}</strong></header><div style={{overflow:'auto',padding:16}}><AvatarPreview avatar={avatar}/><AvatarCreator activity="vr" value={avatar} languageMode={language} onChange={a=>{setAvatar(a);saveVrAvatar(a);}}/></div></div>;
 if(entry==='lesson')return <div className="gear-shell"><header className="gear-header"><button onClick={()=>setEntry('title')}>{t('戻る','Back')}</button><strong>{t('単元問題選択・3問','Select lesson · 3 questions')}</strong></header>{error&&<p role="alert">{error}</p>}<div style={{position:'relative',flex:1,overflow:'auto'}} inert={busy||undefined}><ModeSelectionScreen fixedAnswerMode="CHOICE" languageMode={language} onBack={()=>setEntry('title')} onSelectMode={(mode,modes)=>void choose({mode,modes})}/></div></div>;
 if(entry==='online'&&world&&room.current){if(world.phase!=='lobby')return <OnlineGame room={room.current} world={world} en={en} onBack={leave}/>;return <div className="gear-shell"><header className="gear-header"><button onClick={leave}>{t('退室','Leave')}</button><strong>GAKURO VR</strong></header><main className="gear-select"><section><h1>{t('待機室','LOBBY')}</h1><p>{t('部屋コード','Room code')}: <strong>{room.current.code}</strong></p><button onClick={()=>navigator.clipboard.writeText(room.current!.code)}>{t('コードをコピー','Copy code')}</button><p>{world.lesson.title}</p><p>{world.mode==='coop'?t('協力：全員の課題クリアを目指す。クリア後は他の人を支援。','Co-op: complete everyone’s objectives. Help others after clearing.'):t('3回でアウト。Fホールド・R射撃・T装填。エネルギー不足で3問。','Three hits eliminate. F hold · R shoot · T reload. Answer three questions to restore energy.')}</p>{Object.values(world.players).map(p=><p key={p.id}>{p.name}</p>)}{error&&<p>{error}</p>}{room.current.host?<button className="gear-primary" disabled={world.mode==='royale'&&Object.keys(world.players).length<2} onClick={()=>room.current?.start()}>{t('ホストが開始','START')}</button>:<p>{t('ホストの開始を待っています','Waiting for host')}</p>}</section></main></div>;}
 return <GameTitleScreen kind="vr" title={t('GAKURO VRトレーニング','GAKURO VR Training')} subtitle={t('学校を舞台にしたステルス訓練','TACTICAL SCHOOL TRAINING')} languageMode={language} onClose={props.onBack} backdrop={<div style={{width:'100%',height:'100%',background:'radial-gradient(ellipse at 35% 30%,#55765b,#071b1b 75%)'}}/>} actions={[{label:t('ソロトレーニング','Solo training'),onClick:()=>{setIntent('solo');void audioService.unlockAudio();cue('select');setEntry('lesson');}},{label:t('オンラインルーム作成','Create online room'),onClick:()=>{setIntent('create');void audioService.unlockAudio();cue('select');setEntry('lesson');},disabled:busy},{label:t('ルームに参加','Join room'),onClick:()=>void join(),disabled:busy||!code.trim()},{label:t('キャラクター作成','Create character'),onClick:()=>{void audioService.unlockAudio();cue('select');setEntry('avatar');}}] }>
 <div className="gear-title-options"><label>{t('名前','Name')}<input value={name} maxLength={24} onChange={e=>setName(e.target.value)}/></label><label>{t('部屋コード','Room code')}<input value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>{t('モード','Mode')}<select value={mode} onChange={e=>setMode(e.target.value as OnlineMode)}><option value="coop">{t('協力','Co-op')}</option><option value="royale">{t('バトルロイヤル','Battle royale')}</option></select></label><label>{t('協力ミッション','Co-op mission')}<select value={mission} onChange={e=>setMission(Number(e.target.value))}>{MISSIONS.map(m=><option key={m.id} value={m.id}>{m.id}: {en?m.en:m.name}</option>)}</select></label><label>{t('制限時間（秒）','Time limit (seconds)')}<input type="number" min={60} max={900} step={30} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><small>{t('ホスト通信：レースと同じ接続設定を使用','Host connection: uses the race connection settings')}</small><small>{t('効果音','Sound effects')}: <a href="https://www.springin.org/sound-stock/" target="_blank" rel="noreferrer">Springin’ Sound Stock</a></small>{error&&<p role="alert">{error}</p>}</div>
 </GameTitleScreen>;
}
