// Generated by scripts/generate-vacation-animation-anchors.mjs. Do not edit manually.

export interface VacationAnimationFrameAnchor {
  centerX: number;
  bottomY: number;
  cellWidth: number;
  cellHeight: number;
}

export const VACATION_IDLE_FRAME_ANCHORS: Record<string, VacationAnimationFrameAnchor[]> = {
  "sprites/high-school/vacation-characters-idle-sheets/0.webp": [
    {
      "centerX": 426,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 216,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 407,
      "bottomY": 602,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 280,
      "bottomY": 592,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/1.webp": [
    {
      "centerX": 317,
      "bottomY": 618,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 265,
      "bottomY": 615,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 318,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 278,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/2.webp": [
    {
      "centerX": 371,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 239,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 346,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 242,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/3.webp": [
    {
      "centerX": 339,
      "bottomY": 619,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 277,
      "bottomY": 618,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 340,
      "bottomY": 619,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 241,
      "bottomY": 619,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/4.webp": [
    {
      "centerX": 386,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 246,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 354,
      "bottomY": 572,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 262,
      "bottomY": 568,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/5.webp": [
    {
      "centerX": 401,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 266,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 394,
      "bottomY": 550,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 183,
      "bottomY": 541,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/6.webp": [
    {
      "centerX": 355,
      "bottomY": 593,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 221,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 353,
      "bottomY": 603,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 259,
      "bottomY": 603,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/7.webp": [
    {
      "centerX": 432,
      "bottomY": 594,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 304,
      "bottomY": 595,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 442,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 368,
      "bottomY": 594,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/high-school/vacation-characters-idle-sheets/8.webp": [
    {
      "centerX": 345,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 244,
      "bottomY": 601,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 355,
      "bottomY": 608,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 256,
      "bottomY": 590,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-01-before.webp": [
    {
      "centerX": 438,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 244,
      "bottomY": 588,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 340,
      "bottomY": 586,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 371,
      "bottomY": 591,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-01-after.webp": [
    {
      "centerX": 449,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 298,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 350,
      "bottomY": 608,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 380,
      "bottomY": 612,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-02-before.webp": [
    {
      "centerX": 394,
      "bottomY": 593,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 272,
      "bottomY": 597,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 360,
      "bottomY": 595,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 316,
      "bottomY": 583,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-02-after.webp": [
    {
      "centerX": 333,
      "bottomY": 600,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 271,
      "bottomY": 617,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 342,
      "bottomY": 596,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 271,
      "bottomY": 574,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-03-before.webp": [
    {
      "centerX": 367,
      "bottomY": 591,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 249,
      "bottomY": 592,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 380,
      "bottomY": 594,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 238,
      "bottomY": 581,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-03-after.webp": [
    {
      "centerX": 343,
      "bottomY": 613,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 211,
      "bottomY": 609,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 334,
      "bottomY": 605,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 254,
      "bottomY": 610,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-04-before.webp": [
    {
      "centerX": 276,
      "bottomY": 600,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 340,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 303,
      "bottomY": 605,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 267,
      "bottomY": 606,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-04-after.webp": [
    {
      "centerX": 193,
      "bottomY": 616,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 274,
      "bottomY": 600,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 276,
      "bottomY": 602,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 154,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-05-before.webp": [
    {
      "centerX": 332,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 261,
      "bottomY": 607,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 337,
      "bottomY": 608,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 265,
      "bottomY": 588,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-05-after.webp": [
    {
      "centerX": 316,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 217,
      "bottomY": 586,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 314,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 248,
      "bottomY": 563,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-06-before.webp": [
    {
      "centerX": 349,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 250,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 307,
      "bottomY": 566,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 258,
      "bottomY": 566,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-06-after.webp": [
    {
      "centerX": 347,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 231,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 312,
      "bottomY": 591,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 247,
      "bottomY": 561,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-07-before.webp": [
    {
      "centerX": 366,
      "bottomY": 609,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 219,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 375,
      "bottomY": 573,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 305,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-07-after.webp": [
    {
      "centerX": 433,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 282,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 298,
      "bottomY": 580,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 409,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-08-before.webp": [
    {
      "centerX": 374,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 290,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 316,
      "bottomY": 594,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 266,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-08-after.webp": [
    {
      "centerX": 373,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 263,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 322,
      "bottomY": 616,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 274,
      "bottomY": 621,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-09-before.webp": [
    {
      "centerX": 333,
      "bottomY": 598,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 300,
      "bottomY": 598,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 326,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 295,
      "bottomY": 583,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-characters-idle-sheets/heroine-09-after.webp": [
    {
      "centerX": 343,
      "bottomY": 616,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 237,
      "bottomY": 608,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 347,
      "bottomY": 590,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 293,
      "bottomY": 591,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/ren-before.webp": [
    {
      "centerX": 260,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 189,
      "bottomY": 619,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 272,
      "bottomY": 609,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 228,
      "bottomY": 615,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/ren-after.webp": [
    {
      "centerX": 269,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 365,
      "bottomY": 619,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 383,
      "bottomY": 614,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 224,
      "bottomY": 614,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/soma-before.webp": [
    {
      "centerX": 327,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 307,
      "bottomY": 621,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 362,
      "bottomY": 606,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 270,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/soma-after.webp": [
    {
      "centerX": 330,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 249,
      "bottomY": 603,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 336,
      "bottomY": 617,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 243,
      "bottomY": 610,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/minato-before.webp": [
    {
      "centerX": 400,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 229,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 408,
      "bottomY": 605,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 320,
      "bottomY": 612,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/minato-after.webp": [
    {
      "centerX": 388,
      "bottomY": 610,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 303,
      "bottomY": 577,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 367,
      "bottomY": 599,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 349,
      "bottomY": 602,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/riku-before.webp": [
    {
      "centerX": 379,
      "bottomY": 596,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 242,
      "bottomY": 596,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 337,
      "bottomY": 595,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 236,
      "bottomY": 592,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/riku-after.webp": [
    {
      "centerX": 345,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 264,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 350,
      "bottomY": 625,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 276,
      "bottomY": 620,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/yamato-before.webp": [
    {
      "centerX": 379,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 230,
      "bottomY": 612,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 390,
      "bottomY": 596,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 304,
      "bottomY": 601,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/yamato-after.webp": [
    {
      "centerX": 379,
      "bottomY": 582,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 301,
      "bottomY": 580,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 362,
      "bottomY": 590,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 329,
      "bottomY": 583,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/leon-before.webp": [
    {
      "centerX": 360,
      "bottomY": 606,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 252,
      "bottomY": 610,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 341,
      "bottomY": 603,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 266,
      "bottomY": 598,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/leon-after.webp": [
    {
      "centerX": 321,
      "bottomY": 591,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 252,
      "bottomY": 585,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 309,
      "bottomY": 580,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 241,
      "bottomY": 583,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/elliot-before.webp": [
    {
      "centerX": 325,
      "bottomY": 604,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 251,
      "bottomY": 602,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 331,
      "bottomY": 595,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 241,
      "bottomY": 592,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/elliot-after.webp": [
    {
      "centerX": 352,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 278,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 346,
      "bottomY": 607,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 257,
      "bottomY": 613,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/sakuya-before.webp": [
    {
      "centerX": 318,
      "bottomY": 611,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 224,
      "bottomY": 614,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 316,
      "bottomY": 616,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 220,
      "bottomY": 607,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ],
  "sprites/magic/vacation-male-characters-idle-sheets/sakuya-after.webp": [
    {
      "centerX": 335,
      "bottomY": 614,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 263,
      "bottomY": 626,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 357,
      "bottomY": 605,
      "cellWidth": 627,
      "cellHeight": 627
    },
    {
      "centerX": 251,
      "bottomY": 611,
      "cellWidth": 627,
      "cellHeight": 627
    }
  ]
};

const getAssetPath = (source: string | null): string | null => {
  if (!source) return null;
  const marker = 'sprites/';
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) return null;
  return source.slice(markerIndex).split('?')[0];
};

export const getVacationIdleFrameAnchor = (source: string | null, frameIndex: number): VacationAnimationFrameAnchor | null => {
  const anchors = getAssetPath(source) ? VACATION_IDLE_FRAME_ANCHORS[getAssetPath(source)!] : undefined;
  return anchors?.[frameIndex] ?? null;
};
